### ISSUE TITLE
你好，我想请问下，react怎么跟laravel结合使用呢？

### ISSUE THREAD

**Issue by AmiBang** [zuiidea/antd-admin#1]
我看了react一段时间了，这几天一边看你的更新进度，一边对照你的代码学习，对其有些基本的了解，但是跟laravel框架结合使用一直想不到特别好的办法，我所想到的是使用dav框架或者koa开发react antd的后端，用ajax 和laravel数据交互，但是这样不如直接使用laravel的blade模版去渲染来的方便，更好控制（可能是因为我对react还不够熟练）单单权限这块功能用react觉得都很麻烦。你有什么方法可以和laravel框架结合使用吗？希望能告诉我，谢谢！

**Comment by zuiidea** [comment]
我是前端开发的，对php和laravel不太熟悉哈。
本项目是dva+react+antd的实践，是一个前端项目，没有后端的，build之后生成的文件目录为

```bash
 ├── /dist/         
 ├── common.js 
 ├── index.css
 ├── index.js  
 └── index.html     
```
之所以要用这套方案，是因为antd提供了一套非常完善的中后台UI组件库，dva可以更好的管理state，
本项目中产生的是一个单页面应用，实际上入口只有一个就是index.html，所呈现的页面是通过dva/router来控制的，权限的话应该是在后台也有相应的控制。
目前2.0版本还不够完善，只做了一个数据的增删改查的例子，后面会陆续增加其他例子。

**Comment by AmiBang** [comment]
谢谢你的回答
获取我可以尝试一下放在laravel项目中，你的这个例子很不错。👍

**Comment by supeng911** [comment]
可以看看这个项目：
[react-laravel](https://github.com/talyssonoc/react-laravel)
我也做过php渲染rect的东西，用的是react-php-v8js

但是效果不是很好，非常耗费内存，而且不知道怎么使用react的技术栈，比如react-route， redux，
相当于是每个页面挂一个react的应用，

**Comment by zzr7** [comment]
很赞的项目，但就像你说的相当于是每个页面挂一个react的应用。我现在正在使用react做前后端分离，后端还是用laravel仅提供API
