### ISSUE TITLE
请教一下对全局的登录状态是怎么处理的

### ISSUE THREAD

**Issue by johnsky123** [zuiidea/antd-admin#100]
我把demo运行起来  对于路由中 全局登录状态的处理看的不是特别明白  能解释一下吗 ？

**Comment by feiZhang** [comment]
这个做的不是很彻底，routes/app.js 的 login 变量来控制的，app.js是根view，如果login==false，就显示登录界面。。
这个只是界面的处理，后台业务全部都没处理，比如：在user界面，如果token失效了，刷新，还会自行setup中的获取数据。目前我也没搞懂，这个怎么处理。
另外一个是request.js，的登录失效，获取数据失败等异常，如果全局处理。也没搞明白。

**Comment by zuiidea** [comment]
@feiZhang，现在我是这样处理的
- 每次重载都会请求一次服务器`api/userInfo`，服务器通过cookie判断是否登录，返回未登录或者已登录及用户信息
- 如果未登录跳到登录页，已登录的话将登录信息挂到app的state上

在user界面，这里还是会有未登录去请求user的情况，但是没有登录服务器不会返回数据，另外`api/userInfo`接口完成后会reload到登录页，user的接口在短时间内取消

这并不是一个好方法

全局处理处理错误可以在modle里请求出错时throw错误，会在app的onError里捕获到

**Comment by enlyck** [comment]
@zuiidea 请问 ，这里说的重载是指的页面刷新还是路由变化？ 
我没有在例子发现请求服务器api/userInfo的代码啊，这个请求是如何实现的。。
而且我发现只有F5刷新页面的时候才会去判断cookie是否有效，路由变化是不会判断。。是否我理解有误，请指教

**Comment by zuiidea** [comment]
- 现在的应该是`api/v1/user`，在`model/app.js`里
- 第一次进入时才会判断是否有效，路由变化没有判断

**Comment by superlbr** [comment]
No more feedback. Close.
