### ISSUE TITLE
关于路由的一个小问题

### ISSUE THREAD

**Issue by wlkfec** [zuiidea/antd-admin#1001]
我查看页面上  /zh/  /en/  /都是404页面   按照umi的规则   怎么进入不了pages/index页面   而且经过测试这个页面好像没有用到    还是项目中哪里对根路由进行了限制吗？

**Comment by superlbr** [comment]
1. 因为不止有pages/index这个约定
2. 还有[全局layout路由](https://umijs.org/zh/guide/router.html#%E5%85%A8%E5%B1%80-layout)的约定

**Comment by wlkfec** [comment]
全局路由是一个整体的样式   我的意思是不知道page/index.js在哪里被调用了   登录跳转是没有问题的   如果手动直接输入http://localhost:7000/zh  或者http://localhost:7000/  是404   我看index.js里面 <Redirect to={i18n.t`/dashboard`} /> 好像没有被调用 ？

**Comment by superlbr** [comment]
> 全局路由是一个整体的样式

文档是这样写的，```约定 src/layouts/index.js 为全局路由，返回一个 React 组件，通过 props.children 渲染子组件```

> 我看index.js里面 <Redirect to={i18n.t/dashboard} /> 好像没有被调用 ？

是的，可以没有，兜底

**Comment by wlkfec** [comment]
那如何让这个index组件生效呢？使用/ 跟路由没有对应的组件   一直都是404   我是有点不明白这个组件为什么没生效，这个应该是动态生成的路由  但是没有跟路由？

**Comment by superlbr** [comment]
> 那如何让这个index组件生效呢

为什么要生效呢？个人理解，被全局路由覆盖了。
umi路由表对应/pages/.umi/router.js

**Comment by wlkfec** [comment]
OK   了解了  多谢

**Comment by zjp123** [comment]
为什么我按照上项目里面的路由配置模式来写，组件显示不出来呢？这个里面还有其他注意事项吗

**Comment by superlbr** [comment]
还有权限，mock.js里的对应路由加了没 @zjp123
