### ISSUE TITLE
请问下如何设置post请求的Content-Type？

### ISSUE THREAD

**Issue by yangdachu** [zuiidea/antd-admin#1002]
在request里没有找到对应的参数，请告知一下，谢谢

**Comment by superlbr** [comment]
1. request里有axios
2. 百度下axios设置content-type？
3. 全局可以这么设置```axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';```，其它的请自行研究

**Comment by yangdachu** [comment]
@superlbr 在请求的时候怎么设置下呢  而不是全局里去设置

**Comment by superlbr** [comment]
提供一个思路
1. content-type值也就那么几个，可枚举
2. request的参数能不能再加一个
3. 那么对应services/indexs, services/api 多返回一个请求值，类似'POST'

**Comment by yangdachu** [comment]
@superlbr 谢谢
