### ISSUE TITLE
如何按需加载antd-design-pro

### ISSUE THREAD

**Issue by longfa** [zuiidea/antd-admin#1004]
前提：已经通过yarn add 安装 antd-design-pro；
尝试：尝试了umi block add 和直接将block放在pages下，都没成功运行。

**Comment by superlbr** [comment]
> 按需加载antd-pro

参考文档 https://umijs.org/zh/plugin/umi-plugin-react.html#antd ，只要配置antd: true就可以。本项目自身就有使用antd-pro的组件

> umi block，都没成功运行

参考umi文档，并没有说umi block add 就能直接运行。感觉并没有直接复制user文件夹再修改来的快
```
需要注意的是，区块只是用于开发时新建页面时的提效工具，一般来说区块要实际应用都需要针对项目需求去修改最后的代码，之后的维护都将和普通页面一样由开发者来维护，不存在区块更新的说法。
```

**Comment by longfa** [comment]
antd已经设置为true，我使用umi block list ，区块选项也是会出来的，但umi block add 还是会失败，比如添加分析页，会报 Error: ant-design-pro\Analysis can't match any pattern的错误，直接复制的方式通过排查是我的是js环境里面包含ts文件且缺失了tsconfig.json文件引起的，谢谢。由于我们对页面本身要求不高，尽量能用标准化页面的就基于标准化页面来做，而且前期主要基于antd admin来做的，后面想用pro来快速创建一些页面。

**Comment by superlbr** [comment]
好的
