### ISSUE TITLE
项目使用nginx部署首次访问很慢

### ISSUE THREAD

**Issue by wlkfec** [zuiidea/antd-admin#1005]
使用nginx进行项目部署，浏览器清空缓存首次登陆会访问加载很慢，主要体现在一些js和样式上
![image](https://user-images.githubusercontent.com/6466299/61604480-3f517e80-ac74-11e9-991f-0e5acb95f7a4.png)
这个问题怎么解决，也是需要相关的配置来支持吗？

**Comment by superlbr** [comment]
nginx gzip没开吧

**Comment by wlkfec** [comment]
这个选项开了之后感觉体积没减小，时间缩短了一下
![image](https://user-images.githubusercontent.com/6466299/61608748-70d34580-ac86-11e9-8b3b-4ced28f2b5ee.png)
有一个文件加载五六秒

**Comment by wlkfec** [comment]
刚刚检查了一遍，发现里面的压缩类型写错了 ：gzip_types       text/plain application/javascript text/css application/xml text/javascript;
其中正确的是   application/javascript  刚开始写成  application/x-javascript   导致压缩没有生效
