### ISSUE TITLE
刚把代码git下来 居然启动不了 在线等 很急！！！！！

### ISSUE THREAD

**Issue by ming-lau-1024** [zuiidea/antd-admin#1006]
![image](https://user-images.githubusercontent.com/49233234/61760146-35a75280-adfd-11e9-90d5-00512d20d9d2.png)

如图 跪求大神解救

**Comment by superlbr** [comment]
1. 如果是docker等虚拟环境，请确保内存、cpu充足
2. 请尝试使用yarn\cnpm安装依赖

**Comment by ming-lau-1024** [comment]
> 1. 如果是docker等虚拟环境，请确保内存、cpu充足
> 2. 请尝试使用yarn\cnpm安装依赖

我用得是yarn安装的，然后刚刚在windows上测试了下 。又可以启动。不知是什么原因？？？

**Comment by superlbr** [comment]
网络有波动，正常
