### ISSUE TITLE
打包后浏览器除了谷歌 别的浏览器报错 因该是编译出错了 怎么解决？

### ISSUE THREAD

**Issue by yourdear** [zuiidea/antd-admin#1009]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
1. 啥浏览器
2. 啥错误

**Comment by lvrongzheng** [comment]
ie11 报的语法错误  最近刚发现的问题 你们有钉钉吗 我可以见你们钉钉 这个是我的钉钉号 k9h5cc7加我也行

**Comment by superlbr** [comment]
duplicate in https://github.com/zuiidea/antd-admin/issues/912
去掉spa就好了
