### ISSUE TITLE
Display menu  horizontally 

### ISSUE THREAD

**Issue by javascriptBoiler** [zuiidea/antd-admin#1010]
How to display the main navigation horizontally

seems below option doesn't working
https://ant.design/components/menu/
` <Menu
        mode="horizontal"
      >`

Thanks,

**Comment by superlbr** [comment]
modify here, and css should change also
https://github.com/zuiidea/antd-admin/blob/afd736d615d3fb4630f96f2cfa2866d39159fd7a/src/components/Layout/Menu.js#L99-L101
