### ISSUE TITLE
How do i call an external api

### ISSUE THREAD

**Issue by paventhan89** [zuiidea/antd-admin#1011]
I am trying to call an external api but i couldnt able to call one. I am confused and i dont know from where i need to make the changes. Could you please help me out on this.

**Comment by superlbr** [comment]
> I am trying to call an external api but i couldnt able to call one
put more details pls
>  I am confused and i dont know from where i need to make the changes
just use axios whatever you want to use, there's no limit.Or put external api in server api, that's fine
