### ISSUE TITLE
Okta integration

### ISSUE THREAD

**Issue by joepardi** [zuiidea/antd-admin#1015]
Has anyone gotten Ant Admin to use Okta for its login?  I have Okta working on a regular Material-UI React application but can't get it to work with Ant Admin.  Any help would be appreciated.

- Joe

**Comment by superlbr** [comment]
why not use okta-auth-js, don't be trapped in react

**Comment by joepardi** [comment]
I have to use React as that's my teams' preferred choice.  We also use Ant Design but no one has integrated with Okta yet.  Since this is a new application, I thought Ant Admin was good for the initial scaffolding but the dynamic routes done by udi/dva are making it a challenge to put the correct Okta hooks in place.  I swapped out the standard Ant Admin login page and put in the SignInWidget widget.  I can get the app to display the Okta login page and post the credentials back to Okta.  I can see the /implicit/callback route being invoked.  The Okta cookies are being created, but for some reason the equivalent Okta objects are not being parsed and created within localStorage.  Since this doesn't occur, auth.isAuthenticated() returns false and thus the app is not considered logged in yet.

I'l play around some more but was hoping someone already solved this before me.

**Comment by superlbr** [comment]
how about put a minimal demo to have a look?

**Comment by joepardi** [comment]
@superlbr - I have a minimum version _mostly_ working.  Feel free to submit changes.  The current state of it:

ISSUES:
1. initial routes are incorrect after inital login.  They work after a page refresh.
2. session timeout doesn't work cleanly

NOTES:
A.  see **/mock/user.js** for the Okta user to test with.  It is setup on the Okta service.
B.  see the **//OKTA** marked comments.  

I'll get some more time later today to see if I can fix the remaining two issues.

**Comment by superlbr** [comment]
for routes part, umi cannot found route implicit/callback, just make implicit/callback/index.js under pages. well, make a ```welcome back``` slogan or sth. and let it run js code like ```location.href='/dashboard'```

**Comment by superlbr** [comment]
ah, you need use route in [umi](https://umijs.org/guide/router.html#conventional-routing) style not 'react-router-dom'

**Comment by joepardi** [comment]
Agreed.  I removed the <Route> definition for /implicit/callback from /layouts/index.js and added /pages/implicit/callback/index.js, as you stated.  I took the ImplicitCallback class provided by @okta/okta-react and switched it to use umi.  It still doesn't work as it's not getting invoked.

These changes are now in the repo.

**Comment by joepardi** [comment]
@superlbr - your changes fixed the routing issues (hooray!).  One small thing, however.  The new callback entry in /mock/route.js shows up on the sidebar menu.  Any suggestion on how to get it to not show but still remain valid as a route?  Can that be done in the JSON or does it need to be hidden in the code somewhere?

**Comment by joepardi** [comment]
Found it ... by setting menuParentId: '-1', the layout's <Sider> filters it out.
@superlbr ... thanks for all your help.
