### ISSUE TITLE
请教一个问题 componentWillReceiveProps  

### ISSUE THREAD

**Issue by 544751779** [zuiidea/antd-admin#1016]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

>业务背景
我是用的antd的抽屉功能 在抽屉上有若干的标签页 用来展现不同的功能 如下图所示

![微信截图_20190909165208](https://user-images.githubusercontent.com/7530504/64517195-6e09de00-d322-11e9-9ba3-4f0841eb6ee5.png)
打开抽屉 先ajax请求加载主要的功能(权限信息等)然后下面的标签页自己做ajax操作分别进行加载

>问题是
抽屉组件在打开的时候  请求ajax赋值 然后render函数会调用多次 ,这导致了在子组件中使用 componentWillReceiveProps 获取最新的props 会被调用好多次 造成了子组件ajax请求多次 

>请问 
你们怎么解决的

**Comment by superlbr** [comment]
shouldComponentUpdate or React.PureComponent
