### ISSUE TITLE
部署后如何继续使用mock数据？求大神支招！！！

### ISSUE THREAD

**Issue by ivsass** [zuiidea/antd-admin#1019]
部署后如何继续使用mock数据 ？
应该选择部署在什么服务器上面？
还有具体步骤！！
 
目前我在tamcat的root包下放着可以访问，但是无法使用mock数据，在开发环境下的跨越代理 部署后也不起作用，在开发环境下可以跟我写的后台正常连接。目前主要问题就是部署后如何使用mock数据 ，求大神支招  ！！！！

**Comment by superlbr** [comment]
参考https://github.com/zuiidea/antd-admin/issues/832

**Comment by ivsass** [comment]
我需要在linux环境下进行部署，那个api站点可以用吗？
我的理解是  用nginx 用来做服务器 ，放置前端的静态内容，然后分发请求 使用mock数据的代理到api站点，tomcat上面部署后端项目，调用接口的分发到tomcat。
您看这个思路可行吗？

**Comment by superlbr** [comment]
1. 可以
2. 有后端，为啥还要mock

**Comment by ivsass** [comment]
我对前端不太懂，这个项目中的子页面我都是自己改的，mock数据就登录跟菜单使用，后端项目涉及不到登录跟权限控制，所以感觉用mock会比较方便。我明天试下，不行的话只能写后端了。非常感谢！
