### ISSUE TITLE
Roadhod with env variables

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#1020]
Bit outdated question,  Is it possible to build with env variables as we do right now with umi

**Comment by superlbr** [comment]
roadhog? https://github.com/sorrycc/roadhog#env

**Comment by malinda1986** [comment]
thanks for the link, I need to get different config JSON files at the build time based on the build command 

ex:   "build": "cross-env env=development && roadhog build",

this should load the dev config file 

my .readhogrc.js looks like below 

`env: {
    development: {
      extraBabelPlugins: [
        "dva-hmr",
        "transform-runtime",
        [
          "import", {
            "libraryName": "antd",
            "style": true
          }
        ]
      ],
      alias: {
        envVars: path.resolve(__dirname,"src/utils/env/development.json"),
      },
    },
    production: {
      extraBabelPlugins: [
        "transform-runtime",
        [
          "import", {
            "libraryName": "antd",
            "style": true
          }
        ]
      ]
    }
  },`

**Comment by superlbr** [comment]
set NODE_ENV instead

**Comment by malinda1986** [comment]
Yes that tried, roadhog build command cannot read the NODE_ENV, 
` cross-env env=loc NODE_ENV=loc server=loc && roadhog build` 
below command works fine and reads env. variables 
`cross-env NODE_ENV=dev env=dev server=dev BROWSER=none HOST=0.0.0.0 roadhog server`
