### ISSUE TITLE
antd-admin-5.1.0版本npm install一致不成功

### ISSUE THREAD

**Issue by forgotwho** [zuiidea/antd-admin#1021]
5.1.0版本下载后执行npm install不成功
$ node -v
v10.14.1
$ npm -v
6.4.1

最后会出现
46367 verbose stack Error: EPERM: operation not permitted, unlink 'D:\workspace_minebrand\antd-admin-5.1.0\node_modules\.staging\antd-17f67844\dist\antd-with-locales.js'
46368 verbose cwd D:\workspace_minebrand\antd-admin-5.1.0
46369 verbose Windows_NT 6.1.7601
46370 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
46371 verbose node v10.14.1
46372 verbose npm  v6.4.1
46373 error path D:\workspace_minebrand\antd-admin-5.1.0\node_modules\.staging\antd-17f67844\dist\antd-with-locales.js
46374 error code EPERM
46375 error errno -4048
46376 error syscall unlink
46377 error Error: EPERM: operation not permitted, unlink 'D:\workspace_minebrand\antd-admin-5.1.0\node_modules\.staging\antd-17f67844\dist\antd-with-locales.js'
46377 error  { [Error: EPERM: operation not permitted, unlink 'D:\workspace_minebrand\antd-admin-5.1.0\node_modules\.staging\antd-17f67844\dist\antd-with-locales.js']
46377 error   cause:
46377 error    { Error: EPERM: operation not permitted, unlink 'D:\workspace_minebrand\antd-admin-5.1.0\node_modules\.staging\antd-17f67844\dist\antd-with-locales.js'
46377 error      errno: -4048,
46377 error      code: 'EPERM',
46377 error      syscall: 'unlink',
46377 error      path:
46377 error       'D:\\workspace_minebrand\\antd-admin-5.1.0\\node_modules\\.staging\\antd-17f67844\\dist\\antd-with-locales.js' },
46377 error   stack:
46377 error    'Error: EPERM: operation not permitted, unlink \'D:\\workspace_minebrand\\antd-admin-5.1.0\\node_modules\\.staging\\antd-17f67844\\dist\\antd-with-locales.js\'',
46377 error   errno: -4048,
46377 error   code: 'EPERM',
46377 error   syscall: 'unlink',
46377 error   path:
46377 error    'D:\\workspace_minebrand\\antd-admin-5.1.0\\node_modules\\.staging\\antd-17f67844\\dist\\antd-with-locales.js',
46377 error   parent: 'antd-admin' }
46378 error The operation was rejected by your operating system.
46378 error It's possible that the file was already in use (by a text editor or antivirus),
46378 error or that you lack permissions to access it.
46378 error
46378 error If you believe this might be a permissions issue, please double-check the
46378 error permissions of the file and its containing directories, or try running
46378 error the command again as root/Administrator (though this is not recommended).
46379 verbose exit [ -4048, true ]

**Comment by forgotwho** [comment]
verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...sShrinkwrap":false,"d'

**Comment by forgotwho** [comment]
$ npm install
npm WARN deprecated highcharts-exporting@0.1.7: this package has been deprecated, just import modules from the highcharts folder
npm WARN deprecated highcharts-more@0.1.7: this package has been deprecated, just import modules from the highcharts folder
npm WARN deprecated core-js@2.6.0: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()


到这步就出问题了

**Comment by superlbr** [comment]
use yarn
