### ISSUE TITLE
能否在build上给一些优化建议，目前首屏时间超过了10秒对于客户而言这是致命的，况且我还是在没有做开发的情况下

### ISSUE THREAD

**Issue by admiao** [zuiidea/antd-admin#1023]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
即使开发后，正常的加载在1-2s左右。参考https://github.com/zuiidea/antd-admin/issues/712
