### ISSUE TITLE
本项目怎么才能不使用mock数据,使用真实接口数据?

### ISSUE THREAD

**Issue by w15618776065** [zuiidea/antd-admin#1024]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
1. 开发环境，MOCK=none umi dev
2. 生产环境，npm run build出来的不走mock
