### ISSUE TITLE
默认路由问题 

### ISSUE THREAD

**Issue by admiao** [zuiidea/antd-admin#1026]
默认路由本地开发无效

**Comment by admiao** [comment]
![image](https://user-images.githubusercontent.com/24733229/67359867-17d1c100-f597-11e9-9802-45ffb0d9717d.png)

**Comment by superlbr** [comment]
貌似不是最新的代码

**Comment by admiao** [comment]
> 貌似不是最新的代码, /src/models/app.js 加个判定就好了

我昨天下的 如何使用最新版 新手小白 望告知一下

**Comment by superlbr** [comment]
重新下，再看看

**Comment by admiao** [comment]
> 重新下，再看

> 貌似不是最新的代码, /src/models/app.js 加个判定就好了

**Comment by admiao** [comment]
> > 貌似不是最新的代码, /src/models/app.js 加个判定就好了
> 
> 我昨天下的 如何下载最新版 新手小白 望告知一下



> 貌似不是最新的代码, /src/models/app.js 加个判定就好了

我按照官方的代码加了和官方一样的判断 但有新的问题是 在浏览器刷新后 路由记忆功能失效了 如论任何路由刷新都会go dashboard
