### ISSUE TITLE
路由记忆 逻辑问题

### ISSUE THREAD

**Issue by admiao** [zuiidea/antd-admin#1028]
发现在history 为hash 模式下 , 在models/app.js 下逻辑判断 goDashboard 函数 会导致路由记忆失败，无论 哪个路由 一旦刷新浏览器 都会 跳转 dashboard 因为 初次加载 pathMatchRegexp(['/', '/login'],...) 判断逻辑是成立的。请大佬指教该如何。

**Comment by superlbr** [comment]
window.location.hash
