### ISSUE TITLE
下载下来的项目无法兼容pc端

### ISSUE THREAD

**Issue by WuGuanChao** [zuiidea/antd-admin#1031]
## 大佬们好！
我 npm run start 运行起来的项目默认只支持移动端，在pc端打开的话，页面布局会错位。
+ 在PC端打开
![PC端效果](http://huijutest.bajiaostar.com/profile/photo/2019/10/31/484a495c394550f3613772dc630a2ba5.png)
+ 在移动端打开
![移动端效果](http://huijutest.bajiaostar.com/profile/photo/2019/10/31/f684452c5e483f47f9a3ae3cc33503e3.png)

**Comment by superlbr** [comment]
啥操作系统，啥浏览器？chrome是否正常？

**Comment by WuGuanChao** [comment]
> 啥操作系统，啥浏览器？chrome是否正常？

操作系统是win7
chrome 版本是  74.0.3729.131
不过我是下载的zip 压缩包，因为 clone git 地址每次都因为网速问题失败。感觉可能是这个原因

**Comment by superlbr** [comment]
怀疑chrome插件或脚本影响，本机win7 QQ浏览器测试ok
