### ISSUE TITLE
当token 失效 或 登陆认证失败 请求拦截 跳转到登陆 这些需求行为我该如何在本系统实现呢

### ISSUE THREAD

**Issue by admiao** [zuiidea/antd-admin#1032]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
> token失效

后台请求自然能拦截, request.js对data或者error处理即可。放在modles里也成，或者抛出提示，提示用户注销

**Comment by admiao** [comment]
如果要实现切换到登陆页面 request.js 里要引入router(这里我担心的是不合理引入 会引起体积过大和臃肿)   如果要放在app.js 里好像除了刷新浏览器 普通切换页面无法触发

**Comment by admiao** [comment]
> > token失效
> 
> 后台请求自然能拦截, request.js对data或者error处理即可。放在modles里也成，或者抛出提示，提示用户注销

如果要实现切换到登陆页面 request.js 里要引入router(这里我担心的是不合理引入 会引起臃肿) 如果要放在app.js 里好像除了刷新浏览器 普通切换页面无法触发

**Comment by superlbr** [comment]
app.js里加个诸如expire_time、token之类的检查，request.js里操作一下，然后window.location。。。

**Comment by admiao** [comment]
> app.js里加个诸如expire_time、token之类的检查，request.js里操作一下，然后window.location。。。
感谢
