### ISSUE TITLE
After npm run build running serve dist  provides api/v1/user   404 

### ISSUE THREAD

**Issue by Ej-leone** [zuiidea/antd-admin#1033]
```
1. npm run build
2. serve ./dist 

```
error

**Comment by Ej-leone** [comment]
<img width="1440" alt="Screen Shot 2019-11-06 at 6 37 05 PM" src="https://user-images.githubusercontent.com/26254012/68312680-7a14e080-00c4-11ea-82d9-672e5f3d400e.png">

**Comment by superlbr** [comment]
正常的
build之后就是要访问后端接口了，不走mock
