### ISSUE TITLE
how to remove umi ui bubble

### ISSUE THREAD

**Issue by axelginepro** [zuiidea/antd-admin#1034]
Reproduction link
https://drive.google.com/open?id=1JU52HPDikMn_8oRWvhlJwsasyoN51Asu

Steps to reproduce
tell me how to remove this umi ui bubble please

What is expected?
remove it

What is actually happening?
new in the project

"antd": "^3.24.3",
React | 16.10
System | windows 10
Browser | chrome, brave

**Comment by superlbr** [comment]
well, it's umi's new feature.
add ```UMI_UI=none``` to ```start``` part, such as ```UMI_UI=none umi dev```

**Comment by zellkon** [comment]
> well, it's umi's new feature.
> add `UMI_UI=none` to `start` part, such as `UMI_UI=none umi dev`

how to reopen it bro ?

**Comment by zellkon** [comment]
> well, it's umi's new feature.
> add `UMI_UI=none` to `start` part, such as `UMI_UI=none umi dev`

cause too hard for add new page or route without umi
