### ISSUE TITLE
如何在启动的时候配置log4js?

### ISSUE THREAD

**Issue by Sanbingo** [zuiidea/antd-admin#1035]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
执行npm run start 后，如何自定义执行node代码，在启动node实例的时候初始化log4js配置
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
有入口可以执行自定义代码
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
add it in src/global.(js|ts) is fine

**Comment by Sanbingo** [comment]
global.js只能记录前端请求的日志，如何记录代理转发实际的日志呢？有没有类似express中间件的配置，会自动记录所有的请求日志

**Comment by Sanbingo** [comment]
> add it in src/global.(js|ts) is fine

系统有日志集成功能吗？或者有log4js集成的解决思路吗？谢谢~

**Comment by superlbr** [comment]
>记录代理转发实际的日志

让代理去记录呗

>类似express中间件的配置

让Egg.js去做这样的操作更合适,类似https://github.com/eggjs/egg-ant-design-pro
