### ISSUE TITLE
Bug Config.js layouts exclude not working properly

### ISSUE THREAD

**Issue by Daornit** [zuiidea/antd-admin#1036]
Bug i changed this particular code and requested to localhost:7000/en/register  but it redirected to localhost:7000/en/login

which file i may find helpful code
layouts: [
    {
      name: 'primary',
      include: [/.*/],
      exclude: [/(\/(en|zh))*\/(login|register)/],
    },
  ],

**Comment by superlbr** [comment]
so in short, your problem is layout or redirect?
for layout, i guess works fine
for redirect, just modify related code login => register
