### ISSUE TITLE
config.js中我需要动态的添加配置，这怎么搞

### ISSUE THREAD

**Issue by dingzch** [zuiidea/antd-admin#1042]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
config.js本身就是动态的，以antd-pro为例，参考https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts
1. 根据环境设置参数
   ```
    const { ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION } = process.env;
   ```
2. 根据是否当前站点
  ```
if (isAntDesignProPreview) {
  // 针对 preview.pro.ant.design 的 GA 统计代码
  plugins.push([
    'umi-plugin-ga',
    {
      code: 'UA-72788897-6',
    },
  ]);
  plugins.push(['umi-plugin-antd-theme', themePluginConfig]);
}
  ```
