### ISSUE TITLE
npm install和cnpm以及yarn都无法安装所需的依赖。

### ISSUE THREAD

**Issue by llh1187** [zuiidea/antd-admin#1043]
> 2. Bug反馈  
我已经换了淘宝的源了，使用npm install和cnpm install 以及yarn install都无法成功安装所需依赖。
> 2.1 简单描述下报错  

![image](https://user-images.githubusercontent.com/40154001/71541094-81eb5580-298e-11ea-919e-12837e7cbeb7.png)

> 2.4 可提供运行环境信息  
校园网，win10。

**Comment by llh1187** [comment]
大家可以看到图片吗？我这边看不到图片，是中国防火墙屏蔽了吗？

**Comment by superlbr** [comment]
试试华为源，有npm的
```
npm config set registry https://mirrors.huaweicloud.com/repository/npm/

**Comment by llh1187** [comment]
> 试试华为源，有npm的
> 
> ```
> npm config set registry https://mirrors.huaweicloud.com/repository/npm/
> ```

求助大神，华为源也不行哦。

**Comment by llh1187** [comment]
![image](https://user-images.githubusercontent.com/40154001/71552211-7aca5300-2a33-11ea-8ebd-bf62161dcf47.png)

**Comment by llh1187** [comment]
[2019-12-29T04_06_10_156Z-debug.log](https://github.com/zuiidea/antd-admin/files/4007753/2019-12-29T04_06_10_156Z-debug.log)

**Comment by superlbr** [comment]
> 69139 verbose stack Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\THINK\Desktop\antd-admin\node_modules\.staging\echarts-75326502'

注意这个报错，跟源没有关系，要删掉文件夹

**Comment by llh1187** [comment]
> > 69139 verbose stack Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\THINK\Desktop\antd-admin\node_modules.staging\echarts-75326502'
> 
> 注意这个报错，跟源没有关系，要删掉文件夹

大神你是说删掉node_modules.staging这个文件夹吗，还是删掉整个node_modules?

**Comment by superlbr** [comment]
随意

**Comment by llh1187** [comment]
> 随意

删掉了node_modules之后还是不行。

然后我把整个文件删了，重新clone了下来，现在然后npm install，现在出现这个错误:
![image](https://user-images.githubusercontent.com/40154001/71572595-db808b00-2b1a-11ea-82cd-903ab511a944.png)

**Comment by llh1187** [comment]
[2019-12-30T07_33_41_061Z-debug.log](https://github.com/zuiidea/antd-admin/files/4009198/2019-12-30T07_33_41_061Z-debug.log)
我太南了。

**Comment by superlbr** [comment]
用yarn，给yarn换源

**Comment by llh1187** [comment]
> 用yarn，给yarn换源
用了淘宝源，还是报错，如下图：
![image](https://user-images.githubusercontent.com/40154001/71586315-bf014480-2b54-11ea-8b94-10d4b6f7a964.png)

**Comment by llh1187** [comment]
[yarn-error.log](https://github.com/zuiidea/antd-admin/files/4010016/yarn-error.log)
难道是我的校园网的问题吗 :cry:

**Comment by llh1187** [comment]
![image](https://user-images.githubusercontent.com/40154001/71587555-1ef9ea00-2b59-11ea-9a73-b748933fc250.png)

用了手机热点，好像成功了是吗？

**Comment by llh1187** [comment]
谢谢大家，搞定了

**Comment by ljlhnick** [comment]
> 谢谢大家，搞定了
咋搞定 我现在也碰见了

**Comment by llh1187** [comment]
> > 谢谢大家，搞定了
> > 咋搞定 我现在也碰见了
校园网不太行，后面换了手机热点就可以了
