### ISSUE TITLE
Less样式模块化

### ISSUE THREAD

**Issue by JinGangRed** [zuiidea/antd-admin#1044]
> 请教一个问题，就是在使用React的过程中，对于样式模块化是怎么处理的？

我在使用的过程中，发现对于父组件的一个样式，是全局的。如果子组件修改了该样式，那么会应用到父组件。我看过一下几种解决方案：
1.  StyleComponent
2. Style in JS
3. Less Module.

**Comment by superlbr** [comment]
看过解决方案了，然后呢
可以翻翻文档哈 https://pro.ant.design/docs/style-cn
