### ISSUE TITLE
Can't create new page

### ISSUE THREAD

**Issue by minhdatplus** [zuiidea/antd-admin#1045]
I'm create new page inside page folder, but when access in browser bar web page display 404 page not found.
<img width="1920" alt="Screen Shot 2019-12-29 at 15 37 08" src="https://user-images.githubusercontent.com/9394079/71554407-26ce6700-2a51-11ea-898f-5cc3e8fde470.png">

**Comment by superlbr** [comment]
it's menu.js maybe forgot to set

**Comment by minhdatplus** [comment]
Hi @superlbr . I can't place to add/edit menu item in menu.js . Can you give me line number of code? Many thanks.

**Comment by minhdatplus** [comment]
More detail i think you should adding into documents "How to create new page and option menu in Sider". With new bie like me. I can't find a way to create them. Many thanks.

**Comment by minhdatplus** [comment]
I found problem with menu and page. Sider/Menu get value from local storage to generate menuTrees. When i change database array value in mock/route.js it isn't update to local storage, menuTrees can't get newest value from database to generate new menu when hot module reload run.

**Comment by superlbr** [comment]
lack guide about new page in english, well, pr glad.
menuTrees with hot reload, well, it's rarely change, login off/login on is more common.

**Comment by minhdatplus** [comment]
I'm total argee with you, log on/off is common, but with new bie like me when move from origin ant-design-pro project to your, it so far different, anyway i solved with my problem, thanks for support, greate project, keep going on bro @superlbr
