### ISSUE TITLE
The demo site is down, can we use GitHub pages instead for stability?

### ISSUE THREAD

**Issue by hsluoyz** [zuiidea/antd-admin#1047]
It seems that the author has no enough time to keep the demo server online. We can just use GitHub pages for demo site. So you don't need to maintain the server any more.

**Comment by superlbr** [comment]
You're partly right.
But github pages is not friendly in mainland, so we may put dist in cdn.
lack gzip or sth., it's much slower than before, I' check it later.

**Comment by hsluoyz** [comment]
If the source code is already hosted on GitHub, it means it assumes the users can access GitHub. GitHub pages are the same accessible as GitHub.

Moreover, mainland server is unfriendly to international users. This repo has an English README, meaning that it cares about international users.

**Comment by superlbr** [comment]
1. well, GitHub pages not the same accessible as GitHub in mainland
2. moving to cdn
3. github pages will take into consideration for international users.
