### ISSUE TITLE
一些建议性问题

### ISSUE THREAD

**Issue by admiao** [zuiidea/antd-admin#1048]
使用了几个月 发现的一些问题及建议
1 request封装问题 ，存在当axios 使用响应拦截 那么将是一个很严重的BUG 响应拦截代码将完整一次请求执行多次，引入也并不优雅 需要两步 并非像官网那样一步到位
2 国际化问题  封装不合理(个人认为) 建议看向pro
3 umi 太臃肿

**Comment by superlbr** [comment]
> 响应拦截代码将完整一次请求执行多次

能否提供代码、或者截图

> 引入也并不优雅 需要两步 并非像官网那样一步到位

怎么个两步法？怎么样算优雅呢？

> 国际化问题 封装不合理

也算一种尝试，跟路由耦合确实不合适

> umi 太臃肿

umi臃肿有点必然性，功能多、自然模块多、依赖也多，还可以接受。欢迎去umi开issue。

**Comment by admiao** [comment]
![image](https://user-images.githubusercontent.com/24733229/71998201-2ff1dc00-327a-11ea-8a76-730bdc23c4b9.png)
![image](https://user-images.githubusercontent.com/24733229/71998238-3d0ecb00-327a-11ea-9585-e5744c6214a4.png)

**Comment by admiao** [comment]
> > 响应拦截代码将完整一次请求执行多次
> 
> 能否提供代码、或者截图
> 
![image](https://user-images.githubusercontent.com/24733229/71999063-b529c080-327b-11ea-9d58-27c1c7c91ecf.png)
![image](https://user-images.githubusercontent.com/24733229/71999162-dab6ca00-327b-11ea-8374-8110731fa158.png)
> > 引入也并不优雅 需要两步 并非像官网那样一步到位
> 
> 怎么个两步法？怎么样算优雅呢？
> 
![image](https://user-images.githubusercontent.com/24733229/71998707-169d5f80-327b-11ea-9f06-8cd6925d2047.png)
我觉得官方的就很优雅  但我们实际是 先 import api from 'api'  然后 const { xxxx } = api 

> > 国际化问题 封装不合理
> 
> 也算一种尝试，跟路由耦合确实不合适
> 
> > umi 太臃肿
> 
> umi臃肿有点必然性，功能多、自然模块多、依赖也多，还可以接受。欢迎去umi开issue。
这个可能是个人问题吧  其实让自己来做那么多功能 还没有他们写的那么好

**Comment by superlbr** [comment]
其实就第一个问题，不需要拦截器，下面就已经拦截了，在里面console.log就很清楚，不多不少

https://github.com/zuiidea/antd-admin/blob/d800d6f3ce30fb66f238a4d0e3f7a9cb19124858/src/utils/request.js#L45-L49

**Comment by hishion** [comment]
我的windows下代码保存后编译是这样的:

![image](https://user-images.githubusercontent.com/16174674/90587167-4b0ecc00-e20b-11ea-8276-472fcbe02af0.png)

 配置如下,难道win下面都这么慢么,还未添加任何代码量...

![image](https://user-images.githubusercontent.com/16174674/90587167-4b0ecc00-e20b-11ea-8276-472fcbe02af0.png)

**Comment by superlbr** [comment]
@hishion umi + webpack确实有点重，但二次编译和修改代码触发的编译尚可接受。大概也是snowpack、vite新兴打包器能崛起的原因吧
