### ISSUE TITLE
如何新增一个仅能通过地址栏访问的路由？

### ISSUE THREAD

**Issue by Mirror36594912** [zuiidea/antd-admin#1051]
我通过查阅issues知道了如何新增一个菜单路由；但是我想要新增一个不通过左侧菜单进入的二级页面，我在pages目录下新增一个文件夹并写好index.js和model.js后，route.js自动新增了这个页面的路由，但是我通过这个路由访问页面的时候却是404；而我在menu.js中增加了这个页面的菜单后却又能正常访问了，请问这种情况该如何解决？

左侧菜单有该页面路由时：
![左侧菜单有该页面路由时](https://user-images.githubusercontent.com/19388166/74082683-5c765f00-4a97-11ea-8e57-b67cb74e7a7c.png)

左侧菜单没有该页面路由时：
![左侧菜单没有该页面路由时](https://user-images.githubusercontent.com/19388166/74082685-6009e600-4a97-11ea-97f3-4be7ee934e9f.png)

**Comment by superlbr** [comment]
因为layout里有menu相关的代码，用来展示页面。mpid设为-1不展示即可
