### ISSUE TITLE
request 里 POST 的 data 也是作为 queryString，这个操作是对的吗？

### ISSUE THREAD

**Issue by hlwjia** [zuiidea/antd-admin#1052]
请酌情提供细节，并保持issue精简便于查阅

1. 功能需求 => 

在 API 请求里，对于 POST 的 API 传入的 data，目前同时也作为 queryString `axios({params: PARAMS})` 的。

不应该只在 body `axios({data: DATA})` 里吗？

**Comment by superlbr** [comment]
取决于代码运行有无异常。
个人倾向于优化前的版本， https://github.com/zuiidea/antd-admin/commit/7d5ad95cff779a6d32ea0dabd44e60e9aeff5eed#diff-24dbc3ca3b4db4e46b1194dc68247a70
