### ISSUE TITLE
the  service url in deployment change 

### ISSUE THREAD

**Issue by Sesleone** [zuiidea/antd-admin#1056]
when i build always try to get routes etc from local host to my custom url for routes etc for production. The docs dont eleaborate for a beginner

**Comment by superlbr** [comment]
more details pls, fail to catch up

**Comment by Sesleone** [comment]
when i place 
yarn build and 
serve my application i get 404 error. because tries get from localhost:5000
but i want not use mock api 
rather my domain

**Comment by superlbr** [comment]
just modify proxy in .umirc

**Comment by zellkon** [comment]
> just modify proxy in .umirc

same problems, i already change proxy in .umirc but nothing  change. application just run localhost:7000/api

**Comment by superlbr** [comment]
just modify request.js, force axios use your domain

**Comment by jl63** [comment]
How to change the request.js so that it can use my own domain? After chaging that, in which way should I send the request? I used fetch to send request but the domain is still using 7000

**Comment by superlbr** [comment]
just change `let domain = ''` to `let domain = 'http://www.xx.com'`
