### ISSUE TITLE
在哪里引入百度地图的JS

### ISSUE THREAD

**Issue by luobao1207** [zuiidea/antd-admin#1058]
项目中需要使用百度地图,一般都是在index.htm引入百度地图的js.但是项目中找不到index.html文件.我应该在哪里引入呢

**Comment by superlbr** [comment]
不妨这么考虑，这是个什么项目？React呀，react怎么引入呀？react-amap。
再想index.html没有，是不是变了样子呀？document.ejs是什么东东？

**Comment by luobao1207** [comment]
@superlbr 感谢你的回答.但是在新版的antd-admin项目里面好像也没有document.ejs

**Comment by superlbr** [comment]
@luobao1207 https://umijs.org/zh-CN/docs/html-template

**Comment by luobao1207** [comment]
非常感谢🙏

**Comment by luobao1207** [comment]
@superlbr 非常感谢🙏
