### ISSUE TITLE
作者你好，下载了5.3.0-beta版本的Source code (tar.gz)代码运行仍然是5.2版本的，发布时是否源码包打错了呢

### ISSUE THREAD

**Issue by maccy1** [zuiidea/antd-admin#1059]
作者你好，
 我下载了5.3.0-beta版本的Source code (tar.gz)代码运行仍然是5.2版本的，发布时是否源码包打错了呢。
  运行后仍然是umi 2.x,切换为中文后，地址路径上仍然有zh 如http://localhost:7000/zh/user

package.json中仍然是5.2.0
 "name": "antd-admin",
  "version": "5.2.0",
  "license": "MIT",

看你发布说明，5.3更新了下面的功能，测试没有生效，请帮助指导，多谢！
upgrade umi to 3.x
drop legacy form with antd4
remove i18n from pathname

**Comment by superlbr** [comment]
use branch develop
