### ISSUE TITLE
求教：子页面如何更改父页面的某个组件的状态和值

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#106]
![aaddffgg](https://cloud.githubusercontent.com/assets/6395357/23647485/01dec7ca-0351-11e7-9efe-b11b689bae8f.png)
![aaddff](https://cloud.githubusercontent.com/assets/6395357/23647492/0654000e-0351-11e7-8c4c-1cb0de0f8ae3.png)

**Comment by zuiidea** [comment]
父组件传可更改state的函数参数到子组件，子组件执行参数函数的时候就更改了父组件的state
