### ISSUE TITLE
虚拟机下无法热更新问题

### ISSUE THREAD

**Issue by Chenqt5** [zuiidea/antd-admin#1061]
本机是MAC.
在MAC跑了一个Linux虚拟机
编辑文件无法引起重新编译，每次都需要重新编译很久
开发上非常痛苦。

尝试过HMR=reload和Watch=True都没有效果

**Comment by superlbr** [comment]
> 尝试过HMR=reload和Watch=True都没有效果

HMR\Watch是默认开启的，建议更新到最新的umi看看

> 在MAC跑了一个Linux虚拟机，编辑文件无法引起重新编译

这边测下来是可以的，不知道是什么类型的文件。Mac直接开发不好么。。

> 每次都需要重新编译很久

参考[umi编译提速](https://umijs.org/guide/boost-compile-speed)
主要有几点，SourceMap/nodeModulesTransform/esbuild(可以试试)

**Comment by Chenqt5** [comment]
> Mac直接开发不好么。。

因为我这里是后端的，后端的程序我都放在虚拟机下运行。

**Comment by Chenqt5** [comment]
> > 尝试过HMR=reload和Watch=True都没有效果
> 
> HMR\Watch是默认开启的，建议更新到最新的umi看看
> 
> > 在MAC跑了一个Linux虚拟机，编辑文件无法引起重新编译
> 
> 这边测下来是可以的，不知道是什么类型的文件。Mac直接开发不好么。。
> 
> > 每次都需要重新编译很久
> 
> 参考[umi编译提速](https://umijs.org/guide/boost-compile-speed)
> 主要有几点，SourceMap/nodeModulesTransform/esbuild(可以试试)

感觉这是个共性问题，我拉antd-admin的代码也是无法热更新。

**Comment by superlbr** [comment]
> 感觉这是一个共性问题

如果是这样，Q群分分钟炸


![未命名](https://user-images.githubusercontent.com/8142164/82793088-ee697280-9ea2-11ea-9a3d-d15d8df9ae09.gif)
