### ISSUE TITLE
i18n在非react组件中如何使用，比如model中？

### ISSUE THREAD

**Issue by delonzhou** [zuiidea/antd-admin#1075]
按照@lingui/react的文档（如下）试着做了一下，没有成功。
Translations outside React components

Another common pattern is when you need to access translations (i18n object) outside React components, for example inside redux-saga. In such case, you need a bit more setup:

Create your own instance of i18n using setupI18n() form @lingui/core
Pass this instance as i18n prop to <I18nProvider>. This will replace default i18n object initialized inside <I18nProvider>.

// App.js
import { setupI18n } from "@lingui/core"
import { I18nProvider } from "@lingui/react"

export const i18n = setupI18n()

export default function App() {
   return (
      <I18nProvider i18n={i18n}>
         {/* Out app */}
      </I18nProvider>
   )
}

**Comment by zuiidea** [comment]
可以参考这个文档：
https://lingui.js.org/tutorials/javascript.html#tutorial-internationalization-of-javascript-apps
