### ISSUE TITLE
大佬，我想把页面和组件全部用函数组件实现怎么做？我直接改写成函数组件，页面不显示内容

### ISSUE THREAD

**Issue by Herozzq** [zuiidea/antd-admin#1079]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
上代码，精简点

**Comment by Herozzq** [comment]
`import React from 'react';
import { connect } from 'umi';
import { Breadcrumb, Card, Form, Modal, Table, Select, Row, Col, Input, Button, Radio } from 'antd';
import { Link } from 'react-router-dom';
import { Page } from 'components'
function testList(props) {
    let { dispatch, info, list, params, totals, loading, form } = props;


    return (
        <Page inner>
            <h1>大叔大婶多多多多多多多多多多多多多多多多多多多多多多</h1>
        </Page>

    )
}

function mapStateToProps(state) {
    return {
        ...state.testListModel,
    }
}
export default connect(mapStateToProps)(testList);
`




`/* global window */

import { history } from 'umi'
import { stringify } from 'qs'
import store from 'store'
const { pathToRegexp } = require("path-to-regexp")
import { ROLE_TYPE } from 'utils/constant'
import { queryLayout } from 'utils'
import { CANCEL_REQUEST_MESSAGE } from 'utils/constant'
import api from 'api'
import config from 'config'

const { queryRouteList, logoutUser, queryUserInfo } = api

export default {
  namespace: 'testListModel',
  state: {
   
  },
  subscriptions: {
    setup({ dispatch, history }){
        return history.listen(({ pathname, search }) => {
          if(pathname === '/testList'){
            dispatch({ type: 'init' })
          }
        })
      }
  },
  effects: {
    *init({ payload }, { call, put }){
      
      },
  },
  reducers: {
    updateState(state, { payload }) {
      return {
        ...state,
        ...payload,
      }
    },
  },
}
`


` {
    id: '99',
    breadcrumbParentId: '1',
    name: '测试列表',
    icon: 'user',
    route: '/testList',
  },
`

![image](https://user-images.githubusercontent.com/40377613/100591660-07128380-3331-11eb-8d65-0de7e6315a9d.png)

**Comment by Herozzq** [comment]
路由配错了，已经解决了
