### ISSUE TITLE
v5.3.0版本，启动错误

### ISSUE THREAD

**Issue by leelance** [zuiidea/antd-admin#1085]
您好，我在下载v5.3.0版本后，本地运行：
`
Node:  v12.14.1
yarn install

yarn run start
`
然后浏览器：http://127.0.0.1:7000/

提示错误如下：
`
You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
`
![image](https://user-images.githubusercontent.com/2662685/104542324-40435080-565e-11eb-8d53-b0f52e27cca0.png)

感谢!

**Comment by superlbr** [comment]
这边测试下来，win10是ok的。建议yarn使用淘宝源
```yarn config set registry https://registry.npm.taobao.org/```

**Comment by leelance** [comment]
> 这边测试下来，win10是ok的。建议yarn使用淘宝源
> `yarn config set registry https://registry.npm.taobao.org/`

我是这样操作的： yarn install --registry=https://registry.npm.taobao.org
不好意思， 新手麻烦指导下

**Comment by superlbr** [comment]
>我是这样操作的： yarn install --registry=https://registry.npm.taobao.org

再运行下，也不行么？是不是对代码做了改动？屏幕上有什么提示呢？

**Comment by leelance** [comment]
> > 我是这样操作的： yarn install --registry=https://registry.npm.taobao.org
> 
> 再运行下，也不行么？是不是对代码做了改动？屏幕上有什么提示呢？



非常感谢， 可以了； 不知道什么问题， 我把项目删除了，重新从5.3.0标签拉取， 然后
yarn install --registry=https://registry.npm.taobao.org
yarn run start

现在可以了；

非常感谢老铁的模板， 解决了我们前端薄弱这块问题
