### ISSUE TITLE
关于request.js源码的一点不理解。

### ISSUE THREAD

**Issue by yipanhuasheng** [zuiidea/antd-admin#1086]
src/utils/request.js在request看到如下代码，想问问;[domain]=urlMatch这个分号有什么骚操作吗，防止报错啥的吗？
`let domain = ''
    const urlMatch = url.match(/[a-zA-z]+:\/\/[^/]*/)
    if (urlMatch) {
      ;[domain] = urlMatch
      url = url.slice(domain.length)
    }`

**Comment by superlbr** [comment]
普通的分号而已，不必过度解读
