### ISSUE TITLE
运行extract提取代码中需要翻译的文字报错

### ISSUE THREAD

**Issue by GEOHOTIOS** [zuiidea/antd-admin#1088]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
按照5.0的文档上
运行extract提取代码中需要翻译的文字报错
> 2.1 简单描述下报错  
提示不支持jsx语法
Support for the experimental syntax 'jsx' isn't currently enabled
> 2.2 你期望什么结果  
开箱即用
> 2.3 如何操作导致的  
npm run add-locale ja
npm run extract <- 执行到这里报错了
> 2.4 可提供运行环境信息  
系统: macOS Catalina 10.15.7
node版本 14.3.0
项目主分支(5.1.3分支无问题)
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
fix d897eb2
