### ISSUE TITLE
侧边栏收缩时二级菜单没有收缩

### ISSUE THREAD

**Issue by panxinyang2014** [zuiidea/antd-admin#109]
如下图所示，浏览器为Chrome或者Edge
![default](https://cloud.githubusercontent.com/assets/7912642/23703803/b4ddc498-043c-11e7-88fd-2f710dcc21fa.png)

**Comment by liekkas** [comment]
感觉是antd的问题

**Comment by zuiidea** [comment]
最新的代码已经解决了

**Comment by JackZong** [comment]
@liekkas 这是antd的问题吗 ？ 你是怎么解决的

**Comment by zhayes** [comment]
@zuiidea  我在 最新的 3.0.1 版本里 又发现了这个问题 请问如何解决，设置超出隐藏吗？
