### ISSUE TITLE
登录的时候，为什么会把账号和密码，带到query中。 demo这样设计是不是有问题？

### ISSUE THREAD

**Issue by qinglong-zeng** [zuiidea/antd-admin#1093]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复
![image](https://user-images.githubusercontent.com/25050827/110583863-4ca0e100-81a9-11eb-92a6-b4fad1b4c033.png)

**Comment by superlbr** [comment]
去掉这行就好 https://github.com/zuiidea/antd-admin/blob/9e4e0efbabb4d961bf08dd89f6aa047a96da41ad/src/utils/request.js#L36
