### ISSUE TITLE
SyntaxError: Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by rainyhuynh** [zuiidea/antd-admin#1094]
Please give me adivse for error when I run "npm run start" after clone antd-admin source. 

Please give me advice.
Thank you.

**Comment by superlbr** [comment]
if (ie) give up,go chrome
else yarn install

**Comment by rainyhuynh** [comment]
I ran yarn install already and try many browsers but it's not working.

**Comment by superlbr** [comment]
1. both mac and win runs well in my side
2. if not yarn's network or mirror error, must be your change to user.js related in error above, check your code
