### ISSUE TITLE
Lingui error and deprecated modules

### ISSUE THREAD

**Issue by mukitafans** [zuiidea/antd-admin#1095]
antd admin seems to be deprecated, i tried a lot of changes in the modules but appears the same error with json of languages... this appears a few days.

It happens when i try to clone the repository, that gives error because babel-plugin-import is not installed but the last week all the modules seem to work correctly, when i install that plugin appears this warning and lingui doesnt work more...
![imagen_2021-03-16_095351](https://user-images.githubusercontent.com/48056123/111281694-82c4e180-863d-11eb-895d-b0b6c0c3fe0a.png)

**Comment by superlbr** [comment]
`babel-plugin-import` mis and lingui error is caused by dep upgrade

> antd admin seems to be deprecated

hah, seems. Talk a lot with author recently, hooks or vite, just too subjectively to upgrade.

**Comment by mukitafans** [comment]
haha, okay so there is any solution for the warning or i must update some of the modules too?

**Comment by superlbr** [comment]
@mukitafans done #d92f121
