### ISSUE TITLE
静态资源放到哪里呢

### ISSUE THREAD

**Issue by wangjiaxi90** [zuiidea/antd-admin#1098]
您好，我想问一下，我现在又一个页面 index.js就一个简单的返回image标签
import React, { PureComponent } from 'react'
export default class 显示图片 extends PureComponent {
    render() {
        return (
            <image src="pic/a.png"></image>
        )
    }
}

我这个pic/a.png应该在哪个目录下啊？

**Comment by superlbr** [comment]
public文件夹下面是静态文件

**Comment by wangjiaxi90** [comment]
谢谢谢谢，我已经实现了。
