### ISSUE TITLE
约定路由无效了，找不到配置的路由项？这是bug吗

### ISSUE THREAD

**Issue by aqnaruto** [zuiidea/antd-admin#1100]
最新代码 随便 用 umi g page yemian 无法访问
实测 umi 单独使用 时 是有效的。
整个代码里面也没有找到配置路由的代码？
是我太蠢 找不到 还是代码 约定路由被整没了？

**Comment by superlbr** [comment]
因为权限，mock/route.js

**Comment by aqnaruto** [comment]
我的错 我关闭

**Comment by superlbr** [comment]
哈哈，淡定，一开始我也摸了一会儿
