### ISSUE TITLE
[Deployment] Failed to deploy to Cloudflare Pages and Vercel

### ISSUE THREAD

**Issue by kevinadhiguna** [zuiidea/antd-admin#1102]
Hi, I failed to deploy this project to static-site hosting services such as Cloudflare Pages and Vercel.

[ Cloudflare Pages ]
This is one I deployed to Cloudflare Pages : 
![image](https://user-images.githubusercontent.com/43397636/120048931-ba3f0980-c042-11eb-9761-5d16af376d98.png)

I think the Build Settings in Cloudflare Pages has no problems : 
![image](https://user-images.githubusercontent.com/43397636/120049339-d7c0a300-c043-11eb-9b42-8ff96a195491.png)

I did not see any issues in the build logs in Cloudflare Pages though : 
![image](https://user-images.githubusercontent.com/43397636/120049127-376a7e80-c043-11eb-98a4-89c37629fa7b.png)

[ Vercel ]
This one is the result of deploying to Vercel : 
![image](https://user-images.githubusercontent.com/43397636/120048954-caef7f80-c042-11eb-9d76-f5da32451590.png)

This is the Build & Development Settings in Vercel, in which the build command was `npm run build` or `umi build` which came by default as framework preset was UmiJS : 
![image](https://user-images.githubusercontent.com/43397636/120049202-713b8500-c043-11eb-9b56-d15b090fe057.png)

No error was found in the build logs in Vercel : 
![image](https://user-images.githubusercontent.com/43397636/120049067-143fcf00-c043-11eb-9f74-17429ceaf441.png)

## Steps to reproduce : 
1) Fork this project
2) Go to Vercel and Cloudflare Pages
3) Set framework preset as UmiJS
4) Deploy the project
5) Visit the URL provided by both hosting services, then see the deployed project is blank (only displays white page).

**Comment by superlbr** [comment]
delete publicPath in .umirc.js

**Comment by kevinadhiguna** [comment]
Thanks for the fix, it was helpful @superlbr. However, authentication works on localhost but not on the deployed site. Any suggetsion ?

Steps to reproduce :
1. Access website
2. Enter username and password (both are `guest`)
3. click login button
4. Nothing happens on the deployed site but I was redirected to admin dashboard when trying it on localhost.

**Comment by superlbr** [comment]
deploy means production, mock only works in develop(by ```yarn start```)
