### ISSUE TITLE
http://localhost:7000/  为什么会跳转到登录页面？

### ISSUE THREAD

**Issue by resuper** [zuiidea/antd-admin#1104]
萌新求助

**Comment by superlbr** [comment]
逻辑在src/models/app.js 里的*query中

**Comment by resuper** [comment]
谢谢大佬指点，我明白啦，原来逻辑入口在subscriptions里，dva官方对subscriptions的解释有点儿粗糙，看了文档来看这个项目没看懂，谢谢大佬指点；
---
自己查阅文档得知：
- subscriptions 中配置的key的名称没有任何约束，而且只有在app.unmodel的时候才有用。
- subscriptions 中配置的只能dispatch所在model的reducer和effects。
- subscriptions 中配置的函数只会执行一次，也就是在调用 app.start() 的时候，会遍历所有 model 中的 subscriptions 执行一遍。
- subscriptions 中配置的函数需要返回一个函数，该函数应该用来取消订阅的该数据源。
> 参考两篇文章
> ![https://juejin.cn/post/6925602835388170248](https://juejin.cn/post/6925602835388170248)
> ![https://www.jianshu.com/p/9a8d3d3fb509](https://www.jianshu.com/p/9a8d3d3fb509)
