### ISSUE TITLE
npm run start启动报错

### ISSUE THREAD

**Issue by chenxianpao** [zuiidea/antd-admin#1106]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
![image](https://user-images.githubusercontent.com/8839777/123935092-7d11c280-d9c6-11eb-9c85-bf5b3c676167.png)

> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
git clone master  | cnpm install | cnpm run start   | win7
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
just remove webpack5 in .umirc for now

**Comment by chenxianpao** [comment]
@superlbr thanks!
