### ISSUE TITLE
umi.js from Terser TypeError: _jestWorker.Worker is not a constructor 

### ISSUE THREAD

**Issue by srykatt** [zuiidea/antd-admin#1108]
**Describe the bug**
无法启动项目 提示 ：Failed to compile with 26 errors    
umi.js from Terser
TypeError: _jestWorker.Worker is not a constructor

**To Reproduce**
1. git clone 下载项目
2. 进入目录后，npm install 
3. npm start
4. 错误出现

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52044483/124847777-27dd3e80-dfce-11eb-9129-a2924d36d85a.png)

**Desktop (please complete the following information):**
 - OS: MACOS   Big Sur 11.4 (20F71)
 - Browser  chorme  
 - Version  版本 91.0.4472.114（正式版本） (arm64)

**Additional context**
补充：
1. 该设备是 M1 设备。

**Comment by superlbr** [comment]
seems duplicate in https://github.com/zuiidea/antd-admin/issues/1106

**Comment by tigerjiang** [comment]
It doesn't useful when I accorde the issue #1106

**Comment by superlbr** [comment]
oh, really, so what's this
![截屏2021-07-13 下午5 17 53](https://user-images.githubusercontent.com/8142164/125427083-624da5b7-e454-494f-83b2-6f267bf525d8.png)
