### ISSUE TITLE
IE9、10、11下二级菜单打不开，报js错误

### ISSUE THREAD

**Issue by panxinyang2014** [zuiidea/antd-admin#111]
IE9、10、11下二级菜单打不开，报js错误（components\layout\menu.js）：
![2png](https://cloud.githubusercontent.com/assets/7912642/23739904/0dde117a-04dc-11e7-81e5-0def86f9355d.png)

**Comment by pmg1989** [comment]
需要引入babel-polyfill，可参见[IE 9+ 方案](https://github.com/pmg1989/dva-admin/issues/1)

**Comment by panxinyang2014** [comment]
已经解决了，谢谢。
