### ISSUE TITLE
umi升级

### ISSUE THREAD

**Issue by wooxyz** [zuiidea/antd-admin#1112]
将umi升级到3.5.15，在.umirc.js中添加mfsu: {}后，启动服务，然后报了一大堆错误

src_pages_user_id_index_less_modules.js from Terser
TypeError: _jestWorker.Worker is not a constructor
    ...

zrender.js from Terser
TypeError: _jestWorker.Worker is not a constructor
   ...

echarts.js from Terser
TypeError: _jestWorker.Worker is not a constructor
   ...

请问这个如何修复下？

**Comment by superlbr** [comment]
duplicate in #1110 
记得先把src下.umi删掉

**Comment by wooxyz** [comment]
@superlbr thx

**Comment by wooxyz** [comment]
@superlbr  还是上面的配置，开启mfsu后，服务可以启动，但运行报了如下错误
![image](https://user-images.githubusercontent.com/33221294/127996215-1ae1f2c6-8049-4376-b8d6-6fb58a788e04.png)

**Comment by superlbr** [comment]
@wooxyz 先把src下.umi删掉

**Comment by wooxyz** [comment]
删了，删了，删了，还是一样错误啊

**Comment by superlbr** [comment]
把umirc里的chainwebpack部分删掉

**Comment by wooxyz** [comment]
注释是可以了，那文件分离也需要咋办？

**Comment by superlbr** [comment]
```!isDevelopment && config.merge```

**Comment by superlbr** [comment]
```!isDevelopment && config.merge```
