### ISSUE TITLE
antd与element ui 样式冲突

### ISSUE THREAD

**Issue by YvanSuen** [zuiidea/antd-admin#1118]
我在项目中引入了antd与element ui两种组件，现在出现了两种组件图标覆盖的情况，如图
![image](https://user-images.githubusercontent.com/76144573/137662016-4e9b2ae2-99be-49f0-8902-22a4801d4f15.png)
请问我应该怎样解决这个问题

**Comment by superlbr** [comment]
1. 首先不建议混用
2. 其次是否都是按需引用
3. 从类名上来看，没有冲突的样子，这个情形目测是图标缺失
4. 本地测试了一下，可以正常使用，没有看到冲突的情况
