### ISSUE TITLE
关于同时用代理及mock数据的问题

### ISSUE THREAD

**Issue by xiaosansiji** [zuiidea/antd-admin#112]
在调试的时候，后台有部分功能已经上线了，但有部分还没做好，这时我想一部分走proxy直接到本地8080端口的api，一部分还走浏览器mock的数据api，这个要怎么搞来？
我现在的做法是，使用npm run start启动，注释掉了原先mock里的URL处理，
然后在proxy.config.js里增加了到localhost的代理：
![image](https://cloud.githubusercontent.com/assets/7600149/23740677/a671d202-04df-11e7-8a14-8b469991f582.png)
但是实际上在浏览器里只会在默认的8989端口访问api，并不会去本地8080端口
![image](https://cloud.githubusercontent.com/assets/7600149/23740732/e696b74e-04df-11e7-963d-e166394e3fb3.png)
我试过同时用mock，把service里面的URL直接带本机端口：
![image](https://cloud.githubusercontent.com/assets/7600149/23741032/6619a548-04e1-11e7-830f-bd5b96bbf32a.png)
但是浏览器会报xhr跨域的问题。

**Comment by xiaosansiji** [comment]
现在直接改成roadhog了

**Comment by zuiidea** [comment]
@xiaosansiji  我最新封装了一个`./src/util/request.js`，可以拿去改改，支持CORS，JSONP，YQL跨域

**Comment by xiaosansiji** [comment]
@zuiidea 嗯嗯，看到了，我最近也改了这里，不过用的dva直接返回的fetch：
![Uploading image.png…]()

不过跨域这里的设置确实还是很有借鉴意义的，多谢~

**Comment by allinshang** [comment]
@zuiidea ,最新的./src/util/request.js的jsonp跨域，具体怎么使用呢。。谢谢
