### ISSUE TITLE
There is dependency issue of react. While npm i, using node v16. 

### ISSUE THREAD

**Issue by rishat5081** [zuiidea/antd-admin#1126]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

here is the complete errors

npm WARN Could not resolve dependency:
npm WARN peer react@"~0.14 || ^15.0.0 || ^16.0.0" from react-highcharts@16.1.0
npm WARN node_modules/react-highcharts
npm WARN   react-highcharts@"^16.1.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: antd-admin@5.3.0
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"~0.14 || ^15.0.0 || ^16.0.0" from react-highcharts@16.1.0
npm WARN   node_modules/react-highcharts
npm WARN     react-highcharts@"^16.1.0" from the root project
npm WARN   1 more (react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"~0.14 || ^15.0.0 || ^16.0.0" from react-highcharts@16.1.0
npm WARN   node_modules/react-highcharts
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@">=16.0.0" from @ant-design/icons@4.7.0
npm WARN   node_modules/@ant-design/icons
npm WARN     @ant-design/icons@"^4.6.2" from the root project
npm WARN     1 more (antd)
npm WARN   9 more (react-dom, @lingui/react, antd, draft-js, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"~0.14 || ^15.0.0 || ^16.0.0" from react-highcharts@16.1.0
npm WARN node_modules/react-highcharts
npm WARN   react-highcharts@"^16.1.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@">=16.0.0" from @ant-design/icons@4.7.0
npm WARN   node_modules/@ant-design/icons
npm WARN     @ant-design/icons@"^4.6.2" from the root project
npm WARN     1 more (antd)
npm WARN   9 more (react-dom, @lingui/react, antd, draft-js, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"~0.14 || ^15.0.0 || ^16.0.0" from react-highcharts@16.1.0
npm WARN node_modules/react-highcharts
npm WARN   react-highcharts@"^16.1.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: antd-admin@5.3.0
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"~0.14 || ^15.0.0 || ^16.0.0" from react-highcharts@16.1.0
npm WARN   node_modules/react-highcharts
npm WARN     react-highcharts@"^16.1.0" from the root project
npm WARN   1 more (react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"~0.14 || ^15.0.0 || ^16.0.0" from react-highcharts@16.1.0
npm WARN   node_modules/react-highcharts

**Comment by superlbr** [comment]
nothing to do with node v16, use yarn or change npm mirror

**Comment by rishat5081** [comment]
> nothing to do with node v16, use yarn or change npm mirror
I did not mean about v16, i wanted to show the issue
