### ISSUE TITLE
router.js有点看不懂，为什么没有按react-router那样写呢？

### ISSUE THREAD

**Issue by zyx4986** [zuiidea/antd-admin#113]
里面一些函数比如 getIndexRoute， require.ensure,cb这些没有看懂
如果要加 IndexRedirect 这些应该怎么加呢？

**Comment by zuiidea** [comment]
为了动态加载@zyx4986

**Comment by zyx4986** [comment]
相关文档可以看什么学习呢？另外我想在访问／时，路由转跳/dashboard可以怎样实现呢？

**Comment by zuiidea** [comment]
@zyx4986  
- https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md
- https://github.com/dvajs/dva-knowledgemap

**Comment by evanoxu** [comment]
如果在当前这种写法下，要加 IndexRedirect 这些应该怎么加呢？
我想在访问／时，路由转跳/dashboard可以怎样实现呢？
