### ISSUE TITLE
穿梭框（Transfer）在非严格模式下，选中父节点，再选中子节点，父节点选中状态没有取消；

### ISSUE THREAD

**Issue by chseahai** [zuiidea/antd-admin#1133]
![image](https://user-images.githubusercontent.com/22994896/170953279-2c31adb1-953c-4232-a67b-b76dc9b17b85.png)

**Comment by superlbr** [comment]
1. 貌似跟antd-admin没有关系
2. 请移步ant-design。。或者试试v4？
