### ISSUE TITLE
AutoComplete onSelect偶现不会触发，且不更改输入框的值

### ISSUE THREAD

**Issue by cheapCoder** [zuiidea/antd-admin#1135]
> 请酌情提供细节，并保持issue精简便于查阅
> 2. Bug反馈  
经过form item包裹的Autocomplete组件onSelect可能不会触发
[![Edit 注册新用户 - antd@4.21.0 (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhu-ce-xin-yong-hu-antd-4-21-0-forked-ox3xhe?fontsize=14&hidenavigation=1&theme=dark)

![picture](https://user-images.githubusercontent.com/60960561/172294544-82c01105-0554-4232-9acb-161437f9f617.gif)

> 2.1 简单描述下报错  
无报错信息

> 2.2 你期望什么结果  
onSelect回调函数每次都能触发执行

> 2.3 如何操作导致的  
异步生成options配置对象，偶现选中一条option但输入框值不更改的情况

> 2.4 可提供运行环境信息  
    os: mac
    @ant-design/icons: 4.7.0,
    antd: 4.16.13,
    react: 16.14.0",
    react-dom: 16.14.0,
    react-scripts: ^4.0.0"

**Comment by superlbr** [comment]
handleBlur的逻辑有点问题，.com后缀会反复叠加。建议input加addonAfter后缀标签，清晰明了
