### ISSUE TITLE
[@umijs/runtime] load component failed TypeError: Cannot read properties of undefined (reading 'echarts')

### ISSUE THREAD

**Issue by HongLouyemeng** [zuiidea/antd-admin#1137]
项目克隆下来后，无法显示echarts图表
[@umijs/runtime] load component failed TypeError: Cannot read properties of undefined (reading 'echarts')

**Comment by superlbr** [comment]
可以试试[develop-next](https://github.com/zuiidea/antd-admin/tree/develop-next)分支
