### ISSUE TITLE
为什么提供的文档那几个网站打不开？

### ISSUE THREAD

**Issue by LAmorningsw** [zuiidea/antd-admin#1138]
document那几个网址都打不开是为什么？

**Comment by superlbr** [comment]
浏览下doc文件夹吧。域名、服务器啥的，@zuiidea

**Comment by yl196356303** [comment]
在线demo登录挂了。。。

**Comment by lingansha** [comment]
https://doc.antd-admin.zuiidea.com 打不开了

**Comment by SaulJWu** [comment]
2023年02月18日00:38:08
打不开

**Comment by superlbr** [comment]
https://superlbr.gitee.io/antd-admin/#/
