### ISSUE TITLE
Change proxy 

### ISSUE THREAD

**Issue by jl63** [zuiidea/antd-admin#1139]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

Hi, I want to change the proxy to test my backend at localhost:5000. I changed start in package.json to "start": "MOCK=none umi dev", and tried to add "proxy": "http://localhost:5000" in package json but when I am trying to fetch my api using fetch('/time') it still does not work. The request is still using localhost:7000. How could I changed the request proxy to the right port?
Thanks a lot!

**Comment by superlbr** [comment]
set proxy like code below in .umirc file
```
  proxy: {
    "/api/v1": {
      "target": "http://localhost:5000",
      "changeOrigin": true,
      "pathRewrite": { "^/api/v1": "/" }
    },
  },
```
