### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)  开发环境是正常的，打包后浏览器打开出问题

### ISSUE THREAD

**Issue by esperar** [zuiidea/antd-admin#1140]
umirc.js

  publicPath: '/',
  history: {
    type: 'hash',
  },

**Comment by esperar** [comment]
在src文件夹添加 app.js文件

import { message } from 'antd'

export const dva = {
    config: {
      onError(e) {
        e.preventDefault();
        if (e.message) {
            message.error(e.message)
          } else {
            /* eslint-disable */
            console.error(e)
          }
      },
    },
  };

浏览器访问http://127.0.0.1:5500/dist/#/  显示404 Not Found的页面，I18nProvider did not render. A call to i18n.activate still needs to happen or forceRenderOnLocaleChange must be set to false.

**Comment by esperar** [comment]
和https://github.com/zuiidea/antd-admin/issues/1064#issue-641123094 相同的界面 404

**Comment by superlbr** [comment]
打开浏览器调试，可以看到静态文件走了一个域名
1. 需要在.umirc文件里，删掉或修改publicPath配置
2. /api/v1/user，需要请求后端的接口。调试的时候走的是mock
