### ISSUE TITLE
自己写登录接口

### ISSUE THREAD

**Issue by jl63** [zuiidea/antd-admin#1141]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

想请问一下如果我们想把登录换成自己的接口，除了handleok的时候调接口之外需要set什么store或者修改什么地方呢？用store.set了user和history.push跳转到dashboard以后会404，用户信息也get不到。谢谢！

**Comment by superlbr** [comment]
1. 登录接口只负责登录，后面就交给`yield put({ type: 'app/query' })`
2. 路由、权限什么的都在model/app.js里，调试看下就可以看到对应的请求了。跑一个正常的，跑一个你自己的，对比下，很清楚的。
