### ISSUE TITLE
启动直接报错，我的node版本是18.12.1

### ISSUE THREAD

**Issue by pfeducode** [zuiidea/antd-admin#1147]
使用npm run start启动,报错如下
![image](https://user-images.githubusercontent.com/100210045/215034857-42940392-1195-4aa7-91f7-9bd9aa76807f.png)

**Comment by superlbr** [comment]
node18需要额外运行一个命令，`set NODE_OPTIONS=--openssl-legacy-provider` ，详情可以百度

**Comment by pfeducode** [comment]
> set NODE_OPTIONS=--openssl-legacy-provider
cmd中输入上面的命令任然报错
https://github.com/zuiidea/antd-admin/issues/1147#issuecomment-1406169615

**Comment by pfeducode** [comment]
> node18需要额外运执行一个命令，`set NODE_OPTIONS=--openssl-legacy-provider`，详情可以百度
使用node 16版本可以正常运行
