### ISSUE TITLE
有没有项目说明文档

### ISSUE THREAD

**Issue by pfeducode** [zuiidea/antd-admin#1148]
有没有项目的说明文档啊，能不能注明哪些功能用的什么库，没有说明文档无从下手，项目中的doc中的index.html打不开啊
![image](https://user-images.githubusercontent.com/100210045/215128486-ae33a5c4-c4d8-4cef-8793-870bbf70d468.png)

**Comment by superlbr** [comment]
直接看md也可以

**Comment by pfeducode** [comment]
> 直接看md也可以

好的，谢谢，我主要看前端怎么调用后端API这一部分
