### ISSUE TITLE
打开之后无法加载页面

### ISSUE THREAD

**Issue by pfeducode** [zuiidea/antd-admin#1149]
2.打开之后，不报错，也不显示页面
![image](https://user-images.githubusercontent.com/100210045/216562012-a9c74966-a5ac-4f89-9122-ac51f363587d.png)

**Comment by superlbr** [comment]
麻烦检查下控制台、命令端，应该有提示的

**Comment by pfeducode** [comment]
> 麻烦检查下控制台、命令端，应该有提示的

我把项目删了，从新搭建，可以访问了，谢谢
