### ISSUE TITLE
Select tag mode bug 

### ISSUE THREAD

**Issue by VertigoSHI** [zuiidea/antd-admin#1151]
现象: 在tags 模式下无法接受多个重复的 tag 的值的输入
属性设置:  style={{ width: "20vw" }}
        mode="tags"
        tokenSeparators={[',', ' ']}
        dropdownStyle={{ display: "none" }}
版本: 4.22.8   react:^18.2.0,

**Comment by superlbr** [comment]
antd的问题，请前往 https://github.com/ant-design/ant-design/issues
