### ISSUE TITLE
npm run start doesn't work

### ISSUE THREAD

**Issue by caapontedev** [zuiidea/antd-admin#1152]
![image](https://user-images.githubusercontent.com/126507583/221643780-ea965484-525b-4a94-8fe5-4afdcf453ab4.png)

It wouldn't start with the step-by-step guide provided. 

Opted to add this (see below) but it didn't work either.

![image](https://user-images.githubusercontent.com/126507583/221644204-158ce5f3-5155-46f3-b4a4-8411215ca22d.png)

Thanking you in advance if you could provide further information of how to deploy this template properly

**Comment by superlbr** [comment]
`--openssl-legacy-provider` is just a tip, just google and then solution come out.
Here's the solution, for nodejs >= 18.x.
Windows: `set NODE_OPTIONS=--openssl-legacy-provider && umi dev`
Linux: `export NODE_OPTIONS=--openssl-legacy-provider && umi dev`

**Comment by superlbr** [comment]
keep it open for convenience

**Comment by Batato8291** [comment]
windows:
`"start": "set NODE_OPTIONS=--openssl-legacy-provider && umi dev",`

**Comment by LDD123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by liukx-kellen** [comment]
still doesn`t work

**Comment by LDD123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by superlbr** [comment]
@liukx-kellen show the error, use my solution?
