### ISSUE TITLE
 macbook中出现Assertion Error，无法npm run start

### ISSUE THREAD

**Issue by yixcai** [zuiidea/antd-admin#1153]
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: antd, dva, dynamicImport, nodeModulesTransform, webpack5

macbook中出现Assertion Error，无法npm run start

**Comment by LDD123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yixcai** [comment]
<img width="941" alt="截屏2023-03-28 16 07 37" src="https://user-images.githubusercontent.com/80435526/228133906-6caa0791-762d-4933-96e1-902c19172d5a.png">

**Comment by superlbr** [comment]
请检查umirc配置文件，如果你使用umi4，请参考对应文档
