### ISSUE TITLE
develop分支，修改主题色无效

### ISSUE THREAD

**Issue by wfyweb** [zuiidea/antd-admin#1154]
在 themes 文件 defaults.less 中添加 @primary-color主题色页面未生效。
![01dc3f939c129dab81135aae3dbae3a](https://user-images.githubusercontent.com/26135637/231466834-bb3dccb1-8b35-4d73-b7fc-67dedac4842b.png)

**Comment by wfyweb** [comment]
umi build 编译后主题色生效，本地环境不生效，请教大佬是什么呐

**Comment by superlbr** [comment]
`@primary-color: pink !important;`
