### ISSUE TITLE
Proxy 问题

### ISSUE THREAD

**Issue by Hongda-OSU** [zuiidea/antd-admin#1155]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by LDD123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Hongda-OSU** [comment]
大佬你好，我有一个关于 Proxy 的问题：
我看了下那些关于调用后端 api 的 issue，如果要使用自己的后端，应该在 services/index.js 里面去给 APIFuction 加。（比如 queryWeather）然后在 .umirc.js 里去改 proxy。

我现在有一个服务器在 localhost:7050 上面跑，比如我要调用 api/XXX，我试着去改 .umirc.js 关于 queryWeather 的 proxy
proxy: {
    '/api/v1/weather': {
      target: 'https://localhost:7050',
      changeOrigin: true,
      pathRewrite: {'^/api/v1/weather/now.json': '/api/XXX' },
    },
但是 VSCODE 这边给我报了 [HPM] Error occurred while trying to proxy request /api/XXX from localhost:7000 to https://localhost:7050 (DEPTH_ZERO_SELF_SIGNED_CERT)

前端小白，希望大佬能给点帮助。

**Comment by Hongda-OSU** [comment]
解决方案是：不需要加 process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; 但是在 proxy 里添加 secure: false （会接着去尝试）

**Comment by superlbr** [comment]
一般来说，前端部署之后，都会直接请求域名，也就是后端接口api。umirc只是开发调试有效

**Comment by Hongda-OSU** [comment]
大佬的意思是不是直接在 utils/requests.js 里面直接改 domain？

**Comment by Hongda-OSU** [comment]
大佬，我还想问一下，如果我要新增一个 route，能不用修改 mock/route.js 就添加吗。我想直接从后端调数据，而不是去 mock 数据。比如我想添加 /picture 这个 route，我尝试去 pages 下面直接加一个 picture folder 然后往里面加 index.js 和 model.js。我以为按照 umi 的约定式路由应该能成，但是我看了下 localStorage 中 routeList 里面并没有我想要的 route. 

（models 下面的 app.js 应该是去调了 mock/route.js 里的 queryRouteList）

**Comment by Hongda-OSU** [comment]
我现在的做法是:
1. 在 mock/route.js 里面添加 
![Screenshot 2023-06-02 231032](https://github.com/zuiidea/antd-admin/assets/67817916/9ecebd60-9db2-45a4-a0f4-35890c754cc4)
然后将 6 加进 mock/user.js 里的 userPermission 中。（这一步下来确实 Menu 栏有 Pictures，但是我感觉这样添加路由的方法很奇怪）

2. 在 service/index.js 里面添加
![Screenshot 2023-06-02 231400](https://github.com/zuiidea/antd-admin/assets/67817916/ef0fffd0-cd86-41bd-963a-56ff39d5bf7c) 
backendApp 就是之前后端的域名 https://localhost:7050

3. 在 page 下添加 folder picture，然后添加 index.js 和 model.js
![Screenshot 2023-06-02 231832](https://github.com/zuiidea/antd-admin/assets/67817916/18ab5bbc-e1e6-41ab-a78d-722804a498da)
![Screenshot 2023-06-02 231947](https://github.com/zuiidea/antd-admin/assets/67817916/bd7d662a-5a6e-4b53-99c1-de1fd38393e2)
我本来以为点击 Pictures 后就可以将 model 里的 data 给 log 出来，但是 Network 里却没有对应的 request。

**Comment by superlbr** [comment]
queryPictures没有触发吗？  
`pathToRegexp('/picture').exec(location.pathname) `看的别扭。直接location.pathname =='/picture'就行

**Comment by Hongda-OSU** [comment]
对，没有触发。我以为应该会有类似点击 dashboard 时 network 里的 request。
![Screenshot 2023-06-03 134641](https://github.com/zuiidea/antd-admin/assets/67817916/fbcfcf4b-65de-4129-8ef0-28122a4decf4)
但是什么都没有

**Comment by Hongda-OSU** [comment]
好吧，我太笨了。我把那个请求放到 try catch里面发现我 service/index.js 里面有一个变量没有引入。

**Comment by Hongda-OSU** [comment]
嗯，我想出来了，谢谢
