### ISSUE TITLE
技术问题，怎么实现受控表单

### ISSUE THREAD

**Issue by zhaozhuoguang** [zuiidea/antd-admin#1157]
> 1. 功能需求 => antd官网有个例子http://react-component.github.io/form/examples/redux.html，但我知识面不够，迁移不了。是要实现表单初始赋值，修改 state 值后显示到表单或修改表单后 state 值跟着改。

**Comment by LDD123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by superlbr** [comment]
推荐查看antd文档，[表单方法调用](https://ant.design/components/form-cn#components-form-demo-control-ref)
