### ISSUE TITLE
Demo Prevew version diffirence git clone version?

### ISSUE THREAD

**Issue by tanobi92** [zuiidea/antd-admin#1159]
I downloaded the project and ran it locally, but I see a difference between the local and web preview versions:
- Local: darker colors, rounded button corners, more rounded text,...

- Local:
![Thiết kế chưa có tên](https://github.com/zuiidea/antd-admin/assets/11570162/c92a5b60-931c-433a-94f0-ff6bd5462511)
- Web preview: https://antd-admin.zuiidea.com/
![Thiết kế chưa có tên (1)](https://github.com/zuiidea/antd-admin/assets/11570162/aacb2399-d5be-4edd-b140-2cc9abddb88c)

**Comment by superlbr** [comment]
Web preview maybe outdated
