### ISSUE TITLE
auto focus on modal open

### ISSUE THREAD

**Issue by afvs161** [zuiidea/antd-admin#1163]
How to focus to this input after modal has been opened? I can't use `useRef` cause it's not a component and `autoFocus` is not working, probably cause I have to click button to open this modal

```
export const payModal = () => {
	confirm({
		icon: " ",
		title: <Input type="text" />,
	})
}
```

**Comment by LDD123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by superlbr** [comment]
how about use `Modal` not `confirm`

**Comment by afvs161** [comment]
it's just that `confirm` was a better fit for my case, yes I can customize `modal` and use it
