### ISSUE TITLE
怎么实现热更新

### ISSUE THREAD

**Issue by jackple** [zuiidea/antd-admin#118]
现在修改了文件是会刷新浏览器的

**Comment by zuiidea** [comment]
`npm run dev`目前就是热更新的啊

**Comment by jackple** [comment]
@zuiidea 是直接刷新,没有热更新,你更新个react组件试试

**Comment by chuncui0207** [comment]
+1

**Comment by zuiidea** [comment]
你们想要的那种没办法哦

**Comment by zuiidea** [comment]
关注[#164](https://github.com/zuiidea/antd-admin/issues/164)
