### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by sxl53037072** [zuiidea/antd-admin#119]
![11](https://cloud.githubusercontent.com/assets/3907037/23930902/2c170e52-096a-11e7-92b6-35b86857c0b6.png)

**Comment by pmg1989** [comment]
感觉你包安装的好像有问题吧

**Comment by YouEclipse** [comment]
+1 在本地用MAC 编译正常，在ubuntu 编译报错。
我用的是3.0的版本
![image](https://cloud.githubusercontent.com/assets/8252317/23936045/bb65ae18-098a-11e7-91c9-35405dfd669c.png)

**Comment by YouEclipse** [comment]
本地（MAC）把node_modules 删了，重新npm install 也报错了，应该是react-countup这个包的问题。
![image](https://cloud.githubusercontent.com/assets/8252317/23936774/dfe0cc6a-098e-11e7-8165-93bea210110d.png)

**Comment by YouEclipse** [comment]
解决了，看了下，这个作者在3月10号发布了新版本的包，默认npm install 会安装最新的包，1.3.0后的版本都会报错，我切成1.3.0就ok了。具体什么原因我不太清楚，可能是es5和es6语法的问题。 @sxl53037072 @pmg1989

**Comment by YouEclipse** [comment]
![image](https://cloud.githubusercontent.com/assets/8252317/23937579/35961da0-0993-11e7-969a-4fe37f9ba4b0.png)

**Comment by pmg1989** [comment]
@YouEclipse 你用yarn吧，可能就不会出现了

**Comment by shichenda** [comment]
我也出现了相同的问题
楼主解决方案说明白点儿

**Comment by zuiidea** [comment]
@shichenda `npm i react-countup@1.3.0`

**Comment by shichenda** [comment]
我已经解决了。用 yarn install会检测并安装  package 里面的模块和指定版本号，用 npm i 就会安装最新版本。这可能是最新npm版本的问题。我记得我原来用的npm i 安装就会安装package里面的指定版本。不管怎么说，感谢大牛提供这些个好用的工具和框架。你们辛苦了。为你们点赞。

**Comment by zuiidea** [comment]
我也是初学者，共同学习

**Comment by TopGuo** [comment]
我再npm run build 后，生产的dist文件夹下，找到index.html，但是打开时空白页，这个是什么情况>?

**Comment by superlbr** [comment]
@TopGuo antd-admin使用umi，类create-react-app的打包工具，部署的方式参考https://facebook.github.io/create-react-app/docs/deployment

**Comment by TopGuo** [comment]
> @TopGuo antd-admin使用umi，类create-react-app的打包工具，部署的方式参考https://facebook.github.io/create-react-app/docs/deployment

好的，我理解了，是得部署到服务器才能浏览dist里的东西
