### ISSUE TITLE
选择robe-ajax的原因?

### ISSUE THREAD

**Issue by grunmin** [zuiidea/antd-admin#12]
作者没有使用dva封装的requests, 也不用axios这类常用的库. 使用的robe-ajax似乎只有寥寥几个star

**Comment by zuiidea** [comment]
robe-ajax封装的类似jq的ajax，没什么特别的原因，熟悉一点😭😭，我在注意事项提到了，你可以按照自己的写法改的

**Comment by zhump** [comment]
robe-ajax 有问题  无法设置请求的header 真心不好用，，，作者疯啦 -。-

**Comment by zuiidea** [comment]
哈哈哈。真实原因：在一个无服务器的环境中模拟数据请求，Mock不能拦截Fetch，只能拦截XHR，所以我选了一个类似jquery Ajax的库robe-ajax
