### ISSUE TITLE
请问如何修改webpack-dev-server

### ISSUE THREAD

**Issue by weilannet** [zuiidea/antd-admin#123]
想加入proxy代理解决跨域问题，但是找不到修改的地方。
查了一下说要修改proxy.config.js
{
      ‘/api/(.*)’:'http://10.10.10.10:port'
}
这种方式地址确实能代理过去，但是ajax的data参数没有带过去。
这个规则怎么配置，才能实现代理的功能呢？
多谢！

**Comment by zuiidea** [comment]
#164
