### ISSUE TITLE
npm run start 报错

### ISSUE THREAD

**Issue by weilannet** [zuiidea/antd-admin#124]
![qq 20170315190502](https://cloud.githubusercontent.com/assets/20507447/23945665/55d1ae4e-09b2-11e7-8b11-9bf57c3e9fea.jpg)
proxy.config.js 文件的作用是什么？

const mock = {}
require('fs').readdirSync(require('path').join(`${__dirname}/mock`)).forEach((file) => {
  Object.assign(mock, require('./mock/' + file))
})
module.exports = mock

为何mock 定义了const只读，下面还能修改？

**Comment by pmg1989** [comment]
你应该npm run dev，后面是个好问题！
可参见[why-can-i-change-value-of-a-constant-in-javascript](http://stackoverflow.com/questions/23436437/why-can-i-change-value-of-a-constant-in-javascript)
