### ISSUE TITLE
发现Modal里有个奇怪的Hack代码，想请教下。

### ISSUE THREAD

**Issue by TangMonk** [zuiidea/antd-admin#127]
在 [routes/users.js](https://github.com/zuiidea/antd-admin/blob/master/src/routes/users.js#L91) 中，有个特殊的 `UserModalGen` 方法，用来生成 `UserModal`弹出框，然后在return里render。

```
  const UserModalGen = () =>
    <UserModal {...userModalProps} />

  return (
    <div className="content-inner">
      <UserSearch {...userSearchProps} />
      <UserList {...userListProps} />
      <UserModalGen />
    </div>
  )
```

我想问的是，为什么不直接 return `<UserModal {...userModalProps} />`, 反而要用一个 `UserModalGen` 来包住:

```
  return (
    <div className="content-inner">
      <UserSearch {...userSearchProps} />
      <UserList {...userListProps} />
       <UserModal {...userModalProps} />
    </div>
  )
```

**Comment by zuiidea** [comment]
你是对的

**Comment by pmg1989** [comment]
@TangMonk，究其原因这其实应该是react里的受控组件的概念，Form的 initialValue 和 defaultValue 一样，只有初始化时才生效。具体可参见[controlled-components](https://facebook.github.io/react/docs/forms.html#controlled-components)
 尝试的解决方案感觉目前有两种，其一就如 @zuiidea ，
其二list中可以使用
![image](https://cloud.githubusercontent.com/assets/13361827/23992237/1d3091ac-0a77-11e7-8c77-2ce90232f7b8.png)
但需要在modal Form里resetFields，具体实现可以参见[https://github.com/pmg1989/dva-admin](https://github.com/pmg1989/dva-admin)

**Comment by TangMonk** [comment]
@zuiidea , 你的方式有问题，会导致modal渲染两次
应该在 modal 的 afterClose 方法里加上 resetFields()

**Comment by zuiidea** [comment]
@TangMonk 我封装了Moadl组件，可以测试一下
- 代码：https://github.com/zuiidea/antd-admin/blob/master/src/components/ui/layer.js
- 演示：http://zuiidea.com/antd-admin/#/ui/layer?_k=fhafkt

**Comment by suxiaohei** [comment]
@pmg1989 谢谢,正在为这个问题困扰.第一次使用react,知道问题所在,但是一直不知道react的reset方法怎么用,哈哈.
