### ISSUE TITLE
修改成roadhog各种报错

### ISSUE THREAD

**Issue by codefighting** [zuiidea/antd-admin#128]
请问我们的版本会更新成roadhog么，dva作者建议用roadhog

因为我用proxy,config.js 做跨域代理总是报错，又找不到可以修改webpack配置的地方

急！在线等大神回复

**Comment by wuyongdec** [comment]
同求换成roadhog怎么配置～
跨域可以用nginx反向代理

**Comment by xiaosansiji** [comment]
我已经换用roadhog了，在本地调试的时候用了不同后台的接口，在src下新建.roadhogrc文件，内容如下：
![image](https://cloud.githubusercontent.com/assets/7600149/24087250/aa392a5e-0d57-11e7-819b-36636f46cc1b.png)
跨域的设置应该是`"changeOrigin": true,` 这块还没具体研究，可以翻一翻原作者的文档

**Comment by dicklwm** [comment]
[Min-Admin](https://github.com/dicklwm/Min-Admin)，这是我用roadhog改造过的，欢迎指点指点

**Comment by zuiidea** [comment]
@dicklwm 没有关于数据mock的啊🙃

**Comment by dicklwm** [comment]
@zuiidea 我还没写mock用例，我在登录那写下mock用例吧

**Comment by wuyongdec** [comment]
@xiaosansiji 厉害了，package.json 怎么改的呢？

**Comment by xiaosansiji** [comment]
@wuyongdec ，sorry 没注意github的信息，package.json就是改下启动的脚本为roadhog的就好了
`"start": "set PORT=3000&&roadhog server --no-open",`
`"build": "roadhog build"`
