### ISSUE TITLE
dva脚手架如何按需加载？

### ISSUE THREAD

**Issue by logyLiang** [zuiidea/antd-admin#13]
现在项目越来越大，所有文件都积压在index.js内快10M了，所有我想做成按需加载。就是在路由这块调用页面时候。才把对应的route，service,components相关的所有文件加载。这相关的文件打成一个js文件。应该怎么做？没有思路！请教。

**Comment by zuiidea** [comment]
10M，有点恐怖，这个问题我也想知道，暂时还没找到合适的方案。

**Comment by logyLiang** [comment]
@zuiidea 这是没压缩前，压缩后也有3M多，demo就几个模块，pc端还好些，如果做运营后台系统在移动端流量就太多了。 问官网开发人员也没回我。
