### ISSUE TITLE
导航菜单缩回弹出,页面卡顿

### ISSUE THREAD

**Issue by zhangqqqf** [zuiidea/antd-admin#130]
当主页面视图为dashboard时, 进行导航菜单缩回或弹出, 整个动画过程缓慢卡顿, 不知道这个问题怎么解决

**Comment by 305758409** [comment]
发现dashboard里，把这个组件删掉卡顿会大幅减轻  <Completed data={completed} />

**Comment by xgenvn** [comment]
dashboard里元素太多了，是不是主要原因？其他view还可以的。

**Comment by zhangqqqf** [comment]
@305758409 哪个组件?

**Comment by zuiidea** [comment]
数字倒数的那个组件比较耗性能，不需要可以关掉
