### ISSUE TITLE
输入账号密码无法登陆进去

### ISSUE THREAD

**Issue by Zuckjet** [zuiidea/antd-admin#131]
git clone 下来你的代码，但是卡在登陆界面，输入账号密码后，无法登陆进去，请问这是怎么回事？

**Comment by 305758409** [comment]
在app.js里
req.body 实际存储的值为 "username=guest&password=guest"
const userItem = req.body
return item.username === userItem.username
导致userItem.username undefined
最后都会走分支 用户不存在
登录会变为永远失败

**Comment by 305758409** [comment]
在request.js第13行加上这句
processData: options.method === 'get',

**Comment by zuiidea** [comment]
@305758409 My fault，😂

**Comment by Zuckjet** [comment]
Thanks

**Comment by zhonglaoban** [comment]
为啥还是登不上
<img width="979" alt="2017-03-20 2 52 05" src="https://cloud.githubusercontent.com/assets/14174614/24090615/d43f5d4e-0d7c-11e7-9f6c-29114796ebfb.png">

**Comment by zuiidea** [comment]
@zhonglaoban `npm run dev`

**Comment by zhonglaoban** [comment]
@zuiidea npm run dev 已经执行了，[HMR] connected。就是登录不上。什么原因？

**Comment by zhonglaoban** [comment]
登上了，开发环境注释了mock
