### ISSUE TITLE
请问下，怎么全局应用系统语言为英文？

### ISSUE THREAD

**Issue by bofortitude** [zuiidea/antd-admin#133]
大神好，我看ant的官网是有个国际化的条目介绍的，但是看你这个项目是用dva的几步生成的，我有点晕了，不知道在哪个对应的地方全局应用英文，还望赐教~~多谢！

**Comment by zuiidea** [comment]
还没尝试过，你可以先试试 https://ant.design/docs/react/i18n-cn

**Comment by superlbr** [comment]
最新antd3.0默认全英文
