### ISSUE TITLE
想问下调试方法

### ISSUE THREAD

**Issue by xgenvn** [zuiidea/antd-admin#136]
你好，
我想问下如何本地调试项目？能设置断点调试吗？
作者是用哪个IDE开发和调试呢？

谢谢。

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/blob/master/assets/standard.md

调试就是Chrome啊

**Comment by xgenvn** [comment]
嗯我知道Chrome可以调试。如果能用VSCode或者Webstorm IDE调试就更好了。简单的nodejs应用我可以设置直接在IDE里设断点测试，但是这个项目下就不太懂如何设置了。
谢谢。

**Comment by xiaosansiji** [comment]
@xgenvn 我现在主要是chrome断点 + react 插件 + redux插件，断点看看自己的代码有没有问题，那两个插件看下从后台获取的数据及组件中的state有没有问题，感觉还是比较方便的
