### ISSUE TITLE
你好，请问一下怎么引入iconfont官网下载的字体图标库，自带的文字图标不够用

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#14]
你好，我这边按照官网提供的demo，替换官方的字体图标一直不成功，是不是因为一些依赖没有加载，还是别的原因啊，引入步骤是怎么样的呢？望解答，谢谢了

**Comment by zuiidea** [comment]
1. 如果是不需要antd的字体图标，那得在antd的lib/styles/index.css下将@font-face里的url更换为你在iconfont网站上的项目的url，然后重新编译
2. 如果只是新增图标，按照iconfont官网的做法就可以了，即是页面上添加iconfont生成的css文件，
需要注意的是添加项目时，
![image](https://cloud.githubusercontent.com/assets/16070518/21421760/85b567f6-c86f-11e6-9860-8237535e59c2.png)
另外为了图标不与antd自带图标冲突，这两个值都不要重复
![image](https://cloud.githubusercontent.com/assets/16070518/21421819/d4f69eca-c86f-11e6-83d3-c9c8b8edee64.png)

**Comment by encorehe** [comment]
好的 ，我试试了，谢谢了

**Comment by zuiidea** [comment]
https://github.com/visvadw/dvajs-user-dashboard/pull/2 @encorehe

**Comment by zuiidea** [comment]
@encorehe 我在这个项目里添加了一个Ico的组件，可以看下
![image](https://cloud.githubusercontent.com/assets/16070518/21481672/8586992e-cba5-11e6-912a-5a03b033f9c4.png)
