### ISSUE TITLE
请教下，routers/app.js中App的参数是怎么传进来的呢

### ISSUE THREAD

**Issue by mu2019** [zuiidea/antd-admin#150]
我跟了好久也没找到，弄不明白const App = ({ children, location, dispatch, app, loading }) 这句中的参数是怎么传进来的。
有人指点下吗？谢谢！

**Comment by mu2019** [comment]
总算有点眉目了，从dva createDva的start函数跟下去，收获不少。

**Comment by wuyongdec** [comment]
@mu2019 求指点，我也疑惑这个参数怎么传递

**Comment by mu2019** [comment]
@wuyongdec 
```
const MyApp = ({dispatch, session, app,models, props, kwargs, error}) => {
  return ( ...)
}
function mapStateToProps(state) {
  console.log('map state ',state);
  return { ...state };
}
export default connect(mapStateToProps )(MyApp);
```
主要是用connect传进来，其中mapStateToProps就是把state转为组件的props。可以看下关于高阶组件的文章
https://zhuanlan.zhihu.com/p/24776678
