### ISSUE TITLE
有没有针对不同用户设置的不同权限，然后显示不同的菜单栏呢？

### ISSUE THREAD

**Issue by wentao978** [zuiidea/antd-admin#160]

**Comment by zuiidea** [comment]
进行中..

**Comment by zlotus** [comment]
作者已经在`model/app`里设置`userPermissions`了，之后`effects.login`也返回`userPermissions`了，并且在`reducers.loginSuccess`中做了更新。所以理论上功能已经非常完备了~这个脚手架考虑的很周到~怒赞啊~

我是这么改的：
* 在`routes/app`里多获取一个`userPermissions`属性；
* 把该属性写进`siderProps`，就可以向下传入`components/Layout/Sider`了；
* 再把该属性写进`menusProps`，就可以向下传入`components/Layout/Menus`了；
* 最后把`components/Layout/Menus`里的`getMenus`稍微修改一下，判断`item.key`是否在`userPermissions`里，不在的话直接`return`就可以了~

一开始设计的好，改起来都特别顺:D
感谢作者~

**Comment by zlotus** [comment]
@zuiidea 入门JS很多地方不懂…谢谢 ~ 期待下一个版本的更新 ~

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/384

**Comment by timotanhong** [comment]
权限在客户端控制有安全问题吧

**Comment by kevin50ster** [comment]
我也认为前端权限资源登陆成功后从后端获取，前端对角色的权限设置保存在后端，这样比较合适。

**Comment by zuiidea** [comment]
@timotanhong  @kevin50ster #384 就是从后端获取啊
