### ISSUE TITLE
3.0 ie9运行到yield call 提示 uncaughtat anonymous 错，访问不了后台，这个可能是什么原因呢？

### ISSUE THREAD

**Issue by zyx4986** [zuiidea/antd-admin#163]
uncaughtat anonymous
at anonymous
at takeEvery(app/login,undefined)
at anoymous
undefined

**Comment by zuiidea** [comment]
- 运行`npm i babel-polyfill -D`
- 在`src/index.js`中`import 'babel-polyfill`

另外现在我更新很多东西了
