### ISSUE TITLE
关于roadhog

### ISSUE THREAD

**Issue by zuiidea** [zuiidea/antd-admin#164]
在4.1-dev分支上已加入roadhog，基本能正常使用，也能热更新，
由于[#86](https://github.com/sorrycc/roadhog/issues/86)，roadhog修复post请求的最新包还没发布，
所以我这里也没合并到master分支上

**Comment by 305758409** [comment]
看你最新的回复，是不是可以合并了

**Comment by zuiidea** [comment]
@305758409 还不可以，还要调一下，不过可以切分支过去看看

**Comment by OptimusYang** [comment]
当前Mock的Login 部分,  还是Request.Body还是拿不到payload的username和password, 重新安装roadhog 6.0的版本还是不行

**Comment by zuiidea** [comment]
已更新，有问题反馈一下哈

**Comment by niuxianghui** [comment]
同样是这个问题，正在安装roadhog@0.6.0 beta.3，待会来反馈

**Comment by niuxianghui** [comment]
TypeError: Cannot read property 'username' of undefined
还是post请求报500

**Comment by zuiidea** [comment]
@niuxianghui ,保证package.json里没有roadhog
-  删除`node_modules`
- `npm i`
- `npm i roadhog@0.6.0-beta.3 -g`

**Comment by niuxianghui** [comment]
@zuiidea tks!

**Comment by niuxianghui** [comment]
@zuiidea 按照你说的操作了，现在的情况是登录后跳转到dashborad界面后立即跳回登录界面,admin  guest 和吴彦祖都不行
npm i 之后报这个
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.

**Comment by yanghong1105** [comment]
为什么删除了node_modules后运行npm i会报错npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! file C:\Users\Administrator.USER-20160806AJ\user-dashboard\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 45:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: C:\Users\Administrator.USER-20160806AJ\user-dashboard\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
