### ISSUE TITLE
How to make header fixed

### ISSUE THREAD

**Issue by darwis059** [zuiidea/antd-admin#168]
Is there any option to make header fixed?

**Comment by zuiidea** [comment]
Adjust  'src/components/Header.less'，set `header` style to 
```
{
    position:fixed;
    z-index: 9;
    right: 0;
    left: 224px;
}
```
then adjust other abnormal style

**Comment by doterme** [comment]
@zuiidea 你上面的方法，如果菜单缩起来header的长度变成固定的了

**Comment by zuiidea** [comment]
收起来会在layout上添加fold的class，你再调整header的left:42px;就好了啊

**Comment by darwis059** [comment]
Thank you. i have another question. How to detect screen size on Server Side Rendering to apply sider or isnavbar class?
          
            
            On Apr 13 2017, at 10:23 am, zuiidea <notifications@github.com> wrote:
            
            
              收起来会在layout上添加fold的class，你再调整header的left:42px;就好了啊

**Comment by zuiidea** [comment]
```
  subscriptions: {
    setup ({ dispatch }) {
      window.onresize = () => {
        dispatch({ type: 'changeNavbar' })
      }
    },
  },
```

@darwis059，is it not work? I haven't tried SSR yet.

**Comment by darwis059** [comment]
its working, but i got warning on server console. thanks.Sent from Nylas Mail, the best free email app for work
          
            
            On Apr 13 2017, at 3:55 pm, zuiidea <notifications@github.com> wrote:
            
            
                subscriptions: {
    setup ({ dispatch }) {
      window.onresize = () => {
        dispatch({ type: 'changeNavbar' })
      }
    },
  },

@darwis059，is it not work? I haven't tried SSR yet.
