### ISSUE TITLE
如何动态加载主菜单

### ISSUE THREAD

**Issue by bolord** [zuiidea/antd-admin#172]
1. router.js 为了支持 webpack chunk 实现按需加载需要定义全部的路由？
2. 目前数据写死在 utils/menu.js，如何根据后端的数据动态加载主菜单？且只在登录后加载一次？

在 menu.js 里使用同步请求加载数据肯定不是最佳方案，刚接触 dva 体系，希望大家可以提供点思路

**Comment by encorehe** [comment]
您好 请问一下 你的处理了吗？ 我这边也有这个需求 菜单是通过接口获取的

**Comment by doterme** [comment]
同求

**Comment by zuiidea** [comment]
在`src/routes/app.js`中用到了`Sider`组件，可以把menu数据传下去，你可以在`src/models/app.js`添加menu的state，subscriptions里去查询菜单

**Comment by doterme** [comment]
@zuiidea 能说下怎么跟权限结合么？比如我的菜单信息是从后台传过来的，那我前台要怎么控制呢？如果这样的话，router.js是不是也要动态的？要怎么做？求个思路。

**Comment by jackple** [comment]
我现在是在modal/app的effects下已有的query下面加,暂时可以用

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/384
