### ISSUE TITLE
我想请问一下header部分添加router

### ISSUE THREAD

**Issue by zhien520** [zuiidea/antd-admin#176]
作者你好，我研究你这个项目好久了，就是在Header我想加一个下拉框，并且实现路由。不知道该怎么做.....求教 新手一枚

**Comment by zhien520** [comment]
我在微博上私信你了....

**Comment by zuiidea** [comment]
那就在`src/components/Layout/Header.js`加啊

**Comment by zhien520** [comment]
@zuiidea 我家里下拉框 但是怎么实现跟侧边栏一样的路由啊...

**Comment by zhien520** [comment]
@zuiidea 就是下拉菜单要点击，然后切换中间内容区的，  方便加下我QQ吗  57180484  有点紧急....

**Comment by zuiidea** [comment]
```
import { Link } from 'dva/router'
<Link to="/dashboard">数据表盘</Link>
```

**Comment by zhien520** [comment]
哈哈 整出来了 谢谢大哥 下次有问题再帮我解答下呗..
