### ISSUE TITLE
关于表格数据的问题

### ISSUE THREAD

**Issue by zhien520** [zuiidea/antd-admin#179]
表格里面的数据是怎么传的 要在哪里修改表格的数据呢

**Comment by zbacao** [comment]
我也想知道。找了好久，新手，勿喷。。。

**Comment by zhien520** [comment]
还有就是怎么解决  登录的时候没有同步显示ID名  要刷新一次才出现

**Comment by zbacao** [comment]
上面的朋友能不能加个Q讨论下啊，教下新手啊 54211448

**Comment by zuiidea** [comment]
@zhien520 可以看`4.1-dev`分支上的

**Comment by zhien520** [comment]
@zbacao  我也是新手 估计帮不到你啊  你多问问作者

**Comment by zbacao** [comment]
4.1-dev 是什么- -太基础了我不好意思问开发者。。
