### ISSUE TITLE
好奇登录页是如何从根路由的布局分离出来的啊？

### ISSUE THREAD

**Issue by jiangbo2015** [zuiidea/antd-admin#188]
现在的版本是，登录页是单独页面，但还是根路由的子路由啊，根路由的布局怎么没影响到登录页？好奇，没看到代码在哪里？

**Comment by zuiidea** [comment]
我现在是在`utils/config.js`写了这个`openPages: ['/login'],`只要在openPages里的页面都会直接加载而不会加载布局

**Comment by wangxiansheng001** [comment]
这个我是先登录，后跳转dashboard，单击菜单，整个页面就一个页面，其他的header 菜单全没了

**Comment by superlbr** [comment]
@wangxiansheng001 看上去很像没有权限的症状
