### ISSUE TITLE
新增、修改之类的Modal，如何做到后台验证失败后Modal不关闭？

### ISSUE THREAD

**Issue by doterme** [zuiidea/antd-admin#190]
如题

**Comment by doterme** [comment]
@zuiidea 求帮助

**Comment by zuiidea** [comment]
`Modal`是否关闭是参数visible控制的，这个可由model里的state传下去，
验证出错是你保持visible为true就可以了啊
比如这段代码
```
*update ({ payload }, { select, call, put }) {
      yield put({ type: 'hideModal' })
      const id = yield select(({ users }) => users.currentItem.id)
      const newUser = { ...payload, id }
      const data = yield call(update, newUser)
      if (data && data.success) {
        yield put({
          type: 'querySuccess',
          payload: {
            list: data.data,
            pagination: {
              total: data.page.total,
              current: data.page.current,
            },
          },
        })
      }
    },
```

改为

```
*update ({ payload }, { select, call, put }) {
      const id = yield select(({ users }) => users.currentItem.id)
      const newUser = { ...payload, id }
      const data = yield call(update, newUser)
      if (data && data.success) {
        yield put({ type: 'hideModal' })
        yield put({
          type: 'querySuccess',
          payload: {
            list: data.data,
            pagination: {
              total: data.page.total,
              current: data.page.current,
            },
          },
        })
      } else {
       throw data
       }
    },
```

抛出的错误还可以在`src/index.js`里的onError统一处理

**Comment by doterme** [comment]
@zuiidea这样是可以的，但是Modal会闪一下，感觉不太好。

**Comment by chen610620** [comment]
同样也是遇到了这样的问题。 调试发现是在调用call函数时会闪动一次。

**Comment by doterme** [comment]
@chen610620 有解决方案么？

**Comment by chuncui0207** [comment]
@doterme 
这个是因为 UserModalGen这个方法每次都会创建新的弹层 
改成这样就不会了：
```js
<div className="content-inner">
      <UserFilter {...userFilterProps} />
      <UserList {...userListProps} />
      <UserModal {...userModalProps} />
    </div>
```

**Comment by doterme** [comment]
@chuncui0207 你的方案确实解决了我的问题，但是又带来了新的问题，如果验证成功后，Modal关闭后表格不刷新了，我还在找问题。

**Comment by chuncui0207** [comment]
@doterme  这个是因为form应用了initialValue属性， 需要改为用mapPropsToFields方法

**Comment by doterme** [comment]
@chuncui0207 mapPropsToFields应该写到哪里？怎么写？麻烦给个demo，不胜感激。

**Comment by chen610620** [comment]
@doterme 例子如下：
`Form.create({
  mapPropsToFields (props) {
    return props
  },
})`
然后别的都不用动

**Comment by doterme** [comment]
@chen610620 @chuncui0207 感谢两位大神，按照你们的方法是可以了，又遇到新的问题。如果我的Modal是一个要做修改操作的Modal的话，我把某个字段值改过之后，点击确定按钮，那个字段值在Modal关闭的过程中会变成上一次的值，但是结果是对的，知道是什么问题吗？

**Comment by doterme** [comment]
@zuiidea @chen610620 @chuncui0207 我把Modal的Form.Create()改为Form.create({ mapPropsToFields (props) { return props }, })除了上面发现的问题之外，又发现如果我的Modal包含了Select，例如：
![image](https://cloud.githubusercontent.com/assets/12495369/25607444/30a2e0ae-2f49-11e7-96fc-7d4f9f442920.png)
当我打开Modal的时候会报如下错误：
![image](https://cloud.githubusercontent.com/assets/12495369/25607477/4cb6c1b6-2f49-11e7-8c95-67ec35b143dc.png)
帮忙看看什么问题。

**Comment by doterme** [comment]
通过这种方式解决了，但是不知道啥意思:
Form.create({
  mapPropsToFields(props) {
    return {
      selector: {value: ['1', '2']}
    }
  }
})

**Comment by zuiidea** [comment]
https://github.com/dvajs/dva/issues/349
