### ISSUE TITLE
请问下build 生产环境 支持 hash文件命名吗？

### ISSUE THREAD

**Issue by steadyzeus** [zuiidea/antd-admin#191]

**Comment by lightfish-zhang** [comment]
同问，坐等更新 @zuiidea 
发觉build出来的dist下的文件都是相同名字的文件，不便于版本更新发布

**Comment by zuiidea** [comment]
已经可以了，参考这个Commit
https://github.com/zuiidea/antd-admin/commit/05a86e2f5660508de6370339f4cd5455bf156d7b

**Comment by shenqihui** [comment]
貌似 index.css / index.js 之类的，还是没有支持 hash 的处理。

**Comment by superlbr** [comment]
close https://github.com/zuiidea/antd-admin/pull/770
