### ISSUE TITLE
账号密码错误，登录失败没有error message

### ISSUE THREAD

**Issue by kala888** [zuiidea/antd-admin#195]
Steps:
1. 登录页面，账号guest111， 密码guest
2. 点击登录

期待结果:登录失败，提示账号密码错误
实际结果: 页面没有任何提示，console打印了400错误。
![jietu20170419-173157](https://cloud.githubusercontent.com/assets/1215976/25173306/270a1a08-2526-11e7-9db7-e146e0e93fb3.jpg)

**Comment by kala888** [comment]
看到最新code把login抽出来了，mock验证失败返回400错误，而models/login.js中将
```
yield put({
          type: 'loginFail',
        }
```
 替换为
`throw data`
似乎要去统一处理error message？

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/cfd0172204f2358263cdd85320759987f0937c3f
