### ISSUE TITLE
测试代码无法登录

### ISSUE THREAD

**Issue by darcygail** [zuiidea/antd-admin#197]
npm run dev 运行之后一直登录失败

**Comment by kevin50ster** [comment]
我之前初始化时也遇到这个问题，后来删除node_module重新安装依赖以及按照readme中安装roadhog版本就可以了

2017年4月20日 下午11:53，"darcygail" <notifications@github.com>写道：

**Comment by Tsury** [comment]
I also have this problem. I made sure that I have the correct version of roadhog (0.6.0-beta.3)

**Comment by kevin50ster** [comment]
@Tsury I use the guest user login when the error is login api network request status 500. So i reinstall the dep and the roadhog, There is no problem now.

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/189#issuecomment-295051009

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/pull/202/commits/7284cad8aa982e941e281dcf60c87abbeba2d4de

**Comment by darcygail** [comment]
多谢，就是linux上cookie一直存不进去的问题．
