### ISSUE TITLE
我想请问下演示地址为何和demo有些不同？

### ISSUE THREAD

**Issue by logyLiang** [zuiidea/antd-admin#2]
是这样的。我是后台程序猿。学习react 和dva脚手架遇到一个问题就是登陆问题，所以想参照一下。实在羞涩难当，可否把登陆加上呢？

**Comment by zuiidea** [comment]
演示地址是1.0版本的，当时没有使用dva脚手架，2.0才使用了dva，刚刚我已经把demo已经更新为2.0版本的了，但是没有登录，我最近几天来加上吧

**Comment by logyLiang** [comment]
非常感谢，替后端程序猿谢谢你

**Comment by zuiidea** [comment]
@logyLiang 登录加上了，公司加班没空闲时间做，随后会加一些登录提示和加载效果

**Comment by logyLiang** [comment]
@zuiidea  谢谢。 厉害了 word哥
