### ISSUE TITLE
按需加载文件名称无法自定义

### ISSUE THREAD

**Issue by pfpGit** [zuiidea/antd-admin#20]
`{
          path: 'users',
          name: 'users',
          getComponent(nextState, cb) {
            require.ensure([], require => {
              app.model(require('./models/users'))
              cb(null, require('./routes/users'))
            },u)
          }`
这段代码加上自定义名称会报错

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/64
