### ISSUE TITLE
怎么在apache上发布dist的代码啊

### ISSUE THREAD

**Issue by yhany** [zuiidea/antd-admin#200]
我运行了npm run build并且生成了dist下的相关文件，之后我怎么运行呢，还是 npm run dev?还是有其他命令，或者我想发布到apache服务器上，可以做到吗？求解释一下，小白不尽感激

**Comment by OptimusYang** [comment]
直接运行index.html就可以了，如果要发布到tomcat这种的，那放到目录里，然后web.xml配置指向index.html就行了。
如果有nginx那就直接增加配置，指向对应文件夹下的index.html

**Comment by zuiidea** [comment]
现在的版本不能直接运行了，必须配置服务器，`4.0-dev`及之前的可以

**Comment by JustYJQ** [comment]
@yhany  你好 请问你是不和部署到tomcat 下的

**Comment by superlbr** [comment]
参考 https://github.com/ant-design/ant-design/issues/2226
