### ISSUE TITLE
menu.js的配置bug

### ISSUE THREAD

**Issue by tigaly** [zuiidea/antd-admin#203]
{
    id: 52,
    bpid: 5,
    mpid: 5,
    name: 'BarChart',
    icon: 'bar-chart',
    router: '/chart/lineChart',
  },

应该是router:'/chart/barChart'

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/a4922c75419685577d23d9e9f1ea43942c226c63
