### ISSUE TITLE
如何开启devtool工具？

### ISSUE THREAD

**Issue by kevin50ster** [zuiidea/antd-admin#205]
您好，这个是基于antd的和原生用法还有点不一样，找不着地方。

该如何使用react devtools呢？

http://www.jianshu.com/p/a2d4c1856560

**Comment by zuiidea** [comment]
这跟项目无关

- 打开chrome浏览器，

- 打开：[chrome://extensions/](chrome://extensions/)，

- 找到React Developer Tools，

- 点击启用
