### ISSUE TITLE
热更新问题

### ISSUE THREAD

**Issue by chuncui0207** [zuiidea/antd-admin#207]
- antd-admin v4.2
- roadhog version: roadhog@0.6.0-beta.3
- Nodejs and Npm version node: v6.10.2 npm: 3.10.10
- Operating environment (e.g. OS name) and its version: windows 10, vs code

router.js里的registerModel方法默认会刷新页面，不会进行热更新
```js
const cached = {}
const registerModel = (app, model) => {
  if (!cached[model.namespace]) {
    cached[model.namespace] = 1
    app.model(model)
  }
}
```

替换成这样就正常热更新了：
```js
const registerModel = (app, model) => {
  if (!(app._models.filter(m => m.namespace === model.namespace).length === 1)) {
    app.model(model)
  }
}```

**Comment by zuiidea** [comment]
thanks
