### ISSUE TITLE
登录后用户名显示不对

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#21]

**Comment by encorehe** [comment]
先用 吴彦祖登录 登录名区域显示 guest 必须刷新才正确，麻烦看下，这个怎么处理啊 ，弄半天了 不知道哪儿的问题

**Comment by zuiidea** [comment]
![image](https://cloud.githubusercontent.com/assets/16070518/21602782/b1aab9da-d1d2-11e6-94b0-d29bffa1845e.png)
提了，`models/app.js`数据传错了
