### ISSUE TITLE
npm run dev 错误

### ISSUE THREAD

**Issue by huguijian** [zuiidea/antd-admin#213]
Failed to compile.

Error in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "dva-hmr" specified in "base" at 2, attempted to resolve relative to "/Users/huguijian/Desktop/antd-admin/src"
    at Array.map (native)
 @ multi index

**Comment by zuiidea** [comment]
`roadhog`版本不对，或者不是全局安装的，安装README的注意操作
