### ISSUE TITLE
定义新的model后,路由切换时报app.model: namespace should be unique

### ISSUE THREAD

**Issue by YehanZhou** [zuiidea/antd-admin#22]
定义新的model后,路由切换时报错 app.model: namespace should be unique

model：
<img width="702" alt="models" src="https://cloud.githubusercontent.com/assets/5938245/21674708/de8d8cbe-d369-11e6-8290-3c761fd95745.png">

路由配置：
<img width="379" alt="router" src="https://cloud.githubusercontent.com/assets/5938245/21674712/dff067ac-d369-11e6-99a1-7d245649b7e3.png">

报错截图：
<img width="567" alt="error" src="https://cloud.githubusercontent.com/assets/5938245/21674714/e113a248-d369-11e6-93d1-7371f2737b72.png">

**Comment by xianaldo** [comment]
遇到一样的问题

**Comment by zuiidea** [comment]
依次檢查：

- `src/index.js`有沒有已經定義了該model
- `src/models`文件夾下的文件的`namespace`是否重複定義

**Comment by zuiidea** [comment]
不會啊，第一次跳轉到該路由時，僅加載一次該組件的js，此時是第一次require該組件的model，整個項目衹會require一次model/markets
試試注釋該路由，會不會報錯
方便的話，提交到你的分支，我幫你檢查一下

**Comment by YehanZhou** [comment]
我刚刚download了这个分支上的代码，不加任何改动就会报错。
你试一下，先跳到【仪表盘】，再跳到【用户管理】，再又跳回到【仪表盘】，就会报错。
应该就是第二次跳某个带model的路由时，就会报app.model: namespace should be unique。

**Comment by zuiidea** [comment]
這兩天出去玩了，沒帶電腦😅

**Comment by taven-liu** [comment]
同样的问题

**Comment by taven-liu** [comment]
直接下载下来没有问题，但是在添加新的模块后出现同样问题了

**Comment by zuiidea** [comment]
@taven-liu能看一下你的新增代码吗

**Comment by taven-liu** [comment]
`{
		      path: 't1',
		      name: 't1',
		      getComponent (nextState, cb) {
			      require.ensure([], require => {
				      app.model(require('./modules/aTest/models/t1'))
				      cb(null, {component: require('./modules/aTest/containers/t1Container')})
			      })
		      }
	      },`

**Comment by xianaldo** [comment]
github上的代码就不行了，切换2次就报那个错了，不用添加新的

**Comment by zuiidea** [comment]
https://github.com/dvajs/dva/issues/465

可能是dva版本的原因，暂时先把dva 切换到 1.1 版本吧，后面我解决一下

**Comment by zuiidea** [comment]
已解决 https://github.com/zuiidea/antd-admin/commit/ff2005d26248a70e631d280693f8eab3ab5c9144

**Comment by xiaosansiji** [comment]
@zuiidea  @YehanZhou  @xianaldo 

https://github.com/dvajs/dva/issues/533 官方针对1.2的解决办法，最好还是搞下吧，要不升级到1.2后还会有问题

**Comment by zuiidea** [comment]
@xiaosansiji ，现在升级没问题了啊，https://github.com/zuiidea/antd-admin/commit/ff2005d26248a70e631d280693f8eab3ab5c9144
