### ISSUE TITLE
className={styles.icon}如果有两个类名怎么办

### ISSUE THREAD

**Issue by yanghong1105** [zuiidea/antd-admin#221]
.icon .icon-font这种情况

**Comment by albafica2015** [comment]
有个插件叫  classnames

**Comment by yanghong1105** [comment]
谢谢，您知道可不可以把className={style.title}这种格式的变成class="title"这种格式的可以不

**Comment by zuiidea** [comment]
是 className="title" 这样可以，但是要在roadhogrc关闭css module，或者在less里使用，
```
:global {
  .title{
  }
}
```

**Comment by yanghong1105** [comment]
我想请教您一个问题，我在components/Layout/Menu.js里面引入import styles from '../../iconfont'为什么老是报错，说是找不到，但是我的路径肯定是对的

**Comment by zuiidea** [comment]
`import styles from '../../iconfont.less'`
另外注意大小写，如果还是不行，就iconfont文件名改成其他的

**Comment by yanghong1105** [comment]
我主要是想引入iconfont字体图标里面的图标，那里面包括iconfont.css，iconfont.eto，iconfont.js，iconfont.svg，iconfont.ttf，iconfont.woff文件，然后我在index.html里引入iconfont.css,根本不显示样式，如果在Menu.js里面引入import styles from '../../iconfont.css'的时候，又会提示.eto，.svg，.tff，.woff找不到，很是纠结，不知道怎么弄了

**Comment by zuiidea** [comment]
@yanghong1105  https://github.com/zuiidea/antd-admin/issues/270
