### ISSUE TITLE
我做了一个带Tab的版式，怎么提交给你

### ISSUE THREAD

**Issue by sbyps** [zuiidea/antd-admin#222]
在实际应用中，应该是面包屑和tab共存，方便页签切换和导航，该怎么提交给你，直接提pr么

**Comment by doterme** [comment]
直接pr吧，我也想看看

**Comment by zhangqqqf** [comment]
@sbyps pr了么?  我也想看看,正有需要

**Comment by 102010cncger** [comment]
求大神整合

**Comment by richartan** [comment]
@sbyps 可以简要说一下方案吗？

**Comment by superlbr** [comment]
@sbyps 催更啦，不然close

**Comment by superlbr** [comment]
Duplicate： https://github.com/zuiidea/antd-admin/issues/526
