### ISSUE TITLE
antd-admin (Demo)，基于 antd 和 dva 的后台管理应用 ie访问路径出错

### ISSUE THREAD

**Issue by zhangjingge** [zuiidea/antd-admin#223]
antd-admin (Demo)，基于 antd 和 dva 的后台管理应用
访问http://localhost:8000/
ie访问的时候路径会变为：
http://localhost:8000/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/login?from=/undefined/undefined/undefined/undefined/undefined/undefined/undefined/login

**Comment by zuiidea** [comment]
没有IE，不知道什么情况，可以看看`src/models/login.js`

**Comment by zhangjingge** [comment]
![_20170508184440](https://cloud.githubusercontent.com/assets/20674049/25801039/7581d156-341e-11e7-9e13-1943f2980e12.png)
改了这里不会出现undefined，但是登录还是略微有点又问，需要再次输入进入网址才可以

**Comment by wing2002li** [comment]
ie确实出错，目前不知道如何解决，在chrome下是好的。

**Comment by zuiidea** [comment]
试试。`window.open(URL)`

**Comment by superlbr** [comment]
No more info.Close
