### ISSUE TITLE
为什么用不加分号的风格呢？

### ISSUE THREAD

**Issue by gasxia** [zuiidea/antd-admin#224]
看起来好怪异，改写又很累。。

**Comment by zuiidea** [comment]
- 修改`.eslintrc `：`"semi": [2, "always"],`
- 运行`npm run lint`
- 所有文件都加上分号了

另外这是个人习惯，不加分号看起来更清爽啊

**Comment by gasxia** [comment]
这样啊。我以为是eslint-react一个标准，印象中好像在哪里看过这个建议。
另外，询问下怎么联系您？想参与开发antd-admin。之前给您发了邮件，不过你没回复。。
