### ISSUE TITLE
多条件查询

### ISSUE THREAD

**Issue by sunshinefull** [zuiidea/antd-admin#226]
如果url地址是http://localhost:8000/test?field=name&field1=address&keyword=6&keyword1=2
如何实现多条件查询onSearch (fieldsValue) {
      fieldsValue.keyword.length ? dispatch(routerRedux.push({
        pathname: '/users',
        query: {
          field: fieldsValue.field,
          keyword: fieldsValue.keyword
        }
      })) : dispatch(routerRedux.push({
        pathname: '/users'
      }))

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/1b7c076057dda50fa73cb11ff6d114c0b2e21f06

![image](https://cloud.githubusercontent.com/assets/16070518/25483371/17f0abe6-2b88-11e7-86c8-09c50cb16b46.png)
