### ISSUE TITLE
datepicker的bug

### ISSUE THREAD

**Issue by yangkai314** [zuiidea/antd-admin#227]
![image](https://cloud.githubusercontent.com/assets/20856077/25475102/421d08e4-2b68-11e7-8558-a7e030a3690c.png)
我在modal里有一个这样的表格，如果先填写了其他表格再选择时间选择器，就会报错
Uncaught TypeError: Cannot read property 'clone' of undefined
如果直接选择时间选择器就 不会报错

**Comment by zuiidea** [comment]
https://github.com/ant-design/ant-design/issues/5872

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/228
