### ISSUE TITLE
RangePicker  bug，单独写没有问题，写进form表单里面的时候就会报错

### ISSUE THREAD

**Issue by zhangjingge** [zuiidea/antd-admin#228]
RangePicker  bug，单独写没有问题，写进form表单里面的时候就会报错
MonthPicker， DatePicker这两个没有问题，
点击RangePicker控件Uncaught TypeError: Cannot read property 'clone' of undefined
![17 04 27 1833_1](https://cloud.githubusercontent.com/assets/20674049/25480868/4a354fc2-2b7d-11e7-9b52-a4b93a804489.png)

**Comment by zuiidea** [comment]
DatePicker的值是`[moment,moment]`，看不出来你的是什么问题

**Comment by zhangjingge** [comment]
点击控件的时候就报错，跟值没有关系，不在form表单不报错，将RangePicker放进form表单就会报这个错误

**Comment by zuiidea** [comment]
https://github.com/ant-design/ant-design/issues/5872

**Comment by zhangjingge** [comment]
@zuiidea 非常感谢
