### ISSUE TITLE
IE11下无法登录，开着开发人员工具才能正常登录跳转

### ISSUE THREAD

**Issue by hqm1988** [zuiidea/antd-admin#229]
IE版本![image](https://cloud.githubusercontent.com/assets/1542964/25509996/97b41090-2bef-11e7-8bff-c940646a8cf9.png)
![qq 20170428085321](https://cloud.githubusercontent.com/assets/1542964/25510123/58e645da-2bf0-11e7-85ec-d5a2f9400b76.png)

**Comment by zuiidea** [comment]
这个并不重要，也不是重点，可能是mock的原因，正式线上的时候是不会用这个接口的，用chrome调试就好了
