### ISSUE TITLE
请问routes/app.js文件中children值是怎么设置的？

### ISSUE THREAD

**Issue by 190589751** [zuiidea/antd-admin#24]
你好，  请问routes/app.js文件中children值是怎么设置的？

**Comment by zuiidea** [comment]
請看src/router.js

**Comment by 190589751** [comment]
@zuiidea 看过愣是没看懂，请指教...

**Comment by zuiidea** [comment]
```
<Router history={hashHistory}>
  <Route path="/" component={App}>
    <Route path="/dashboard" component={Dashboard}/>
    <Route path="/users" component={Users}/>
  </Route>
</Router>
```
這是路由嵌套，子路由就是父路由的children，
`src/router.js`裏為了實現動態加載，采用了參數的寫法

參考
https://github.com/ReactTraining/react-router
http://www.ruanyifeng.com/blog/2016/05/react_router.html?utm_source=tool.lu

**Comment by zhangolve** [comment]
谢谢楼主提这个问题，也谢谢 @zuiidea ，正想问这个问题呢，一搜果然有人问了。项目代码还是很简洁清晰的。
