### ISSUE TITLE
请教下，那个编辑器能上传图片吗，

### ISSUE THREAD

**Issue by lpp288** [zuiidea/antd-admin#243]
请教下，这个Draft 编辑器能上传图片吗

**Comment by lpp288** [comment]
在Editor中配置uploadCallback，点击选文件很久才会出弹框，而且react-draft-wysiwyg.js:25 Uncaught TypeError: Cannot read property 'then' of undefined这个报错唉

**Comment by jeffhtli** [comment]
> 点击选文件很久才会出弹框

这个问题好像只有Chrome有，但Firefox和Safari好着。其他Editor我也试过，比如Ueditor，也点了好久才弹出
