### ISSUE TITLE
dist下面没有文件生成，空目录

### ISSUE THREAD

**Issue by dangyanglim** [zuiidea/antd-admin#245]
[root@iZwz9fctqcpbye9y20ikcdZ antd-admin]# npm run build
> @ build /home/wjwl/test/antd-admin
> roadhog build --analyze

Creating an optimized production build...
[root@iZwz9fctqcpbye9y20ikcdZ antd-admin]# ls
assets  dist  LICENSE  node_modules  package.json  README.md  src  theme.config.js  yarn.lock
[root@iZwz9fctqcpbye9y20ikcdZ antd-admin]# ls ./dist
a
[root@iZwz9fctqcpbye9y20ikcdZ antd-admin]# ls ./dist/a
1.0.0
[root@iZwz9fctqcpbye9y20ikcdZ antd-admin]# ls ./dist/a/1*

npm run dev可以看到网页

**Comment by zuiidea** [comment]
![image](https://cloud.githubusercontent.com/assets/16070518/25616553/0ea36d6c-2f70-11e7-90fa-c0e095ca5464.png)

你是什么版本

**Comment by dangyanglim** [comment]
@zuiidea 
谢谢，
node 版本是7.9.0，
roadhog是0.6.0-beta.6
我试了roadhog build --debug有信息出来，但是--analyze不行



我是不是缺少了compress工具，是什么呢？
![screenshot from 2017-05-02 21-46-31](https://cloud.githubusercontent.com/assets/16640185/25620817/2c27a01c-2f82-11e7-9b32-1cb546068671.png)


![Uploading Screenshot from 2017-05-02 21-46-31.png…]()

**Comment by dangyanglim** [comment]
阿里云centos7
webpack 1.15.0
直接
git clone https://github.com/zuiidea/antd-admin.git
yarn install
![screenshot from 2017-05-02 22-04-51](https://cloud.githubusercontent.com/assets/16640185/25621305/9c694a46-2f83-11e7-8a21-51aac87dd9d1.png)

**Comment by dangyanglim** [comment]
@sorrycc
谢谢

**Comment by zuiidea** [comment]
在linux上好像是build不出来

**Comment by dangyanglim** [comment]
我在windows上可以了，一开始下载不来nvm for windows我才在linux上开发
windows7上可以

**Comment by encorehe** [comment]
你好 我也碰到这个问题了 系统是osx 10.12.4，有解决办法吗？

**Comment by dangyanglim** [comment]
@encorehe 
我在windows build出来了
