### ISSUE TITLE
roadhog 0.6-beta6 bug

### ISSUE THREAD

**Issue by tigaly** [zuiidea/antd-admin#246]
新的commit用了beta6以后又出现了之前的登陆bug

```
TypeError: Cannot read property 'username' of undefined
```

os：osx，浏览器：chrome Safari

**Comment by zuiidea** [comment]
windows没有问题，你排查一下，PR一下呗🙃

**Comment by FatFatFox** [comment]
您好，macbook下有问题 osx 浏览器chrome，有登陆问题

**Comment by zuiidea** [comment]
应该是`req.body`没有值，调试一下`mock/user.js` 里的 `user/login`接口

**Comment by FatFatFox** [comment]
从fdb0fcb这个版本之后的1b7c076版本开始出现问题
<img width="449" alt="qq20170503-105250 2x" src="https://cloud.githubusercontent.com/assets/1856776/25646828/b0950206-2fee-11e7-83f2-7e3b339dde1d.png">
报：Failed to load resource: the server responded with a status of 404 (Not Found)错误

最新版本88d835c
报：TypeError: Cannot read property 'user' of undefined

**Comment by tigaly** [comment]
不是太好调试，报错的是这行
```
 [`POST ${apiPrefix}/user/login`] (req, res) {
```
可能是req都没接收到，我在后面console.log都不会执行，说明这个函数入口就跳出了

**Comment by zuiidea** [comment]
@FatFatFox 是有这个问题，热更新时会有，但跟这个issue没关系

**Comment by zuiidea** [comment]
@tigaly 怎么会，应该是`req.body`没有值， `const { username, password } = req.body `这句报错的，我没有mac，你看看吧

**Comment by tigaly** [comment]
```
TypeError: Cannot read property 'username' of undefined
    at undefined (/Users/tigaly/react/antd-admin/src/mock/user.js:83:47)
    at mockHandler (/Users/tigaly/react/antd-admin/node_modules/roadhog/lib/utils/mock.js:74:13)
    at Layer.handle [as handle_request] (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/layer.js:95:5)
    at /Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:275:10)
    at goNext (/Users/tigaly/react/antd-admin/node_modules/webpack-dev-middleware/middleware.js:28:49)
    at webpackDevMiddleware (/Users/tigaly/react/antd-admin/node_modules/webpack-dev-middleware/middleware.js:36:11)
    at Layer.handle [as handle_request] (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:317:13)
    at /Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/tigaly/react/antd-admin/node_modules/express/lib/router/index.js:275:10)
```

这个是报错的完整内容，83行就是
```
[`POST ${apiPrefix}/user/login`] (req, res) {
```

我在这行后面加了一个
```
console.log(JSON.stringify(req.body))
```

然而这句并不会执行

**Comment by FatFatFox** [comment]
@zuiidea 您好，最新版本的登陆报错问题同tigaly所描述。

**Comment by tigaly** [comment]
@zuiidea 我检查req.body的请求，发现有一条 
```
username is required
```
这个在mock里有验证么？

**Comment by zuiidea** [comment]
@tigaly 这个是antd的前端验证，没关系的

**Comment by tigaly** [comment]
哦，那就无解了，除非去分析beta6的源码，我这边用beta3测试是好的。
看来roadhog还有很多路要走

**Comment by zuiidea** [comment]
那是`GET ${apiPrefix}/user`这个接口里的问题了，看看这句`user.username = userItem[0].username`

**Comment by tigaly** [comment]
@zuiidea 
应该不是这个问题

我试过cookie里有token的情况下是正常的
但是清空cookie了以后，登陆的时候都不会走到你说的那句，在判断cookie是否存在的时候就跳出去了
```
if (!cookies.token) {
      res.status(200).send({ message: 'Not Login' })
      return
    }
```

**Comment by dangyanglim** [comment]
我也报错了，mock里面
  [`POST ${apiPrefix}/user/login`] (req, res) {
    console.log(qs.parse(req.body));
    const { username, password } = req.body

这个可能是因为req.body没有被解析，nodejs是需要bodyparser，
这里面mock没有用中间件解析req.body，req.body是undefined，
但是我不知道怎么改

**Comment by dangyanglim** [comment]
const { username, password } = req.body
这句话报错
req.body.username  是undefined的，
req.body也是undefined的

**Comment by dangyanglim** [comment]
把post改成get就可以了
export async function login (data) {
  return request({
    url: userLogin,
    method: 'get',
    data,
  })
}

  [`GET ${apiPrefix}/user/login`] (req, res) {
    console.log(qs.parse(req.query));
    const { username, password } = req.query
    const user = adminUsers.filter((item) => item.username === username)

不知道mock如何解析post过来的req.body

**Comment by zuiidea** [comment]
@dangyanglim ， 讲道理是这样的，不科学的是为什么windows可以呢， 不妨检查一下真正使用是roadhog的哪个版本

**Comment by figo2young** [comment]
@zuiidea 我在windows下也是不行，roadhog 0.6.0-beta6，nodejs 6.10.2

**Comment by dangyanglim** [comment]
@zuiidea 我用的是win7
roadhog是0.6.0-beta.6
也是不行的

**Comment by zuiidea** [comment]
@dangyanglim 不会吧，难道是node的版本，我的node是v7.9.0

**Comment by dangyanglim** [comment]
应该是req.body没有解析
![image](https://cloud.githubusercontent.com/assets/16640185/25649949/040b00b2-300c-11e7-88df-2eee3e333441.png)

**Comment by zuiidea** [comment]
@dangyanglim  你看一下node_modules下roadhog有没有roadhog目录，有的话，先看一下版本

- npm uninstall roadhog

- npm install roadhog@0.6.0-beta.6 -g

**Comment by dangyanglim** [comment]
@zuiidea 
node_modules下确实有个roadhog目录
版本是roadhog@0.6.0-beta2
我npm uninstall roadhog
post也可以了，
不过那个node_modules目录下的roadhog还在，可能是切断联系了吧

**Comment by dangyanglim** [comment]
![image](https://cloud.githubusercontent.com/assets/16640185/25650278/4e6b4412-300e-11e7-96d1-1d317820fc5d.png)

**Comment by zuiidea** [comment]
@dangyanglim 不知道怎么优先使用了node_modules的

**Comment by figo2young** [comment]
@dangyanglim 你npm uninstall roadhog 删掉全局roadhog就可以post了？

**Comment by zuiidea** [comment]
@figo2young  `npm uninstall roadhog`是删除本项目的

**Comment by figo2young** [comment]
@dangyanglim 执行 npm uninstall roadhog依然不行。。

**Comment by eddiebai** [comment]
第一次clone这个项目。。。。。。报错很严重啊
![image](https://cloud.githubusercontent.com/assets/20298142/25653662/8103991c-3020-11e7-9968-0d19d55d3dea.png)

**Comment by zuiidea** [comment]
@eddiebai 
- `npm uninstall roadhog`
- `npm install roadhog@0.6.0-beta.6 -g`

**Comment by eddiebai** [comment]
@zuiidea Thx, it's working well now

**Comment by zuiidea** [comment]
找到问题原因了，
`package.json`里，
` "roadhog": "^0.6.0-beta.6" ` 改为 ` "roadhog": "0.6.0-beta.6"`
https://github.com/sorrycc/roadhog/issues/240

**Comment by zheeeng** [comment]
@zuiidea 确实是版本的问题，默认安装的是 beta 2

**Comment by tigaly** [comment]
@zuiidea OK，果然是roadhog的问题
