### ISSUE TITLE
npm run build导出的dist如何打开？双击直接打开还是需要部署之类？

### ISSUE THREAD

**Issue by FatFatFox** [zuiidea/antd-admin#247]
问题比较low
我在之前的非roadhog版本中做的例子，是可以直接在dist目录里双击网页文件打开执行，并且可以和后台数据交互的（我计划是把dist目录的前端文件放在tomcat和java交互）。
但是更新到昨天的版本，貌似是不能直接双击执行的。不知道要做什么调整，请教各位。

**Comment by FatFatFox** [comment]
![image](https://cloud.githubusercontent.com/assets/1856776/25687531/b85a3f04-30a9-11e7-82d4-934ec73586ac.png)
我调整了一下index.html的关联文件的方式（不调整的话报找不到index.js和index.css错误）
双击执行后
![image](https://cloud.githubusercontent.com/assets/1856776/25687563/002f3942-30aa-11e7-88a5-ff7aafaf3997.png)

**Comment by doterme** [comment]
部署到nginx上就行

**Comment by FatFatFox** [comment]
@doterme @zuiidea 
已经部署到了nginx上，但是症状和下面这位遇到的问题是一样的
https://github.com/zuiidea/antd-admin/issues/252

**Comment by zuiidea** [comment]
nginx配置示例：

```
server
	{
		listen       666;
		server_name 47.92.30.98;
		root  /home/www/antd-admin/dist;

		location /api {
			 proxy_pass http://localhost:8000/api;
		}

		location / {
				index  index.html;
				try_files $uri $uri/ /index.html;
		}
	}
```

演示地址：http://47.92.30.98:666

**Comment by yanghong1105** [comment]
您好，npmrun build是空白的问题怎么解决的，我现在也是这种情况

**Comment by zuiidea** [comment]
@yanghong1105 https://github.com/zuiidea/antd-admin/issues/269

**Comment by JustYJQ** [comment]
@FatFatFox 你好 请问你是如何部署到tomcat 下的，谢谢

**Comment by FatFatFox** [comment]
我还没试，只是在nginx上试成功了，现在在忙别的事情，试成功了告诉你，如果你搞成功了也烦请告诉我。

**Comment by ivsass** [comment]
> @FatFatFox你好请问你是如何部署到tomcat下的，谢谢
你好 ，你们成功了吗？ 我选择也在面临部署问题
