### ISSUE TITLE
如何进行跨域请求啊？

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#248]
现在的请求 是：
Request URL:http://120.27.159.127:48080/backend-coach/backend/loginBackend
Request Method:OPTIONS

原来的Request Method:POST 不知道在哪更改啊，麻烦提示一下 谢谢！

**Comment by zuiidea** [comment]
- 如果是CORS跨域，`src/utils/config.js`下有个CORS字段
- 如果CORS，YQL都没有设置的跨域，将会使用JSONP

**Comment by encorehe** [comment]
![a](https://cloud.githubusercontent.com/assets/6395357/25697038/096100f8-30ec-11e7-984b-2d8bc5297ad6.png)

CORS里面 怎么设置呢 ？ 我看request里面 有个fetchType参数 但是改了 也不行啊 🙏
![b](https://cloud.githubusercontent.com/assets/6395357/25697109/41d19cb8-30ec-11e7-9f6b-294feae1044d.png)
![c](https://cloud.githubusercontent.com/assets/6395357/25697126/50880ff8-30ec-11e7-9605-ea83e626de6f.png)

![c](https://cloud.githubusercontent.com/assets/6395357/25697111/430d3a9c-30ec-11e7-81e9-285f3f0ed7a3.png)
![c](https://cloud.githubusercontent.com/assets/6395357/25697114/44dcbba4-30ec-11e7-8886-d493ae2eefe7.png)

**Comment by FatFatFox** [comment]
你先从chrome的开发者工具network里看看服务端的header里返回的response的有没有开放跨域给你。

**Comment by eddiebai** [comment]
建议使用nginx反向代理
