### ISSUE TITLE
有计划做菜单权限的动态控制么？

### ISSUE THREAD

**Issue by doterme** [zuiidea/antd-admin#249]
如题，看见好多人有这个需求

**Comment by FatFatFox** [comment]
我觉得这个不难，zuiidea都已经把menu的数据源独立出来了，无非就是把它做成动态的json放在后台，根据不同的人获取menu的json，作为datasource展示

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/384
