### ISSUE TITLE
start 有错误哦，能帮忙解答下这个是为什么吗~~

### ISSUE THREAD

**Issue by taven-liu** [zuiidea/antd-admin#25]
![qq 20170109153515](https://cloud.githubusercontent.com/assets/11688796/21759716/7010d7ee-d681-11e6-8324-7ae9c11c671f.png)

**Comment by zuiidea** [comment]
请暂时用`npm run dev`

**Comment by taven-liu** [comment]
谢谢哈，那么这个代理跨域 直接在这里配置并使用么，现在启动不报错了，代理单独开的apache。

**Comment by zuiidea** [comment]
跨域我在 `src/utils/request.js` 里做了简单处理，可能在生产环境不适用，你可以根据你的情况修改
