### ISSUE TITLE
发布问题

### ISSUE THREAD

**Issue by zongzi8899** [zuiidea/antd-admin#252]
![qqq](https://cloud.githubusercontent.com/assets/15646427/25732472/8658d98c-3182-11e7-9800-ecc41d8a91f8.gif)

**Comment by zongzi8899** [comment]
已经放到服务器上的了，问题如上

**Comment by FatFatFox** [comment]
@zongzi8899 你已经解决了吗？我不部署到了nginx服务器上，问题和你一模一样
你部署的是tomcat服务器吧？

**Comment by zuiidea** [comment]
nginx配置示例：

```
server
	{
		listen       666;
		server_name 47.92.30.98;
		root  /home/www/antd-admin/dist;

		location /api {
			 proxy_pass http://localhost:8000/api;
		}

		location / {
				index  index.html;
				try_files $uri $uri/ /index.html;
		}
	}
```

演示地址：http://47.92.30.98:666

**Comment by zongzi8899** [comment]
tomcat的也可以？
在2017年05月8日 19:09，zuiidea<notifications@github.com> 写道：

nginx配置示例：

server
	{
		listen       666;
		server_name 47.92.30.98;
		root  /home/www/antd-admin/dist;

		location /api {
			 proxy_pass http://localhost:8000/api;
		}

		location / {
				index  index.html;
				try_files $uri $uri/ /index.html;
		}
	}


演示地址：http://47.92.30.98:666

**Comment by zuiidea** [comment]
@zongzi8899 我没试过，道理都是一样，都是把所有除了资源文件的路由指向`index.html`

**Comment by zongzi8899** [comment]
好滴。THANKS


在2017年05月8日 19:17，zuiidea<notifications@github.com> 写道：

@zongzi8899 我没试过，道理都是一样，都是把所有除了资源文件的路由指向index.html

**Comment by JustYJQ** [comment]
@zongzi8899 你好 请问你是如何部署到tomcat 下的

**Comment by mapengze** [comment]
@zongzi8899 我也是部署到tomcat上面 改成了hashHistory  跟你的效果一模一样  你解决了吗
