### ISSUE TITLE
求指教，路由有40个 然后运行npm run build就不动了

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#253]
你好 我这边路由有40个 运行npm run build 就没反应 等蛮长时间也是

**Comment by zuiidea** [comment]
pakage.json中
`  "build": "roadhog build --analyze"`改成`"build": "roadhog build"`

**Comment by superlbr** [comment]
No more info. Close.
1. 路由40多，不影响build完成，预计2min左右
2. 可以试下新版本，yarn包管理
