### ISSUE TITLE
CORS跨域可能是个bug，请看看

### ISSUE THREAD

**Issue by FatFatFox** [zuiidea/antd-admin#256]
request.js里有个判断
` if (CORS && CORS.indexOf(origin) > -1) `
则流向CORS分支。
作者可能的意思是在config.js的CORS项里配置要跨域的http地址之后，就可以通过CORS方式获取这个地址的跨域数据了。
但是，即使配了，CORS.indexOf(origin)也永远都是等于-1的，进不到这个分支。
不太了解ES6标准，以往的经验看，这是不是检查字符串是否含有特定地址？

config.js代码改了一下就可以了
`CORS: 'http://localhost:7001,http://192.168.0.106:8080/,http://192.168.0.190:8080/',`

感谢zuiidea这个开源项目，谢谢

**Comment by zuiidea** [comment]
`CORS: ['http://localhost:7001','http://192.168.0.106:8080','http://192.168.0.190:8080']`
没有斜杠就对了

**Comment by FatFatFox** [comment]
果真如此，看来是我搞错了。
