### ISSUE TITLE
favicon.ico 本地怎么引入，放在根目录build后也没有

### ISSUE THREAD

**Issue by zhangjingge** [zuiidea/antd-admin#260]
favicon.ico 本地怎么引入，放在根目录build后dist文件夹也没有
![public](https://cloud.githubusercontent.com/assets/20674049/25831325/ca914a24-3495-11e7-863a-0285cae289cb.png)
把favicon.ico放到public 目录下build后也没有生成

**Comment by dangyanglim** [comment]
修改index.html
添加

link rel="icon" href="http://120.77.241.56/manage/favicon.ico" type="image/x-icon"

把favicon.ico拷贝到/managex下就可以了

**Comment by zhangjingge** [comment]
@dangyanglim
你说的index.html页面是src下面的吗。好像没用，build后dist目录下面也没有生成
![default](https://cloud.githubusercontent.com/assets/20674049/25930395/8bb576be-3638-11e7-847a-0f491b3530a6.png)

**Comment by dangyanglim** [comment]
build后没有，你部署的时候把favicon放到网络根目录/manage/favicon.icon，网页不就可以get到了吗
开发的时候不管它了

**Comment by zuiidea** [comment]
@zhangjingge 他的文件目录跟你的不一样，应该把favicon.ico放在public目录下

`<link  href="/favicon.ico" type="image/x-icon" >`

**Comment by zuiidea** [comment]
@dangyanglim 。。。

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/pull/277/commits/c7789f103e2a9417770a6894a11296d7299eb79b

**Comment by zhangjingge** [comment]
@zuiidea @dangyanglim 
都很感谢
我知道问题了，最开始的时候我把public文件夹放到src里面了
