### ISSUE TITLE
新commit登出bug

### ISSUE THREAD

**Issue by tigaly** [zuiidea/antd-admin#261]
新commit登出有bug，不会自动跳转到登陆页面

另外登陆的时候第一个页面面包屑那里会有个错误的显示，not found

**Comment by tigaly** [comment]
我看了眼，是在moden/app的61行这里有bug
```
 if (data.success) {
        yield put({ type: 'query' })
      } else {
```

原来方法是queryUser，改成这样就好。

另外第二个问题我还发现衍生出来另一个问题，那就是登陆之后，app的state/user这块是空的，必须刷新才有值，表象就是登出那块有没有用户名显示不出来

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/pull/263/commits/664aeba1330a79b7b0559870b856c3b25b074a5a
