### ISSUE TITLE
公司有自己的后台，怎样可以用公司的真实数据和这套模板结合

### ISSUE THREAD

**Issue by yanghong1105** [zuiidea/antd-admin#262]

**Comment by zuiidea** [comment]
1. 用Nginx将真实接口代理项目中的接口
2. 项目中有个src/config.js可以配置使用的接口

**Comment by yanghong1105** [comment]
utils/config.js中的这些地址吗？
 baseURL: 'http://localhost:8000/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:7000'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/user/login',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    dashboard: '/dashboard',
