### ISSUE TITLE
menu.js 里的 bpid和mpid的作用是什么？

### ISSUE THREAD

**Issue by TangMonk** [zuiidea/antd-admin#267]
为啥把原来的children嵌套的方式改掉了？这样看起来好不直观

**Comment by zuiidea** [comment]
[菜单配置文件](https://github.com/zuiidea/antd-admin/wiki/%E8%8F%9C%E5%8D%95%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

**Comment by TangMonk** [comment]
谢谢
