### ISSUE TITLE
布置到nignx下，闪一下登录界面就到404了

### ISSUE THREAD

**Issue by dangyanglim** [zuiidea/antd-admin#268]
怎么样打开127.0.0.1/index.html
就打开登录界面
![qq 20170509175425](https://cloud.githubusercontent.com/assets/16640185/25845492/aa3d697e-34e0-11e7-9997-ceafdbadeae4.png)

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/269
