### ISSUE TITLE
项目模块比较多，如何拆分route文件如何汇总到route中

### ISSUE THREAD

**Issue by taven-liu** [zuiidea/antd-admin#27]
在绑定model时需要一个app对象，这个app对象如何传递，或者在拆分的子路由中如何绑定model

**Comment by zuiidea** [comment]
app组件作为根路由`'/'`，
```
  const routes = [
    {
      path: '/',
      component: App,
      getIndexRoute (nextState, cb) {
        require.ensure([], require => {
          app.model(require('./models/dashboard'))
          cb(null, {component: require('./routes/dashboard')})
        })
      },childRoutes: [
        {
          path: 'dashboard',
          name: 'dashboard',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              app.model(require('./models/dashboard'))
              cb(null, require('./routes/dashboard'))
            })
          }
        }
      ]
    }
  ]
```
其他所有的页面都作为子路由放在app下面，每个子路由组件都拥有自己的model，上面是动态加载路由的示例，具体参看`src\router.js`

**Comment by taven-liu** [comment]
明白你的意思，现在有个问题哈，这个项目有n多个菜单，每个菜单对应一个模块，每个模块下面有n多个路由，那么所有的路由配置都放在这个router.js文件下，会不好管理，能不能在总的router.js文件中引入每个模块中的路由，如果能的话，每个模块的model如何绑定

**Comment by taven-liu** [comment]
例如：index如下：
`
import routes from './routes'
<Provider store={store}>
   <Router routes={routes} history={history} />
</Provider>
`
routes文件如下：
`
import Route1 from '../modules/m1/Route';
import Route2 from '../modules/m2/Route'
// 汇总modules里面Route
export default {
  name: 'home',
  path: '/',
  component: IndexApp,
  childRoutes: [
    Route1,
    Route2
  ]
}
`

每个模块的route文件定义规则，但是每个模块中如何得到app对象并且去绑定model了。

**Comment by zuiidea** [comment]
这样的写法会使加载所有的路由并打包到一个总的js，就不能动态加载了

**Comment by taven-liu** [comment]
谢谢哈， 刚玩这个，代码都还没格式化的，谢谢你耐心看完了。 希望这个以后能有个办法，将这个文件拆分，要不这个文件太大了
