### ISSUE TITLE
关于Iconfont

### ISSUE THREAD

**Issue by zuiidea** [zuiidea/antd-admin#270]
演示地址：http://47.92.30.98:666/UIElement/iconfont

扩展Antd的Icon，总结Iconfont在项目中的使用方法：

- 在[iconfont](http://www.iconfont.cn/)官网上创建图标项目
- 注意设置`Symbol 前缀`和`Font Family`

一、 font-class引用，单色

![qq 20170509191407](https://cloud.githubusercontent.com/assets/16070518/25848185/c422784c-34eb-11e7-97b2-c1c904db3027.png)

- 在`src/utils/config.js`设置`iconFontCSS`，该路径可为线上地址，或者本地路径（下载后放到`public`目录中）
- 使用：`<Iconfont  type="home" />`

二、 symbol引用，可彩色图标

![qq 20170509191330](https://cloud.githubusercontent.com/assets/16070518/25848179/c06244f8-34eb-11e7-969a-014cc9a4d54e.png)

- 在`src/utils/config.js`设置`iconFontJS`，该路径可为线上地址，或者本地路径（下载后放到`public`目录中）
- 使用：`<Iconfont colorful type="boluo" />`

单个SVG图标的使用方法

一、 先导入再使用

- 将svg图标放入src/svg目录中
- 使用
```
import '../../svg/emoji/vomiting.svg'
<Iconfont colorful type="vomiting" />
```

一、 require直接使用

`<Iconfont colorful type={require('../../svg/emoji/vomiting.svg')} />`

**Comment by blackboyhc** [comment]
现在src/utils/config.js只有iconFontUrl可以设置，是不是把iconfont下载下来后放到public下面，然后设置iconFontUrl就行了？
比如：iconFontUrl: 'fonts/iconfont/iconfont.js'

**Comment by blackboyhc** [comment]
将iconFontJS和iconFontCSS设置成本地路径后还是会去网络请求字体，因为antd中指定的icon-url还是设定的网络的，这个可以解决吗？因为项目可能只在内网用。

**Comment by zuiidea** [comment]
@blackboyhc  这个方案是扩展，而不是覆盖，覆盖需要在themes/default.less里设置

`@icon-url :'"icon-url"'`

- icon-url设置为本地的，将资源放在public目录

- icon-url设置为iconfont网站上的url，这样可以覆盖，但是会有个问题，因为自己iconfont项目里的Unicode(16进制)和antd里的不对应，导致antd组件的一些小图标显示不出来

- 这是antd在iconfont上的项目，希望对你有帮助
http://www.iconfont.cn/collections/detail?cid=790

**Comment by blackboyhc** [comment]
@zuiidea 
我试了在themes/default.less里设置，出现下面问题
`PickLHiMac:antd-admin picklh$ npm run build

> @ build /Users/picklh/work/nodejs/antd-admin
> roadhog build --analyze

Creating an optimized production build...
Failed to compile.

Module not found: Error: Cannot resolve 'file' or 'directory' ./core/"public/iconfont".eot in /Users/picklh/work/nodejs/antd-admin/node_modules/antd/lib/style

`

**Comment by zuiidea** [comment]
@blackboyhc `public`目录是资源文件的根目录，本地部署iconfont参考这个commit
https://github.com/zuiidea/antd-admin/pull/285/commits/c3c8cf6f9b3d7b1d184ca087b60b01c8adc089c2

**Comment by LDD123** [comment]
根本不好使啊，使用的antd@2,12,3  ,在public文件夹下放置了，和楼上一个问题

**Comment by superlbr** [comment]
@LDD123 
iconfont如何处理加载，跟antd没啥关系，主要看roadhog、umi的处理逻辑。
就这个https://github.com/zuiidea/antd-admin/commit/c3c8cf6f9b3d7b1d184ca087b60b01c8adc089c2 版本来说，iconfont引入完全ok，那简单，对比下代码，看哪里有出入

ps: 另外注意下路径
```
@icon-url: "/antd/iconfont";
```

**Comment by superlbr** [comment]
@LDD123 1楼说得不是很详细，看这个吧https://github.com/umijs/umi/issues/246#issuecomment-410931780

**Comment by superlbr** [comment]
since antd use svg to replace font, there's already a natural way to use [iconfont](https://ant.design/components/icon/#Use-custom-icon-with-iconfont.cn).
