### ISSUE TITLE
dist生成的文件不放在根目录的问题

### ISSUE THREAD

**Issue by dangyanglim** [zuiidea/antd-admin#271]
我根目录打算这样/manage/dist/...
我修改了index.html
<script src="/manage/dist/index.js"></script>
/manage/dist/index.css
修改了roadhogrc.js
svgSpriteLoaderDirs: svgSpriteDirs,
"publicPath": "/manage/dist/",
但是还是不行
不知道怎么修改了

**Comment by dangyanglim** [comment]
![image](https://cloud.githubusercontent.com/assets/16640185/25850537/4d4bc9ee-34f5-11e7-8449-6bcc98674959.png)

**Comment by dangyanglim** [comment]
dist里面的文件直接放在根目录是可以的

**Comment by dangyanglim** [comment]
http://120.77.241.56/manage/dist/

**Comment by zuiidea** [comment]
nginx可以指定根目录的

**Comment by dangyanglim** [comment]
@zuiidea 
不太理解你的意思，
我的根目录是root/wjwl/www/
但是那个dist里面的文件我不能直接放在www下面，因为下面已经有其他网站了，
我需要放在www/manage 下面这样

![image](https://cloud.githubusercontent.com/assets/16640185/25880938/d968d904-356c-11e7-9c4c-62b8770601fa.png)

**Comment by sbyps** [comment]
@dangyanglim 
location / {
  root /home/wjwl/www/manage/dist
  index index.html
  try_files  $uri $uri/ /index.html;
}

**Comment by dangyanglim** [comment]
@sbyps 
这样做，我想同时访问www/index.html这个怎么办？

**Comment by dangyanglim** [comment]
@sbyps 
需要部署多个网站
/下面有一个网站
/manage/下面才是这个网站

**Comment by sbyps** [comment]
@dangyanglim 
location /manage {
root /home/wjwl/www/manage/dist
index index.html
try_files $uri $uri/ /index.html;
}

**Comment by sbyps** [comment]
@dangyanglim 去了解下nginx的location规则吧

**Comment by dangyanglim** [comment]
@sbyps 
你这样配置，相当没配置
因为即使你不配置这个
访问/manage也会定位到/manage,
因为manage本来就是房子根目录下
location /manage {
root /home/wjwl/www/manage/
index index.html
try_files $uri $uri/ /index.html;
}

**Comment by sbyps** [comment]
@dangyanglim 
这样配置/manage的root就指向了具体的目录，nginx发现/manage的url就会覆盖/的location设置

**Comment by dangyanglim** [comment]
@sbyps 
不行啊

![Uploading QQ图片20170509175425.png…]()

**Comment by dangyanglim** [comment]
@sbyps 
![image](https://cloud.githubusercontent.com/assets/16640185/25882526/7d95f670-3576-11e7-8379-27571fa38ad3.png)

**Comment by dangyanglim** [comment]
@zuiidea 
能否试下部署到
127.0.0.1/manage/

**Comment by zuiidea** [comment]
你可以部署到其他端口

**Comment by dangyanglim** [comment]
@zuiidea 
嗯我试了
我manage部署到了7900端口，这个端口root是home/wjwl/www/manage
然后通过proxy-pass到了80端口的manage,这个端口root是home/wjwl/www
登录http://120.77.241.56/manage
跳转到了
http://120.77.241.56/login?from=/manage/
500错误

**Comment by zuiidea** [comment]
你看看http://120.77.241.56/manage/login?from=/manage/能不能访问，
改`src/models/app.js`的51行
```
window.location = `${location.origin}/login?from=${from}`
```
为
```
window.location = `${location.origin}/manage/login?from=${from}`
```

**Comment by dangyanglim** [comment]
@zuiidea 
试了跳转到http://120.77.241.56/manage/login?from=/manage/login
也不行
我正在把route.js里面login前面加manage

**Comment by dangyanglim** [comment]
@zuiidea 
favicon怎么修改？
可以了，修改了
window.location = `${location.origin}/manage/login?from=${from}`
修改了route.js里面login前面加manage
修改了roadhogrc.js
"publicPath": "/manage/",
 修改了config.s
  logo: './logo.png',
  iconFontCSS: './iconfont.css',
  iconFontJS: './iconfont.js',
修改了
index.html
<script src="./index.js"></script>

  还剩favicon怎么修改？
GET http://120.77.241.56/favicon.ico 500 (Internal Server Error)

**Comment by dangyanglim** [comment]
@zuiidea 
有些文件可以改成相对路径
http://120.77.241.56/manage/
还剩favicon怎么修改？

**Comment by zuiidea** [comment]
favicon.ico 放在 public 目录

**Comment by dangyanglim** [comment]
@zuiidea 
怎么改变它的地址
GET http://120.77.241.56/favicon.ico 500 (Internal Server Error)

**Comment by zuiidea** [comment]
啥？

**Comment by dangyanglim** [comment]
@zuiidea 
http://120.77.241.56/manage/

登录获取不到favicon.ico

**Comment by zuiidea** [comment]
http://120.77.241.56/manage/logo.png
这个都能访问啊，你把favicon.ico放在public目录，通过http://120.77.241.56/manage/favicon.ico就能访问了啊，wtf，这跟登录不登录有什么关系

**Comment by dangyanglim** [comment]
@zuiidea 
说错了，是打开那个链接看报错找不到favicon.ico
把favicon.ico放在public也不行的吧，因为它现在是通过http://120.77.241.56/favicon.ico 这个地址来请求的而不是http://120.77.241.56/public/favicon.ico

**Comment by zuiidea** [comment]
好气噢

**Comment by sbyps** [comment]
@zuiidea 
能给个联系方式么，我现在基于这个做一个大项目的开发，有代码抽象的问题想请教你

**Comment by dangyanglim** [comment]
可以了，原来那个是图标
修改index.html
添加

<link rel="icon" href="http://120.77.241.56/manage/favicon.ico" type="image/x-icon" />

多有麻烦，抱歉

**Comment by zhangjingge** [comment]
@dangyanglim 我也想实现这个前面加统一开始路径的功能，/manage/  ，这样的话是不是所有判断路径的时候都要加/manage         

路径判断location.pathname === '/manage/user'是不是要加/manage/
本地，如果登录的时候就开始加http://localhost:8000/manage/login?from=/
index.html页面的js 写为相对路径./index.js就会报错找不到
如果不写为相对路径，那么build后js路径是http://localhost:666/index.js，预期结果应该是http://localhost:666/manage/index.js
![10](https://user-images.githubusercontent.com/20674049/27363947-185cafd2-566a-11e7-946d-7eb01fd5223b.png)
