### ISSUE TITLE
打包后放IIS，login直接404

### ISSUE THREAD

**Issue by internet5** [zuiidea/antd-admin#274]
打包后放IIS，login直接404，请问如何解决

**Comment by internet5** [comment]
刚把权限去掉试了下，发现其他页面可以进去，导致404的问题是在url后面加?参数

**Comment by zuiidea** [comment]
检查一下你未登录跳转的链接

**Comment by internet5** [comment]
直接下载后没作更改的代码，链接是http://localhost:802/login?from=/

**Comment by zuiidea** [comment]
进得了其他页面，进login 404 ??

**Comment by internet5** [comment]
其他页面可以进，但是在URL那里敲下回车就404了

**Comment by internet5** [comment]
你有IIS吗，可以测试下

**Comment by zuiidea** [comment]
没有

**Comment by internet5** [comment]
那咋办

**Comment by zuiidea** [comment]
你需要一个URL Rewrite模块，把所有的路由指向index.html，具体怎么做我也不会
如果嫌麻烦就用nginx , https://github.com/zuiidea/antd-admin/issues/269

**Comment by internet5** [comment]
好，谢谢了

**Comment by zuiidea** [comment]
404 的原因就是因为，那个路由没有资源，
还有一种方法就是把browserHistory改为hashHistory，就不需要部署服务器了

**Comment by internet5** [comment]
了解了

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/269

**Comment by enlyck** [comment]
请问问题最后解决了么？我也遇到这种问题，

**Comment by mapengze** [comment]
@zuiidea 我改成hashHistory了  build之后还是访问不了html啊

**Comment by taliove** [comment]
IIS安装rewrite模块，将下面code保存为`.htaccess`，然后使用IIS的重写模块导入规则就可以哒。
<IfModule mod_rewrite.c>
  Options +FollowSymlinks -Multiviews
  RewriteEngine On

  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.html [QSA,PT,L]
</IfModule>

**Comment by dugu666** [comment]
怎么部署在tomcat下面

**Comment by 0end1** [comment]
umirc的配置里做一下html的输出 exportStatic: { },然后再iis上就可以跑了
