### ISSUE TITLE
新手请教：如何禁止form表单的自动刷新页面操作？

### ISSUE THREAD

**Issue by gtUserName** [zuiidea/antd-admin#275]
@zuiidea ，您好：
我是一个reactjs新手，参考antd-admin实现了一个登陆页，在antd-admin的登录页中，如果用户名或者密码没有输入的时候会弹出提示，页面保持在登录页，但是在我的页面中，handleOK函数中的代码运行完成后页面立即重新加载了，按照以前的经验在onSubmit函数最后`return false`，尝试后发现dva不是这样玩的，我看了一天多也没有找到问题在哪里，请帮忙指教一下，多谢！

我的项目完整代码位置：[代码仓库](https://code.aliyun.com/opsi.coco/opsi-client/tree/master/src)

> antd-admin登陆处理代码
```js
  function handleOk () {
    validateFieldsAndScroll((errors, values) => {
      if (errors) {
        return
      }
      dispatch({ type: 'login/login', payload: values })
    })
  }
```
下面是我的处理函数
```js
  function handleOk() {
    validateFieldsAndScroll((errors, values) => {
      if (errors) {
        return false
      }
      dispatch({ type: 'app/login', payload: values })
      debugger;
      return false
    })
    return false
  }
```

### ps:
关于antd-admin登录页的两个小疑问：
1. 表单使用的 html 原生的 form 元素而不是 Ant Design of React 提供的 Form 组件
2. 监听 form 提交使用了表单元素的回车和按钮点击事件而不是直接使用 form 的 submit 事件

**Comment by zuiidea** [comment]
提交的按钮不要使用 `htmlType="submit"`

**Comment by gtUserName** [comment]
尝试了一下，问题解决了，多谢指导。

在你提供的思路下我又去看了一下 [Ant Design of React 的 Form 表单](https://ant.design/components/form-cn/)文档，发现在示例里通过 `e.preventDefault()` 阻止页面刷新，我测试了一下也是OK的

> Ant Design of React 的 Form 表单示例代码
```
  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        console.log('Received values of form: ', values);
      }
    });
  }
```

**Comment by Keung123** [comment]
> 尝试了一下，问题解决了，多谢指导。
> 
> 在你提供的思路下我又去看了一下 [Ant Design of React 的 Form 表单](https://ant.design/components/form-cn/)文档，发现在示例里通过 `e.preventDefault()` 阻止页面刷新，我测试了一下也是OK的
> 
> > Ant Design of React 的 Form 表单示例代码
> 
> ```
>   handleSubmit = (e) => {
>     e.preventDefault();
>     this.props.form.validateFields((err, values) => {
>       if (!err) {
>         console.log('Received values of form: ', values);
>       }
>     });
>   }
> ```

感谢！！！
