### ISSUE TITLE
请问在modal中使用autocomplete，onSelect使模态框持续刷新问题

### ISSUE THREAD

**Issue by acpplife** [zuiidea/antd-admin#289]
大神你好~
       模态框中使用自动填充组件，提示列表由redux维护，每次输入内容变化都会触发模态框刷新。请问有什么办法解决这个问题吗？

**Comment by FatFatFox** [comment]
因为作者使用的是这种方式，每次都会初始化一下:
`const UserModalGen = () =>
    <UserModal {...userModalProps} />`

你可以在Modal文件中使用：
`return
    isNew ? null :
    <Modal {...userModalProps} >`
方式，在model里加一个isNew，记录一下弹出框状态

**Comment by acpplife** [comment]
嗯嗯，发现啦，解决啦。谢谢大神😄
