### ISSUE TITLE
哪位大神知道不想用mock里面的数据了，想从后台直接获取，应该怎么改

### ISSUE THREAD

**Issue by yanghong1105** [zuiidea/antd-admin#291]

**Comment by jiangbo2015** [comment]
不用roadhog.mock.js就可以了啊

**Comment by jackple** [comment]
@jiangbo2015 删除吗

**Comment by yanghong1105** [comment]
删除了就可以了吗，不用再改其他的东西，我删除了，和后台已经请求成功了，数据还是不显示

**Comment by jiangbo2015** [comment]
看你后台返回数据没，models里面数据是否拿到

**Comment by yanghong1105** [comment]
后台返回数据了，已经显示status是200
Request URL:http://localhost/o/organ/list
Request Method:GET
Status Code:200 
Remote Address:127.0.0.1:80

**Comment by Junrui-L** [comment]
这个系统的架构看起来怎么这么费劲啊

**Comment by jackple** [comment]
熟悉之后觉得挺好的, 我是直接删除了mock部分. 向本地或者远程服务器请求数据

**Comment by Junrui-L** [comment]
可是我才看着个东西，三天，就要搞一个后台管理的出来，不知道数据怎么传递，这种函数式无状态的写法，参考太少了，也不知道数据是怎么传递的。。。

**Comment by zuiidea** [comment]
@Junrui-L  https://github.com/dvajs/dva-knowledgemap

**Comment by allinshang** [comment]
user实例。好像不能修改接口的字段名吧
