### ISSUE TITLE
一个页面显示多个table列表的大概思路是什么，一直有问题

### ISSUE THREAD

**Issue by zhangjingge** [zuiidea/antd-admin#297]
一个页面显示多个table列表的大概思路是什么？
models是分开写么？
namespace是多个吗？
尝试这么写相对应的routes文件夹下面获取不到多个namespace具体应该是怎么样的？

**Comment by FatFatFox** [comment]
是我的话，我会写到一起。。。用一个namespace。
一个页面(index.js)是总的models，一个namespace。
参考：
https://github.com/dvajs/dva-docs/tree/master/v1/zh-cn/tutorial

**Comment by zhangjingge** [comment]
@FatFatFox 尝试过写到一起，但是分页处理的时候出错，分页处理是又写了一个pagination2，类似这样的，但是实际处理的过程中出错，目前不能十分确定是我处理错误还是不能这样处理所以尝试分开写，但是分开直接获取不到第二个namespace

**Comment by FatFatFox** [comment]
是我的话，一个state里，一个表格的数据就封装成一个大的对象，pagination嵌套在里边。两个表格就两个对象，公用一个namespace。

**Comment by zhangjingge** [comment]
@FatFatFox 我还没尝试你说的办法，但是我觉得会出现深层嵌套的问题？

![12](https://cloud.githubusercontent.com/assets/20674049/26334345/fcfaaa8a-3f96-11e7-9ce6-320a2c2ad042.png)
pagination字段会出现深层嵌套的问题，我觉得这个方案有待商榷

**Comment by zhangjingge** [comment]
@FatFatFox 
采用多个registerModel的方法解决了，感谢帮忙！！！

**Comment by FatFatFox** [comment]
我在router.js里也看到了registModel的方法，能否告诉我一下你是如何做的？

**Comment by zhangjingge** [comment]
@FatFatFox 
![17 05 26 1048_2](https://cloud.githubusercontent.com/assets/20674049/26478747/f62121aa-4200-11e7-8c82-a50c8d338aaf.png)

**Comment by FatFatFox** [comment]
@zhangjingge 谢谢了，这样搞应该更合理！
