### ISSUE TITLE
browserHistory的疑问

### ISSUE THREAD

**Issue by HengCC** [zuiidea/antd-admin#298]
有个疑问请教下, 现在demo中使用的是browserHistory, 当我浏览器在刷新的时候前端是如何能够正确渲染的呢?  比方 我请求的路径是 http://xxxx/user/123,  按理来说在刷新的时候这样的URL在后端是不存在的. 肯定会返回一个404的错误.  但是实际却能够正常的根据mockjs中的配置渲染出来页面. 这样的"后端"渲染过程是由谁完成的呢?

**Comment by darcygail** [comment]
当请求这个URL时,前端route会进行匹配显示相应的页面,而后端数据则是在model中使用subscriptions中的setup去发起Action,将返回的数据放进state,之后render整个页面.

**Comment by HengCC** [comment]
@darcyaf Hi 我了解你的意思  , 这块的渲染逻辑我也清楚. 我想表达的意思是 "当我**手动刷新**浏览器" 

这个时候前端的路由是只能等页面加载后才能生效的. 我通过捕获了网络请求, 每次手动刷新的时候都会先加载index.html, 然后在加载index.js和剩余的. 所以在执行手动刷新的时候一定有一个位置将我的请求导向了index.html. 我想知道的就是这个位置或者时间点 , 谢谢. 望解惑

**Comment by zuiidea** [comment]
@HengCC  https://github.com/zuiidea/antd-admin/issues/269

**Comment by HengCC** [comment]
@zuiidea 3Q
