### ISSUE TITLE
感谢作者分享！问个mock数据的问题

### ISSUE THREAD

**Issue by rockswang** [zuiidea/antd-admin#3]
我发现用npm run build构建出来的js里面包含mock.js的测试数据，感觉这样会导致大不少，但是不知道生产版版在哪里引用的mock.js呢，为什么会被webpack导入？

**Comment by zuiidea** [comment]
讲道理，build后的js里不会带有mock数据，mock数据是在代码运行时产生的，并存储在localstrorge里，你看到的可能是mock.js这个插件的代码，生产环境中可以将src/utils/index.js中的，require('./mock.js')注释掉，请求就不会被代理了
