### ISSUE TITLE
控制台报错，proxy.config.js parse error

### ISSUE THREAD

**Issue by dicklwm** [zuiidea/antd-admin#30]
代码是直接clone下来的，没有修改过，npm start 之后，控制台报这个错了，这个代理是做什么用的呢？ @zuiidea

**Comment by zuiidea** [comment]
暂时先 `npm run dev` 试试

**Comment by dicklwm** [comment]
@zuiidea 用npm run dev是可以，但是切换菜单，还是会报model唯一的那个错误呢

**Comment by wuyongdec** [comment]
Linux下我换成npm run dev后台不报错了，但是访问登陆页面的时候还是不行，一直在加载用户信息那里打转。
Windows没有这个问题。
