### ISSUE TITLE
表单中输入框值远程合法性验证问题

### ISSUE THREAD

**Issue by chenbaolou** [zuiidea/antd-admin#300]
问题是这样的，有一个输入框，我想在onBlur时机去验证该值在数据库中是否已经存在，就像我们平时注册邮箱的时候会实时提示该邮箱名称是否已经被使用。之前在jquery时代可以是指ajax请求为同步。但是，在antd+dva框架中请求都是通过dispatch发起的，在这种情况下该如何实现呢？

**Comment by FatFatFox** [comment]
你的问题是要远程同步校验吗？
dispatch到reducer里不就可以了嘛？

**Comment by chenbaolou** [comment]
是要远程校验的，但是实际上并不需要同步实现，因为antd框架form组件validateFields方法会自动对异步操作进行阻塞。

**Comment by yinxuan1128** [comment]
这个问题最后怎么解决的呢？

**Comment by superlbr** [comment]
利用validator(内置的是async-validator)
写法如下:
`rules: [{   
                    validator: (rule, value, cb) => {   
                      validateBill(value)   
                      cb()}]`
这样validateBill里面就可以调用逻辑判断，远程接口
参考https://github.com/yiminghe/async-validator#validator
