### ISSUE TITLE
登录时直接报跨域问题

### ISSUE THREAD

**Issue by musicsnap** [zuiidea/antd-admin#301]
windows10 启动运行后，登录时直接报跨域问题

XMLHttpRequest cannot load http://localhost:8000/api/v1/user. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access.

**Comment by zuiidea** [comment]
你访问  http://localhost:8000 就好了啊
