### ISSUE TITLE
是否能支持hash路由？

### ISSUE THREAD

**Issue by train860** [zuiidea/antd-admin#306]
之前的版本默认是hash路由，新版本没有了，这样部署就不太方便，需要配单独的web服务器，是否有方法支持hash路由？这样直接扔服务器目录就可以用了。
谢谢

**Comment by zuiidea** [comment]
src/index.js中去掉browserHistory

**Comment by train860** [comment]
打包成静态文件后，好像还是不行。希望可以打包成静态文件后，放到nginx目录直接可以访问

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/269

**Comment by zuiidea** [comment]
browserHistory也是打包后放在nginx目录就可以了
另外去掉browserHistory，默认就是hash路由的，此时不需要部署就可以直接访问

**Comment by train860** [comment]
我再试试，谢谢
