### ISSUE TITLE
更改整体布局后，内容部分怎么处理？

### ISSUE THREAD

**Issue by doterme** [zuiidea/antd-admin#308]
@zuiidea 我把布局调整成这样了
![image](https://cloud.githubusercontent.com/assets/12495369/26432841/304b9124-4131-11e7-9325-33ac715e9158.png)
上下两部分的布局，顶部Header固定，中间Content根据顶部菜单动态加载，请问Content怎么做占位处理。

**Comment by FatFatFox** [comment]
看一下routes/app.js文件里的{children}部分
