### ISSUE TITLE
Router.js 重复注册 dashboard模块，导致从别的菜单点回dashboard时候报错

### ISSUE THREAD

**Issue by ulongx** [zuiidea/antd-admin#31]
![dashboard](https://cloud.githubusercontent.com/assets/1161624/21881091/517b48ba-d8dd-11e6-8cb2-65336ece15de.png)
![dashboard2](https://cloud.githubusercontent.com/assets/1161624/21881111/6c732bce-d8dd-11e6-8b65-49b4b2572768.png)

**Comment by ulongx** [comment]
把app.model(require('./models/dashboard')) 都移动到index.js面就不会有问题

**Comment by zuiidea** [comment]
这个可能是dva版本问题，你暂时把dva安装为1.1，移动到index.js就不能动态加载了
https://github.com/dvajs/dva/issues/465

**Comment by files3** [comment]
@WX20170117-162811@2x.png

我应该是已经安装了1.1版本还是不行

**Comment by zuiidea** [comment]
`npm install dva@1.1.0`，这样试试，@files3，你打开`node-modules`里的`dva/packge.json`，应该不是1.1

**Comment by files3** [comment]
ok，thanks
