### ISSUE TITLE
npm WARN deprecated react-addons-transition-group@15.5.2

### ISSUE THREAD

**Issue by cdaiga** [zuiidea/antd-admin#310]
Beautiful! I just downloaded it and try to install the packages using: `npm install` but I am getting:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
G:\NodeJs\antd-admin-master>npm run dev

> @ dev G:\NodeJs\antd-admin-master
> set BROWSER=none&&set HOST=0.0.0.0&&roadhog server

'roadhog' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Claude_daiga\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `set BROWSER=none&&set HOST=0.0.0.0&&roadhog server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'set BROWSER=none&&set HOST=0.0.0.0&&roadhog
 server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     set BROWSER=none&&set HOST=0.0.0.0&&roadhog server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\NodeJs\antd-admin-master\npm-debug.log

How do I fix this please?

**Comment by zuiidea** [comment]
try  `npm i roadhog@0.6.0-beta.6 -g`

**Comment by cdaiga** [comment]
Thank you for your response but I am getting another issue:


G:\NodeJs\antd-admin-master>npm i roadhog@0.6.0-beta.6 -g
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ro
adhog\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Claude_daiga\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "roadhog@0.6.0-beta
.6" "-g"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.1
npm ERR! file C:\Users\Claude_daiga\AppData\Roaming\npm-cache\graceful-readlink\
1.0.1\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!

npm ERR! ^
npm ERR! File: C:\Users\Claude_daiga\AppData\Roaming\npm-cache\graceful-readlink
\1.0.1\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     G:\NodeJs\antd-admin-master\npm-debug.log

**Comment by superlbr** [comment]
maybe `yarn install` is better
