### ISSUE TITLE
已经使用了browserHistory，为什么访问页面的时候链接后还会出现?_k=hl4khv这种后缀

### ISSUE THREAD

**Issue by iceking112** [zuiidea/antd-admin#311]
如题

**Comment by wing2002li** [comment]
浏览器为了提高用户访问同一页面的速度，会对页面数据进行缓存。当url请求地址不变时，
有时候会导致浏览器不发送请求，直接从缓存中读取之前的数据。
如果数据改变了，而没加随机数，读取的数据会跟之前一样。
加上随机数，就是欺骗浏览器url改变了，会每次都向服务器发送请求而不去读缓存

**Comment by zuiidea** [comment]
这个项目中没有后缀吧
