### ISSUE TITLE
怎么做权限管理呢

### ISSUE THREAD

**Issue by JackZong** [zuiidea/antd-admin#314]

**Comment by JackZong** [comment]
请问下怎么实现权限管理？有什么好的解决方案吗谢谢😆

**Comment by jackple** [comment]
- 我现在是分4种用户权限类型level(0超级管理员,1管理员,2权限组账户,3普通账户)
- 有user和userGroup表,其中包含authorizedMenu字段
- 如果level为0/1,拥有全部权限(其中0超级管理员不能新增,并且只给开发者使用),如果level为2,对应的权限在userGroup表的authorizedMenu字段,如果level为3,对应的权限在user表的authorizedMenu字段
只是大概说一下,谢谢

**Comment by DiroKate** [comment]
@jackple 有没有源码可以参考一下？

**Comment by jackple** [comment]
@DiroKate 我是都在服务端控制的
贴主要的给你
`
async function getUserMenu(uid) {
    const resdata = Object.assign({}, BASERESDATA),
        startTime = new Date().getTime(),
        userInfo = await new DBCtrl(User).findOne({
            _id: uid
        });
    if (!userInfo) {
        Object.assign(resdata, {
            menu: [],
            message: '没有要查询的账户',
        });
        return resdata;
    }
    const {level, userGroupID, authorizedMenu} = userInfo;
    let result;
    //超级管理员和管理员拥有全部菜单权限
    if (level === 0 || level === 1) {
        result = await new DBCtrl(Menu).find({}, null, {
            sort: {
                orderBy: 1
            }
        });
    }
    //查找用户组权限
    else if (userGroupID) {
        const userGroupuInfo = await new DBCtrl(UserGroup).findOne({
                _id: userGroupID
            }),
            userGroupuAthorizedMenu = userGroupuInfo.authorizedMenu;
        result = await new DBCtrl(Menu).find({
            "id": {
                "$in": userGroupuAthorizedMenu
            }
        }, null, {
            sort: {
                orderBy: 1
            }
        });
    }
    //查找用户权限
    else if (authorizedMenu && authorizedMenu.length > 0) {
        result = await new DBCtrl(Menu).find({
            "id": {
                "$in": authorizedMenu
            }
        }, null, {
            sort: {
                orderBy: 1
            }
        });
    } else {
        Object.assign(resdata, {
            menu: [],
            message: '用户无菜单权限',
        });
        return resdata;
    }
    if (result && result.length) {
        Object.assign(resdata, {
            menu: result,
        });
        return resdata;
    }
    Object.assign(resdata, {
        menu: [],
        message: '获取菜单失败',
    });
    return resdata;
}`
代码写得烂,见笑了
前端直接用antd的Tree组件来调整权限

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/384
