### ISSUE TITLE
antd-admin/src/router.js 按需加载在运行编译后的代码会报错 Help

### ISSUE THREAD

**Issue by MrChongdong** [zuiidea/antd-admin#317]
不编译 直接运行是不会有问题 , 但跑编译后的代码时就会出现 bug

<img width="968" alt="qq20170529-141754 2x" src="https://cloud.githubusercontent.com/assets/20316147/26538414/2458fa78-4479-11e7-851a-479bff735aff.png">

找到原因是 require.ensure 编译后缺少了某些组件, 全部改回同步加载组件后问题解决, 但是这样做会把所有组件都加载到同一个 js 文件里面去 ,无法做到按需加载对应路由的 js 文件, 有什么办法何以解决吗?

**Comment by zuiidea** [comment]
检测一下是不是每一个模块生成的文件别名相同，导致部分模块实际上没加载

**Comment by MrChongdong** [comment]
不允许动态路径
