### ISSUE TITLE
如何覆盖antd自带样式(不使用:global 这种全局覆盖的办法，只针对单一页面进行样式覆盖)

### ISSUE THREAD

**Issue by ppboyly** [zuiidea/antd-admin#319]

**Comment by zuiidea** [comment]
`:global `没有全局覆盖啊，它的作用是它作用域内的class不使用css module

**Comment by ppboyly** [comment]
使用global修改原来antd的样式后，别的页面同样的组件也会被修改，有办法只覆盖掉当前页面的样式么

**Comment by ppboyly** [comment]
如果单纯的覆盖组件样式  不加global又不起作用

**Comment by zuiidea** [comment]
在当前页面加一个顶级的class名，该页面的所有class嵌套在该顶级class下就可以了啊

**Comment by enlyck** [comment]
@zuiidea 请问， 如果组件是在body节点下，这种情况，我想局部修改样式，如何处理呢？例如我想改变级联下拉框的高度，这个组件就是放在body节点。
