### ISSUE TITLE
把批量删除加上去就更完美了，表格一般都会有批量删除

### ISSUE THREAD

**Issue by yanghong1105** [zuiidea/antd-admin#320]

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/b83c5e7819b9e38430e432df0273ab51e4fb69cd，加上了

**Comment by yanghong1105** [comment]
批量删除的时候如果选中2,3请求地址是/delelt/2,3,这种地址应该怎么匹配

**Comment by zuiidea** [comment]
我有封装这种restful风格啊

```
request({
    url: `/delelte/:id`,
    method: 'delelte',
    data: {
       id:'2,3'
    },
  })
```

**Comment by yanghong1105** [comment]
url:'/delete/:id'
GET /o/organ/delelte/:id?ids[]=nmnmnmnmn&ids[]=tytytytyt 
用get请求的时候怎么是这种情况，而不是我想要的delete/nmnmnmnmn,tytytytyt 这种形式，这是哪的问题请教一下 您

**Comment by zuiidea** [comment]
`:id` 就代表 data 里的id属性，只是一个变量而已，你既然叫ids那就可以改成
```,
request({
    url: `/delelte/:ids`,
    method: 'delelte',
    data: {
       ids:'nmnmnmnmn,tytytytyt '
    },
  })
```
url中的多个中括号代表的是数组，你传的ids是数组不是字符串吧

**Comment by yanghong1105** [comment]
我这边传的是数组，但是删除的时候不对,地址GET /o/organ/delelte/:id?id[]=nmnmnmnmn&id[]=tytytytyt 


url:'"/o/organ/delelte/:id"'
id:Array[2]
0:"nmnmnmnmn"
1:"tytytytyt"
length:2

**Comment by yanghong1105** [comment]
解决了，谢谢楼主
