### ISSUE TITLE
大家有遇到过index打包过大，js加载时间为5S的问题么？

### ISSUE THREAD

**Issue by zhangjingge** [zuiidea/antd-admin#321]
index打包过大，js加载时间为5S
![js](https://cloud.githubusercontent.com/assets/20674049/26670907/23e6e036-46e6-11e7-9a38-8a64ced5bf8e.png)

**Comment by zuiidea** [comment]
看index.js能不能拆分一下啊，太大了

**Comment by zhangjingge** [comment]
@zuiidea 是通过 roadhog  进行拆分吗？没找到用那个方式拆分，只找到一个多页抽取公共js的方法

**Comment by lilyAlucy** [comment]
hi楼主，解决了吗？我后面也需要借鉴下

**Comment by zhangjingge** [comment]
@lilyAlucy 还没有

**Comment by richartan** [comment]
去掉echart就会好很多。

**Comment by zhangjingge** [comment]
@richartan 可是项目中该是要用图标的，估计不能去掉

**Comment by MengStar** [comment]
![image](https://user-images.githubusercontent.com/16573409/28993125-f518ef64-79e0-11e7-9baa-c67d6b1660b0.png)
你们解决了吗，build出来的文件都 压缩后都400k了

**Comment by daizhikai** [comment]
没压缩的。。。每个文件有5m左右，难怪build的时候内存溢出了。。。，发现里面的sourceMappingURL=data 很大，而且每个文件似乎都重复的。
![image](https://user-images.githubusercontent.com/4993802/29104774-d7b73274-7cfa-11e7-9ecc-bb4dbf18d09e.png)

**Comment by zhangjingge** [comment]
@MengStar 没解决，可以问一下怎么搞定么的？？

**Comment by suiyi8760** [comment]
@zhangjingge 解决了么，我这也用到了echart，build出来2m多的index.js

**Comment by superlbr** [comment]
参考我的答案，https://github.com/zuiidea/antd-admin/issues/712

**Comment by superlbr** [comment]
dist的大小还可以再压缩的,比如nginx,apache之类。

**Comment by zhangjingge** [comment]
@superlbr 谢谢，目前采取了Nginx的方法
