### ISSUE TITLE
请教一下，登录之前不会加载根路由的方法

### ISSUE THREAD

**Issue by htlhenry** [zuiidea/antd-admin#322]
我是新学习dva的，我在看您的例子摸索一些常用功能，我有一个问题：
##### 问题描述：
用户第一次请求过来，路由发生变化然后加载models/app.js，执行subscriptions定义的函数，请求用户信息，成功之后跳转到/dashboard，这个流程是没错的吧？
##### 疑问：
当我按照您的方法自己做的时候会有一个问题，subscriptions函数没执行完，会先加载一下我的根路由，会把UI加载出来一下，之后再跳到登录页。请问下，您是怎么避免这个问题的，因为从源码中没看出，所以来请教一下
PS: 我还发现了一个你的demo如果我请求不存在的地址，你还是会把根路由渲染出来再重定向到/login

**Comment by zuiidea** [comment]
这里是优先加载内容是为了保证登录状态下保持工作现场，你也可以做成，第一次进入时假定用户未登录，获得用户已登录信息后再跳转到内容区域，暂时还没想到更好的折中方法
