### ISSUE TITLE
请问如何把antd的图标放到本地？

### ISSUE THREAD

**Issue by wing2002li** [zuiidea/antd-admin#327]
#270 
1、在src/themes/default.less中添加了@icon-url: "/antd/iconfont";但是还请求的网络地址，请问还有什么注意
2、我在iconfont'上已经生成了新项目，如何下载以后和默认的antd图标合并在一起,补充，我是想把menu的icon改变到本地，并且menu的icon是自定义的图标，原有的antd自带的icon保留。。

**Comment by wing2002li** [comment]
补充，我是想把menu的icon改变到本地。

**Comment by zuiidea** [comment]
- `@icon-url :'"icon-url"'`，请注意引号，这种方式会覆盖的
- 扩展请参照 #270，请看项目中的为了扩展图标写的 `Iconfont `组件

**Comment by wing2002li** [comment]
我按照你的项目里面写的。

**Comment by zuiidea** [comment]
https://ant.design/changelog-cn  2.9至2.10 你看一下这里有没有不兼容升级就可以了

**Comment by haanyip** [comment]
发现一个粗暴的方法  把 node_modules/antd/lib/style/themes/default.less里面的@icon-url路径换掉后再打包 可以临时解决问题  不推荐
