### ISSUE TITLE
页面卡顿问题

### ISSUE THREAD

**Issue by lilyAlucy** [zuiidea/antd-admin#329]
ie11下跑起该项目，感觉页面切换有卡顿，给人一种很不流畅的感觉，有解决方式么？

**Comment by zuiidea** [comment]
把动画相关的去掉吧

**Comment by bindazhong** [comment]
ios下访问的时候比Android下卡很多

**Comment by superlbr** [comment]
使用antd 的table代替Components的DataTable，去掉motion等等。。。
