### ISSUE TITLE
部署到 tomcat 项目名称问题

### ISSUE THREAD

**Issue by javahuang** [zuiidea/antd-admin#330]
您好，我使用 springboot 集成 antd-admin 打成 war 包部署到 tomcat，但是部署的时候只能将 war 包改成 ROOT.war，项目才正常运行，请问能够加上项目名称，比如 10.211.55.13:8080/app/login？我试着改了下，发现前端路由很多都乱了，请问有没有解决方案，非常感谢
![jietu20170605-203132](https://cloud.githubusercontent.com/assets/3992393/26784072/2f62af8a-4a2e-11e7-9250-54bac06697a8.jpg)

**Comment by zuiidea** [comment]
你可以设置其他端口代理到你需要的文件夹，路由上就不要多余的层级了，不然就要改前端代码了
