### ISSUE TITLE
为什么effects里面有的generator函数名加了引号？

### ISSUE THREAD

**Issue by BenAnn** [zuiidea/antd-admin#331]
代码    *'delete' ({ payload }, { call, put, select }) {
      const data = yield call(remove, { id: payload })
      const { selectedRowKeys } = yield select(_ => _.user)
      if (data.success) {
        yield put({ type: 'updateState', payload: { selectedRowKeys: selectedRowKeys.filter(_ => _ !== payload) } })
        yield put({ type: 'query' })
      } else {
        throw data
      }
    },
尝试把引号去掉后并没有发现区别，自己在定义函数的时候并不能使用"xxx"这种形式，在看es6generator相关文章也没有发现任何头绪，不知道是dva特有的还是generator特性，有什么区别呢？

**Comment by yolo2013** [comment]
因为是ES原生的属性

**Comment by LuckyYaYaChen** [comment]
因为delete是关键字，所以用引号了
