### ISSUE TITLE
index.css response Content-Type is text/html

### ISSUE THREAD

**Issue by wuyao1994** [zuiidea/antd-admin#333]
src/index.html 中的`<link rel="stylesheet" href="/index.css" />` 返回的是index.html的内容，response Content-Type 是 text/html。
使用dora的时候，index.css返回的是css样式，从 atool-build + dora 转到 roadhog 后开始出现的这个问题，
现在最新的antd-admin也是这样的

**Comment by Deantsui** [comment]
+1

**Comment by superlbr** [comment]
请提供Network的截图，未能复现

**Comment by superlbr** [comment]
可能 https://github.com/dvajs/dva/issues/1207

**Comment by wuyao1994** [comment]
很久以前的问题了，当时没有大的影响，只是有这个疑问，现在最新版本已经没有这个bug了，closed
