### ISSUE TITLE
index.js/css 没加hash, 缓存依然存在吧

### ISSUE THREAD

**Issue by jackple** [zuiidea/antd-admin#336]
@zuiidea webpack.config.js就这样单纯地改chunkFilename没用吧, index.js还是被浏览器缓存了,要加载的异步js还是旧的, 这个是我以前一直遇到的问题.
我现在只是取巧的把webpack.config.js改成下面这样

module.exports = (webpackConfig) => {
    // FilenameHash
    webpackConfig.output.filename = '[name].[hash:6].js';
    webpackConfig.output.chunkFilename = '[id].[chunkhash:6].async.js'; // http://webpack.github.io/docs/configuration.html#output-chunkfilename
    /* eslint-disable */
    const ExtractTextWebpackPlugin = require('extract-text-webpack-plugin');
    /* eslint-enable */
    webpackConfig.plugins[3] = new ExtractTextWebpackPlugin('[name].[hash:6].css');
    // ClassnameHash
    const cssLoaderOption = {
        importLoaders: 1,
        modules: true,
        localIdentName: '[hash:base64:5]',
    };
    const cssLoaders = webpackConfig.module.loaders[3].loader.split('!');
    webpackConfig.module.loaders[3].loader = cssLoaders.map(item => {
        if (item.startsWith('css')) {
            return `css?${JSON.stringify(cssLoaderOption)}`;
        }
        return item;
    }).join('!');
    // PreLoaders
    // webpackConfig.module.preLoaders = [{
    //     test: /\.js$/,
    //     enforce: 'pre',
    //     loader: 'eslint',
    // }];
    return webpackConfig;
};

添加build.js
const fs = require('fs');
const path = require('path');
const dist = path.join(__dirname, 'dist'),
    indexHtml = path.join(dist, 'index.html')
//固定的要替换的字符串
const replaceJsString = '"/index.js"';
const replaceCssString = '"/index.css"';
fs.readdir(dist, (err, files) => {
    if (err) {
        console.log(err);
        return;
    }
    let fileContent = fs.readFileSync(indexHtml, 'utf8');
    files.forEach(filename => {
        if (filename.includes('index.')) {
            if (filename.includes('.css')) {
                fileContent = fileContent.replace(replaceCssString, `"/${filename}"`);
            } else if (filename.includes('.js')) {
                fileContent = fileContent.replace(replaceJsString, `"/${filename}"`);
            }
        }
    });
    fs.writeFile(indexHtml, fileContent, err => {
        if (err) {
            console.error('写入文件失败');
        }
        console.log('写入文件成功');
    });
});

然后把命令改成
`roadhog build && node build"`

PS: 我试过随便修改一个异步文件, index.js的chunkhash是会改变的,filename应该是用hash和chunkhash都是一样的

不过显然这样是不符合规范的,只是临时实现

**Comment by zhangjingge** [comment]
@jackple 你好我准备也有build.js的这样方法，我手动加了v=1，时间长chrome页面控制台调试的时候页面会整个黑掉，想问一下目前你这边用build.js是否一切正常

**Comment by jackple** [comment]
@zhangjingge 一切正常,只是不太优雅

**Comment by zhangjingge** [comment]
@jackple 好的，非常感谢
