### ISSUE TITLE
怎么启动的哈 

### ISSUE THREAD

**Issue by pisful** [zuiidea/antd-admin#339]
小白玩家碰到问题
Error in multi index
Module not found: 'eslint' in E:\antd-admin

 @ multi index

Error in multi index
Module not found: 'eslint' in E:\antd-admin

 @ multi index

**Comment by jsven** [comment]
遇到同样的问题

**Comment by youthcity** [comment]
我将根目录下`webpack.config.js`中， 19-24行注释掉就可以启动了。注释掉的代码如下。
```
  // PreLoaders
  webpackConfig.module.preLoaders = [{
    test: /\.js$/,
    enforce: 'pre',
    loader: 'eslint',
  }]
```

**Comment by jsven** [comment]
@youthcity  这个是打包前的eslint检测，这个包就是eslint啊，装了的

**Comment by pisful** [comment]
@jsven @youthcity 删了那个的确可以 但是我load了eslint 不知道为啥要删除
![qq 20170609093422](https://user-images.githubusercontent.com/19769904/26957327-db8e938a-4cf6-11e7-8132-b8dcc6bc19ec.png)

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/pull/340/commits/bfff28411d056300150ad9aee8967cad0b2565ca

`npm i eslint-loader -D`

**Comment by jsven** [comment]
代码里面开启eslint之后代码有很多不符合规范的地方，基本看到的都是defined but never used  no-unused-vars，建议把这些东西都改好，虽然说我自己改比较简单但是别人都来clone，都要改一次就不好了。

**Comment by zuiidea** [comment]
@jsven  最新的代码都是通过eslint了啊

**Comment by jsven** [comment]
@zuiidea 我昨天拉的代码，里面有几处地方defined but never used no-unused-vars. 还有npm run build之后我希望在dist中的index.html能直接在浏览器中打开运行，目前发现资源路径有问题，不知道这个需要怎么改。我看了资源路径好想都是绝对路径引入的。

**Comment by zuiidea** [comment]
@jsven  https://github.com/zuiidea/antd-admin/issues/269
