### ISSUE TITLE
输入完账号密码点击登陆后报错，无法进入，再次刷新后就直接登录进去了

### ISSUE THREAD

**Issue by willcj** [zuiidea/antd-admin#34]
The width(0) and height(0) of chart should be greater than 0,
       please check the style of container, or the props width(100%) and height(100%),
       or add a minWidth(undefined) or minHeight(360) or use aspect(undefined) to control the
       height and width.

LogUtils.js? (第 23 行)
uncaught

at _callee 
 at _callee4 
 at takeEvery(app/login, sagaWithCatch) 
 at sagaWithCatch 
 start/onError<@webpack:///./~/dva/lib/createDva.js?:201:15
apply/<@webpack:///./~/dva/lib/plugin.js?:97:11
onErrorWrapper@webpack:///./~/dva/lib/createDva.js?:206:11
sagaWithCatch$@webpack:///./~/dva/lib/createDva.js?:494:17
tryCatch@webpack:///./~/regenerator-runtime/runtime.js?:64:37
invoke@webpack:///./~/regenerator-runtime/runtime.js?:355:22
defineIteratorMethods/</prototype[method]@webpack:///./~/regenerator-runtime/runtime.js?:116:16
next@webpack:///./~/redux-saga/lib/internal/proc.js?:293:18
currCb@webpack:///./~/redux-saga/lib/internal/proc.js?:392:7
end@webpack:///./~/redux-saga/lib/internal/proc.js?:359:18
abort@webpack:///./~/redux-saga/lib/internal/proc.js?:95:5
addTask/task.cont@webpack:///./~/redux-saga/lib/internal/proc.js?:108:9
next@webpack:///./~/redux-saga/lib/internal/proc.js?:332:7
currCb@webpack:///./~/redux-saga/lib/internal/proc.js?:392:7
notify/</run@webpack:///./~/core-js/library/modules/es6.promise.js?:87:22
notify/<@webpack:///./~/core-js/library/modules/es6.promise.js?:100:28
module.exports/flush@webpack:///./~/core-js/library/modules/_microtask.js?:18:9

utils.js? (第 197 行)
![2017-01-13 9 34 46](https://cloud.githubusercontent.com/assets/1034714/21915270/c01bfdbe-d973-11e6-8cdf-a5a9271fc59e.png)

**Comment by zuiidea** [comment]
看不出来是什么，建议拉取最新代码，确保依赖完整安装

**Comment by otawa811** [comment]
@willcj 之前遇到同样问题，把 "antd": "2.6.0" 设置为这个之后就没再出现过。
