### ISSUE TITLE
楼主，我如何把后台的一串数字转换成年月日时分秒

### ISSUE THREAD

**Issue by yanghong1105** [zuiidea/antd-admin#343]
createDate:1497237181838

**Comment by dj940212** [comment]
`const formatDate=function(value){
    if(value){
        var year = value.getFullYear();
        var month = value.getMonth() + 1;
        var date = value.getDate();
        var hours = value.getHours();
        var minutes = value.getMinutes();
        var seconds = value.getSeconds()
        if (month >=1 && month <= 9) {
            month = "0"+month;
        }
        if (date >= 0 && date <= 9) {
            date = "0"+date;
        }
        if (hours >=1 && hours <= 9) {
            hours = "0"+hours;
        }
        if (minutes >= 1 && minutes <= 9) {
            minutes = "0"+minutes;
        }
        if (seconds >= 1 && seconds <= 9) {
            seconds = "0"+ seconds;
        }
        return year+"-"+month+"-"+date+" "+hours+":"+minutes+":"+seconds;
    }
    return
}`
不知道能不能帮到你

**Comment by zuiidea** [comment]
`new Date(1497237181838).format('yyyy-MM-dd hh:mm:ss')`

https://github.com/zuiidea/antd-admin/blob/master/src/utils/index.js
