### ISSUE TITLE
使用stateless的组件的写法，如何在切换路由时动态更新表单中的值？

### ISSUE THREAD

**Issue by richartan** [zuiidea/antd-admin#346]
现在有这样一个场景：
![image](https://user-images.githubusercontent.com/6970495/27063228-024474c0-5023-11e7-8957-25f4dd489351.png)

两个路由对应同一个页面，两个页面的头部搜索区域的文本框在切换路由时需要清空里面的值，在组件中直接使用setFieldsValue, 会直接报错，使用initialValue不起作用， 看一下各位有没有什么方法实现这一个常用的场景？

![image](https://user-images.githubusercontent.com/6970495/27063220-f49eea9e-5022-11e7-951a-929dc081e42b.png)

![image](https://user-images.githubusercontent.com/6970495/27063247-1e3a09e2-5023-11e7-8447-a85e51a487a3.png)

还有一个疑问：使用From的getFieldDecorator 进行数据双向绑定，数据保存到哪里了，怎样才能取到或者修改它？ 谢谢。

**Comment by zuiidea** [comment]
filter对象取的是路由上的参数，切换路由时不带参数就可以了

**Comment by richartan** [comment]
@zuiidea filter取值路由上的参数这个我清楚，现在主要问题路由上没有带参数也不起作用的，在组件内部还可以通过按钮触发一个事件，调用setFieldsValue重置form 表单。但是切换路由就不知道怎么重置了。

**Comment by zuiidea** [comment]
没懂你的意思

**Comment by richartan** [comment]
花了比较长的时间找了资料，但是始终没有找到对应的解决方法，测试发现，stateless的写法使用了getFieldDecorator数据双向绑定后，加载路由时不能使用setFieldsValue对表单中的input值赋值, 不然就会陷入死循环。我的表单比较简单，所以没有使用form提交数据了。

**Comment by cigarx** [comment]
@richartan 那最后你是怎么解决的呢？我跟你的情况类似，就是checkbox.group中想点了全选按钮就把附属的checklist全部选中，一直不知道怎么实现。@zuiidea
