### ISSUE TITLE
关于mock

### ISSUE THREAD

**Issue by zuiidea** [zuiidea/antd-admin#348]
- [mock](https://github.com/nuysoft/Mock)的优点在于可以在后端未开发接口时，前端可以模拟数据接口进行开发。

- [roadhog](https://github.com/sorrycc/roadhog)为我们提供了一个完善的mock功能，在本项目中的接口均为mock的

- 在开发过程中，后端部分接口已经开发完成，我们怎么使用别人的接口呢？如果需要同时请求多个同事的电脑或者多台服务器上的接口呢？我是这样做的，roadhog的配置中有接口代理的功能（`.roadhogrc.js`），
自己mock的接口加上前缀‘/api/v1’，A同事的接口加上前缀‘/api/v2’，C同事的接口加上前缀‘/api/v3’，利用roadhog分别匹配‘/api/v2’，‘/api/v3’并代理到A、B同事的电脑上。这样就可以不跨域的情况下愉快的开发啦。
- 当发布到正式环境后，利用nginx或者其他工具，将‘/api/v1’，‘/api/v2’，‘/api/v3’分别代理到指定的端口或者服务器，也可以正常运行啦

可参考
https://github.com/zuiidea/antd-admin/blob/master/src/utils/config.js
https://github.com/zuiidea/antd-admin/blob/master/.roadhogrc.js

**Comment by qingjiaowochengzd** [comment]
@zuiidea @FatFatFox
问题描述：在本地搭建好了Nginx服务器，本地服务器上运行起来
http://192.168.0.136:8080/nhsoft-mercury-web/checkLoginPhone?phoneNumber=18667411797&password=123456&callback=jsonp_1502759125384
Request Method:GET
Status Code:200 OK
Remote Address:192.168.0.136:8080
返回：
{"status":0,"msg":"登录成功","data":null}
但是models/login.js里：
const data = yield call(login, payload)
console.log(data.status)
接收不到data.status

这是什么原因？
@cdscawd 和你的问题很像login明明是post请求结果变get了，后台已经解决跨域问题了

我在utils/config.js调用作者的登录接口可以登录。
综合上述情况，问题出在哪呢？

后台返回给我的数据是{"status":0,"msg":"登录成功","data":null}
看作者的data返回是{success: true, message: "Ok", statusCode: 200,data:""}
那我要让后台写死了，success: true, message: "Ok", statusCode: 200？

**Comment by zuiidea** [comment]
你请求的接口和你当前所在域不同，跨域后默认使用了jsonp

**Comment by qingjiaowochengzd** [comment]
@zuiidea 看了你的这个回答
请求的接口域和当前的域不一致而跨域，默认走了JSONP，可以在utils/config.js里的CORS属性加上接口的域名。或者利用ngnix代理，使接口的域和当前域相同。
试过了还是不行。
拿了你比较老的版本
![2](https://user-images.githubusercontent.com/30749028/29396293-98b345fe-8349-11e7-8134-9dd88dec3bb9.png)
我这边200请求成功，为什么他那边会是没进来呢？
就是我service/login.js里面写get可以进去，我写post他怎么改都进不去。。。

**Comment by zuiidea** [comment]
OPTIONS 方式的请求是个探针，一般还有第二个请求，你看看呢，
另外CORS的话，需要后端配合设置Access-Control-Request-Method，

推荐你使用roadhog的proxy功能，在`.roadhogrc.js`这样就不会跨域，也不会有这些问题了

**Comment by qingjiaowochengzd** [comment]
CORS改成了http://192.168.0.73:8080，后端Access-Control-Request-Method改成了‘*’，还是不行，我登录写post就是不行。
还有个问题，放回的数据和service/login.js打印出来的数据是什么关系。。。后台返回的信息要怎么让在data里呢？

**Comment by zuiidea** [comment]
@qingjiaowochengzd ，这个是在`src/request.js`处理了的，真实的数据在浏览器的控制台的network那里看啊，建议多了解一下网络相关的知识

**Comment by qingjiaowochengzd** [comment]
@zuiidea 拿了比较老的项目版本。昨天后台做了CORS处理，可以接收到两次请求后，返回给我11111，今天早上返回给我正规的json数据，后台数据可以通过...data加入到那三个字段里了，这样我也可以获取了。

还有一版最新的4.3.2还是调同样的后台接口，message:"Timeout"，未解决，目前先用老的已经调通的。

**Comment by zuiidea** [comment]
@qingjiaowochengzd  这种情况不是服务端的错，排查一下`src/request.js`

**Comment by allinshang** [comment]
/api/v1/users
返回的接口total能修改成别的字段么？比如totalCount?

**Comment by allinshang** [comment]
@zuiidea 如何调试mock目录下的响应的js文件呢。。如果mock/user.js?谢谢。。

**Comment by laiwanping** [comment]
各位大哥，这个能在本地调接口吗？
![image](https://user-images.githubusercontent.com/12541388/32762938-21b99e6c-c8c2-11e7-8f32-f1c7c7b5dbaf.png)
![image](https://user-images.githubusercontent.com/12541388/32762945-2ab3ccfe-c8c2-11e7-9266-694f9ee4ef2b.png)

**Comment by laiyiyi** [comment]
只想访问本地的api，这个mock怎么关掉呢，

**Comment by MrSuntb** [comment]
楼上 你的问题解决了吗？我也遇到同样的问题。proxy没有生效

**Comment by laiyiyi** [comment]
@MrSuntb 把.roadhogrc.mock.js 注释掉

**Comment by superlbr** [comment]
目前master分支使用了umi, 加上启动参数MOCK=none即可

**Comment by lee-Tony** [comment]
请问部署到测试或是生成环境该怎么打包啊

**Comment by superlbr** [comment]
@lee-Tony npm run build

**Comment by zecor** [comment]
.roadhogrc.js 文件在哪里，自己建么？ .webpackrc.js 里的proxy 和这个是什么关系？

**Comment by superlbr** [comment]
> .roadhogrc.js 文件在哪里，自己建么?

.roadhogrc.js 是roadhog的配置文件，[4.x](https://github.com/zuiidea/antd-admin/blob/4.3.9/.roadhogrc.js) 版本使用
目前master分支已使用umi来处理，直接使用即可，不需要额外的配置，[参考](https://umijs.org/guide/mock-data.html)

> .webpackrc.js 里的proxy 和这个是什么关系？

Mock 是开发环境下用来模拟后端接口的，那如果是生产环境呢？[proxy](https://umijs.org/config/#proxy)就出场了
开发环境下，两者可以同时作用，存在优先级关系，目前是proxy优于Mock

**Comment by Wine-in-June** [comment]
还是没看懂怎么在本地开发取消mock^^^^^^

**Comment by Wine-in-June** [comment]
> 目前master分支使用了umi, 加上启动参数MOCK=none即可

也不行哦

**Comment by superlbr** [comment]
@Wine-in-June 经测试，最新的master分支，在package.json中改为
```
    "start": "MOCK=none umi dev"
```
mock没有生效，无法登陆
