### ISSUE TITLE
menu菜单，vertical和inline切换不了

### ISSUE THREAD

**Issue by files3** [zuiidea/antd-admin#35]
侧边栏收缩进去，vertical看不了，试了一下直接mode="vertical"菜单也不出来，实在不知道怎么解，请教一下

**Comment by zuiidea** [comment]
暂时性解决
 https://github.com/zuiidea/antd-admin/commit/60ff1ec0bb779d033669797327781dbc525c3359

但是会存在这个bug
https://github.com/zuiidea/antd-admin/pull/26

明天看能不能一期解决下
