### ISSUE TITLE
部署到nginx后发送接口请求成功，但是没有返回还是报跨域失败

### ISSUE THREAD

**Issue by GeekSpring** [zuiidea/antd-admin#350]
将项目部署到nginx后，由于后台接口还未提供,暂时把本地的项目中的mock数据作为接口，请求是200，但是response没有数据，请大神指教？
![image](https://user-images.githubusercontent.com/26270585/27117988-b14b11b6-510b-11e7-9b1b-a5ebad3778f7.png)
![image](https://user-images.githubusercontent.com/26270585/27118004-c36765d4-510b-11e7-8d0e-cc43c5512436.png)
![image](https://user-images.githubusercontent.com/26270585/27118014-cdc4f258-510b-11e7-974e-c7fc6dcf213b.png)

**Comment by zuiidea** [comment]
你在8001请求8007的接口，肯定跨域啊

具体怎么做参考https://github.com/zuiidea/antd-admin/issues/348
