### ISSUE TITLE
session

### ISSUE THREAD

**Issue by pisful** [zuiidea/antd-admin#351]
登录的时候为什么访问“api/v1/user/login”之后 还会访问一次“api/v1/user”，重新访问这个路径的时候没有带任何参数，除了在login的时候记住session还有其他的解决办法么？

**Comment by wuyao1994** [comment]
api/v1/user/login登录成功过后，跳转的url是localhost:3000/,会在model/app.js 里面去dispatch query，产生的请求就是 api/v1/user ，去请求user的数据，还有就是login保存的是cookie，不是session
