### ISSUE TITLE
树形控件，如何点击每一个节点，显示出不同的信息

### ISSUE THREAD

**Issue by yanghong1105** [zuiidea/antd-admin#356]
点击机构列表下面的节点，显示出不同的用户信息
![qq 20170615173701](https://user-images.githubusercontent.com/26755970/27175380-a3f493de-51f1-11e7-90cc-628ab50195ef.png)

**Comment by superlbr** [comment]
点击的时候触发onSelect事件，然后在函数里dispatch右侧列表的值即可
