### ISSUE TITLE
  请问在mock下的user.js 取id的问题？

### ISSUE THREAD

**Issue by wing2002li** [zuiidea/antd-admin#357]
[`PATCH /user1/:id`] (req, res) {
    console.info(req)
 //const { id } = req.params  原有的方法渠道这个数据id的值为:id，请问是哪里的错。
  
    const { id } = req.body.id
    const editItem = req.body
    let isExist = false

**Comment by superlbr** [comment]
检查models/user.js中update
`const id = yield select(({ user }) => user.currentItem.id)`
此处id是否正常获取
