### ISSUE TITLE
bug: Header 导航栏中，添加 Menu.item 至 user 登出菜单时，被 numberCard 遮挡

### ISSUE THREAD

**Issue by jzoe** [zuiidea/antd-admin#360]
`./src/components/Layout/Header.js` 中添加如下代码：

```javascript
<SubMenu style={{
            float: 'right',
          }} title={< span className={styles.button}> <Icon type="user" />
            {user.username} </span>}
          >
            <Menu.Item ic key="changePassword">
              <Icon type="key" />
              修改密码
            </Menu.Item>
            <Menu.Divider />
            <Menu.Item key="logout">
              <Icon type="poweroff" />
              Sign out
            </Menu.Item>
          </SubMenu>
```

这时由于 Menu 的属性  styles.rightWarpper 中 display: flex，导致 Sign out 子菜单被遮挡。去掉该属性后，修改密码和 sign out 子菜单都可以正常显示，但是与 mail 图标div 的排版又有问题。

google 发现这个问题好像是 antd-design 本身的 bug https://github.com/ant-design/ant-design/issues/2830 。

我目前的解决办法是把 mail div 去掉，把 rightWarpper 的 display 属性也去掉。

**Comment by kuanger** [comment]
我是在Recharts发现的这个问题，菜单被Show More的按钮挡住了，我通过对Header设置z-index解决了问题，并且已经发了PR，你可以试一下

**Comment by jzoe** [comment]
@kuanger 已采用，非常感谢
