### ISSUE TITLE
没有登录也可以跳转到dashboard页面

### ISSUE THREAD

**Issue by chenkang084** [zuiidea/antd-admin#362]
问题：
> 由于 <https://github.com/zuiidea/antd-admin/blob/master/src/models/app.js#L20  >  代码是异步的。在没有登录的时候，会出现 先到 dashboard，然后再重定向到了 login 界面。

建议将这块逻辑修改为同步，即首先在cookie 中查看该用户是否登录，如果没有登录，直接跳转到登录界面，如果登录了，再去做后续操作。

**Comment by zuiidea** [comment]
嗯，是的

**Comment by jzoe** [comment]
这个问题，目前有什么解决办法吗？

**Comment by chenkang084** [comment]
我觉得作者这是给我们示范了一下登陆流程。具体如何实现需要根据具体应用场景。
简单的实现方法就是我上面说的：通过cookie 判断，或者用token，方法很多。
