### ISSUE TITLE
楼主大大，项目中哪里有用到sockjs-node吗，为什么老是会报websocket的错误

### ISSUE THREAD

**Issue by warplan** [zuiidea/antd-admin#368]
WebSocket connection to 'ws://localhost:8000/sockjs-node/653/43mix3ns/websocket' failed: Connection closed before receiving a handshake response

**Comment by wuyongdec** [comment]
热加载用到了吧

**Comment by warplan** [comment]
用了"babel-plugin-dva-hmr": "^0.3.2",是这个热加载用到的webSocket吗?

**Comment by wuyao1994** [comment]
你是不是用express做了代理，我以前也遇到过这个错，是因为sockjs-node和websocket的协议不一样，所以握手closed。解决办法是在express代理上加了一层ws就没报这个错了
const app = express(),
  expressWs = require('express-ws')(app);
app.ws('/*');
