### ISSUE TITLE
首次进入页面不能展开左侧菜单

### ISSUE THREAD

**Issue by Cnax** [zuiidea/antd-admin#372]
复制项目中的二级栏目的地址，重新打开浏览器粘贴网址进入页面，左侧菜单栏不能展开显示

原因： model中app.js文件中代码行  siderFold: localStorage.getItem(`${prefix}siderFold`) === 'true'
在第一次进入页面是  localStorage.getItem(`${prefix}siderFold`) 为 null ， 导致siderFold=false，
  components/Layout/Menu.js中代码行  let menuProps = !siderFold ? {
    onOpenChange,
    openKeys: navOpenKeys,
  } : {}
会使 menuProps.openKeys = [] （navOpenKeys在model/app.js中默认为空数组） ，在Menu 组件上当属性openKeys为空数组时， defaultOpenKeys会失效

**Comment by superlbr** [comment]
 navOpenKeys 没有根据当前路径重新计算
`navOpenKeys: JSON.parse(window.localStorage.getItem(`${prefix}navOpenKeys`)) || [],`
