### ISSUE TITLE
动态加载外部文件

### ISSUE THREAD

**Issue by zhanghj-jacky** [zuiidea/antd-admin#373]
通过npm run build 对项目进行了打包，部署到nginx 代理服务上。

我需要把 项目中访问后端服务器的配置config.js 文件中的 提取出来，进行动态加载？
![image](https://user-images.githubusercontent.com/28745535/27523197-43fa6448-5a5e-11e7-9ef6-c0c01c230b18.png)

能通过什么好的方式来实现吗？望楼主指点！！！

**Comment by zuiidea** [comment]
什么场景下需要这样做

**Comment by zhanghj-jacky** [comment]
我们的代码都是放在docker 里面的，這样就方便移动。

這样，我的后端程序，移动了，需要部署在其他的服务器上，那么我的前端程序就需要修改config 文件，然后重新打包，放到docker 里面去。

想问问楼主，如果我的前端可以动态加载文件、参数或者环境变量任何一种方式，我就可以通过把后端服务器的信息，通过文件、参数、或者环境变量的方式 给我的前端，這样就不需要重新打包了？

**Comment by zuiidea** [comment]
参考这个 https://github.com/zuiidea/antd-admin/issues/348

**Comment by superlbr** [comment]
docker玩法多了
1. docker 构建的时候，可以构建git不同分支
2. docker run的时候可以注入参数
3. jenkins pipeline 各种config，拉去后端接口，或修改config，或覆盖
