### ISSUE TITLE
请问下menu.js 里的 id bpid mpid 参数是做什么的？

### ISSUE THREAD

**Issue by cdscawd** [zuiidea/antd-admin#375]

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/wiki/%E8%8F%9C%E5%8D%95%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by superlbr** [comment]
https://github.com/zuiidea/antd-admin/wiki/Menu-Config
