### ISSUE TITLE
从model通知到界面到方法？

### ISSUE THREAD

**Issue by DiroKate** [zuiidea/antd-admin#377]
请问有什么便捷到方法，可以在model从服务端获取到数据之后，通知到前端显示中去吗？
比如使用了antd，我在登录用户到时候，登录成功的时候在左上角显示一个antd的notification通知，登录失败的时候返回另一个通知。类似的功能。
谢谢各位大神不吝赐教。

**Comment by zuiidea** [comment]
https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md 
onError

**Comment by DiroKate** [comment]
不是这种啊， 是Notifications https://ant.design/components/notification-cn/
比如创建条目成功，用onError不好。

**Comment by zuiidea** [comment]
是一样的啊，你也可以把Notifications 写在effects里面

**Comment by DiroKate** [comment]
可以直接在model里面使用antd的message和notification这种全局通知方法
