### ISSUE TITLE
请问部署tomcat问题

### ISSUE THREAD

**Issue by xforgchengz** [zuiidea/antd-admin#379]
楼主你好，本人是一枚java后端开发，请问这个项目能像传统的web项目一样部署在tomcat、weblogic等中间件吗？我通过npm run build将生成的文件夹拷贝到tomcat下，访问index.html却抱404错误， login?from=/index.html

**Comment by lanke** [comment]
![image](https://user-images.githubusercontent.com/1082843/27821610-6b20b414-60d5-11e7-937c-4dc20ca5ff10.png)
在后端处理下 重新返回index.html就可以了。  models下app.js文件中query方法最后调用了window.location

**Comment by xforgchengz** [comment]
谢谢，我试下

**Comment by javahuang** [comment]
![jietu20170707-153548](https://user-images.githubusercontent.com/3992393/27947819-093ec608-632a-11e7-9268-3ea53093564b.jpg)

给楼主看下我的配置，因为是单页应用，除了常见的静态文件，所有的请求都要映射到 index.html

**Comment by lanke** [comment]
静态文件不用自己再写controller配置了吧，spring boot直接能映射到static文件

**Comment by javahuang** [comment]
@lanke 因为我使用 /** 设置了所有请求都映射都 index.html，spring boot 就映射不到 static 文件的。我这样做的目的是，我在浏览器手动输入路由对应的连接，也能刷新页面。不知道您是怎么解决这种情况的

**Comment by mapengze** [comment]
@lanke 大神怎么部署tomcat啊 就教教我 方便的话加下我扣 57180484呗
