### ISSUE TITLE
你好，请问一下 您对 tree 控件有研究吗？

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#38]
我这边遇到的问题是 ；tree 控件里面的 treenode 节点 怎么添加自定义属性？
需求是：点击 treenode 右侧出现一个 form 里面显示节点的信息，可以进行 修改和删除
看文档没有提供此类方法 请问一下，有什么好方法吗？

**Comment by zuiidea** [comment]
没有使用场景，没尝试过，我看了一下TreeNode的props title 的类型是String/element，意思是可以在title上放操作的按钮的，你可以尝试一下
