### ISSUE TITLE
axios跨域请求SHAREJSESSIONID为空，导致其它接口请求身份验证失败

### ISSUE THREAD

**Issue by GeekSpring** [zuiidea/antd-admin#381]
1. 前端设置了withCredentials: true允许跨域， 后端Access-Control-Allow-Credentials:true设置允许跨域的写入cookie   然后指定跨域的IP： Access-Control-Allow-Origin:http://x.x.x.x:xxxx  浏览器SHAREJSESSIONID写入了，但是为undefined

2. 登陆set-cookie是有SHAREJSESSIONID值

![image](https://user-images.githubusercontent.com/26270585/27847279-572cae50-616f-11e7-8c4b-1b073de66e84.png)

![image](https://user-images.githubusercontent.com/26270585/27847356-afe250e0-616f-11e7-97b3-87bd9b757148.png)

3. 登陆后请求其它接口
![image](https://user-images.githubusercontent.com/26270585/27847375-ce483fc2-616f-11e7-9855-145b1139ffe0.png)
![image](https://user-images.githubusercontent.com/26270585/27847397-ebd8dbd2-616f-11e7-84d2-a0dcf45eec84.png)
![image](https://user-images.githubusercontent.com/26270585/27847412-02b2181e-6170-11e7-8930-1b4bd8a1f187.png)
为什么SHAREJSESSIONID赋值为空，我也获取不到登陆set-cookie的值，求大神指教

**Comment by superlbr** [comment]
目测没有跨域成功
