### ISSUE TITLE
chrome:config is not defined  safari:can't find variable:config

### ISSUE THREAD

**Issue by rayshen** [zuiidea/antd-admin#386]
这什么问题 ？

npm install 后 npm run dev 就提示这个问题

node 8.0
npm 5.1

**Comment by rayshen** [comment]
是webpack里的alias没识别出来

npm run lint 后显示：

/Users/shenzw/Desktop/demo/src/components/DataTable/DataTable.js
  4:25  error  Unable to resolve path to module 'utils'  import/no-unresolved

/Users/shenzw/Desktop/demo/src/components/Layout/Bread.js
  7:28  error  Unable to resolve path to module 'utils'  import/no-unresolved

/Users/shenzw/Desktop/demo/src/components/Layout/Footer.js
  3:24  error  Unable to resolve path to module 'utils'  import/no-unresolved

/Users/shenzw/Desktop/demo/src/components/Layout/Menu.js
  5:41  error  Unable to resolve path to module 'utils'  import/no-unresolved

/Users/shenzw/Desktop/demo/src/components/Layout/Sider.js
  5:24  error  Unable to resolve path to module 'utils'  import/no-unresolved

/Users/shenzw/Desktop/demo/src/models/app.js
   5:24  error  Unable to resolve path to module 'config'  import/no-unresolved
   6:30  error  Unable to resolve path to module 'enums'   import/no-unresolved
  75:13  error  'config' is not defined                    no-undef
  75:33  error  'config' is not defined                    no-undef


请问如何解决？

**Comment by huangzhuohe** [comment]
+1

**Comment by zuiidea** [comment]
提交了错误的代码，解决了
https://github.com/zuiidea/antd-admin/commit/ec8db0e0fb3a56af5ff13221f6a1a5dc8c7d59ad

lint没找到原因，可以暂时在`.eslintrc`加入
`
"import/no-unresolved":0
`

**Comment by zuiidea** [comment]
fix了
https://github.com/zuiidea/antd-admin/pull/427/commits/755c1250e538187f49f71d1417b45a4e959dbda8
