### ISSUE TITLE
问个题外的问题，我创建了两个model，两个model里面都有subscriptions 。。

### ISSUE THREAD

**Issue by Slice-dd** [zuiidea/antd-admin#387]
问个题外的问题，我创建了两个model，两个model里面都有subscriptions 。。但是只有在index.js中引入的model中的subscriptions `事件才触发了，另外一个就没有触发，这个没有触发的model我也通过这种方式引入了`connect(({user}) => `({user}))(IndexPage);`大神求解答啊

**Comment by zuiidea** [comment]
try
`connect(({a,b}) => ({a,b}))(IndexPage)`

**Comment by Slice-dd** [comment]
是不是另外一个model也要用`app.model(require('./models/products'));`这样的方式才能生效啊

**Comment by zuiidea** [comment]
是的啊，没有这句就是没加载

**Comment by Slice-dd** [comment]
我刚刚看了一下你是router.js里面引入的，官方的教程里面好像没有说要在哪引入啊

**Comment by 102010cncger** [comment]
a,b在是你model中的namespace:
比如namespace: a,namespace: b,

a和b在你的路由中配置了动态加载
比如参考
, {
          path: 'user',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              registerModel(app, require('./models/user'))
              cb(null, require('./routes/user/'))
            }, 'user')
          },
        }

你可以添加
registerModel(app, require('./models/a'))
registerModel(app, require('./models/b'))

不知道我理解的对不对
