### ISSUE TITLE
请问下npm run build打包后的async.js 文件有什么用？怎么把它们放一个文件夹？因为好像是一个页面对应一个async.js文件

### ISSUE THREAD

**Issue by 310731483** [zuiidea/antd-admin#388]
请问下npm run build打包后的async.js 文件有什么用？怎么把它们放一个文件夹？因为好像是一个页面对应一个async.js文件

**Comment by zuiidea** [comment]
什么版本，最新的是[name].[hash].js

**Comment by 310731483** [comment]
我也不知道是哪个版本的，我那时候下载的还没有webpack.config.js这个文件。现在加的话是怎么加啊？

**Comment by zuiidea** [comment]
那你的代码有点老了

**Comment by 310731483** [comment]
那现在要怎么把webpack.config.js这个文件加上去呢？而且我下载了最新的打包后dist文件夹下也是有很多个js文件

**Comment by 310731483** [comment]
`webpackConfig.output.chunkFilename = 'async/[name].[hash].js'`  
直接加上webpcak.congfig.js然后改成这样确实可以打包到一个文件夹里了，但是打包时会出现这个问题
`⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since roadhog\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, pl
ease be careful of the compatibility after upgrading roadhog.
`请问下这个怎么解决啊？
