### ISSUE TITLE
搜索框bug & 没有请求错误处理的相关演示么?

### ISSUE THREAD

**Issue by xutou12** [zuiidea/antd-admin#39]
搜索框回车页面就显示登录界面无限旋转等待~

代码中貌似没有做请求错误处理, 这是很重要的一块吧? 看了下请求的错误处理基本没有...

^_^ 期待相关代码演示

**Comment by zuiidea** [comment]
搜索框bug已经修复了的  https://github.com/zuiidea/antd-admin/commit/142b059fc31098a5e3f4ed92183e80ec402a0827

错误处理后面慢慢补上吧，没太多空闲时间
