### ISSUE TITLE
作者你好 我想改远程数据table里的数据，后端给我一个接口的

### ISSUE THREAD

**Issue by mapengze** [zuiidea/antd-admin#390]
作者你好 我想修改远程数据table里的数据，后端给我一个接口的的话 我要往哪里放

**Comment by cdscawd** [comment]
utils/config

**Comment by mapengze** [comment]
@cdscawd 谢谢哥们 我还想问下是改那个baseURL是吗  其他js文件还需要改吗

**Comment by cdscawd** [comment]
@mapengze 当然 这个项目只是作者的一个demo

**Comment by mapengze** [comment]
@cdscawd 能加下联系方式吗 新手有问题请教呀 57180484  qq

**Comment by cdscawd** [comment]
@mapengze 我也是新手 仅限于讨论

**Comment by zuiidea** [comment]
重点不在于哪里放，是你要在model里调用接口，拿到数据后更新model的state，从而更新数据

**Comment by mapengze** [comment]
@zuiidea 我在datatable.js把url改成后端给我http的接口 然后数据刷不出来呀

**Comment by mapengze** [comment]
@zuiidea 接口地址http://172.12.1.211:8086/getData  能帮我试试么

**Comment by 102010cncger** [comment]
.roadhogrc.js中配置
  "proxy": {
    "/api": {
      "target": "http://172.12.1.211:8086",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "/" }
    }
  },

service中写请求

export async function getData (params) {
  return request({
    url: 'api/getData',
    method: 'post',
    data: params,
  })
}

**Comment by zhien520** [comment]
@102010cncger 你可以加下我qq吗 大哥  麻烦啦
