### ISSUE TITLE
npm run build后出现这个⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since roadhog\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, pl ease be careful of the compatibility after upgrading roadhog.

### ISSUE THREAD

**Issue by 310731483** [zuiidea/antd-admin#391]
npm run build后出现这个`⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since roadhog\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, pl ease be careful of the compatibility after upgrading roadhog.` 这个问题大不大啊？请问有没有什么解决办法？

**Comment by jiangyijoin** [comment]
我也遇到这个问题，是不是出现这个问题后热处理不行的啊，我改了代码一定要重启才能生效

**Comment by zuiidea** [comment]
roadhog报的警告，没问题
