### ISSUE TITLE
如何将 antd-admin 与 SpringBoot 集成

### ISSUE THREAD

**Issue by jzoe** [zuiidea/antd-admin#395]
使用 SpringBoot 作为 RESTful 后台，请问如何将 antd-admin 打包后集成到 SpringBoot 项目中？我把dist 目录放到 `src/main/resources/templates` 下面，访问的时候总是 404 。 烦请有经验的大神指点！

**Comment by 102010cncger** [comment]
最好用chrome看下请求路径,我没遇到这个问题

**Comment by lanke** [comment]
![image](https://user-images.githubusercontent.com/1082843/28021474-993bf2ac-65ba-11e7-91e0-f2bca0efbbfd.png)
这样，打包前 在webapp中，打包后在static当中

**Comment by jzoe** [comment]
我是将 dist 目录拷贝至 static 目录，并设置 HomeController 了后可访问到页面了。

**Comment by jzoe** [comment]
我是将 dist 目录拷贝至 static 目录，并设置 HomeController 了后可访问到页面了。
```java
@Controller
public class HomeController {

    @GetMapping(value = "/")
    public String index() {
        return "index.html";
    }

    @GetMapping(value = "/login")
    public String login() {
        return "index.html";
    }
}
```
其它我都没有设置，包括 webconfig。这样能访问到静态页面了，但是跳转到登录页面的时候，我看返回的 js 并没有被渲染出来。报了语法错误。
![image](https://user-images.githubusercontent.com/11612990/28022024-74856ae0-65bc-11e7-8568-9b57d2d76e59.png)

![image](https://user-images.githubusercontent.com/11612990/28022004-5f54b8b0-65bc-11e7-9180-975792219e92.png)

**Comment by jzoe** [comment]
不设置 `/login` 拦截器的话，会报这个请求的404。
![image](https://user-images.githubusercontent.com/11612990/28022247-33c865d8-65bd-11e7-854f-3a233687bda7.png)

呜呜 已经晕了。不知道怎么设置，才能让前端请求被前端的 router 拦截！

**Comment by lanke** [comment]
![image](https://user-images.githubusercontent.com/1082843/28046488-89b3c70e-6616-11e7-8277-24f4e58eddba.png)
java端这样返回就好了。
你可以看前端代码
models/app.js
![image](https://user-images.githubusercontent.com/1082843/28046548-03729764-6617-11e7-88c0-7f687b41193b.png)

**Comment by jzoe** [comment]
还是不行。我将 antd-admin 拉到本地，不作修改，直接 build ，然后把 dist 目录拷贝到 `src/main/resource/static` 目录下，初始化一个空的 springboot 项目，设置上面的 getLoginPage ，启动 springboot 项目，访问 `localhost:8080` ，这个时候重定向到 `/login?from=/` ，请求的是 `login.js` ，但返回的 js 文件内容是 `index.html` 的内容。这个时候，js 文件就报语法上面的语法错误了。
![image](https://user-images.githubusercontent.com/11612990/28051691-865f743c-6638-11e7-8760-a489f0db5260.png)

**Comment by jzoe** [comment]
下面是使用 `npm run dev` 方式启动 `antd-admin` 开发环境时的请求截图：
![image](https://user-images.githubusercontent.com/11612990/28052705-1acbfdd8-663f-11e7-82de-7caf6c5b314c.png)

**Comment by lanke** [comment]
npm run dev 且开启mock的时候应该没错吧？  有没有可能是哪个后端接口没写的原因?

**Comment by lanke** [comment]
![image](https://user-images.githubusercontent.com/1082843/28053711-68cb4e8a-6644-11e7-9451-9d50de77ba06.png)
对了 ，我当时也因为这个卡住了，  对login.js 的请求配spring mvc 映射到了控制器上而不是文件上。   spring boot 需要加上上图的配置

**Comment by lanke** [comment]
`@Configuration
public class MyWebAppConfig extends WebMvcConfigurerAdapter {
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/*/**.**.js").addResourceLocations("classpath:/static/");
        super.addResourceHandlers(registry);
    }
    /**
     * 重写configurePathMatch此方法	 * 设置其参数PathMatchConfigurer的属性UseSuffixPatternMatch值为false	 * 可以让路径中带小数点“.”后面的值不被忽略
     */
    @Override
    public void configurePathMatch(PathMatchConfigurer configurer) {
        configurer.setUseSuffixPatternMatch(false);
    }

}`

**Comment by jzoe** [comment]
@lanke 非常感谢，设置了 `PathMatchConfigurer` 后解决了，可以渲染了！

**Comment by MengStar** [comment]
mark一下，我是把springboot 单独做服务器了。

**Comment by javahuang** [comment]
分享一下我的集成代码，之前也走了不少弯路。
除正常的 ajax 请求和静态资源请求之外的所有请求都映射到默认的 index.html，目的是在浏览器输入任意链接也能够刷新页面。静态资源请求一定要设置 order，优先级设置最高。

``` java
@Configuration
@RestController
public class WebConfig extends WebMvcConfigurationSupport {

    @Value("classpath:/static/index.html")
    private Resource indexHtml;

    private static final String[] STATIC_RESOURCES = {
            "/**/*.css", "/**/*.js",
            "/**/*.jpg", "/**/*.png", "/**/*.svg",    // 图片
            "/**/*.eot", "/**/*.ttf", "/**/*.woff"    // 字体文件
    };

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.setOrder(Ordered.HIGHEST_PRECEDENCE).  // 设置静态资源映射优先级高于下面配置的 @GetMapping
                addResourceHandler(STATIC_RESOURCES).
                addResourceLocations("classpath:/static/");
    }

    @Override
    public void configurePathMatch(PathMatchConfigurer configurer) {
        configurer.setUseSuffixPatternMatch(false); // 默认 /index 会匹配 /index.js
    }

    @GetMapping
    public Object index() {
        return ResponseEntity.ok().body(indexHtml);
    }

}
```

**Comment by jzoe** [comment]
@javahuang 采用你这种方式部署的话，在刷新页面时，会变成 ajax 请求吧？

比如我在  localhost:8080/home 下刷新页面，这个时候应该返回的是 404，而不是刷新整个页面，重新载入静态资源

**Comment by javahuang** [comment]
@jzoe 需求不一样吧，我的目的是手动输入不存在的连接，返回 404 和前端跳转到不存在的路由返回的 404 页面保持一致

**Comment by javahuang** [comment]
我将我的集成代码开源出来了，欢迎交流 https://github.com/zuiidea/antd-admin/issues/613

**Comment by jzoe** [comment]
@javahuang 感谢！周末我clone你的代码来测试一下！
