### ISSUE TITLE
effects中如何获取state中的值

### ISSUE THREAD

**Issue by 102010cncger** [zuiidea/antd-admin#396]
谢谢大神

例子用户界面中,查询条件中设置了条件,当新增后重新加载数据的时候,查询条件中的值没有被传递到后台作为条件

如题
  state: {
    abilityId: '',
  },
setup阶段获取了url中默认值

  subscriptions: {
    setup ({dispatch, history}) {
      history.listen(() => {
        const match = pathToRegexp('/ability/template/:id').exec(location.pathname)
        if (match) {
          dispatch({type: 'setup', payload: {abilityId: match[1]}})
        }
      })
    },
  },

    *setup ({payload = {}}, {call, put}) {
      let {abilityId} = payload;
      yield put({type: 'updateState', payload: {abilityId: abilityId}})
      yield put({type: 'query'})
    },

我想在effect的query方法中传递abilityId

*query ({payload = {}}, {call, put}) {
      let {pageIndex, pageSize} = payload;
      pageIndex = (pageIndex == null ? 1 : pageIndex);
      pageSize = (pageSize == null ? config.defaultPageSize : pageSize);
      let query = {...payload, pageIndex, pageSize};
      const data = yield call(findTemplateByPage, parse(query))
      if (data) {
        yield put({
          type: 'querySuccess',
          payload: {
            list: data.data.result,
            pagination: {
              current: Number(payload.pageIndex) || 1,
              pageSize: Number(payload.pageSize) || config.defaultPageSize,
              total: data.data.total,
            },
          },
        })
      }
    },

**Comment by RocDeanGit** [comment]
select

**Comment by 102010cncger** [comment]
select 用于从 state 里获取数据。
const abilityId= yield select(state => state.abilityId);
