### ISSUE TITLE
4.2.3版本bug，当用admin用户访问时，页面不能正常显示（没有权限）

### ISSUE THREAD

**Issue by louischencn** [zuiidea/antd-admin#398]
【版本号】4.2.3
【现象描述】当admin用户访问时，页面不能正常显示（没有权限）
【问题代码】
./mock/user.js

> `const userPermission = {
  DEFAULT: {
    visit: ['1', '2', '21', '7', '5', '51', '52', '53'],
    role: EnumRoleType.DEFAULT,
  },
  ADMIN: {
    role: EnumRoleType.ADMIN,
  },
  DEVELOPER: {
    role: EnumRoleType.DEVELOPER,
  },`

在此处，ADMIN中并没有为visit数组赋值。

./routes/app.js

> `  const hasPermission = current.length ? permissions.visit.includes(current[0].id) : false
`

在此处会通过permissions.visit判断是否有权限，因此没有权限访问

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/3ad5a6cfb6cb5341a96a5ca2c952b66e997a1cac
