### ISSUE TITLE
不能克隆代码

### ISSUE THREAD

**Issue by zhangzequan** [zuiidea/antd-admin#399]
hello，author， git clone https://github.com/zuiidea/antd-admin.git;代码克隆不下来，每次都在98%的时候失败，下载zip包，也不能解压，请问是什么问题，thank you

**Comment by wefine** [comment]
HI，可能跟你的网络环境有关，antd-admin仓库代码是由 github 本身托管的，你所提的问题跟项目本身没有关系的。

你可以换个网络，或换个机器试下。
