### ISSUE TITLE
咨询下这里用的robe-ajax如何对全局的ajax错误进行统一处理

### ISSUE THREAD

**Issue by taven-liu** [zuiidea/antd-admin#40]
以前用jquery可以通过`$(document).ajaxError`去处理，但是看dvajs介绍是如下图操作，
![image](https://cloud.githubusercontent.com/assets/11688796/22009633/74285020-dcbf-11e6-88c5-33b7a113624e.png)
那么具体怎么做呢。

**Comment by xiaosansiji** [comment]
我现在是在request.js里就把跟后台约定好的业务逻辑错误给处理掉了：

![image](https://cloud.githubusercontent.com/assets/7600149/22583631/c10b77ca-ea28-11e6-8812-f6bd79e5517a.png)
试过在done里判断有错手动抛异常的方式，但是因为这时候实际上已经处理完了，所以并没有进到dva的onError钩子里，暂时这么搞了。

但是想了一下，错误处理当然最好还是集中到一个地方比较好，我再试试有木有办法可以都到onError里处理。。。

**Comment by zuiidea** [comment]
> 在一个无服务器的环境中模拟数据请求，Mock不能拦截Fetch，只能拦截XHR，所以我选了一个类似jquery Ajax的库robe-ajax

所以如果不需要无服务器的环境中拦截请求，可以直接换成Fetch

**Comment by wuhuatianbao007** [comment]
同问，如何在onError 里统一处理请求错误

**Comment by xiaosansiji** [comment]
@wuhuatianbao007 就这样咯：
![image](https://cloud.githubusercontent.com/assets/7600149/25172054/6fb7ebf8-2522-11e7-8e13-96af5964ed22.png)
你在request写的中间件代码那里手动抛出了异常，dva的onError钩子就能获取到，像上图里就是把错误提示通知用户，并在console里打印出来

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/cfd0172204f2358263cdd85320759987f0937c3f
