### ISSUE TITLE
最新更新出现'includes' of undefined错误

### ISSUE THREAD

**Issue by kevin50ster** [zuiidea/antd-admin#400]
更新到最新后,npm run dev 出现如下错误:
Uncaught TypeError: Cannot read property 'includes' of undefined
----
const hasPermission = current.length ? permissions.visit.includes(current[0].id) : false

**Comment by lanke** [comment]
你看下visit是否被正确的初始化为数组了。  如果不是，就证明permissions没有传过来

**Comment by tianskyluj** [comment]
请问解决了，我也是这个问题

**Comment by andrewsty** [comment]
我也遇到这个问题

**Comment by lanke** [comment]
![image](https://user-images.githubusercontent.com/1082843/28048987-ec3d4a02-6626-11e7-8a0d-8ea6712825b5.png)
mock/user.js  permission增加  visit就不会报错了

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/pull/407/commits/3ad5a6cfb6cb5341a96a5ca2c952b66e997a1cac
