### ISSUE TITLE
请教关于safari浏览器上editor中选择文本颜色和背景颜色选择不了的问题 

### ISSUE THREAD

**Issue by ouyangyu** [zuiidea/antd-admin#401]
在Safari浏览器上，编辑器选择文本颜色和背景颜色选择不了，下拉时颜色选择没有出现，这是浏览器兼容问题吗？

**Comment by superlbr** [comment]
1. 实测未复现，手机电脑都ok。
2. 编辑器非必要组件，可替换参考 https://ant.design/docs/react/recommendation-cn
