### ISSUE TITLE
npm run build 打包后 index.html打开是空白页面

### ISSUE THREAD

**Issue by zhien520** [zuiidea/antd-admin#402]
报错：index.js 和index.css 

Failed to load resource: net::ERR_FILE_NOT_FOUND
index.js Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by dkvirus** [comment]
@zuiidea  作者大大，我这里也是这个问题，我 build 之后将静态文件放到 tomcat 下的 ROOT 下，并切也把 tomcat 跑起来了，结果登录网站还是报错，能帮忙看下什么问题吗？现在整体都高差不多了，就差这最后一步，折腾了两条也没整明白啥情况。

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/269

**Comment by mapengze** [comment]
@dkvirus 你tomcat整出来了吗
