### ISSUE TITLE
真实的数据，不是写在mock里，会出现跨域，怎么解决？？

### ISSUE THREAD

**Issue by albafica2015** [zuiidea/antd-admin#403]
真实的数据，不是写在mock里，会出现跨域，怎么解决？？

**Comment by sduworm** [comment]
配roadhog的proxy就行

**Comment by zhien520** [comment]
@sduworm 怎么配呢 没有注释 不知道那些参数的意思啊

**Comment by sduworm** [comment]
@zhien520 https://github.com/sorrycc/roadhog

**Comment by dkvirus** [comment]
他这里是直接使用 fetch 处理的，也用 jsonp 处理了跨域请求，但貌似效果不咋地，我在项目里用  axios 替换了 fetch，简单点说就是 src/utils/request.js 这个文件进行修改，具体如何修改，可以查看 axios 文档（官方是英文的，还好有人给翻译成中文了）[axios 中文文档](https://segmentfault.com/a/1190000008470355?utm_source=tuicool&utm_medium=referral)

**Comment by zuiidea** [comment]
`.roadhogrc.js`这个文件里不是有接口代理示例吗

**Comment by heyunjiang** [comment]
我用的php+dva，实现开发时跨域数据交互，写得不怎么样，可以参考一下https://github.com/heyunjiang/graduate
