### ISSUE TITLE
如何将post提交 改为表单提交

### ISSUE THREAD

**Issue by somewhereMrli** [zuiidea/antd-admin#406]
如题， 我在header里面加入
'Content-Type' : 'application/x-www-form-urlencoded'

但是仍然不行。。。希望作者给一个方案，谢谢啦，

**Comment by AILINGANGEL** [comment]
我可以呀，用了formData了吗

**Comment by addedjacky** [comment]
@somewhereMrli request.js line 66 return axios.post(url, qs.stringify(cloneData))
