### ISSUE TITLE
atool-build 路由异步加载问题

### ISSUE THREAD

**Issue by DylanMay** [zuiidea/antd-admin#409]
我用的是老版本的脚手架，配置了路由动态加载，但是构建的时候，并没有把异步的组件单独打包.
![image](https://user-images.githubusercontent.com/1918144/28148499-9dc28e34-67b9-11e7-8877-424725c776e9.png)

**Comment by zuiidea** [comment]
`  callback(null, { component: require('./routes/dashboard') })`试试
