### ISSUE TITLE
dashboard的card元素在鼠标hover的时候，会自动出现滚动条，并把别的元素挤开

### ISSUE THREAD

**Issue by jzoe** [zuiidea/antd-admin#411]
![image](https://user-images.githubusercontent.com/11612990/28167849-a411b430-680f-11e7-9862-9c90cbbad1ce.png)
找了好久，并没有看到相关样式，求解！

**Comment by JackZong** [comment]
同样的问题+1

**Comment by afc163** [comment]
#413
