### ISSUE TITLE
在mock/user中的处理登录请求的时候，提示服务器错误，经调试发现 req.body是undefined,这是怎么回事啊

### ISSUE THREAD

**Issue by PebblerWon** [zuiidea/antd-admin#414]
@zuiidea ，代码都是跟着model自己一步步写出来的，但是这里的req.body一直打印出来的是undefined，不知道是什么原因。

**Comment by PebblerWon** [comment]
已发现同类问题 <a href='https://github.com/sorrycc/roadhog/issues/86'>#86</a>,尝试解决中

**Comment by zuiidea** [comment]
`roadhog -v ` 看一下roadhog版本，目前用的是`0.6.0-beta.6`
