### ISSUE TITLE
CDN部署问题

### ISSUE THREAD

**Issue by WillPangZi** [zuiidea/antd-admin#417]
我把编译出来的资源丢进CDN，然后在index.html中修改静态资源的访问方式为：
<link rel="stylesheet" href="http://cdn.test.com/index.css" />
<script src="http://cdn.test.com/index.js"></script>

实际访问发现子路由的静态资源又回到tomcat的域名了：
如：
http://localhost:8080/dashboard.4ded427b327761d4e413.js

请问作者，有办法在把子路由的域名与index.js域名保持一致吗？

**Comment by doterme** [comment]
你只说打包之后的文件名带了hash么？

**Comment by WillPangZi** [comment]
不是hash，是域名问题，比如本地开发的时候，index.js是使用CDN资源：
http://cdn.test.com/index.js
但子路由的js又会回到localhost
http://localhost:8080/dashboard.4ded427b327761d4e413.js

**Comment by zuiidea** [comment]
`publicPath: "//cdn.test.com"`

https://webpack.js.org/configuration/output/#output-publicpath
