### ISSUE TITLE
form表单验证默认提示的英文的，如何修改默认的提示内容呢

### ISSUE THREAD

**Issue by somewhereMrli** [zuiidea/antd-admin#419]
如题，我找到
![qq 20170717134059](https://user-images.githubusercontent.com/16183674/28256515-c8339228-6af5-11e7-980a-4bb727f271ba.png)
是在这个位置定义的，

**Comment by doterme** [comment]
![image](https://user-images.githubusercontent.com/12495369/28399168-fda8f17e-6d3d-11e7-8bcc-885701db4db4.png)
在表单的验证规则里面设置

**Comment by somewhereMrli** [comment]
我指得是默认全局的定义，每一个都这样单独写麻烦

**Comment by doterme** [comment]
按道理说应该是每个都单独写，每个都不一样，统一提示不太友好
