### ISSUE TITLE
菜单收缩进去，鼠标悬停的时候，menu没有vertical   不显示

### ISSUE THREAD

**Issue by files3** [zuiidea/antd-admin#42]
<img width="306" alt="wx20170118-152243 2x" src="https://cloud.githubusercontent.com/assets/15240870/22054715/fbd72ee2-dd91-11e6-87d2-550d169bf5fd.png">

我有写二级菜单，也检查了代码，代码也判断了

**Comment by zuiidea** [comment]
已解决 https://github.com/zuiidea/antd-admin/issues/35
