### ISSUE TITLE
使用路由 配置嵌套路径，无法加载页面

### ISSUE THREAD

**Issue by mindreading** [zuiidea/antd-admin#422]
![10f342bd-a84a-44a0-8a9a-930cc48e3941](https://user-images.githubusercontent.com/12807738/28265471-84c15afc-6b22-11e7-9dbf-7baf5033fbdc.png)
配置 /xxx 的 path 是可以加载的， 但是配置 /xxx/xxx 这样的嵌套路径就加载不了了，请教一下是什么原因呢？

**Comment by doterme** [comment]
你register model了么？

**Comment by zuiidea** [comment]
跟register model 无关，请检查`test/list.js`是否有误

参考

```
{
      path: 'UIElement/iconfont',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              cb(null, require('./routes/UIElement/iconfont/'))
            }, 'UIElement-iconfont')
          },
 },
```

**Comment by mindreading** [comment]
囧， 问题解决了， 折腾了两天， 是因为 index.html 里面 引用 index.js 的地址 默认是 src="index.js" 需要改成 "/index.js" 绝对路径， 这样当访问 /xxx/xxx 这样的 path 的时候 才能加载，，  感谢大家的帮助！！
