### ISSUE TITLE
eslint跑不起来

### ISSUE THREAD

**Issue by Nuoky** [zuiidea/antd-admin#423]
貌似eslint v4不兼容eslint-config-airbnb？
https://github.com/airbnb/javascript/issues/1454

**Comment by zuiidea** [comment]
?
`npm run lint` 0 error

**Comment by Nuoky** [comment]
环境：
win10
npm -v 5.3.0
node -v v6.9.2

换到windows环境并重新拉了代码，npm run lint时提示：

> PS I:\git\antd-admin> npm run lint

> @ lint I:\git\antd-admin
> eslint --fix --ext .js src

can't resolve reference #/definitions/basicConfig from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #

I:\git\antd-admin\src\components\DataTable\AnimTableBody.js
   1:1  error  Definition for rule 'jsx-a11y/href-no-hash' was not found                                             jsx-a11y/href-no-hash
   1:1  error  'react' should be listed in the project's dependencies. Run 'npm i -S react' to add it                import/no-extraneous-dependencies
   2:1  error  'prop-types' should be listed in the project's dependencies. Run 'npm i -S prop-types' to add it      import/no-extraneous-dependencies
   3:1  error  'rc-tween-one' should be listed in the project's dependencies. Run 'npm i -S rc-tween-one' to add it  import/no-extraneous-dependencies
  49:5  error  JSX not allowed in files with extension '.js'                                                         react/jsx-filename-extension
  62:3  error  propType "body" is not required, but has no corresponding defaultProp declaration                     react/require-default-props
  63:3  error  Prop type `any` is forbidden                                                                          react/forbid-prop-types
  63:3  error  propType "page" is not required, but has no corresponding defaultProp declaration                     react/require-default-props
.....
✖ 577 problems (576 errors, 1 warning)
  6 errors, 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint: `eslint --fix --ext .js src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by zuiidea** [comment]
试试最新的
