### ISSUE TITLE
npm run list gives 538 errors. is it normal ? 

### ISSUE THREAD

**Issue by netfish88** [zuiidea/antd-admin#426]
when I did _npm install_, there were some warnings.

![image](https://user-images.githubusercontent.com/11173194/28327670-139be0a6-6c1f-11e7-84c0-9cd5d4e34373.png)

after I did _npm run lint_ same as the readme file, it gives us 538 errors. 

![image](https://user-images.githubusercontent.com/11173194/28327683-228b8788-6c1f-11e7-9bb2-8a0c7ea169aa.png)

Is it normal behavior or wrong configuration ?

**Comment by zuiidea** [comment]
- remove `node_modules` folder
- then` npm install`

**Comment by luotuocao2008** [comment]
you do   npm install --save-dev eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y
