### ISSUE TITLE
npm run build 后，发布到服务器，显示的界面功能还是旧的

### ISSUE THREAD

**Issue by andrewsty** [zuiidea/antd-admin#428]
npm run build 后，dist目录生成的文件发布到服务器，网页显示的界面功能还是旧的
但是npm run dev ，在本地开的服务又是修改后的。不明白怎么回事。服务器目录都清空重新上传还是一样。可能是哪里的问题呢？出问题之前做了代码上传git，按道理没关系啊。有人遇到过类似问题吗

**Comment by doterme** [comment]
缓存？清空浏览器试试。

**Comment by andrewsty** [comment]
果然是缓存。。。。F5刷新后就ok了。谢谢
