### ISSUE TITLE
build 构建的时候 没有把 assets 里面的东西构建到 dist 文件夹下 导致 logo.gif 显示不了

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#43]
你好，我这边在运行 npm run build 的时候 构建成功了 但是 assets 里面的东西没有构建进去 导致logo图片显示不了 ,我这个 logo 是在 src/utils/config.js 里面配置的路径 。。。

谢谢!

**Comment by zuiidea** [comment]
assets里面的图片是我用来写文档用的，logo配置的相对路径的话应该不会打包进去，建议直接写在组件里去应该就可以了，也只有两个地方应用了

**Comment by zuiidea** [comment]
@encorehe ，应该可以这样写

```
import logoSrc from './assets/logo.png'

module.exports = {
  logoSrc,
}
```
