### ISSUE TITLE
请问antd的版本升级到最新版本会影响现有功能吗？

### ISSUE THREAD

**Issue by cranehe** [zuiidea/antd-admin#430]
请问antd的版本升级到最新版本会影响现有功能吗？目前antd已经到2.12.1，修复了不少之前的问题，还有就是现在用的组件里面ant的表格分页条那里有上下不对齐的情况,如下图：
<img width="1210" alt="-01" src="https://user-images.githubusercontent.com/1540581/28447699-184756f2-6e05-11e7-9373-5d712d1760c9.png">

**Comment by lanke** [comment]
你看下 theme中index.less 样式修改下 就没问题了

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/pull/431/files

一般不会影响
