### ISSUE TITLE
按需加载

### ISSUE THREAD

**Issue by zhengqizhang** [zuiidea/antd-admin#434]
求救 我在路由中使用了require.ensure 但是打包出来的文件还是一个 还需要在其他别的位置进行配置么 谢谢
<img width="765" alt="2017-07-22 4 17 13" src="https://user-images.githubusercontent.com/12936800/28489632-ae0f39c6-6ef9-11e7-9893-1f00bb6ef9da.png">

**Comment by zuiidea** [comment]
`.default`是什么？
看项目代码
