### ISSUE TITLE
Longer URL path not working 

### ISSUE THREAD

**Issue by malindar** [zuiidea/antd-admin#436]
I tried to add url path restaurant/order/1 , seems main router does not recognize that path, if I changed to order/1 it's working. any idea why it's behaved in differently ?

**Comment by zuiidea** [comment]
show code?

**Comment by malindar** [comment]
router.js
```
    {
          path: 'restaurants/orders/:id',
          getComponent (nextState, cb) {
            require.ensure([], require => {
              registerModel(app, require('./models/restaurant/orders'))
              cb(null, require('./routes/restaurant/orders'))
            }, 'barOrders')
          },
     },
```

in order model file
```
subscriptions: {
    setup ({ dispatch, history }) {
      history.listen(location => {
        const match = pathToRegexp('/restaurants/orders/:id').exec(location.pathname)
          console.log('detail url')
        if (match) {
          dispatch({ type: 'query', payload: { id: match[1] } })
        }
      })
    },
  },
```
what I have noticed is, it does not go inside to the getComponent function. If I remove the :id then it works , i tried with adding static url ex: restaurants/orders/detail to check whether is goes to getComponent function. having the same problem :(

**Comment by zuiidea** [comment]
Try  this way

```
{
    path: 'restaurants',
    childRoutes:[
      {
        path: 'orders/:id',
        getComponent (nextState, cb) {
          require.ensure([], require => {
            registerModel(app, require('./models/restaurant/orders'))
            cb(null, require('./routes/restaurant/orders'))
          }, 'barOrders')
        },
      },
    ]
},
```

**Comment by malindar** [comment]
thanks @zuiidea , will try and give you an update

**Comment by malinda1986** [comment]
it's working @zuiidea 
thanks

**Comment by tanszepin** [comment]
Hi,
I tried to add parameters to the url following  '/user/:id' for openPages '/login' and it throws me error 404. Please advise on how to add parameters like '/user/:id' for '/login/XXX'

    {
      path: '/user/:id',
      models: () => [import('./models/user/detail')],
      component: () => import('./routes/user/detail/'),
    }, {
      path: '/login/:id',
      models: () => [import('./models/login')],
      component: () => import('./routes/login/'),
    }

**Comment by malinda1986** [comment]
@tanszepin I faced the same issue for open urls, but inside pages parameters working, If it works for me ill update here

**Comment by tanszepin** [comment]
@malinda1986, thanks for the reply. Any idea how the '/user/:id' works?

I changed the following and no error when '/user/foo':
    {
      path: '/user',
      models: () => [import('./models/user')],
      component: () => import('./routes/user/'),
    }, {
      path: '/user/:id',
      models: () => [import('./models/user')],
      component: () => import('./routes/user/'),
    }

but 404 on the following when '/login/foo':
    {
      path: '/user/:id',
      models: () => [import('./models/user/detail')],
      component: () => import('./routes/user/detail/'),
    }, {
      path: '/login/:id',
      models: () => [import('./models/user/detail')],
      component: () => import('./routes/user/detail/'),
    }, {

**Comment by malinda1986** [comment]
I can suggest you a quick workaround for login/: id, use login?id={param} that works
"login/: id" I also have the same issue :( and I used  login?id={param} , I did not dig into more, If I find a solution for login/: id I'll update you.

**Comment by superlbr** [comment]
@tanszepin 
1. guide1 https://github.com/zuiidea/antd-admin/issues/725
2. guide2 check parameter in model->app.js
    from pathname、current to hasPermission
    Basicly you won't miss it
