### ISSUE TITLE
dist中的内容直接运行

### ISSUE THREAD

**Issue by 102010cncger** [zuiidea/antd-admin#439]
大神,你好
https://github.com/zuiidea/antd-admin/issues/200
中你说 "现在的版本不能直接运行了，必须配置服务器，4.0-dev及之前的可以"

项目需要dist直接运行的需求已经让我不得不解决这个问题了

不知道是什么原因导致的,能否稍微提示下,我可能要稍微调整下,谢谢了!

我研究了dva-quickstart中的dist是可以直接运行的.

谢谢了!

**Comment by doterme** [comment]
为什么一定要直接运行呢？放到任意一个web Server下都行。

**Comment by 102010cncger** [comment]
@doterme 

哈哈,直接运行的好处你不懂.

我用antd编译出来的东西是放在app中或spring-cloud中的

**Comment by mapengze** [comment]
@102010cncger  老哥 dist直接运行的方法你找到了吗 求解啊

**Comment by mapengze** [comment]
@doterme 大神 你说任意一个web server都行 那如何把dist放到tomcat里面直接运行呢

**Comment by 102010cncger** [comment]
// 1. Initialize
const app = dva({
  ...createLoading({
    effects: true,
  }),
  // history: browserHistory,
  onError (error) {
    message.error(error.message)
  },
})

中把history: browserHistory注释掉就可以了
