### ISSUE TITLE
配置正式环境 url

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#44]
你好 我如何配置正式环境的 url 参数呢？ 是注释掉 src/utils/index.js 里面的 require('./mock.js'),然后写死放到请求接口里面吗？类似这样 return request('192.168.1.123：8080/api/login', {
    method: 'post',
    data: params
  }) 还是有地方可以配置啊，怎么配置呢？

谢谢!

**Comment by mtboom** [comment]
我注释掉了mock但是还是发不出proxy的请求,请问我应该再改哪些地方才能在本地使用proxy

**Comment by zuiidea** [comment]
@encorehe，没有其他地方了，不过你可以在`utils/config.js`里添加一个字段，引入就可以了

**Comment by zuiidea** [comment]
@mtboom，如果要使用可以本地proxy，

- 使用`npm run start`命令
- 访问`localhost:8989`
- 注释掉 ` src/utils/index.js ` 里的 `mock`
- 还需要改`mock`文件夹下的代码，具体怎么样我还不知道怎么改，你可以尝试一下😭

**Comment by mtboom** [comment]
@zuiidea 问题已经解决
使用npm run start命令
访问localhost:8989
注释掉 src/utils/index.js 里的 mock
使用 fetch 发送请求

**Comment by wuyongdec** [comment]
@mtboom 
本地proxy怎么配置呢？
是不是类似这样：
`"proxy": {
    "/api": {
      "target": "http://jsonplaceholder.typicode.com/",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  }`

**Comment by 102010cncger** [comment]
我用springboot的zuul做的代理

配置如下,坑了我好久的是必须配置/base/而不是/base,希望能给大家帮助

zuul配置如下

"scripts": {
    "start": "dora --plugins \"proxy,webpack?publicPath=/base/,webpack-hmr,browser-history?index=/src/index.html\"",
    "dev": "dora --plugins \"webpack?publicPath=/base/,webpack-hmr,browser-history?index=/src/index.html\"",
    "lint": "eslint --fix --ext .js,.jsx src/components/layout",
    "build": "atool-build"
  },

#eit反向代理到8000端口,多个用,分隔
zuul.routes.base.path=/base/**
zuul.routes.base.url=http://127.0.0.1:8000
zuul.routes.base.stripPrefix=false
#eit.ribbon.listOfServers=127.0.0.1:8080
