### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by webxiaomin** [zuiidea/antd-admin#440]
⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since roadhog\'s major
 or minor version upgrades may result in incompatibility. If you insist on doing
 so, please be careful of the compatibility after upgrading roadhog.

Failed to compile.

Error in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "import" specified in "base"
 at 3, attempted to resolve relative to "D:\\xm\\tz\\dva\\github-demo2\\antd-adm
in\\src"
    at Array.map (native)
 @ multi index

**Comment by zuiidea** [comment]
试试最新的代码
