### ISSUE TITLE
user 里面的表格 查询框的接口咋替换啊 一直找不到方法

### ISSUE THREAD

**Issue by zhien520** [zuiidea/antd-admin#445]
user 里面的表格 查询框的接口咋替换啊 一直找不到方法

**Comment by doterme** [comment]
在mock里面，如果你不需要用mock，用自己提供的后台接口可以把.roadhogrc.mock.js删掉

**Comment by yinxuan1128** [comment]
把.roadhogrc.mock.js删掉后 自己的后台接口在哪里定义呢？

**Comment by doterme** [comment]
自己写个service
