### ISSUE TITLE
如何管理路径？import XX from './../../../……/Model.js'这样的方式太糟糕了

### ISSUE THREAD

**Issue by dkvirus** [zuiidea/antd-admin#457]
使用绝对路径的话，只能这样：```import 'D:/work/前端框架原型/octopus-admin/src/index.html';```
但是如果根目录位置换了就完蛋，本想找找看可有类似 JAVA 的 classpath 写法，也没找到解决方案。

**Comment by dkvirus** [comment]
最烦恼的是变换子目录位置，简直是一动就报错，报错。后期很不利于调整项目结构吧。

**Comment by zuiidea** [comment]
`webpack.config.js`里可以设置Alias

**Comment by dkvirus** [comment]
@zuiidea  查了一下 webpack alias 用法，确实可以解决这个问题。但是又要添加一个配置文件，随着配置文件的增多，而且直接暴露根目录下，总感觉不是很优雅！！
