### ISSUE TITLE
 系统报错：uncaught at sagaWithCatch TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by pmg1989** [zuiidea/antd-admin#46]
![image](https://cloud.githubusercontent.com/assets/13361827/22174409/be0c7ba6-e018-11e6-80a7-ea5f9b0b081a.png)

dear zuiidea，我本地刚从你的code上拉了份代码，啥也没改动，npm install 以后，运行就发现出现了如上图的系统错误，试了好几次都是的，请问你能看出是什么原因么？

**Comment by zuiidea** [comment]
你先`npm install antd@2.6.0`，我明天看下，应该是antd升级带来的，你的antd版本应该是2.6.4

**Comment by pmg1989** [comment]
zuiidea ，确如你所说，我npm install antd@2.6.0后就没出现问题了，算是初步解决了，但貌似这样也不是最好的解决方案，总不能一直都安装固定版本了吧，antd那边会发现并解决这个问题么？期待解决方案

**Comment by zuiidea** [comment]
https://github.com/ant-design/ant-design/pull/4609

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/4692
