### ISSUE TITLE
User下面的Modal.js 添加一个FormItem（新建用户 修改用户）里面都是一样的 咋解决

### ISSUE THREAD

**Issue by zhien520** [zuiidea/antd-admin#462]
![7878](https://user-images.githubusercontent.com/20012232/28863974-95e8146a-779d-11e7-9ec5-af5bfdacf1ab.jpg)

比如我在Modal里面添加这段代码 新增数据和修改数据 都有啊 咋解决....求助

**Comment by zhien520** [comment]
@zuiidea

**Comment by zhien520** [comment]
@zuiidea

**Comment by superlbr** [comment]
那么user为啥一个modal既可以新增又可以修改？
`  const modalProps = {
    item: modalType === 'create' ? {} : currentItem,
    。。。}`
把modalType传进来
`{modalType === 'create' && <FormItem`
就这样
