### ISSUE TITLE
新版本在FireFox和IE下无法显示

### ISSUE THREAD

**Issue by aiyowa** [zuiidea/antd-admin#465]
如题，FireFox和IE下无法显示，首页空白，chrome下正常。包括演示的地址：http://47.92.30.98:8000

**Comment by stanNo1** [comment]
我火狐没有这样的问题

**Comment by aiyowa** [comment]
我用的老版本火狐45.0.2.经过测试，45.0.2，47.0.2版本都不行。更新到54.0.1后正常显示。

**Comment by stanNo1** [comment]
是的，我火狐版本也是54.0,1
