### ISSUE TITLE
npm run build 中报了一个警告，部署后访问index.html页面报错

### ISSUE THREAD

**Issue by lazyopen** [zuiidea/antd-admin#466]
一、build 信息
> roadhog build

Creating an optimized production build...
(node:14689) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since roadhog\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, please be careful of the compatibility after upgrading roadhog.

Compiled successfully in 185.7s.

File sizes after gzip:

  341.45 KB  dist/1.0.0/index.js
  197.6 KB   dist/1.0.0/scenic-classify.793234532c1c46af4df6.js
  196.63 KB  dist/1.0.0/feedback.793234532c1c46af4df6.js
  196.51 KB  dist/1.0.0/footprint.793234532c1c46af4df6.js
  196.5 KB   dist/1.0.0/userList.793234532c1c46af4df6.js
  195.48 KB  dist/1.0.0/user.793234532c1c46af4df6.js
  174.64 KB  dist/1.0.0/scenic.793234532c1c46af4df6.js
  137.11 KB  dist/1.0.0/dashboard.793234532c1c46af4df6.js
  70.07 KB   dist/1.0.0/menu.793234532c1c46af4df6.js
  68.34 KB   dist/1.0.0/role.793234532c1c46af4df6.js
  50.59 KB   dist/1.0.0/adminUser.793234532c1c46af4df6.js
  33.19 KB   dist/1.0.0/login.793234532c1c46af4df6.js
  29.32 KB   dist/1.0.0/index.css
  5.29 KB    dist/iconfont.js
  1.76 KB    dist/1.0.0/role-detail.793234532c1c46af4df6.js
  1.54 KB    dist/1.0.0/adminUser-detail.793234532c1c46af4df6.js
  1.54 KB    dist/1.0.0/scenic-classify-detail.793234532c1c46af4df6.js
  1.53 KB    dist/1.0.0/user-detail.793234532c1c46af4df6.js
  1.52 KB    dist/1.0.0/scenic-detail.793234532c1c46af4df6.js
  1.52 KB    dist/1.0.0/menu-detail.793234532c1c46af4df6.js
  774 B      dist/1.0.0/error.793234532c1c46af4df6.js
  374 B      dist/iconfont.css
二、访问报错信息

![1](https://user-images.githubusercontent.com/4491617/28906411-fdbbe510-7849-11e7-892f-49b387b63a62.png)

页面空白

npm run dev 运行访问都正常

**Comment by zuiidea** [comment]
`ctrl + F5`

**Comment by lazyopen** [comment]
![image](https://user-images.githubusercontent.com/4491617/28908842-677f5366-7858-11e7-906c-8de2ef7e5d4d.png)
我去，更新了你的配置
   publicPath : `/${version}/`,
  outputPath : `./dist/${version}`,
我以为nginx location 要配置到版本目录  /dist/1.0.0
为啥还是只要配置到  /dist 就行,是哪里处理了么
