### ISSUE TITLE
@zuiidea请教关于跳转到login页面的问题

### ISSUE THREAD

**Issue by jackyren0** [zuiidea/antd-admin#467]
zuiidea，大神，你好！
参考您的项目，我用dev-cli搭了一个项目，但是跳转login的时候有问题。
两个现象：
1.在浏览器地址中输入http://ip:port。
在models/app.js的effects *query中，在我自己的项目中，如果使用window.location = `${location.origin}/login?from=${from}`方法，始终会以ip:port/去执行routes/app.js，登录后的页面会一闪，然后以ip:port/login?from=/跳转至login.js。
改成yield put(routerRedux.push(`${location.origin}/login?from=${from}`));就不会以ip:port/去执行routes/app.js，直接以ip:port/login?from=/跳转至login.js。
在跳转之前没有任何其他操作。
对比了两个项目的配置，包的版本调整为一样，还是不能解决这个问题。debug你的项目，就不会出现这样的问题。
2.当我在yield put(routerRedux.push(`${location.origin}/login?from=${from}`));之前再加上const { success, user } = yield call(query, payload)，又会出现先以ip:port/去执行routes/app.js，登录后的页面会一闪，然后以ip:port/login?from=/跳转至login.js。的现象了。
这个情况困扰我很久了，烦请大神指点迷津，非常感谢！

**Comment by jackyren0** [comment]
我猜测可能和异步处理有关，但是从配置上和你的项目相比，看不出来什么区别。

**Comment by chenkang084** [comment]
@jackyren0  我在我自己fork的分支里面已经fixed 了这个问题。请参考 https://github.com/chenkang084/antd-admin/blob/master/src/models/app.js#L67 
问题原因：由于 subscriptions 中异步去查询，如果后台返回比较慢，这个时候页面其实已经渲染完毕了，然后，返回解决回来之后，又重新 direct 到 login page 造成页面闪烁。
解决办法：加了一个loading，等待 请求回来，如果没有权限，跳转到login页面，如果有权限，跳到dashboard页面。

**Comment by superlbr** [comment]
duplicat https://github.com/zuiidea/antd-admin/issues/479
