### ISSUE TITLE
model文件已经删除，并且在index.js并未引用该model，npm start的时候报module not found错误

### ISSUE THREAD

**Issue by PebblerWon** [zuiidea/antd-admin#470]
model并未引用<br>
![image](https://user-images.githubusercontent.com/10150276/28913655-65ddd20e-786b-11e7-8a19-b464728855e1.png)<br>
但是却报了如下的错误<br>
![image](https://user-images.githubusercontent.com/10150276/28913724-9f2a1c98-786b-11e7-8ede-68dfad8bd27b.png)<br>
文件目录里也已经删除了该文件<br>
![image](https://user-images.githubusercontent.com/10150276/28913752-b7258f30-786b-11e7-81b0-3521e981edad.png)
@zuiidea

**Comment by zuiidea** [comment]
module not found 而不是 model not found，
你的src/index.js引用了不存在的文件

**Comment by PebblerWon** [comment]
src/index.js里引用的文件在models文件夹下都可以找到啊，为什么说引用了不存在的文件呢，但是报的错误就是找不到module(这个module是以前引用过的，但现在已经删除了，并没有在引用)。

**Comment by PebblerWon** [comment]
现象一：经过调试发现当注释
`app.model(require('./models/IZTable2'))`
的时候编译通过并且不报错。
![tim 20170803172602](https://user-images.githubusercontent.com/10150276/28915181-e7de095e-7870-11e7-8083-29e1a71e0b77.png)
<br>
现象二：将第二个model改名为`IZT`的时候，编译通过并且也不报错。
现象三：在将第二个model重新把名字改回IZTable2的时候，编译报错module not found<br>并且报错的module not found指向的是 IZT 找不到<br>
![image](https://user-images.githubusercontent.com/10150276/28915551-0befa518-7872-11e7-92c0-813edb2362f0.png)

猜想：model的命名可能有某种潜在的规定，如：IZTable1和IZTable2两个同时存在的话会报错。
不知道真实的情况是什么？
@zuiidea
