### ISSUE TITLE
关于执行npm run dev 无法启动服务的问题【解决方案】

### ISSUE THREAD

**Issue by hanxiansen** [zuiidea/antd-admin#475]
我执行npm run dev的时候发现无法正确的启动对应的浏览器并且ip显示为0.0.0.0: 8000，所以我在package.json的“script” 中添加了一条执行命令："start": "roadhog server"。如下：
`"scripts": {
     "start": "roadhog server",
    "dev": "set BROWSER=none&&set HOST=127.0.0.1&&roadhog server",
    "lint": "eslint --fix --ext .js src",
    "build": "roadhog build",
    "build:dll": "roadhog buildDll"
  }`
然后在命令行中输入：npm start 就可以启动默认浏览器，运行程序了，希望能帮到大家。

**Comment by addedjacky** [comment]
6

**Comment by zuiidea** [comment]
这个没什么意义
