### ISSUE TITLE
login路由下按需加载出现闪屏

### ISSUE THREAD

**Issue by yangbin1994** [zuiidea/antd-admin#479]

**Comment by chenkang084** [comment]
@yangbin1994 
我在我自己fork的分支里面已经fixed 了这个问题。请参考 https://github.com/chenkang084/antd-admin/blob/master/src/models/app.js#L67 
问题原因：由于 subscriptions 中异步去查询，如果后台返回比较慢，这个时候页面其实已经渲染完毕了，然后，返回解决回来之后，又重新 direct 到 login page 造成页面闪烁。
解决办法：加了一个loading，等待 请求回来，如果没有权限，跳转到login页面，如果有权限，跳到dashboard页面。

**Comment by superlbr** [comment]
fixed in https://github.com/zuiidea/antd-admin/commit/08f40efd2bb52cd6581dba83f4f32a29a0bea73c
