### ISSUE TITLE
侧边栏导航问题

### ISSUE THREAD

**Issue by myqianlan** [zuiidea/antd-admin#48]
感谢共享此方案
问题如下：

1.侧边栏导航过多的时候，不能上下滚动

2.侧边栏导航不能根据地址栏路径自动定位到当前需要高亮的导航目录

**Comment by zuiidea** [comment]
第一个问题：https://github.com/zuiidea/antd-admin/issues/42 有待讨论和优化
第二个问题：


我这边正常的

**Comment by wanghao524151** [comment]
1. 改成只展示当前菜单的父级菜单，其他的收缩起来
2. components/layout/menu.js defaultSelectedKeys改成selectedKeys
![image](https://cloud.githubusercontent.com/assets/1575269/22395580/afb3fb78-e57d-11e6-96e0-9e7b4860095b.png)

**Comment by wanghao524151** [comment]
第一个问题：左侧导航菜单过多，不能实现上下滚动的问题
height: 100%;
overflow-y: auto;
![image](https://cloud.githubusercontent.com/assets/1575269/22396408/f4071876-e593-11e6-869b-2762553f2417.png)

components/layout/sider.js
`
const Sider = ({ siderFold, location }) => {
  const menusProps = {
    siderFold,
    location,
  };

  return (
    <div className={styles.left_bar}>
      <div className={styles.logo}>
        <img alt="{config.logoText}" src={config.logoSrc} />
        {siderFold ? '' : <span>{config.logoText}</span>}
      </div>
      <div className={styles.left_menus}>
        <Menus {...menusProps} />
      </div>
    </div>
  );
};

export default Sider;
`

components/layout/main.less
`
.sider {
    width: 224px;
    background: #3e3e3e;
    position: absolute;
    overflow: visible;
    height: 100vh;
    transition: @transition-ease-out;
    box-shadow: @shadow-1;
    z-index: 1994;
    color: #999;

    &.light {
      background: #fff;

      .switchtheme {
        background: #fff;
        border-top: solid 1px #f8f8f8;
      }
    }

    .left_bar {
      height: 100%;

      .logo {
        width: 224px;
        position: absolute;
        top: 0;
        text-align: center;
        height: 48px;
        line-height: 48px;
        cursor: pointer;
        transition: @transition-ease-out;
        overflow: hidden;
        border-bottom: 1px solid #999;
        background-color: #3e3e3e;
        z-index: 100;

        img {
          width: 20px;
          margin-right: 8px;
          transition: @transition-ease-out;
          vertical-align: middle;
        }

        span {
          vertical-align: middle;
          font-size: 16px;
          text-transform: uppercase;
          display: inline-block;
        }

        .anticon {
          transition: @transition-ease-out;
        }
      }

      .left_menus {
        padding-top: 50px;
        height: 100%;
        overflow-y: auto;
      }
    }

    :global {
      .ant-menu-dark,
      .ant-menu-dark .ant-menu-sub {
        color: #999;
      }

      .ant-menu {
        transition: @transition-ease-out;
        overflow-y: auto;

        .ant-menu-item,
        .ant-menu-submenu-title {
          overflow: auto;
          white-space: normal;
        }
      }
    }
  }
`

**Comment by zuiidea** [comment]
@wanghao524151 这样会有另外一个问题，就是菜单收拢时，二级菜单被overflow了

**Comment by wanghao524151** [comment]
没明白，你说的是下面的样子，会不显示二级菜单？
![image](https://cloud.githubusercontent.com/assets/1575269/22401033/5ecc1e10-e600-11e6-94ec-ae9df78249d2.png)

**Comment by zuiidea** [comment]
对的，使用了`overflow:hidden;`或者`overflow-y:hidden;`收拢时都会使二级菜单显示不了

**Comment by wanghao524151** [comment]
我加了这个：收起来的时候fold left_bar去除overflow-y,这样就可以了
```
&.fold {
    .sider {
      width: 42px;

      .left_bar {
        overflow-y: visible;
      }
   }
}
```

**Comment by zuiidea** [comment]
@wanghao524151 讲道理可以，晚点我加上，极端情况就是收拢也需要滚动，不过这应该是最好的解决方法了

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/a2abe411c491c156426bc43f32d7f6d2b1695b89

**Comment by myqianlan** [comment]
我自己的解决方案是取消了侧边栏的固定，整页滚动

**Comment by myqianlan** [comment]
还有就是某些页面可能不在侧边栏菜单中进行导航，比如某个列表中某一项的详情页，但是是需要菜单高亮的。我目前的做法是从菜单数据中找到这条路径，如果找不到，就截取最后一段继续找。
比如 /product/list/123
我会依次寻找 /product/list/123，/product/list，/product。。。
这种做法需要约定无菜单的页面与有菜单的页面的路径关系

**Comment by zuiidea** [comment]
@myqianlan 最新的代码没有问题了啊

**Comment by myqianlan** [comment]
@zuiidea 
1.当前方案收拢时并不能上下滚动
2.当前方案并未考虑到无侧边栏菜单页面在侧边栏高亮其父级菜单
