### ISSUE TITLE
页面刷新后，页面先出现404，然后再显示页面

### ISSUE THREAD

**Issue by reawei** [zuiidea/antd-admin#481]
pathToRegexp路径丢失,菜单栏不能选中，造成刷新之后出现404，这个问题应该出现在哪个地方

**Comment by shaomingming008** [comment]
你好  问题解决了吗

**Comment by xingwus** [comment]
pathToRegexp路径丢失没解决，我只是把app.js里面条404的代码去掉了

**Comment by xingwus** [comment]
现在不会出现404.但是页面刷线，菜单栏不会选中。有可能是因为菜单栏是通过后台获取造成的

**Comment by superlbr** [comment]
pathToRegexp路径丢失，不是这个原因吧，是开发的时候，出现的所谓闪屏，build版本应该没有这个问题。或者developer版本，试试umi，全屏loading。。。
