### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by miaozilong** [zuiidea/antd-admin#483]
⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since roadhog\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, please be careful of the compatibility after upgrading roadhog.

Failed to compile.

./src/svg/cute/congratulations.svg
Module build failed: TypeError: Cannot read property 'join' of undefined
From previous event:
    at Promise (<anonymous>)

**Comment by z253573760** [comment]
我也是这个问题

**Comment by zuiidea** [comment]
npm i roadhog@1.0.0-beta.7, 不要安装到全局

**Comment by superlbr** [comment]
@zuiidea 还是不行

**Comment by wedaren** [comment]
还是不行+1

**Comment by chengwangping** [comment]
我也是这个问题

**Comment by wedaren** [comment]
我的环境
node    v7.7.2
mac   10.12.6 (16G29)

**Comment by zuiidea** [comment]
造成这个的原因其实就是roadhog下的包`svg-sprite-loader`版本不是最新的。旧版的roahog下的`svg-sprite-loader`版本号只有`0.3.0`

依次排查：
- `roahog -v ` 查看是否是1.0.0-beta.7，如果不是，请先保证不是使用的全局的roahog，再`npm i roadhog@1.0.0-beta.7`。

- ` cd  node_modules\roadhog\node_modules\svg-sprite-loader`  查看svg-sprite-loader版本是否为3.0.8。

**Comment by wedaren** [comment]
roadhog@1.0.0-beta.7
svg-sprite-loader@3.1.2

**Comment by quanpower** [comment]
开始不行，然后运行了下npm i roadhog@1.0.0-beta.7可以了，是之前npm install 按照package.json安装没装上？另外，看了下现在node_modules\roadhog\node_modules下面没有svg-sprite-loader也没报上面这个错了。是不是跟它无关？
先别笑哈，原用Python写服务端的，有点白，现在用npm装，完了用npm list一看一大堆堆的红色error missing xxxx,npm安装都这样吗？是网络原因还是什么造成的？npm install的结束的时候没看到报错啊。这可靠性感觉不放心啊，都是要先npm install 完了再检查遍手动安装？

**Comment by superlbr** [comment]
roadhog的版本已经更新到1.0.2，其中svg-sprite-loader已更新到3.1.2。经测试没有问题了。

**Comment by JustYJQ** [comment]
Compiled successfully in 14.3s!

The app is running at:

  http://0.0.0.0:8000/

访问 http://0.0.0.0:8000/ 页面 Cannot GET /

**Comment by zuiidea** [comment]
@JustYJQ 访问 http://localhost:8000啊

**Comment by Yunfly** [comment]
还是有这个问题现在的版本

**Comment by xiaofengqqcom123** [comment]
"roadhog": "^2.1.0"，依旧有这个问题，什么方面的原因呢

**Comment by superlbr** [comment]
@ xiaofengqqcom123 已经过去好多版本了，4.3.9？还是最新的master

**Comment by xiaofengqqcom123** [comment]
@superlbr 我同事说是因为，dva不建议只写一个webpack.config.js文件。不过，我不知道，dva建议的配置咋弄？
