### ISSUE TITLE
NPM RUN DEV 跑不起来

### ISSUE THREAD

**Issue by z253573760** [zuiidea/antd-admin#484]
Failed to start the server, since you have enabled dllPlugin, but have not run `
roadhog buildDll` before `roadhog server`.
 提示这个 我是小白

**Comment by z253573760** [comment]
可以了

**Comment by doterme** [comment]
@z253573760 怎么解决的？我也遇到了。

**Comment by zuiidea** [comment]
@doterme  `npm run build:dll`先
