### ISSUE TITLE
build完之后直接访问显示不出字体图片

### ISSUE THREAD

**Issue by renhonghai** [zuiidea/antd-admin#487]
在编译完，直接访问index.html时 显示不出字体图片， 例如 用户名&密码后面的对号之类

**Comment by qingjiaowochengzd** [comment]
@renhonghai 你解决了吗？

**Comment by renhonghai** [comment]
@qingjiaowochengzd 还没有解决， 你那知道问题所在么

**Comment by zuiidea** [comment]
什么意思？

**Comment by renhonghai** [comment]
@zuiidea build完  配置代理以index.html 为入口直接访问的时候 icon图 全都显示不出来 但是字体文件都已经加载

**Comment by zuiidea** [comment]
配置的`/dist/index.html` 还是 `/dist/1.0.0/index.html`

**Comment by renhonghai** [comment]
配置的  /dist/index.html   所有文件都在 dist目录下

**Comment by zuiidea** [comment]
@renhonghai  我刚刚才编译的 http://antd-admin.zuiidea.com

你说的Icon图是什么，截图？代码？

**Comment by renhonghai** [comment]
@zuiidea sorry..  应该是我的改动影响到的  重新克隆项目之后发现是没有问题的 多谢耐心回复。
