### ISSUE TITLE
npm run lint之后很多错误

### ISSUE THREAD

**Issue by addedjacky** [zuiidea/antd-admin#490]
[版本问题？更新最新的git库了。

✖ 2411 problems (2411 errors, 0 warnings)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/xxx/.nvm/versions/node/v6.9.0/bin/node" "/Users/xxx/.nvm/versions/node/v6.9.0/bin/npm" "run" "lint"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! antd-admin@4.3.2 lint: `eslint --fix --ext .js src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-admin@4.3.2 lint script 'eslint --fix --ext .js src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --fix --ext .js src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd-admin
npm ERR! There is likely additional logging output above.

**Comment by addedjacky** [comment]
切换最新版本 8.3.0

**Comment by addedjacky** [comment]
切换最新版本 8.3.0
✖ 2411 problems (2411 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd-admin@4.3.2 lint: `eslint --fix --ext .js src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-admin@4.3.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zuiidea** [comment]
我知道了，
因为这个原因，我把public目录移动到src文件夹里去，public下的文件，lint时应该忽略
https://github.com/sorrycc/roadhog/issues/341

**Comment by zuiidea** [comment]
Fix:https://github.com/zuiidea/antd-admin/commit/d26a92ce7993420def96713845b6e05c855a4c93
最好忽略CRLF/LF

```
git config --global core.autocrlf false
```
