### ISSUE TITLE
Compiled successfully 访问 http://localhost:8000/  出现Cannot GET /

### ISSUE THREAD

**Issue by JustYJQ** [zuiidea/antd-admin#491]
It\'s not recommended to use webpack.config.js, since roadhog\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, please be careful of the compatibility after upgrading roadhog.

Compiled successfully in 14.3s!

The app is running at:

  http://0.0.0.0:8000/

浏览器打开  http://0.0.0.0:8000/ 出现 Cannot GET /

Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAAAmCAYAAACoPemuAAAAGXRFW…K/r7fivfbNZeQ4JhnWFFGbTKbyo67Ap6zo5FDUX/tfgAEAQ3WUFGFdgUwAAAAASUVORK5CYII=' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by JustYJQ** [comment]
@zuiidea  访问 http://localhost:8000/  也出现这个问题

**Comment by gardner** [comment]
Additionally, I see these messages in the console:

```
roadhog.dll.js:2 Uncaught SyntaxError: Unexpected token <
webpack-internal:///1674:9 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (webpack-internal:///1674:9)
    at eval (webpack-internal:///1674:31)
    at Object.<anonymous> (index.js?d8999e0dc574d05473b8:11900)
    at __webpack_require__ (index.js?d8999e0dc574d05473b8:708)
    at fn (index.js?d8999e0dc574d05473b8:113)
    at eval (webpack-internal:///1660:22)
    at Object.<anonymous> (index.js?d8999e0dc574d05473b8:11802)
    at __webpack_require__ (index.js?d8999e0dc574d05473b8:708)
    at fn (index.js?d8999e0dc574d05473b8:113)
    at eval (webpack-internal:///835:34)

```

**Comment by gardner** [comment]
After loading `roadhog.dll.js` directly from http://localhost:8000/roadhog.dll.js I can then see the contents are of `index.html` not the javascript.

<img width="670" alt="screen shot 2017-11-06 at 12 47 59 pm" src="https://user-images.githubusercontent.com/787026/32420557-e3841a90-c2f0-11e7-9728-db5d66936661.png">
