### ISSUE TITLE
Presentational Component 中如何定义自己的 state?

### ISSUE THREAD

**Issue by jzoe** [zuiidea/antd-admin#497]
看了一下 dva 的文档中有关组件设计的文章 [04-组件设计方法](https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/tutorial/04-%E7%BB%84%E4%BB%B6%E8%AE%BE%E8%AE%A1%E6%96%B9%E6%B3%95.md)

项目中也尽量遵循这种模式，但一直有个疑问就是 Presentational Component 中如何定义自己的 state 呢？

```js
import React, { Component, PropTypes } from 'react';

// state 如何定义？
const MyComponent = (props)=>{}
MyComponent.propTypes = {};

export default MyComponent;
```

还是说，应该尽量设计成 stateless 的组件，把相关的 state 放入 Container Component 的 model 中来定义，通过 props 传入！但实践过程中，还是会涉及到  Presentational Component 的一些局部 state 变量，这样如果都放在 Container 中，会使得 Container 更难以维护。

**Comment by dkvirus** [comment]
想法很好，dva 中用到了 React，你可以只当做是展示 View 使用，至于 React 中也有的 state，dva 中统一放到 models 层里的数据模型中写的。然后通过 dva 提供的 API，在 routes 层将对应的模型绑定到当前组件中：
```
// models/index.js
module.exports = {
    namespace: 'mystate',      // 当前数据模型的唯一标识，在组件中通过 connect 方法找到该数据模型，与组件绑定
    state: {
       // 你想要的 state 
   }
}
```
```
// routes/index.js
import { connect } from 'dva';

const MyComponent  = ()=> {
    return ();
}

export default connect(({ mystate }) => ({ mystate }))(MyComponent );  // connect 方法将数据模型层绑定到组件中，这样在组件中可以使用数据模型中的 state 对象
```

**Comment by zuiidea** [comment]
这种方式是没有state的，你就把它当成一个函数。
如果有需要：

**Comment by jzoe** [comment]
3Q @zuiidea  那我就用你说的方式来定义吧

**Comment by jzoe** [comment]
@dkvirus 这个是 dva 推荐的写法，对于状态进行了统一管理，但是对我一些只和局部状态有关的 state，我觉得还是应该放在组件内。

**Comment by cigarx** [comment]
@jzoe 我想问下你说的这种放在组件内的状态怎么和其他的dva形式的state一起管理和传递呢？

**Comment by superlbr** [comment]
@cigarx 建议阅读源码[文档](https://github.com/dvajs/dva/blob/master/docs/Concepts_zh-CN.md)，或者源码解读
