### ISSUE TITLE
为什么routes下页面会出现加载多次的情况？

### ISSUE THREAD

**Issue by meyer-net** [zuiidea/antd-admin#498]
进入src/routes/user/index.js 在 return前打上一句日志，console.log("entry in user")，随即回到dashboard，点击Users会打印3行entry in user，再点Posts会追加打印1~2行。是DVA路由加载的原因么？随后用dva提供的dva-example-user-dashboard，未曾发现此问题。

**Comment by meyer-net** [comment]
这样的话，性能耗损很大。同时app.js内部，也是存在相同的情况。

**Comment by superlbr** [comment]
话说还有好多可以优化的地方。。。先欢快地跑起来再说

**Comment by meyer-net** [comment]
@superlbr 表示赞同。

**Comment by zuiidea** [comment]
页面组件函数的写法可以改写成ES6的class的写法，在shouldComponentUpdate 中根据需求是否重新渲染
```
class Chart extends Component {
  shouldComponentUpdate (nextProps) {
    if (isEqual(this.props, nextProps)) {
      return false
    }
    return true
  }
  render () {
    return <TinyLineChart data={this.props.data} />
  }
}
```

**Comment by meyer-net** [comment]
@zuiidea DVA中是否存在Component的继承机制，类似于dva-model-extend，不然每个组件都要写一个，会挺繁琐。。。

**Comment by zuiidea** [comment]
跟dva无关
