### ISSUE TITLE
看了一圈，，那个登录权限控制在哪写的呀。。求教

### ISSUE THREAD

**Issue by zhump** [zuiidea/antd-admin#5]
```
export default Form.create()(login)
```

这行代码做什么用的呀

**Comment by zuiidea** [comment]
mock/app.js里模拟了两个管理员用户

**Comment by zhump** [comment]
楼主、我发现 你在 routes/App.js 
`login? xx:yy`
是以这种方式判断用户是否有权限登陆的
可为什么触发网页刷新操作， 这个js 被执行了两次呢？

**Comment by zuiidea** [comment]
@ zhump，是这样的，第一次是login有个默认的值，第二次是去模拟查询login状态产生的，在这里是因为只有静态的js才这样做的，生产环境中是否已经登录，显示哪个视图，由后台控制

**Comment by zhump** [comment]
楼主 单页面应用每触发一次页面路由改变，是否有需要 去后台查询一下 是否有该页面的权限和当前登录状态？

**Comment by zuiidea** [comment]
@zhump ，我不会做后台，权限这个需要和做后台的协商一下，common.js是在npm run build的时候生成的，这跟webpack有关
