### ISSUE TITLE
react-router 怎么使用动态嵌套路由，类似 user/:id/:detailId

### ISSUE THREAD

**Issue by SongFuZhen** [zuiidea/antd-admin#501]
需求： 在用户界面(/user)，点击详情进入用户详情界面(/user/:id)，用户详情界面点击列表项，进入详情的详情界面（/user/:id/:detailId）

当前效果： 进入用户界面OK，进入用户详情界面OK，进入详情的详情界面，只更改URL，但是不会跳转界面，但是F5刷新，会显示出来详情的详情界面

要达到的效果：使用Link，点击进入的时候，跳转界面

**Comment by PerHar3** [comment]
关注下

**Comment by cdhjava** [comment]
就是希望嵌套路由，而不是整个视图的重复渲染，比如左侧的菜单，只需要渲染一次，右侧内容区根据菜单点击渲染

**Comment by superlbr** [comment]
@cdhjava 可以build完再引入，或者完全手写。

**Comment by superlbr** [comment]
1. react router是服务前端的，不是后端，不需要restful 参考 https://github.com/ReactTraining/react-router/issues/3800
2. user/:id/:detailId 这样的写法，深表怀疑，是否能正常work。请勿效仿
3. 不推荐该写法，完全可以避开

**Comment by superlbr** [comment]
另附路由匹配原理：https://react-guide.github.io/react-router-cn/docs/guides/basics/RouteMatching.html
