### ISSUE TITLE
部署到nginx   /login?from=/      跳404页面

### ISSUE THREAD

**Issue by fishmankkk** [zuiidea/antd-admin#503]
![image](https://user-images.githubusercontent.com/20349363/29311118-19ceeef8-81e3-11e7-8d01-a2d827db6aa3.png)
![image](https://user-images.githubusercontent.com/20349363/29311133-2f6289f0-81e3-11e7-8801-5ce7083e5e89.png)

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/issues/269
