### ISSUE TITLE
关于chart从后台加载数据data的疑问

### ISSUE THREAD

**Issue by qwerasdfzxvv** [zuiidea/antd-admin#504]
疑问帮忙解答一下，看了一下route/chart样例，都是写死的 const data = [
  {
    name: 'Page A',
    uv: 4000,
    pv: 2400,
    amt: 2400,
  }, {
    name: 'Page B',
    uv: 3000,
    pv: 1398,
    amt: 2210,
  }。如果从后台调数据放到前台，例如在【一个界面】放6个chart表图像，每个图像都有不同的数据，是不是得model的state中使用:
state: {
list_1:[],
list_2:[],
list_3:[],
list_4:[],
list_5:[],
list_6:[],
}
这样会不会导致states占用内存很大？

**Comment by zuiidea** [comment]
是这样做，没毛病

**Comment by superlbr** [comment]
这是由于对于数据没有直观的概念，仔细观察http里的xhr请求，正常数据交互一个json小的可怜呐
