### ISSUE TITLE
Tomcat部署后报404错误，楼主，帮忙！

### ISSUE THREAD

**Issue by edwardxh** [zuiidea/antd-admin#505]
我把dist目录的内容部署到tomcat的ROOT目录中，但是无法打开页面，直接报404错误，请楼主帮忙看看。
打开的网址是：http://localhost:8080/login?from=/
错误信息如下：
HTTP Status 404 - /login
type： Status report
message： /login
description： The requested resource is not available.
Apache Tomcat/7.0.67

**Comment by zuiidea** [comment]
把所有的路由指向dist/index.html
https://github.com/zuiidea/antd-admin/issues/269

**Comment by edwardxh** [comment]
我也是刚刚开始学习react，不知道在哪里修改，请问是否可以举个例子？
