### ISSUE TITLE
初学React，请教一个登录问题。

### ISSUE THREAD

**Issue by caliven** [zuiidea/antd-admin#508]
使用mock数据时，登录成功后保存cookie是在mock/user.js文件中操作的，如果我不使用mock，使用代理请求后台接口登录成功后，如何在modules/login.js的login()中保存cookie了？这段代码：
`res.cookie('token', JSON.stringify({ id: user[0].id, deadline: now.getTime() }), {
        maxAge: 900000,
        httpOnly: true,
})`

**Comment by zuiidea** [comment]
这只是验证的一种方式而已，用什么方式验证取决于你和后端的约定，再修改相应代码即可

**Comment by caliven** [comment]
好，感谢

**Comment by jusheng** [comment]
请问有没有登录账号，上面没有注册，无法登陆

**Comment by zuiidea** [comment]
@jusheng  admin admin
