### ISSUE TITLE
项目慢慢变大，甚至页面有几十个到几百个的时候，model要如何组织更合理

### ISSUE THREAD

**Issue by pmg1989** [zuiidea/antd-admin#51]
![image](https://cloud.githubusercontent.com/assets/13361827/22237464/f1603800-e246-11e6-83e1-c393f07078e1.png)
我可能期望能达到这样的model结构，希望把model拆分细化，可以怎么组织代码结构，然后把细化的model重新合成新的model tree呢？

**Comment by liupeng110112** [comment]
@pmg1989 除了像demo使用路由的方式挂载 ，其他的方式试过么

**Comment by pmg1989** [comment]
你可以在connect(mapStateToProps)的时候，把细分的model作为mapStateToProps参数带入进去试试

**Comment by liupeng110112** [comment]
直接 require('../../models/alertTagsSet').state 然后把这个传进去么？

**Comment by pmg1989** [comment]
应该写你的各个model的命名空间的state

**Comment by liupeng110112** [comment]
@pmg1989 你那边有局部代码么？ 我这边试了下好像不行
![image](https://cloud.githubusercontent.com/assets/2655916/22238837/9415fdda-e24e-11e6-81db-6b60c68ecbc5.png)

**Comment by pmg1989** [comment]
你可以把require 换成 import 或者 require('./app').default();试试

**Comment by liupeng110112** [comment]
@pmg1989  试过了 import 是一样的 他的model导出的是对象 肯定不能执行，刚才改成路由的方式可以传进去，另外connect被 dva封装了一层，你那边试过拆分么？

**Comment by pmg1989** [comment]
你的alertTagsSet不是一个标准的dva model对象么

**Comment by liupeng110112** [comment]
![image](https://cloud.githubusercontent.com/assets/2655916/22239773/ffef2398-e252-11e6-815b-8faf590e4289.png)
是的 我路由的方式可以挂载上去 ，require的方式挂载不上去

**Comment by pmg1989** [comment]
我这边是可以的，dva装载model的时候，
// 2. Model
app.model(require('./models/alertTagsSet'))，这句你加了没

**Comment by kennir** [comment]
我也有这个问题，比如modal可能需要异步验证，会不会把验证的状态放在组件内部会更方便一点，state本身不推荐有太多层，扁平的结构也不太好管理

**Comment by pmg1989** [comment]
@kennir dva 不支持 combineReducer，所以state也只能扁平化了，这点用起来还是有点纠结的。个人感觉异步验证状态放在组件内部好像不太好，感觉放在model的effects会好点
