### ISSUE TITLE
现在npm install下来的ant 默认是英文的国际化,  怎么恢复成中文呢?

### ISSUE THREAD

**Issue by huerhai** [zuiidea/antd-admin#510]
https://ant.design/docs/react/i18n-cn 没有中文国际化的包~

**Comment by superlbr** [comment]
参考 https://ant.design/docs/react/i18n-cn

**Comment by superlbr** [comment]
@occultskyrong 
`import zh_CN from 'antd/lib/locale-provider/zh_CN';`
这个是ant design 3.0的内容，跟2.x不一样

**Comment by occultskyrong** [comment]
@superlbr 对啊。。。

我下边说了啊。。
这个repository的antd是2.13.11
而2.13.11的antd官方文档写的是
> antd 目前的默认文案是中文，如果需要使用英文或其他语言，可以参考下面的方案。

所以，并不存在title说的 
**现在npm install下来的ant 默认是英文的国际化, 怎么恢复成中文呢**

所以我问：谁动了我的中文。。。

查看项目里面。发现英文是因为整个项目本身就是用英文写的`placeholder`

0.0
