### ISSUE TITLE
如何将 项目名‘ant-admin’ 改成自己的项目名？

### ISSUE THREAD

**Issue by liuqiao1** [zuiidea/antd-admin#513]
我将文件夹的名字改为 'a', 同时将package.json 的name字段改成'a'.
运行 ：npm run dev 发现缺少了很多依赖，比如chalk, color-name等，但是这些依赖在原来的package.json 中就没有。
我以为只缺几个，试图手动安装，但是安装了五六个还没完。
我应该如何解决这个问题？

**Comment by liuqiao1** [comment]
我把项目删了，重新clone, 将文件夹的名字改为 'a', 同时将package.json 的name字段改成'a'.
居然可以了，但是还是不知道这其中的原因。

**Comment by zuiidea** [comment]
项目没有依赖这些包，是依赖的包依赖了这些，可能是某个包没有安装成功

**Comment by hllhui** [comment]
你先npm install完再去改名字吧
