### ISSUE TITLE
请教一下您在less 引用的别名方式是如何实现的

### ISSUE THREAD

**Issue by VanquisherMe** [zuiidea/antd-admin#514]
我看到了这一段
但是好像webpack 也没法支持  less里 别名是用了其他什么插件么
![f _igj7vgn _ywb8f tl](https://user-images.githubusercontent.com/4927398/29443500-0c4591cc-840b-11e7-85bd-ec07fdecd46a.png)

**Comment by zuiidea** [comment]
应该是roadhog里引用了less-loader

**Comment by VanquisherMe** [comment]
https://github.com/sorrycc/roadhog/issues/121#issuecomment-323101496
之前问过
说用babel-plugin-module-resolver
但是好像也没支持了less
roadhog 配置如上

**Comment by zuiidea** [comment]
less-loader 4之后可以的，使用`~`符号
https://github.com/webpack-contrib/less-loader

**Comment by VanquisherMe** [comment]
感谢！ 加一个webpack.config 配置alias 满足需求了，如果roadhog能开放 alias 配置就 更好了，不知道作者会不会考虑加上
