### ISSUE TITLE
如何在Apache上部署

### ISSUE THREAD

**Issue by LeoyangUp** [zuiidea/antd-admin#515]
Apache上部署需要如何设置？

**Comment by jiang223** [comment]
java上我试了好几次不行，最后改成up用的ngnix，然后路由分配调用java后台接口的。

**Comment by mapengze** [comment]
同问...如何部署dist到tomcat

**Comment by liaojuncong** [comment]
部署dist到ngnix后，login页面怎么弄呀，没整出来。

**Comment by superlbr** [comment]
nginx 参考 https://github.com/zuiidea/antd-admin/issues/641
apache 参考 https://gist.github.com/YW-Tseng/63c36ccb58a25a09f7096bbb602ac1de#step-3--deploy

**Comment by zhaozhuoguang** [comment]
记录一下apache2.4 的部署配置。PS：我也不懂，但亲测有效
httpd-vhosts.conf
<VirtualHost *:80>
  ServerName antd-admin.zuiidea.com
  DocumentRoot "${INSTALL_DIR}/www/antd"
  <Directory "${INSTALL_DIR}/www/antd">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require all granted
  </Directory>

  ProxyRequests Off
  ProxyPass /api http://localhost:7000/api
  ProxyPassReverse /api http://localhost:7000/api
</VirtualHost>

/www/antd/.htaccess
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
</IfModule>
