### ISSUE TITLE
在menu接口只有dashboard的情况下访问根域名内容区域提示404

### ISSUE THREAD

**Issue by Nuoky** [zuiidea/antd-admin#516]
排查了下，发现出现标题情况时， routes/app.js 下 current为空，且在代码默认情况下current获取的值也不正确。
![image](https://user-images.githubusercontent.com/24731549/29446844-0244d49c-8421-11e7-800b-11dbff7e6f57.png)

临时解决办法，在current前加上：
```
if(pathname == '/'){
    pathname = '/dashboard'
 }
```

**Comment by chenkang084** [comment]
我在我自己fork里面已经fix了这个。请参考
https://github.com/chenkang084/antd-admin/commit/e2119bb483bab83d88424001fc94ac5aa8f722fe

**Comment by superlbr** [comment]
这个应该修复过了，close
