### ISSUE TITLE
如何引入包？

### ISSUE THREAD

**Issue by hllhui** [zuiidea/antd-admin#517]
我想引入下面三个文件，在routes/app.js 内添加没有反应，应该怎么做？

<script type="text/javascript" charset="utf-8" src="ueditor/ueditor.config.js"></script>
      <script type="text/javascript" charset="utf-8" src="ueditor/ueditor.all.min.js"></script>
      <script type="text/javascript" charset="utf-8" src="ueditor/lang/zh-cn/zh-cn.js"></script>

**Comment by zuiidea** [comment]
我...
`webpack.config.js`中HtmlWebpackPlugin插件scripts属性
