### ISSUE TITLE
Build的时候报错

### ISSUE THREAD

**Issue by yinxuan1128** [zuiidea/antd-admin#519]
自己加了些代码进去，在开发服务器上运行没问题，但是一旦build，就报错，报错信息里也看不出问题出在哪里啊？
`Failed to compile.

EISDIR: illegal operation on a directory, open 'D:\MyWork\wisto-gallery\dist\0.5.0'

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wisto-gallery@0.5.0 build: `roadhog build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wisto-gallery@0.5.0 build script 'roadhog build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wisto-gallery package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     roadhog build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wisto-gallery
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wisto-gallery
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\MyWork\wisto-gallery\npm-debug.log`

**Comment by yinxuan1128** [comment]
已经解决了，是我的静态文件目录配错了，麻烦关闭吧，谢谢！

**Comment by blackboyhc** [comment]
@yinxuan1128 @zuiidea 我这里也出了这个问题，报错信息都一样，具体是什么解决的啊
