### ISSUE TITLE
model和mock如何组织的？

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#52]
[http://o79go0ik9.bkt.clouddn.com/aa.png](url)

[http://o79go0ik9.bkt.clouddn.com/bb.png](url)

如图 一直显示没有数据

您好 我这边 是把示例里面的users.js这个路由 外面包了一层 代码啥的 都木有改 然后就一直显示没有数据 我想问下应该怎么改呢？

**Comment by zuiidea** [comment]
可以看看最新的代码
