### ISSUE TITLE
关于nginx部署的问题

### ISSUE THREAD

**Issue by mapengze** [zuiidea/antd-admin#522]
D:\ss-work\sszz-admin\dist 这是dist的路径 D:\nginx-1.13.4这是ngx的路径 监听的是80端口
报500错误 配置跟作者的一样为啥我的不行
![image](https://user-images.githubusercontent.com/28557297/29502420-859a3c36-8662-11e7-8de6-5fd9db240dbf.png)

![image](https://user-images.githubusercontent.com/28557297/29502427-94c40282-8662-11e7-8f7a-ef4bcf734ff9.png)

**Comment by zuiidea** [comment]
root "D:\ss-work\sszz-admin\dist";

**Comment by mapengze** [comment]
@zuiidea 现在可以进去了 但是是不是每次需要电脑上跑一遍npm run dev 才行

**Comment by zuiidea** [comment]
自己好好看，找答案，这种问题真的不想回答了
