### ISSUE TITLE
关于4.3.2 BrowserHistory 转换成hashHistory的相关问题

### ISSUE THREAD

**Issue by chengwangping** [zuiidea/antd-admin#525]
由于BrowserHistory 需要服务端环境设置，所以我考虑换成 hashHistory，也看过其他issues，按照方法都去做了，遇到的问题是

1: 
我修改src/index.js 
![image](https://user-images.githubusercontent.com/5220595/29597429-15ff2e7e-87f5-11e7-86c9-63b333a57875.png)

或者去掉BrowserHistory 
![image](https://user-images.githubusercontent.com/5220595/29597457-3fe74eba-87f5-11e7-89c4-bad945460218.png)

得到的结论是无论我访问那个路由，都会出现
http://172.16.9.112:8000/login?from=/#/?_k=3x61wq
http://172.16.9.112:8000/login?from=/user#/?_k=x3hjat
我尝试去掉src/router.js 下的所有childRoutes  还是会跳转到/login
我想知道 默认路由地址在哪儿修改？

2 : 跳转到from指定地址的控制在哪个文件里面？ 后面跟得这些参数?_k=3x61wq是如何生成的？

3: 想得到的效果是  

http://172.16.9.112:8000/#/login?from=user
http://172.16.9.112:8000/#/user

**Comment by mapengze** [comment]
@chengwangping 你是不是想做到打包生成的文件直接打开？

**Comment by chengwangping** [comment]
是

**Comment by mapengze** [comment]
我跟你一样的疑问啊  加个扣一起讨论一下？ 57180484

**Comment by zuiidea** [comment]
看一下这个分支：https://github.com/zuiidea/antd-admin/tree/develop-hash
在`models/app.js`,`models/login.js`

**Comment by chengwangping** [comment]
好的

**Comment by chengwangping** [comment]
@zuiidea  好像稍微有点问题    
![image](https://user-images.githubusercontent.com/5220595/29601203-d343be20-880c-11e7-8e22-7917c19fd48e.png) 
用develop-hash 这个分支下的代码会出现这个问题 我的路由地址是login 对应的组件好像没加载进来

**Comment by zuiidea** [comment]
自己调一下吧

**Comment by weishijun14** [comment]
找了我老半天，总算找到正确处理hashhistory的方法了
