### ISSUE TITLE
【咨询】登陆状态

### ISSUE THREAD

**Issue by wanghao524151** [zuiidea/antd-admin#53]
为什么登陆后，刷新页面也不用登陆？实现的思路是？？？？

**Comment by zuiidea** [comment]
登录状态保存在cookie里了，有效期1天
![image](https://cloud.githubusercontent.com/assets/16070518/22328353/bb132ec2-e3f6-11e6-85be-39deb37fc6f1.png)

**Comment by wanghao524151** [comment]
谢谢回复，我是react的菜鸟，多多请教你
routes/app.js render是根据models/app.js里的state.login去判断的，没有读取Cookie值，那为什么登陆后再次刷新页面，没有登录框？刷新页面state值还是不变的？

我照着代码写，可以刷新页面还是需要登陆，不知道为什么？

**Comment by zuiidea** [comment]
是的，`models/app.js’里
![image](https://cloud.githubusercontent.com/assets/16070518/22363508/bd1107f8-e4a5-11e6-8660-9473475a5757.png)

**Comment by wanghao524151** [comment]
看懂了，谢谢过年也回复我
