### ISSUE TITLE
关于检测用户登陆状态

### ISSUE THREAD

**Issue by liuqiao1** [zuiidea/antd-admin#530]
在mock/user.js里可以看到：
`if (user.length > 0 && user[0].password === password) {
      const now = new Date()
      now.setDate(now.getDate() + 1)
      res.cookie('token', JSON.stringify({ id: user[0].id, deadline: now.getTime() }), {
        maxAge: 900000,
        httpOnly: true,
      })
      res.json({ success: true, message: 'Ok' })
    }`
意思是登陆成功就把用户信息存入cookie中，失效时间是900000.

另外还有一段判断cookie失效的代码：
 if (token) {
      response.success = token.deadline > new Date().getTime()
 }

我的问题是：系统在哪里调用了判断cookie失效的代码？

**Comment by superlbr** [comment]
1. cookie失效是浏览器执行的
2.  An expiration date or duration can be specified, after which the cookie is no longer sent. 参考 https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
