### ISSUE TITLE
ie11 登入是空白页

### ISSUE THREAD

**Issue by kevin0713** [zuiidea/antd-admin#535]
antn-admin 第一次登陆在IE11下面是空白的页面。
<img src="https://user-images.githubusercontent.com/13919688/29956947-2a907184-8f1d-11e7-8a9a-b1a9169eb9cb.png">

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/67b90c4df0e08512c740014b527f4842f5f3bcb2

**Comment by kevin0713** [comment]
thank you for your  help!
