### ISSUE TITLE
关于更改登录检测机制问题

### ISSUE THREAD

**Issue by qingjiaowochengzd** [zuiidea/antd-admin#537]
问题描述：
我们的需求是，登录有两种方式，一种是正常账号密码登录，另一种是支付宝授权登录：我们是这么做的，页面上点击按钮跳支付宝登录页面，用户输入账号密码，我们后台可以拿到支付宝是否授权的信息，然后调前台路由页面http://192.168.0.53:8000/vip/card?user_id=12131312&shop_id=123123
跳这个页面的目的是让我在vip/card页面上可以拿到id,依据id来直接拿到一些用户信息。
但是作者的路由会检测是否登录，后台跳我的路由页面的时候被登录验证给处理掉了，结果就是先跳了card页马上就跳回登录页。
还有个问题是我登录成功后应该是要localstorage存支付宝授权过期时间的吧，如果过期的话商户下次需要再次输入账号密码。我的这一步限制是要在哪里处理呢？

目前思路：
修改models/app.js:
if (data.success && data.user) {}
else{
      if (location.pathname === '/vip/card') {
          yield put(routerRedux.push('/vip/card'))
      }
}
改掉了else里面的逻辑，但是这样会有一个问题，我进去了card页面，但是我直接在页面上路由http://192.168.0.53:8000/vip/card直接就进去了....没有了登录验证

想达到的效果：
方式1登录没问题，方式2支付宝授权登录，如果登录成功跳我某个页面，跳过来的时候我们的后台要给我用户id、支付宝授权过期信息等，如果过期，商户需要再次登录。商户主动退出的时候我需要清掉授权信息。

**Comment by zuiidea** [comment]
根据需求来就可以了
