### ISSUE TITLE
关于引入antd-design组件在antd-admin的结合的问题。

### ISSUE THREAD

**Issue by cigarx** [zuiidea/antd-admin#539]
举例：比如antd-design用户列表中我想设置如下在antd-design中的一个组件，
https://codepen.io/anon/pen/xLBOVa?&editors=001
不仅想要达到这个组件的效果，还需要在点击达到用户列表中的搜索效果，怎么来实现呢？

**Comment by superlbr** [comment]
1. 点击到达，利用Checkbox的onChange事件，跳转到某url，并可以附上参数, 类似?user=2
2. 用户列表中的搜索效果，根据1中的url参数user, 在model中传入query即可
