### ISSUE TITLE
设置history 为 browserHistory，刷新页面后会报page not found

### ISSUE THREAD

**Issue by xiaosansiji** [zuiidea/antd-admin#54]
index.js中设置history 为 browserHistory：
`import { browserHistory } from 'dva/router'
const app = dva({
   history: browserHistory,
 })`

点击左侧菜单可以正确跳转到指定页面，URL也是browserHistory风格了，但在每个页面里刷新的时候就会找不到页面，这里还需要在什么地方设置吗？

**Comment by zuiidea** [comment]
我也试过，所以这里没有用`browserHistory`，需要讨论下

**Comment by miaoyinjun** [comment]
用browserHistory的话，需要服务端渲染吧

**Comment by xiaosansiji** [comment]
好吧，原来还有dora的这个插件dora-plugin-browser-history。。。
感谢@pmg1989，结案
相关修改[#82](https://github.com/zuiidea/antd-admin/commit/e03316423f627ae4c758b71f15f8cb5f1be50153)

**Comment by miaoyinjun** [comment]
使用了browserHistory，刷新会下载一个文件，请问怎么解决

**Comment by xiaosansiji** [comment]
@miaoyinjun 没太明白，是刷新后浏览器中自动下载文件吗？什么样的文件？

**Comment by miaoyinjun** [comment]
比较我访问home这个路由，就会下载home文件内容是index的内容

**Comment by xiaosansiji** [comment]
这个有点奇怪了，我建议你按照这次[#82](https://github.com/zuiidea/antd-admin/commit/e03316423f627ae4c758b71f15f8cb5f1be50153)commit的内容查一下，并不是只有router和index.js有修改，我这里改完以后是可以的。（最好重新编译一下）你试试看有没有问题，还不行的话晚点下班了改改我本地的工程，看什么情况下会有这种情况

**Comment by miaoyinjun** [comment]
补充下，我用的是index.ejs

**Comment by xiaosansiji** [comment]
啊~ 你用了ejs模板啊，这个我以前为了配合打包以后文件名里加的MD5后缀用过，如果你确定你修改的跟commit一致，可能是用模板搭配webpack里改文件名的姿势不对（如果有的话）

**Comment by miaoyinjun** [comment]
现在我将index.ejs修改为index.htnl，HtmlWebpackPlugin的注掉了，index.js修改了
`import './index.html';
import dva from 'dva';
import {browserHistory} from 'dva/router';
const app = dva({
  history: browserHistory,
  onError (error) {
    console.error('app onError -- ', error)
  }
});`

package.json
"start": "dora --plugins \"proxy,webpack,webpack-hmr,browser-history?index=/src/index.html\"",

重启访问发现浏览器的<div id="root"></div> 是空白

**Comment by miaoyinjun** [comment]
如果有时间，请帮忙解决下，谢谢
