### ISSUE TITLE
为什么全局less 要用:gobal包起来 是通过配置吗

### ISSUE THREAD

**Issue by fishmankkk** [zuiidea/antd-admin#545]

**Comment by jdwdw** [comment]
应该是为了做公共组件，如果没有用:global,在其他地方引入后会带一hash码，这样如果需要在当前页面使用该组件时就比较难去修改其样式了

**Comment by fishmankkk** [comment]
@jdwdw 我知道是为了公共组件 我想知道原理跟如何配置的 我用其他脚手架都没有这种写法 想了解原理

**Comment by jdwdw** [comment]
@fishmankkk 这个我也是参考antd组件的写法，因为webpack打包时用cssmodules，less文件打包后
具体可以看webpack官方文档
不带:global 后面会带hash例如：
(图片一直上传不了) 下面是两种情况
hash了的：class=" Component-Society-Common-EmptyDiv30---emptyDiv30---2eTyW"
加了:global 没有hash的：class="xy-society-common-stretchableView"

**Comment by zuiidea** [comment]
对，css modules

**Comment by jdwdw** [comment]
@fishmankkk  不好意思上面的语序有点乱而且这也是我自己写项目时总结的不知到是不是对的，我们可以大家研究一下。
这个我也是参考antd组件的写法，因为webpack打包时用cssmodules，less文件打包后
不带:global 后面会带hash例如：
(图片一直上传不了) 下面是两种情况
hash了的：class=" Component-Society-Common-EmptyDiv30---emptyDiv30---2eTyW"
加了:global 没有hash的：class="xy-society-common-stretchableView"
（具体可以看webpack官方文档）

**Comment by fishmankkk** [comment]
@jdwdw 好的 看了文档懂了😯谢谢

**Comment by jdwdw** [comment]
@fishmankkk 那就好了
@zuiidea 我是从你的这个项目开始学习的，现在dva出了2.0了，不知到你后面有没有把这项目去使用dva2.0重构的想法？

**Comment by mirkcale** [comment]
@zuiidea 请问下开启css modules只要css-loader配置吗 less-loader要不要另外配置
