### ISSUE TITLE
如何删除menu.js里的border bottom line

### ISSUE THREAD

**Issue by TangMonk** [zuiidea/antd-admin#55]
如图：

![image](https://cloud.githubusercontent.com/assets/3498786/22581612/5d5549ce-ea1c-11e6-930a-afb18867e9cd.png)

**Comment by zuiidea** [comment]
这里应该不是border，应该是横向滚动条

**Comment by TangMonk** [comment]
@zuiidea , 谢谢!

**Comment by TangMonk** [comment]
但是现在登陆界面和首页有点错乱了：

登陆界面显示一半：
![image](https://cloud.githubusercontent.com/assets/3498786/22589739/bc99063a-ea46-11e6-9ba5-fcf32414ddb4.png)


侧边栏超出：
![image](https://cloud.githubusercontent.com/assets/3498786/22589752/d793d334-ea46-11e6-8c6b-7d7c27710c44.png)

**Comment by zuiidea** [comment]
不好意思，可能是编辑器格式化的时候弄乱了，重新pull下就好了

**Comment by TangMonk** [comment]
谢谢！
