### ISSUE TITLE
关于less的模块导入语法

### ISSUE THREAD

**Issue by yangbin1994** [zuiidea/antd-admin#551]
```less
@import "~themes/default";
@import "~themes/mixin";
```
这种方式是webpack的配置还是less的语法呀，需要单独设置吗？

**Comment by zuiidea** [comment]
less-loader

**Comment by yangbin1994** [comment]
请问作者，你是在项目哪里设置了less-loader的[path](https://github.com/webpack-contrib/less-loader#less-resolver)选项呀，我在`webpack.config.js`没有发现啊

**Comment by yangbin1994** [comment]
原来是这段代码` themes: `${__dirname}/src/themes`,`嘎嘎，自己覆盖了半天的less-loader的options，囧~
