### ISSUE TITLE
本地开发使用代理proxy，上测试怎么去掉？

### ISSUE THREAD

**Issue by albafica2015** [zuiidea/antd-admin#554]
前后端独立上线部署，在本地开发的时候使用了代理proxy，前后端代码上传到同一个服务器同ip，要去掉这个proxy吗？那么本地代码应该怎么配置呢，能够上测试的时候自动去掉？另外我只需要上dist文件夹里面内容

**Comment by albafica2015** [comment]
"dev": "set BROWSER=none&&set HOST=0.0.0.0&&roadhog server",

这个 set HOST=0.0.0.0  是不是自己配置   test  uat  prod 的ip？

**Comment by zuiidea** [comment]
- 不需要去掉，具体看https://github.com/zuiidea/antd-admin/issues/348
- 仅在开发时，本机ip可直接访问
