### ISSUE TITLE
IE 11下面 modal框会偏移至最右方

### ISSUE THREAD

**Issue by kevin0713** [zuiidea/antd-admin#555]
IE 11下面 modal框会偏移至最右方? 我该如何处理这个兼容问题。
![tim 20170906120137](https://user-images.githubusercontent.com/13919688/30094022-cef6c2b4-92fb-11e7-88ef-9925264fc852.png)

**Comment by superlbr** [comment]
参考 https://ant.design/components/modal-cn/#components-modal-demo-position
flex not work in ie
