### ISSUE TITLE
webpack 多入口文件

### ISSUE THREAD

**Issue by zhangxiaoj** [zuiidea/antd-admin#556]
有的项目需要多入口文件配置，不知道如何将相应的入口对应相应的路由

**Comment by zuiidea** [comment]
多入口就不需要router了吧

**Comment by zhangxiaoj** [comment]
不知道怎么做，我就是为了引入百度地图，其他页面不加载地图

**Comment by superlbr** [comment]
Duplicate. https://github.com/zuiidea/antd-admin/issues/550
