### ISSUE TITLE
npm run build:dll 报错

### ISSUE THREAD

**Issue by QizhongFang** [zuiidea/antd-admin#557]
运行 npm run build:dll 报错。

## 操作步骤
npm -v
5.3.0

node -v
v8.4.0

git clone https://github.com/zuiidea/antd-admin.git

npm install

npm run build:dll 

报错：
[fangqizhong@fangqizongdeMBP antd-admin (master ✗)]$ npm run buid:dll
npm ERR! missing script: buid:dll

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fangqizhong/.npm/_logs/2017-09-06T05_37_27_176Z-debug.log
[fangqizhong@fangqizongdeMBP antd-admin (master ✗)]$ npm run build:dll

> antd-admin@4.3.4 build:dll /Users/fangqizhong/Projects/FrontEnd/Study/antd-admin
> roadhog buildDll

Creating dll bundle...
Failed to compile.

Module not found: Error: Can't resolve 'roadhog' in '/Users/fangqizhong/Projects/FrontEnd/Study/antd-admin'

## 问题
删掉 package.json 中 dependencies下的 "roadhog": "^1.2.1"后正常，dependencies和devDependencies里同时存在不通版本的roadhog？

**Comment by shcolo** [comment]
请问解决了吗？

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/blob/67b90c4df0e08512c740014b527f4842f5f3bcb2/package.json
