### ISSUE TITLE
IE11运行报错

### ISSUE THREAD

**Issue by old-wang** [zuiidea/antd-admin#561]
我把您的项目下载过来然后在win10 IE11下运行，报错：语法错误

**Comment by duwei54** [comment]
我也遇到了   貌似是roadhog的问题  连用dva-cli new 出来的新项目都无法在ie上跑

**Comment by superlbr** [comment]
1. 推荐使用yarn安装依赖
2. 实测可以跑
3. 先close，有问题可以继续issue，并请附上代码或者报错截图
