### ISSUE TITLE
关于 loading.effects

### ISSUE THREAD

**Issue by qwerasdfzxvv** [zuiidea/antd-admin#565]
我仔细阅读了你的代码，发现了几处都引用了：loading.effects 
例如：
confirmLoading: loading.effects['user/update']
loading: loading.effects['user/query'],
这个方法有什么作用吗？什么异步情况需要用它？

**Comment by shaomingming008** [comment]
loading是dva中的 这样写就相当于你请求接口的时候showloading  然后返回数据后再hideloading  这样写是让你省去每次都show和hide的步骤   正常的异步情况都可以使用   看接口的响应时间  如果很短也可以不使用    正常的用户体验是都要使用的

**Comment by superlbr** [comment]
参考 https://github.com/dvajs/dva/tree/master/packages/dva-loading
