### ISSUE TITLE
版本4.3.5 中用户画面翻页无效的问题

### ISSUE THREAD

**Issue by dong894** [zuiidea/antd-admin#575]
4.3.5 中user的model在query的时候使用的是location.search, 但是location.search是空的，导致翻页无效，在线demo也有这个问题，我改成使用location.query了，测试下来是可以的，我提交了一个PR，请确认一下是否可以这样改。

**Comment by yangbin1994** [comment]
https://github.com/zuiidea/antd-admin/pull/576

**Comment by dong894** [comment]
@yangbin1994 thanks，你的方案好，希望这个PR尽早合并。
