### ISSUE TITLE
刚升级到最新版本，发现Users的查询都没有提交查询参数，导致条件无法过滤

### ISSUE THREAD

**Issue by newnewcloud** [zuiidea/antd-admin#579]
刚升级到最新版本，发现Users的查询都没有提交参数，导致条件无法过滤

**Comment by newnewcloud** [comment]
dispatch(routerRedux.push({
        pathname: location.pathname,
        query: {
          ...value,
          page: 1,
          pageSize,
        },
      }))
就是这个dva的方法问题

**Comment by yangbin1994** [comment]
https://github.com/zuiidea/antd-admin/pull/576
