### ISSUE TITLE
chrome环境：LocalStorage中mock数据何时过期

### ISSUE THREAD

**Issue by xiaosansiji** [zuiidea/antd-admin#58]
在用mock造数据时发现修改mock中数据结构，此时重新编译，但浏览器中拿到的还是原来的数据结构，手动清缓存什么的也不好使，只有如下手动删掉这一条记录再重新请求才可以

![image](https://cloud.githubusercontent.com/assets/7600149/22616355/8e7e660a-eae6-11e6-8382-867253f00beb.png)
大家没有这样的问题吗？难道是我用mock的姿势不对。。。

**Comment by zuiidea** [comment]
额，姿势确实不对，具体可以参考这个文件`src/utils/mockStorge`，这里做的是先查询当前key的LocalStorage是否存在，如果有的话就用，就不会重新生成mock数据，如果需要调试只需要修改
`  global[key] = localStorage.getItem(key)
    ? JSON.parse(localStorage.getItem(key))
    : defaultValue`
为
`  global[key] = defaultValue`
