### ISSUE TITLE
如何断点debug .roadhogrc.mock.js中各个api接口的处理逻辑

### ISSUE THREAD

**Issue by peacesky** [zuiidea/antd-admin#584]
如何断点debug .roadhogrc.mock.js中各个api接口的处理逻辑？
经过各种方式尝试，也看了roadhog关于mock的源代码，但是仍没有找到比较好的方式来断点debug各个api接收到request后逐步解析payload并处理的逻辑的办法。
请问大家在这方面有没有什么实践经验？

**Comment by allinshang** [comment]
同求。。。

**Comment by LiuSuY** [comment]
别想了，哪里还有端点啊

**Comment by superlbr** [comment]
1. 如何断点 https://segmentfault.com/a/1190000005113673
2. 如何调试react https://github.com/facebook/react-devtools
3. 如何调试dva/roadhog http://react-china.org/t/reactjs/11753/10  https://github.com/dvajs/dva/issues/1085 https://github.com/dvajs/dva/issues/52
