### ISSUE TITLE
登录或者刷新页面，发现404的闪屏

### ISSUE THREAD

**Issue by newnewcloud** [zuiidea/antd-admin#586]
@zuiidea 今天更新了最新的master，发现一个404的闪屏，大体我分析了一下，是菜单权限的问题，menu的初始数据只有仪表页面，如果我在/user页面刷新，第一次渲染页码的时间就会出现hasPermission等于false，app.js中的代码段是{hasPermission ? children : <Error />}，当菜单请求返回后updateState后再次渲染页码，这个过程就会出现404的一个闪屏。

**Comment by isafe** [comment]
![snip20170925_1](https://user-images.githubusercontent.com/5019002/30784436-aff897d4-a11a-11e7-9df8-02b5f97732cc.png)

**Comment by newnewcloud** [comment]
编译后生产环境不会有这个问题

**Comment by superlbr** [comment]
Duplicate. https://github.com/zuiidea/antd-admin/issues/758
