### ISSUE TITLE
在开发环境中子路由页面没有问题，打包后用nginx和anywhere运行，子路由都报错

### ISSUE THREAD

**Issue by pfpGit** [zuiidea/antd-admin#588]

**Comment by samuelzuuka** [comment]
我也遇到了这个问题。这就是一个大坑。。。。antd 本身的路由是使用 #/ 来实现的单页面应用的，这个也是很常见的做法，。。。这个不知道为什么要另开旗帜改造成去掉 #/ 的，并且在这么重要的问题上没有任何说明出现在README 里面。。。。因为对于html 协议来讲，没有# 代表属于不同的html了，也就是属于多页面应用了，必须得有那个html文件才可以的，比如 /user , 所以这个超级大坑真不负责任。。。，本来也就没有几个页面可以使用，无非是免去了 dva 配置的一些事儿。。。有些基础的文件路径规范了下。。相比这个大坑来说。。真是相形见绌了。。。还好是个demo的。。这要是真实开发。。到了交付了用不了。。大大的差评。。。

**Comment by LayGit** [comment]
nginx 两行配置代码的事情，自己不会就不要乱喷，谁告诉你必须得有文件才行，作为一个合格的前端学的不止是一点点html和js。
`location / {
        index index.html;
         if (!-e $request_filename) {
            rewrite .* /index.html break;
        }
    }`
