### ISSUE TITLE
小建议调整折叠菜单开关和面包屑的位置

### ISSUE THREAD

**Issue by leijian** [zuiidea/antd-admin#59]
![image](https://cloud.githubusercontent.com/assets/2032390/22617323/e03515c8-eafc-11e6-91b1-7ec52a441b1f.png)
如图所示，建议位置2的折叠菜单开关调整到位置1，将位置3的面包屑调整到位置2，可以增大内容区。gitlab、bootstap admin lite等中后台模板就是这样设计的。

**Comment by zuiidea** [comment]
这个没好大必要哈，该了之后反倒不美观，如果实在有需求，可以自己去实现
