### ISSUE TITLE
部署后子路由刷新报错

### ISSUE THREAD

**Issue by pfpGit** [zuiidea/antd-admin#590]
刷新报这个错误，一开始以为是程序重定向问题，后面程序改成不重定向还是这个错

`An error occurred.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.`

nginx配置：
`        location / {
            root    D:\DEMO\vc\dist;
            index  index.html index.htm;
            try_files $uri $uri/ @router;
        }`

**Comment by yzzting** [comment]
`        location ~* html {
                 rewrite .* /index.html break;
                 root /usr/share/nginx/html/dist;
         }
`

将所有请求重定向到index.html
