### ISSUE TITLE
getComponent渲染延迟

### ISSUE THREAD

**Issue by lsdiao** [zuiidea/antd-admin#593]
在页面渲染开始之前会有段时间css没加载进来，导致可以看到无样式状态，外层套了个Loading 也是先显示无样式页面，再显示

Loading加载，请问有没有方法结局的，或者变更加载优先级？

![qq 20170906163818](https://user-images.githubusercontent.com/5077314/30365731-3ad4c0c2-989b-11e7-8638-cbab6798f78f.png)

**Comment by blackboyhc** [comment]
@zuiidea 我这里本地也有这个问题，但是看你发布的demo没这个现象，这是为啥？

**Comment by zuiidea** [comment]
编译后的没问题的，具体后面要看roadhog的解决

**Comment by superlbr** [comment]
Duplicate. https://github.com/zuiidea/antd-admin/issues/758
