### ISSUE TITLE
What does the tilde (~) mean between background-image and url(...) ?

### ISSUE THREAD

**Issue by rockallite** [zuiidea/antd-admin#597]
There's a tilde (`~`) here:
https://github.com/zuiidea/antd-admin/blob/b8162060cd43d839d469ad61e926003853b606d1/src/routes/dashboard/components/user.less#L10

I googled a lot and found nothing about this. Would you please explain the meaning of it?

**Comment by superlbr** [comment]
less语法，转义，参考https://www.w3cschool.cn/less/escaping.html
