### ISSUE TITLE
重复渲染问题

### ISSUE THREAD

**Issue by defolly** [zuiidea/antd-admin#599]
打断点试了一下，每次打开菜单，都会多次重复渲染。其实第一次渲染页面就出来了
![image](https://user-images.githubusercontent.com/10161473/30517886-067ffcc6-9ba0-11e7-8dcf-d17e9d492cf2.png)

**Comment by doterme** [comment]
我也遇到了

**Comment by fkpwolf** [comment]
https://github.com/dvajs/dva-example-user-dashboard/issues/25 一样的问题。

**Comment by cdhjava** [comment]
1、左侧菜单是树形目录，需要递归遍历，老是重复渲染，在i3低配置的笔记本上，根本就是卡死
2、根路由同级除了/  还会有 /login什么的，然后左侧菜单点击时，右侧的路由视图更新，而不是App.jsx重复渲染，卡卡的

**Comment by superlbr** [comment]
菜单这种不经常变动的，可以缓存，或者间接生成。这一点，我觉得ant-design-pro 好些，但是界面没有这个好看，吐槽。

**Comment by quanpower** [comment]
同样碰到一个页面渲染若干次，尤其是用了setInterval定时刷新的页面更不得了了，直接干爆

**Comment by superlbr** [comment]
1. 渲染是浏览器的行为
2. 一个页面加载完了，是不是就不渲染了呢？错，浏览器一直在渲染
3. 为什么感觉到了多次渲染/闪屏？因为数据更新了，react.render重新返回了jsx元素
4. 所以有loading、预加载块样式
