### ISSUE TITLE
菜单与路由状态不同步。

### ISSUE THREAD

**Issue by zhump** [zuiidea/antd-admin#6]

**Comment by zuiidea** [comment]
不是很懂说什么啊

**Comment by zhump** [comment]
就是点击一个左侧菜单链接，这个标题链接高亮，并且路由发生变化，页面切换。此时再刷新页面，虽然页面跟路由对用，但是菜单不会高亮了。。

**Comment by zuiidea** [comment]
嗯，这个可以改

**Comment by zhump** [comment]
估计 菜单的状态要给models管理了，，不过2，3天代码敲下来，觉得react真的好吗，要不是antd的组件库，我绝壁不想用react啊，简单应用 写起来太复杂了  建store 指向组件的 prop  state ,然后通过 dispatch 掉 异步/同步的 action 去修改store ，  复杂的应用 真tm的太复杂了，动不动 重复render 每个组件都得判空，还要考虑性能，脑袋绷着一个弦在写代码 ，擦 太累了，就是跟楼主牢骚一下，，，

**Comment by zuiidea** [comment]
嗯，现在上班，公司的项目用的react，没dva，也没redux，也不是单页面应用，敲得挺开心的😂，

**Comment by zhump** [comment]
https://github.com/dvajs/dva/issues/348
这个问题 楼主碰到过吗？

**Comment by zuiidea** [comment]
@zhump 菜单那个提了哈
