### ISSUE TITLE
帅哥能否给咱们这些开发后端的指条明路。

### ISSUE THREAD

**Issue by phproot** [zuiidea/antd-admin#60]
：）

这套后台前端非常不错，帅哥作者能否帮咱们这些开发后端又想自己做点小东西的小伙伴们指条明路呢？

真搞不明白这个数据如何与后端API进行捆绑。
也就是：如何从第三方接口或自己的接口中得到数据呢。

有没有捆绑后的例子、教程啥的吗？哪怕只给一个登陆的例子也行呀。

**Comment by zuiidea** [comment]
![image](https://cloud.githubusercontent.com/assets/16070518/22626748/cd5f6fa4-ebef-11e6-9705-59c6f8e8596d.png)
首页那个天气卡片就是调的第三方接口哈，
如果是正式环境可以参考这个https://github.com/zuiidea/antd-admin/issues/44#issuecomment-277150744

**Comment by phproot** [comment]
非常感谢！去研究一下：）
