### ISSUE TITLE
facebook的开源协议问题是不是有影响？还会继续更新吗？

### ISSUE THREAD

**Issue by albafica2015** [zuiidea/antd-admin#601]
facebook的开源协议问题是不是有影响？还会继续更新吗？

**Comment by wangbagang** [comment]
同问！

**Comment by SynChron1zed** [comment]
![image](https://user-images.githubusercontent.com/18717051/30581942-7d20eb0a-9d54-11e7-9fa2-fb0d620af7ec.png)

**Comment by zuiidea** [comment]
又改回来了....
