### ISSUE TITLE
升级dva2.0后分页url 地址不发生变化的问题

### ISSUE THREAD

**Issue by szwork2013** [zuiidea/antd-admin#609]
升级到dva2.0后，分页url 地址不发生变化，内容正常。比如第2页不会显示：http://antd-admin.zuiidea.com/post?page=2&pageSize=10，而是永远显示http://antd-admin.zuiidea.com/post
问了作者 @sorrycc 他认为是不支持browserHistory,其实不是这个原因，我测试了browserHistory，hashHistory和memoryHistory都不行。把ConnectedRouter修改为Router 后其实在大多数浏览器是正常的，在ios微信环境下问题依然存在。请大家看看。谢谢@zuiidea

**Comment by szwork2013** [comment]
找到原因里，只要浏览器不支持标准的H5 API: history.pushState ,就会出现问题，万恶的微信根据升级的版本不一样，bug 反复重现。

**Comment by szwork2013** [comment]
与dva版本无关

**Comment by albafica2015** [comment]
怎么升级到 dva 2.0

**Comment by superlbr** [comment]
貌似最新版本没有这个问题
