### ISSUE TITLE
用户管理界，面点击打开弹框时，若有异步请求时会闪屏

### ISSUE THREAD

**Issue by pmg1989** [zuiidea/antd-admin#61]
用户管理界面，点击打开弹框时，若有异步请求（如请求需要修改ID的详情数据）时会闪屏，弹框会重复打开，可有修复方案？

**Comment by jasminecjc** [comment]
这个问题你怎么解决的 @pmg1989

**Comment by zuiidea** [comment]
@jasminecjc  https://github.com/zuiidea/antd-admin/commit/839a7c5e0d76875325e86427fe85bf6ba26aebad#diff-c5aac5b7407f4d56a48056bdb9280092

`{modalVisible && <Modal {...modalProps} />}`
