### ISSUE TITLE
如何部署到服务器上添加二级域名的问题

### ISSUE THREAD

**Issue by shaomingming008** [zuiidea/antd-admin#612]
服务器上不能直接访问根目录  要设置二级目录   项目中那些跳转路由怎么实现   是一个个写死吗

**Comment by zuiidea** [comment]
server
	{
		listen       80;
		server_name test.zuiidea.com;
		root  /home/www/antd-admin/dist;

		location /api {
			 proxy_pass http://localhost:8000/api;
		}

		location / {
				index  index.html;
				try_files $uri $uri/ /index.html;
		}
	}
