### ISSUE TITLE
开源 antd-admin java 后台解决方案

### ISSUE THREAD

**Issue by javahuang** [zuiidea/antd-admin#613]
演示地址 
<http://114.215.47.214:8080/> _admin/hello_

项目地址
[antd-admin-springboot](https://github.com/javahuang/antd-admin-springboot)
主要特性

- 具有 antd-admin 前端的全部特性
- 开发简单，同时启动前后端服务即可，配置了 proxy，所有 restful 请求会自动代理到后台
- 部署简单，前端执行 `npm run build` 之后将 dist/ 目录下面的全部内容拷贝到 java 的 static 目录直接打 war 包就可以部署，无需额外修改其他配置

希望对大家有帮助

**Comment by jasonperk** [comment]
真不错，👍一个，支持
