### ISSUE TITLE
这个怎么使用 React Developer Tools

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#62]
chrome浏览器装了 React Developer Tools这个插件
但是在控制台区域点击react react左侧区域就一直闪烁 无法捕捉组件 该怎么办呢？
求大神指教

**Comment by zhangolve** [comment]
![qq 20170207141548](https://cloud.githubusercontent.com/assets/7566337/22679822/ce83ac00-ed3f-11e6-8506-d4c65254f298.png)

我这边是没有问题的，所以不是react插件的问题，也不是项目本身的问题，你可以再排查一下吧。

**Comment by dicklwm** [comment]
升级你的插件版本吧，你插件版本过低就会闪烁，用最新的插件
