### ISSUE TITLE
查询分页Bug

### ISSUE THREAD

**Issue by toutouli** [zuiidea/antd-admin#626]
比如查询2017年创建的用户
出来的数据一共有两页
这时如果点第二页，看到的并不是2017年的数据
而是所有数据第二页的内容

**Comment by allinshang** [comment]
如何解决的呢

**Comment by Orecic** [comment]
同问

**Comment by zuiidea** [comment]
查询的时候把页码重置为1

**Comment by allinshang** [comment]
@zuiidea 查询的时候把页码重置为1
怎么理解呢？求解。

**Comment by allinshang** [comment]
没人遇到这个问题么？求解呢

**Comment by zuiidea** [comment]
```
    onFilterChange (value) {
      dispatch(routerRedux.push({
        pathname: location.pathname,
        query: {
          ...value,
          page: 1,
          pageSize,
        },
      }))
    },
```

貌似现在没问题吧

**Comment by allinshang** [comment]
@zuiidea 不行呢。
假如：查询条件Search Name 使用D,请求地址如下：
http://antd-admin.zuiidea.com/api/v1/users?name=D&page=1&pageSize=10
接口返回：有66条数据，分7页
在当前状态点第二页，请求的地址为：
http://antd-admin.zuiidea.com/api/v1/users?page=2&pageSize=10
这样查询Search Name为D的数据，就没有办法查看除第一页以为的数据了。。

**Comment by ly809652226** [comment]
同问，找到解决的办法了吗

**Comment by njzyt2010** [comment]
字段放到state里， 分页查的时候 ，参数从state 里取

**Comment by allinshang** [comment]
@njzyt2010，能详细解答下么？
是需要修改这个组件么？
![image](https://user-images.githubusercontent.com/914579/34331628-7b467362-e963-11e7-9c16-61f6e14adcd5.png)
谢谢

**Comment by allinshang** [comment]
@njzyt2010，能详细解答下么？

**Comment by allinshang** [comment]
管理员最新的代码，已经解决了这个问题啦。大家可以看看。
