### ISSUE TITLE
dllPlugin config not found in .roadhogrc

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#627]
when I run the npm run build:dll, it gives following error 
`dllPlugin config not found in .roadhogrc
`
`npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dll"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! antd-admin@4.3.8 build:dll: `roadhog buildDll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the antd-admin@4.3.8 build:dll script 'roadhog buildDll'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     roadhog buildDll
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd-admin
npm ERR! There is likely additional logging output above.`
node version - v7.6.0

**Comment by superlbr** [comment]
对比下.roadhogrc，估计你下面少了两行

**Comment by malinda1986** [comment]
@superlbr  thanks, that was due to the permission issue
