### ISSUE TITLE
关于atool-build打包文件数量限制

### ISSUE THREAD

**Issue by mtboom** [zuiidea/antd-admin#63]
请问能不能将打包文件的js打包成一个文件而不是0.js-x.js这种多文件
打包成多文件后,html文件和js文件就无法分开放置,
类似
/views/index.html
/js/index.js
这样分开放以后就会报0.js 找不到的错误

**Comment by miaoyinjun** [comment]
项目搜索关键字require.ensure，再看下 webpack的Code Splitting方面的就解决了
