### ISSUE TITLE
npm run build  内存溢出 

### ISSUE THREAD

**Issue by LDD123** [zuiidea/antd-admin#631]
node 6.10.3   npm run build 报内存溢出，目前有82个依赖文件
![image](https://user-images.githubusercontent.com/11335860/31592756-1957b7f2-b25d-11e7-8c2f-c36f1cd642c8.png)
![qq 20171016103144](https://user-images.githubusercontent.com/11335860/31592789-45cb56a4-b25d-11e7-8cc5-26bd2b4f629d.png)

**Comment by FatFatFox** [comment]
和你一样。模块一写多了，8G内存的macbook pro打包就会内存溢出。即使升级最新npm也是如此。
1.干掉router.js里的一些开发好的模块，就没有问题。
2.找了台16G内存的macbook pro打包，可以通过。
这不科学

**Comment by LDD123** [comment]
你怎么解决的？删掉了一些功能呢模块？我的这个用了4台机子测试，好像只有一台偶尔可以通过，其他的都是内存溢出

**Comment by FatFatFox** [comment]
我用方案2解决的。。

**Comment by LDD123** [comment]
@FatFatFox 不对啊，node.js 在windowsx64上好像默认给了1.7g的内存。换大内存的好像node.js还是默认那么大内存啊
我在网上查的  ，在\node_modules\roadhog\bin\roadhog.js 里面修改#!/usr/bin/env node为#!/usr/bin/env node --max_old_space_size=4096   来增加node内存，好像没起作用

**Comment by FatFatFox** [comment]
我不知道默认给了多少内存，事实就是如此：16G的可以build成功，8G的内存溢出。

**Comment by LDD123** [comment]
@sorrycc @FatFatFox  不知道这种问题该如何解决，耗得内存太大了。我现在还卡着呢

**Comment by jindada** [comment]
@LDD123 https://lweiwei.com/view/597fd3cb28b8073aea2a697d

**Comment by LDD123** [comment]
@jindada 这个我搜过了，不知道为什么，按照他写的不好使，后来使用的roadhog build --debug      这样打包的时候把代码没有压缩，就过了，感觉这样解决好牵强，有没有比较好的办法

**Comment by jindada** [comment]
试试下面这个那 这种情况我没实际遇到过 只是偶然看到过
```bash
node --max_old_space_size=4096 ./node_modules/roadhog/bin/roadhog.js build
```

**Comment by FatFatFox** [comment]
@jindada 谢谢了，有效！

**Comment by daizhikai** [comment]
我也遇到了，困扰很久了，目前也是暂时用jindada说的那种方法解决，但是打完包真大啊，总共85M！

**Comment by jindada** [comment]
@daizhikai 可以想办法优化 网上很多教程的

**Comment by LDD123** [comment]
@daizhikai     这样试试
node --max_old_space_size=4096 ./node_modules/roadhog/bin/roadhog.js  --build

**Comment by LDD123** [comment]
现在在他的roadhog下的配置文件，加了  sourcemap:false;   不让他生成map树，减少了内存使用，没有使用--debug,现在能够成功编译了

**Comment by mr-zhangyuan** [comment]
> @jindada 这个我搜过了，不知道为什么，按照他写的不好使，后来使用的roadhog build --debug 这样打包的时候把代码没有压缩，就过了，感觉这样解决好牵强，有没有比较好的办法

厉害，我找寻了两天终于解决了。给你点个赞👍，比个小星星✨。 roadhog build --debug
