### ISSUE TITLE
关于加入了二级目录，登录的问题

### ISSUE THREAD

**Issue by shaomingming008** [zuiidea/antd-admin#634]
部署到服务器上加了二级目录。登录界面会变成这样
![image](https://user-images.githubusercontent.com/22759207/31612200-8cb656fa-b2b1-11e7-9332-96a9875d6fcc.png)
不再是单独的页面了   被头部 底部  菜单包围了   变成了一般的菜单页了   哪位大神指导下

**Comment by wkm-wangZhe** [comment]
我也有这个问题   关注下

**Comment by javahuang** [comment]
参见[正确方式](https://github.com/dvajs/dva/issues/1497#issuecomment-361496046) 添加二级目录
