### ISSUE TITLE
开发环境下渲染时闪屏问题

### ISSUE THREAD

**Issue by taoyage** [zuiidea/antd-admin#635]
在开发环境下css文件为什么没有自动打包到index.css中去加载，而是一个一个的加载，而且是在页面渲染后才加，导致渲染被阻塞，出现闪屏的问题。
换了less后就出现了这个问题，我是直接用的roadhog来启动的，是不支持less还是什么问题呢，求教

![2017-10-18 10 49 18](https://user-images.githubusercontent.com/7186771/31698831-1c1d734a-b385-11e7-8e8f-3d9e431a29be.png)

**Comment by Stoneleee** [comment]
是404闪屏么？
我遇到的是开发环境下，刷新页面，出现404闪屏的情况，不知道什么原因呢，闪一下就恢复正常

**Comment by superlbr** [comment]
其实不算白屏啦，不是loading就是404，开发环境嘛，代码改动都会触发渲染

**Comment by superlbr** [comment]
Duplicate. https://github.com/zuiidea/antd-admin/issues/758
