### ISSUE TITLE
How is login page rendered?

### ISSUE THREAD

**Issue by cihadturhan** [zuiidea/antd-admin#636]
Sorry, I don't know any Chinese. Hope you know English enough to help me about it.

In router.js page, I see https://github.com/zuiidea/antd-admin/blob/master/src/router.js#L74
all the subpages (including login) are at the same level in the router. How come login page doesn't have sidebar, header but the other ones have?

If it would be like: 
```jsx
  <ConnectedRouter history={history}>
      <App>
        <Switch>
          <Route exact path="/" render={() => (<Redirect to="/dashboard" />)} />
          {
            routes.map(({ path, ...dynamics }, key) => (
               ...
            )
          }
          <Route component={error} />
        </Switch>
    </App>
    /* Same level with app */
    <Route exact path={'login'} component={dynamic({app, ...}) />
  </ConnectedRouter>
```
then I can understand `App` and `Login` are at the same level so all header, footer, sidebar will be inside `App` component. However, I can't understand how it works in your code.

Thanks in advance,

**Comment by zuiidea** [comment]
There are some options in [src/utils/config.js](https://github.com/zuiidea/antd-admin/blob/master/src/utils/config.js),`openPages` will be filtered in [src/routes/app.js](https://github.com/zuiidea/antd-admin/blob/master/src/routes/app.js) as follows


```
  if (openPages && openPages.includes(pathname)) {
    return (<div>
      <Loader fullScreen spinning={loading.effects['app/query']} />
      {children}
    </div>)
  }
```

**Comment by cihadturhan** [comment]
Oooh I totally missed that. Thanks
