### ISSUE TITLE
访问后端数据时cookie丢失

### ISSUE THREAD

**Issue by zhonglaoban** [zuiidea/antd-admin#638]
//代理如下
proxy: {
    "/api": {
      "target": "http://172.16.3.55:7890/smart/api/",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  }

**Comment by superlbr** [comment]
你直接访问ip呢，估计是跨域了吧

**Comment by superlbr** [comment]
No more info. Close
