### ISSUE TITLE
阿里云虚拟主机怎么配置nigx呀！！

### ISSUE THREAD

**Issue by mokennnnn** [zuiidea/antd-admin#641]
纠结了一大天了，有谁知道解决过或者知道解决方案的吗！~
谢谢各位

**Comment by xudihui** [comment]
兄弟，你应该去找阿里云客服啊

**Comment by superlbr** [comment]
1. npm install -g serve
2. serve -s dist路径
3. 然后nginx把location /请求都到1337端口

**Comment by superlbr** [comment]
另参考 https://github.com/zuiidea/antd-admin/issues/269
