### ISSUE TITLE
前端小白，想问一下顶部的浏览器进度条是哪里控制显示的，还是组件里面已经将其封装好了？

### ISSUE THREAD

**Issue by wlkfec** [zuiidea/antd-admin#644]

**Comment by dkvirus** [comment]
在 package.json 中有个 npm 叫 nprogress，在代码中是在 app.js 中有使用，关于 dva-loading 和 nprogress 的实践用法，可以参考 [dva-loading + nprogress 用法](http://www.jianshu.com/p/61fe7a57fad4)
