### ISSUE TITLE
随便指定一个端口启动，都提示已占用

### ISSUE THREAD

**Issue by basicfu** [zuiidea/antd-admin#645]
mac系统
1.随便指定一个端口启动，都提示已占用
![image](https://user-images.githubusercontent.com/26153901/32093222-337d8f28-bac1-11e7-9fe2-408874556287.png)
如果选择是启动后
![image](https://user-images.githubusercontent.com/26153901/32093563-54f2eb8e-bac2-11e7-8785-a841f64e144a.png)
也没有指明端口
命令`lsof -i:8000`并没有发现端口被占用，哪个端口都不行
我在linux下尝试可以直接运行，请问mac下需要怎么修改
2.将默认的dev修改为`set PORT=8866&&set BROWSER=none&&set HOST=127.0.0.1&&roadhog server` 可以启动成功，但是自定义端口无效

**Comment by weishijun14** [comment]
8001

**Comment by zuiidea** [comment]
```
# OS X, Linux
$ PORT=3000 roadhog server

# Windows (cmd.exe)
$ set PORT=3000&&roadhog server

# Or use cross-env for all platforms
$ cross-env PORT=3000 roadhog server
```

https://github.com/sorrycc/roadhog

**Comment by srw4115** [comment]
在系统host文件里面配置 127.0.0.1 localhost 后，配置指定端口冲突的问题解决了
