### ISSUE TITLE
menu中没有注册的页面Link访问报404

### ISSUE THREAD

**Issue by Yufeikang** [zuiidea/antd-admin#646]
例如 menu中有个页面 order搜索，搜索到的结果orderList。点击某一项显示orderDetail。因为orderDetail没有注册在menu里面，但是在router里注册了。无法访问，报404

**Comment by koupeng** [comment]
是，，，我也遇到这个问题了，按照目前的逻辑，是不是所有的界面都需要注册到menu里才行~~~

**Comment by malinda1986** [comment]
faced the same issue, if there is new URL path, it needs to be added to the router as well as menu

**Comment by namoweixiao** [comment]
@koupeng @Yufeikang 在routes/app.js里有判断的
