### ISSUE TITLE
怎么在代码里模拟刷新整个界面

### ISSUE THREAD

**Issue by koupeng** [zuiidea/antd-admin#647]
你好，怎样在代码里模拟刷新整个界面。效果同手动点击浏览器的刷新按钮一致！！谢谢

**Comment by koupeng** [comment]
![image](https://user-images.githubusercontent.com/6110684/32140323-8593bec6-bc98-11e7-96e9-9b50c441548c.png)

**Comment by zuiidea** [comment]
`window.location.reload()`
 ???

**Comment by koupeng** [comment]
谢谢~~~
