### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by prionkor** [zuiidea/antd-admin#648]
I really like antd-admin. But I am not familiar with the design pattern you have used here. dva is all new to me and there is not much documentation available. Would like to have some direction how to start using this pattern.

Love your work! Keep up the great work. Thank you!

**Comment by zuiidea** [comment]
http://pro.ant.design/docs/getting-started

I recommend you `Ant Design Pro`，It's very similar to `antd-admin`

**Comment by jasonperk** [comment]
Here is the documentation for the DVA project
https://github.com/dvajs/dva

**Comment by prionkor** [comment]
Thank you! Very helpful!
