### ISSUE TITLE
多层次页面跳转问题

### ISSUE THREAD

**Issue by koupeng** [zuiidea/antd-admin#652]
请问，比如我有一个这样的需求，实现三个层次的页面跳转，且携带参数。
比如：
第一个界面：展示班级。路由/classes
第二个界面：展示某个班级的学生。/classes/id/students
第三个界面：展示某个学生的成绩。/classes/id/students/id/socres
==================================
我的需求是：只能从班级-->查看某个班级的学生--->查看某个学生的成绩。
我应该怎样设计？

**Comment by koupeng** [comment]
我遇到的问题是，必须注册三个菜单到menu里，否则无法跳转。我是下面这样跳的。。。
dispatch(routerRedux.push({
              pathname: '/storms/topodetails',
              summary: {
                topoId: id,
                topoName:text
              },
            }));

**Comment by superlbr** [comment]
问题描述不清楚。感觉您已经解决问题了不是嘛？路由可以灵活些，不一定要那么长呀
