### ISSUE TITLE
怎样定时刷新？

### ISSUE THREAD

**Issue by koupeng** [zuiidea/antd-admin#654]
怎样定时刷新？

**Comment by koupeng** [comment]
@zuiidea 你好，需要帮助~~~应该怎样定时刷新？我尝试使用setTimeout或者setInterval，倒是可以定时刷新。可是没法控制clear,,,总是越来越多的后台刷新在累加。希望帮忙给个方案~~~
==========================================
需求就是一个页面，可以定时拉取数据。

**Comment by koupeng** [comment]
sorrycc给的回复解决了我的疑问：
可以在 effect 里写个无限循环，比如：

while (true) {
  yield fetch(data);
  yield delay(300);
}
然后，你可以需要适时地关闭或者开启他，可以在 state 里加个开关。比如：

while (true) {
  const enableFetch = yield select(state => state.namespace.enableFetch);
  if (enableFetch) {
    yield fetch(data);
  }
  yield delay(300);
}

**Comment by qingjiaowochengzd** [comment]
while (true) {
        if (enableFetch) {
          yield put({ type: 'getsynchrolist', payload: { filter: { page: 1, per_page: 10 } } })
        }
        yield delay(10000)
      }
你好，我执行的是put，但是计时器一触发就狂刷，enableFetch改为false了也没用
