### ISSUE TITLE
  const { locationPathname } = yield select(_ => _.app)    求解 这一步的意思

### ISSUE THREAD

**Issue by wkm-wangZhe** [zuiidea/antd-admin#655]
yield select(_ => _.app )  意思是选取 state 中的值   
 但是 app .js 的state中  没有 ( _ => _.app)  这个值 

可否讲一下 effects 中 * query     的  业务流程

**Comment by lovemegowin** [comment]
hello  我也看到这行代码了  看到你自己关闭了这个issues 应该是自己理解了 能告诉我下吗？

**Comment by superlbr** [comment]
@lovemegowin 这里_是简写，其实就是state
参考 [dvajs文档](https://dvajs.com/knowledgemap/#effects)
