### ISSUE TITLE
判断用户未登录跳转到登录页面  这段代码在哪

### ISSUE THREAD

**Issue by blackholll** [zuiidea/antd-admin#659]
"校验是否登录，如果没登陆就跳转登录页面"    这段代码在哪里？ models/app.js？ 没找到，前端比较菜，可以指出下是哪段代码么？
我试了将登录接口通过proxy指向自己的后端代码，返回和mock里面相同格式的内容。登录后浏览器端会请求/user、   /dashboard等接口，这个是根据登录http状态200就会请求这几个接口么？这块逻辑代码在哪里？
非常感谢

**Comment by koupeng** [comment]
![image](https://user-images.githubusercontent.com/6110684/32415115-385cca08-c26f-11e7-86a1-9d08f4a9d7bd.png)

**Comment by blackholll** [comment]
thx

**Comment by allinshang** [comment]
请问有登录时间的限制么？

**Comment by zuiidea** [comment]
登录时间的限制并不重要，这只是一个mock，换成真实数据，登录失效由后台控制啊

**Comment by llh1187** [comment]
> thx

你好，请问一下，你的问题是哪里有‘判断用户未登录跳转到登录页面’的代码，但是那个哥们给出的答案是登陆成功后跳转到仪表盘的代码，请问你是礼貌地说thx还是我没有看懂那哥们给出的代码:cry:
