### ISSUE TITLE
关于.roadhogrc的问题，是否与dva版本有关？

### ISSUE THREAD

**Issue by phproot** [zuiidea/antd-admin#66]
.roadhogrc中可以设置proxy。在开发过程中可以使用：

``` 
 "proxy": {
    "/api": {
      "target": "http://URL",
      "changeOrigin": true,
      "pathRewrite": {
        "^/api": ""
      }
    }
  }
```

http://127.0.0.1/api/users 等于 http://URL/users

这样在生产环境中，可以比较方便的与后端进行结合。但是antd-admin好像不支持这样的设置。不知道是不是和dva版本有关呢？

**Comment by phproot** [comment]
我看到了antd-admin 3.1版本是支持.roadhogrc的。3.1版本是否可以用于生产？

**Comment by zuiidea** [comment]
并不可以，老是报错，有空的时候再搞

**Comment by phproot** [comment]
加油！

**Comment by zuiidea** [comment]
#164
