### ISSUE TITLE
重置Tab控件上的样式的问题

### ISSUE THREAD

**Issue by jackieyangyi** [zuiidea/antd-admin#660]
Tab里面有样式
.ant-collapse > .ant-collapse-item > .ant-collapse-header
我想下一个样式覆盖它里面的padding值
想把顶部底部调小一些

发现根本找不到地方绑定样式

请问有解决的方式吗？

**Comment by superlbr** [comment]
1. themes中index.less可以加上样式去覆盖
2. react 元素都可以加上style属性去覆盖样式
