### ISSUE TITLE
BackTop无效

### ISSUE THREAD

**Issue by koupeng** [zuiidea/antd-admin#663]
BackTop这个到底怎么用，能不能给个例子？看到有人提了issue,,他的回答还是不行~

**Comment by asthon2017** [comment]
我遇到的事浏览器滚动事件无效

**Comment by zuiidea** [comment]
https://github.com/zuiidea/antd-admin/commit/6ba75de5764bbe20180b04211d51d735dbdf8fcc
因为main设置了高度，所以滚动条在main上
