### ISSUE TITLE
关于antd-admin的URL路径的请教

### ISSUE THREAD

**Issue by htlhenry** [zuiidea/antd-admin#666]
hello,
  我最近看了antd-admin的项目代码，看到您这边是用localStorage存储的Sider的openKeys。这种方式比如我把`http://antd-admin.zuiidea.com/chart/ECharts`这个链接分享给别人，别人localStorage没有保存这个，或者别人的保存的是别的，这样的话组件的状态就和URL路径不同了，看着稍微有些瑕疵。
  因为我最近在想把URL路径通过route组件可选参数传到容器组件中，这样URL和state就关联在一起了，但是在subscription中又没有直接拿到match的方法，所以请教下您这边又没有相关的栗子。

**Comment by zuiidea** [comment]
这种属于个人自定义的东西，共享并不是很好啊
