### ISSUE TITLE
User Detail界面更新问题

### ISSUE THREAD

**Issue by youzhiyong** [zuiidea/antd-admin#667]
由于界面通常会被渲染三次, 而router下面的界面会保留上一次的数据, 所以一进入界面后看到的数据是上一次的(即第一次渲染界面), 只有当Models请求到新数据并返回后数据才会更新(亲测为第二次渲染).
那么问题来了:
1. 当网络请求很慢时,对用户体验非常不好
2. 当请求的数据没有完全覆盖上一次的所有数据的话, 那么没有被覆盖的数据就不会被更新

请问有没有什么方式能让router下的界面不保留上一次的状态或是其他的解决方案?

**Comment by allinshang** [comment]
能帮忙解释下为什么界面被渲染三次么？谢谢

**Comment by youzhiyong** [comment]
我也有点疑惑,, 你可以参考下这个[https://github.com/dvajs/dva-example-user-dashboard/issues/25](url), 
但是他解释的第二次渲染时间不符合我观察到的呀. @allinshang

**Comment by superlbr** [comment]
1. 当网络请求很慢时，怎样对用户体验好？
2. 更新很快的，要么都更新，要么都不更新，数据一致
3. 让router下的界面不保留上一次的状态，那保留什么状态？如果是初始状态，可以在model的setup里初始化值

**Comment by superlbr** [comment]
@youzhiyong react rerender很正常，初始加载组件，数据获取loading，数据来了更新

**Comment by superlbr** [comment]
如果想避免数据一致情况下的重复渲染，可以考虑react优化，比如 https://segmentfault.com/a/1190000008656863
