### ISSUE TITLE
body节点下如何做组件样式的局部修改？

### ISSUE THREAD

**Issue by enlyck** [zuiidea/antd-admin#672]
一般组件通过:global 就可以做到组件样式的修改，局部修改加上顶级class也能处理，但是如果组件是在body节点下，如何做局部的样式修改呢? 例如级联的下拉框的高度，请大佬解惑。 @afc163 @zuiidea

**Comment by zuiidea** [comment]
使用的antd的组件吗，看看`dropdownClassName`属性
https://ant.design/components/select-cn/
