### ISSUE TITLE
能请教下怎么设置请求头吗？

### ISSUE THREAD

**Issue by laiyiyi** [zuiidea/antd-admin#678]
我这样写，没效果
![image](https://user-images.githubusercontent.com/12541388/32842159-543e060c-ca57-11e7-8730-af42428194ec.png)
![image](https://user-images.githubusercontent.com/12541388/32842620-80e729d0-ca58-11e7-98df-9c032d4e350d.png)
![image](https://user-images.githubusercontent.com/12541388/32842635-8cbcd0d4-ca58-11e7-88c9-31b120a1eb4a.png)

**Comment by malinda1986** [comment]
You have to update the request library which is in [src/utils/reqest.js], that use axios as http client.
Check this doc to see how to set the headers 
https://github.com/axios/axios

**Comment by laiyiyi** [comment]
谢谢
