### ISSUE TITLE
warning antd , peer dependency react@^0.14.0 || ^15.0.0-0

### ISSUE THREAD

**Issue by webmobiles** [zuiidea/antd-admin#681]
warning "antd > react-lazy-load@3.0.12" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".
  warning "antd > react-lazy-load@3.0.12" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0".
  warning "antd > react-slick@0.15.4" has incorrect peer dependency "react@^0.14.0 || ^15.0.1".
  warning "antd > react-slick@0.15.4" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1".
  warning "antd > react-slick > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".

**Comment by superlbr** [comment]
1. 这是antd的依赖，提错地方了
2. 把react版本往上提就可以呀
