### ISSUE TITLE
npm run build 提示错误 Unexpected token: operator，请问下这是什么原因，如何解决呢？

### ISSUE THREAD

**Issue by Fennay** [zuiidea/antd-admin#686]
环境：
> node -v
v8.4.0
> npm -v
5.3.0

![image](https://user-images.githubusercontent.com/4941514/33161598-79422448-d05f-11e7-8b17-cca380b4ccd0.png)

**Comment by allinshang** [comment]
我的node和npm跟你的版本一样呢。。没有这个问题

**Comment by Fennay** [comment]
@allinshang 我是后端开发，想玩一下react，不太会，没有找到错误原因....

**Comment by allinshang** [comment]
@Fennay npm run dev有问题么？

**Comment by zuiidea** [comment]
是linux吗，有可能内存不足...

**Comment by weishijun14** [comment]
https://stackoverflow.com/

**Comment by Fennay** [comment]
@zuiidea docker中的虚拟机跑的，有这可能......

**Comment by Fennay** [comment]
@allinshang 好像也有问题，放弃了...有时间再去研究下

**Comment by superlbr** [comment]
node v9.8.0
镜像 aliyun node
yarn 包管理
build 正常
![image](https://user-images.githubusercontent.com/8142164/37202716-3c2536da-23c6-11e8-8f86-929b372d8114.png)
