### ISSUE TITLE
更新antd到3.0

### ISSUE THREAD

**Issue by superlbr** [zuiidea/antd-admin#688]
rt，目前已经是3.0.0-rc.3。

**Comment by superlbr** [comment]
now, released

**Comment by superlbr** [comment]
如果自己升，样式比较崩溃。。。

**Comment by chengnuo** [comment]
如果是2.x 升级的话，感觉还好。

**Comment by superlbr** [comment]
@chengnuo ant-design-pro出来后，就没更新了，小小惋惜下

**Comment by superlbr** [comment]
@chengnuo 请教下，升级之后，收纳左侧菜单栏的按钮<i class="anticon anticon-menu-fold"></i>，图标找不到了(对应下图左上角)，但是其他图标都正常，把属性里的content改成'/E658' 也就是2.x里的对应content就正常了
<img width="721" alt="a" src="https://user-images.githubusercontent.com/8142164/34148730-7e41c128-e4dd-11e7-873d-3808058233bf.png">

**Comment by zuiidea** [comment]
已更新

**Comment by superlbr** [comment]
@zuiidea 
<img width="303" alt="bug" src="https://user-images.githubusercontent.com/8142164/34407201-157852ac-ebf8-11e7-9940-3c2c9a8c12f2.png">

**Comment by xioozq** [comment]
@superlbr 我也发现了那个菜单的问题，找了半天没找到原因，你的解决了吗

**Comment by superlbr** [comment]
@xioozq 把node_modules删掉，重新install，应该是字体的问题

**Comment by xioozq** [comment]
这个我最后追到antd源码里面看了下，Menu.Item会在折叠起来以后渲染一个ToolTip，内容直接用的Menu.Item的children，但是我们的业务代码逻辑是Menu收缩以后，文字会不渲染，只留一个图标，然后这个时候ToolTip就显示不正常了。。我暂时的办法是强行改了下antd那部分源码

**Comment by superlbr** [comment]
@xioozq 之前看错了，囧。正常情况，children不该为空的。改源码。。。还是去ant-design开issue吧
