### ISSUE TITLE
关于routerRedux push跳转的问题

### ISSUE THREAD

**Issue by shaomingming008** [zuiidea/antd-admin#690]
dispatch(routerRedux.push({
                        pathname: 'rules/new',
                        query: { },
                    }))
每次跳转到新页面的时候   新页面中的form表单都保留着上一次的数据   怎么解决  跪求

**Comment by weishijun14** [comment]
跟 routerRedux 无关。 你自己的页面逻辑有问题，或者说页面切换逻辑， 或者说你的initialValue的取值。总而言之，是你的redux的状态不对。

**Comment by xudihui** [comment]
form 表单使用rc-form吗，如果是的话，可以检查下是否用了initialValue来进行初始化赋值！

**Comment by superlbr** [comment]
item 会保留在model的state里，跳转是不会改变的，弹出表单之前记得清空
