### ISSUE TITLE
打包后放IIS，login直接404，请问如何解决

### ISSUE THREAD

**Issue by 64237442** [zuiidea/antd-admin#696]
如题，

**Comment by 64237442** [comment]
Request URL:http://test:99/antd/iconfont.woff
Request Method:GET
Status Code:404 Not Found

**Comment by 64237442** [comment]
上面的处理了，现在又来了 一个：

Request URL:http://test:99/login?from=%2F
Request Method:GET
Status Code:404 Not Found
Remote Address:10.1.1.22:99
Referrer Policy:no-referrer-when-downgrade

**Comment by superlbr** [comment]
参考 vue iis 部分，总之在histroy mode下你需要把所有的请求转发到index.js处理。https://router.vuejs.org/zh-cn/essentials/history-mode.html

**Comment by 64237442** [comment]
谢谢
