### ISSUE TITLE
响应式支持

### ISSUE THREAD

**Issue by TheWaWaR** [zuiidea/antd-admin#7]
参考: [AdminLTE2](https://almsaeedstudio.com/themes/AdminLTE/index2.html)

1. 折叠菜单
2. 内容宽度自适应

**Comment by zuiidea** [comment]
1.现在有个按钮可以点击折叠菜单
2.宽度自适应只会做中大屏响应式，小屏幕应该不会做

**Comment by TheWaWaR** [comment]
像 AdminLTE2 这样手机上也能看 Dashboard 不是很好么

**Comment by zuiidea** [comment]
后台管理系统的常用使用场景在pc上，另外antd在手机上的体验并不是很好
