### ISSUE TITLE
routes中dispatch参数是如何传进来的？

### ISSUE THREAD

**Issue by masterzh01** [zuiidea/antd-admin#70]
比如 src/routes/app.js 中 {children, location, dispatch, app} 参数？

```
function App ({children, location, dispatch, app}) {
....
}
```

**Comment by mu2019** [comment]
我也有同样的疑问，看来是没法得到解答了。

**Comment by masterzh01** [comment]
@mu2019 应该是dva脚手架做的工作，看一下dva文档

**Comment by mu2019** [comment]
@masterzh01 ,感谢回复，我从dva的createDva源文件开始看下去，找到点眉目了。刚入手react几天，二三年没接触前端的东西了，感觉颠覆之前前端的一切。
