### ISSUE TITLE
关于手机UC无法渲染问题

### ISSUE THREAD

**Issue by Kunoky** [zuiidea/antd-admin#701]
我试着用手机UC访问你线上的Demo可以正常访问，但是我下载到本地启动之后手机UC无法渲染。所以想请教一下在打包或者部署的时候有哪些需要注意的地方

**Comment by superlbr** [comment]
信息不足：无法渲染如何理解。
部署参考：https://github.com/zuiidea/antd-admin/issues/269

**Comment by superlbr** [comment]
Duplicate. https://github.com/ant-design/ant-design/issues/8613
