### ISSUE TITLE
关于 public文件 在根目录下打包报错

### ISSUE THREAD

**Issue by VanquisherMe** [zuiidea/antd-admin#702]
我发现是0.0.1的问题
也就是
publicPath : `/${version}/`,
outputPath : `./dist/${version}/`,
如果是默认参数就可以 

https://github.com/sorrycc/roadhog/issues/30
https://github.com/sorrycc/roadhog/issues/341
我查看了 但是没有找到答案 
public放在根目录 就会报错
官方
`我们约定 public 目录下的文件会在 server 和 build 时被自动 copy 到输出目录（默认是 ./dist）下。所以可以在这里存放 favicon, iconfont, html, html 里引用的图片等。`

官方说的默认 那修改是怎么修改 outputPath : `./dist/${version}/` 这样？

**Comment by superlbr** [comment]
这个报错很有意思，npm run build --analyze 可以看到具体错误。
怀疑更改目录之后，会造成某缓存里的数据不一致。我把public移出去再移回来，发现build异常，git 显示clean。。。然后我把整个admin删掉，再build好了。
建议改完public路径后，除了设置了改下，把文件夹拷走，或者重命名试试

**Comment by superlbr** [comment]
嗯，修改outputPath
参考https://github.com/zuiidea/antd-admin/blob/308fc09b336430741c1fc609254ad3d521354025/webpack.config.js#L32
