### ISSUE TITLE
antd-admin示例的登录账号和密码是多少，求告知!

### ISSUE THREAD

**Issue by jackywq** [zuiidea/antd-admin#703]
![1](https://user-images.githubusercontent.com/21954704/34139043-856fb3a4-e4ad-11e7-8cd3-2bbc049fcaa5.png)

**Comment by xudihui** [comment]
Username:guest Password: guest

**Comment by zuiidea** [comment]
Username:admin Password: admin
Username:guest Password: guest

**Comment by ramen-curator** [comment]
Why not add it to the readme file?

**Comment by superlbr** [comment]
@ramen-curator done
