### ISSUE TITLE
IE兼容是在那里做的，我这边IE11打开都是空白

### ISSUE THREAD

**Issue by lettywiterock** [zuiidea/antd-admin#704]
IE浏览器就是有个性，理论上应该兼容才对，我这边打开却是空白

**Comment by runthinker** [comment]
https://ant.design/docs/react/getting-started-cn

**Comment by lettywiterock** [comment]
不是这个，开了两个项目，同一个源复制的，一个可以显示，一个不能显示
IE报语法错误
降低了webpack版本，还是报roadhog  参数错误

**Comment by superlbr** [comment]
怀疑是调试白屏吧，build完是可以正常跑的

**Comment by superlbr** [comment]
No more info.Close
参考 https://github.com/dvajs/dva/issues/897
