### ISSUE TITLE
部署后的页面偶尔出现打开无显示，在本地测试没有问题

### ISSUE THREAD

**Issue by runthinker** [zuiidea/antd-admin#705]
如果出现打开无显示时，在Console中出现如下错误信息：
Uncaught (in promise) Error: Loading chunk 11 failed.
    at HTMLScriptElement.n (index.js?8d86a4499b2aebfe9d63:1)

**Comment by superlbr** [comment]
浏览器有缓存，部署完要刷新

**Comment by runthinker** [comment]
已经解决，是电信DNS劫持的问题。

**Comment by superlbr** [comment]
https也会这样的
