### ISSUE TITLE
关于router配置问题

### ISSUE THREAD

**Issue by SecretCastle** [zuiidea/antd-admin#707]
您好，请教一个问题，我在routerjs中配置了dynamic，参考你的方法 

![image](https://user-images.githubusercontent.com/12498143/34239145-682694f4-e640-11e7-99c0-8e658731fe45.png)

![image](https://user-images.githubusercontent.com/12498143/34239169-860ff12c-e640-11e7-81d8-dc26d3a0d625.png)

这样编写，但是， 当我点击Link 如 `http://localhost:8001/#/application/info` 时不显示对应的component，只有重新刷新才显示，我想请问下这个是说明原因？？

**Comment by superlbr** [comment]
建议将HashHistory更换为本项目使用的是BrowserHistory
二者差异参考: https://segmentfault.com/q/1010000007788281/a-1020000007789987  
https://www.cnblogs.com/yzfdjzwl/p/7106792.html
