### ISSUE TITLE
index 文件太大了，请问应该怎么优化呢？

### ISSUE THREAD

**Issue by herrdu** [zuiidea/antd-admin#712]
你好：
index文件有点大，本地看有 2m多，web加载的时候有7m多。我正在做CommonsChunkPlugin，想请问作者有没有好的建议，怎么去做这个CommonsChunkPlugin？

**Comment by superlbr** [comment]
npm run build --analyze , 看里面stat.html. 
基本上都是依赖包比较大。可能看到总共7.3m，依赖包5.8m, 自己代码才1.5m.
一般部署上去，都带压缩的（比如nginx开gzip之类），如下图，首页7百k，对于PC首页来说，简直迷你
![image](https://user-images.githubusercontent.com/8142164/34433696-e802beba-ecbb-11e7-929b-82d08478725a.png)

**Comment by herrdu** [comment]
1. 我执行  NODE_ENV='production' && roadhog build --analyze  ，并没有生成  stats.html 
2. 我的index文件  压缩后是1.8m左右

3.我使用的webpack的dll 功能，虽然build成功了，但是npm start 之后，却显示webpackJosn.__name__ not defined。

4. 是不是roadhog 不支持  webpack 的dll ？

**Comment by herrdu** [comment]
我想打开是我引用的图片过多了，我去要把图片拷贝过去。

**Comment by superlbr** [comment]
@herrdu 重新更新了答案，我觉得antd-admin的配置无可厚非。

**Comment by Maple-Ro** [comment]
@superlbr @zuiidea 
大家能看下我的，为啥500kb的js文件，下载时间需要3s多（zuiidea的demo网站才不到500ms）
服务器端nginx做了gzip压缩，阿里云服务器
![qq20180108-214514](https://user-images.githubusercontent.com/16970224/34673543-8e0b3be4-f4bd-11e7-99a0-b6ca50efcb4a.png)
不知道我哪里没配置好呢，谢谢大家

**Comment by superlbr** [comment]
估计服务器的带宽是1-2M，三点可以优化，1. 负载均衡 2. CDN 3. 加宽带

**Comment by Maple-Ro** [comment]
@superlbr，非常感谢。嗯，服务器带宽是1M的。
