### ISSUE TITLE
upgrade roadhog to 2.0

### ISSUE THREAD

**Issue by superlbr** [zuiidea/antd-admin#715]
内部人士说两句呗，https://github.com/sorrycc/blog/issues/55

**Comment by zuiidea** [comment]
变化太多，先稳一稳😂

**Comment by hanxiansen** [comment]
先别急着上，有些地方貌似亟需优化

**Comment by superlbr** [comment]
ant-design-pro 1.0.0 https://github.com/ant-design/ant-design-pro/issues/333 耳目一新

**Comment by superlbr** [comment]
看样子大概率要换成umi了

**Comment by superlbr** [comment]
umi 1.0 https://github.com/sorrycc/blog/issues/64

**Comment by superlbr** [comment]
Finish https://github.com/zuiidea/antd-admin/pull/770
