### ISSUE TITLE
怎么做模块下的子路由？

### ISSUE THREAD

**Issue by Marrten** [zuiidea/antd-admin#717]
`路由<ConnectedRouter history={history}>
      <App>
        <Switch>
          <Route exact path="/" render={() => (<Redirect to="/dashboard" />)} />
          {
            routes.map(({ path, ...dynamics }, key) => (
              <Route key={key}
                exact
                path={path}
                component={dynamic({
                  app,
                  ...dynamics,
                })}
              />
            ))
          }
          <Route component={error} />
        </Switch>
      </App>
    `</ConnectedRouter>是照着antd-admin这个项目的router.js写的。现在我在User模块下有个Modal弹出框，弹出框里有Menu，Menu的Item加了Link标签， <Menu.Item key="publics" ><Link to='/user/publics'><span><Icon type="global" /></span>公共配置</Link></Menu.Item>写子路由，一直报404，该怎么解决？希望大神们能解答下，或者提供相关的demo。`

**Comment by qqsbxk1234** [comment]
@zuiidea

**Comment by superlbr** [comment]
首先，梳理下路由的涉及到的部分，以user为例：
1. router.js里要注册，并且component一定要有，models可选
2. mock文件夹里menu.js要注册，涉及models部分的方法还需自己再写个mock.js这样
其次，遇到404怎么去分析呢？
1. 你可以对比可以访问的路由，看看component、models是怎么组成的，mock方法怎么实现的
2. 会不会是权限有问题呢？这样思路就展开了。。。
就我所知，antd-admin里404要么router.js里没配置，要么是mock里面user.js里面userPermission有visit访问限制

**Comment by yanghuayi** [comment]
@superlbr 遇到子路由404问题，
一级路由：
`<Route exact path="/project" render={props => <Project apps={app} {...props} />} />`
二级路由：
![image](https://user-images.githubusercontent.com/8624466/35084662-f64b01ea-fc5f-11e7-92a4-2988a0b7f1f6.png)
二级路由第一个可以匹配成功，第二个就404了，
![image](https://user-images.githubusercontent.com/8624466/35084688-1d97b50e-fc60-11e7-8e48-bd53441fff5b.png)
![image](https://user-images.githubusercontent.com/8624466/35084695-24fb4bb2-fc60-11e7-9c4d-88a9a5876fb1.png)

**Comment by yanghuayi** [comment]
上面第二个二级路由放在一级路由下是可以访问的
![image](https://user-images.githubusercontent.com/8624466/35085197-7c0839a4-fc62-11e7-8bea-3977e2746ec6.png)

**Comment by superlbr** [comment]
@yanghuayi 对比https://github.com/zuiidea/antd-admin/blob/master/src/router.js

**Comment by srrrr** [comment]
如何在页面中添加子路由？
我的代码是这么写的：
![c_code](https://user-images.githubusercontent.com/5070841/37862068-016be8d2-2f82-11e8-9cc5-b994dc7f7f66.png)

但并没有达到子路由的效果，还是按根路由来的结构来显示。。。
![c_1](https://user-images.githubusercontent.com/5070841/37862074-2963f55a-2f82-11e8-8055-3ea1ec70f4bb.png)
![c_2](https://user-images.githubusercontent.com/5070841/37862076-2d352e92-2f82-11e8-9692-777636a7fdc2.png)

**Comment by superlbr** [comment]
@srrrr tab跟子路由没有关系吧，至少在router里注册吧

**Comment by srrrr** [comment]
@superlbr ant-design-pro-template 官方DEMO里有个例子就是用Tab+子路由实现。我现在按官方的方法来写，但不知道为什么，子路由的写法没生效。
![antd](https://user-images.githubusercontent.com/5070841/37882760-ae581f50-30d8-11e8-87da-2f6217a95799.png)

**Comment by superlbr** [comment]
如果router.js里面注册过的话，对应的链接就是跳转对应的页面，没毛病
![image](https://user-images.githubusercontent.com/8142164/37885544-6e17cc78-30e8-11e8-9f08-aa184d4fd7c1.png)
