### ISSUE TITLE
点击用户详情，左侧菜单不能聚焦选中

### ISSUE THREAD

**Issue by KingHUBIYIN** [zuiidea/antd-admin#718]
点击用户详情，左侧菜单不能聚焦选中，本来是这样设计的吗？？

**Comment by superlbr** [comment]
首先用户详情是二级路由，观察左侧菜单栏，并没有“用户详情”这一项，说明是被隐藏了。同理你对比Test Navigation->Test Navigation2->Test, 发现没有，就是这样子的

**Comment by KingHUBIYIN** [comment]
我把用户详情路由显示出来，但是用户详情查询是需要用户id的，点击选项，是要报错的

**Comment by superlbr** [comment]
诺，这就是面包屑导航解决的问题

**Comment by KingHUBIYIN** [comment]
如果左侧菜单收起了，点击面包屑导航到上一级，左侧菜单没有展开

**Comment by superlbr** [comment]
嗯，设计就是这样

**Comment by KingHUBIYIN** [comment]
哦，谢谢大牛

**Comment by superlbr** [comment]
惭愧，会用而已
