### ISSUE TITLE
为什么不使用 dva/fetch ?

### ISSUE THREAD

**Issue by TangMonk** [zuiidea/antd-admin#72]

**Comment by yyjazsf** [comment]
axios 更好吧

**Comment by zuiidea** [comment]
mockJs拦截不了fetch

**Comment by Zuckjet** [comment]
我试过用fetch发起get请求是可以返回到数据的，你说的“mockJs拦截不了fetch”，是说fetch发起的post请求，mockjs不能响应吗？ @zuiidea

**Comment by TangMonk** [comment]
@Zuckjet ajax 请求可以拦截，但是fetch不可以拦截，然后就不能mock了，所以就没有用fetch来做api请求

**Comment by Zuckjet** [comment]
https://github.com/dvajs/dva-example-user-dashboard/blob/master/src/utils/request.js
那这个例子中用的就是fetch啊，是可以得到mockjs的数据的 @TangMonk

**Comment by zuiidea** [comment]
@Zuckjet mockjs在一个纯静态的环境中不能拦截fetch，你可根据项目实际需求换成fetch，我现在打算换成@yyjazsf 说的axios

**Comment by Zuckjet** [comment]
谢谢指导。还有一个问题想请教一下，我按照你的教程仿写了一个对话框，大致如下：
class UserModal extends Component {
...
okHandler = () => {
dipatch() //此处出现错误，错误信息Uncaught ReferenceError: dispatch is not defined
}
...
}
export default Form.create()(UserModal);
如何在这个组件中使用dispatch呢
