### ISSUE TITLE
Input输入框，绑定chang事件，里面用getFieldsvalue获取不到值

### ISSUE THREAD

**Issue by KingHUBIYIN** [zuiidea/antd-admin#720]
<Col {...ColProps}>
          {
            getFieldDecorator("carNumber", {
              initialValue: carNumber
            })(
              <Input placeholder="车牌号" onChange={handleChange.bind(null, 'carNumber')}/>
            )
          }
        </Col>

  const handleChange = (key, values) => {
    let fields = getFieldsValue();
    fields[key] = values;
    onFilterChange(fields);
  };

**Comment by superlbr** [comment]
代码没看出问题，给你看个实例吧，https://codepen.io/superlbr/pen/OzwLXZ
建议可以使用CodePen、CodeSandbox 调试或者展示代码。
