### ISSUE TITLE
打包后的dist可以部署到网站子目录里吗？

### ISSUE THREAD

**Issue by songxh2** [zuiidea/antd-admin#722]
因为有多个后台，想把不同后台部署到不同子目录里，项目怎么打包成相对目录？
项目中的browserHistory能否改成hashHisrtory？

**Comment by superlbr** [comment]
部署子目录啥的，让代理服务器去做，Apache或者Nginx

**Comment by superlbr** [comment]
browserHistory可以改成hashHisrtory, 但不推荐
参考： https://react-guide.github.io/react-router-cn/docs/guides/basics/Histories.html#browserHistory
