### ISSUE TITLE
AutoComplete组件的赋值问题

### ISSUE THREAD

**Issue by KingHUBIYIN** [zuiidea/antd-admin#724]
const children = companyListComplete.map((item) => {
    return <CompleteOption key={item.id} value={item.id.toString()}>{item.companyName}</CompleteOption>;
  });
{
            getFieldDecorator("companyId", {
              initialValue: companyId
            })(
              <AutoComplete
                style={{ width: '100%' }}
                allowClear
                backfill
                onSearch={handleSearch}
                onSelect={handleSelect}
                placeholder="请选择公司"
              >
                {children}
              </AutoComplete>
            )
          }

赋值的时候没有找到对应的中文的值

**Comment by superlbr** [comment]
参考文档，children 可以改成map((item) => {
      return <Option key={item.companyName}>{item.companyName}</Option>;
    }); （记得引入const Option = AutoComplete.Option;）
![image](https://user-images.githubusercontent.com/8142164/35022146-57a4d8fe-fb6f-11e7-949c-029adb43b288.png)
