### ISSUE TITLE
routerRedux.push问题

### ISSUE THREAD

**Issue by zhaoyuan7845** [zuiidea/antd-admin#728]
抱歉，我在地铁上，手打请谅解。今天遇到一个问题，我的一级路由是roter path＝"/login"登录页组件,  route path＝"/" 布局组件，根路由加载布局，然后布局的子路由里配置了一个redirect from＝`/` to＝"/login"， 前提是只在未获取到登录态时才加载该路由。但是当url在重定向到登录页后，点击登录，我的登录成功以后的routerRedux.push("/")就失效了。如果直接请求登录页不会有问题，登录后可以跳转。就是重定向过来有问题。我是新人，不知道该怎么解决，还请指教，非常感谢！

**Comment by zhaoyuan7845** [comment]
跟redirect 没关系，是我路由加载逻辑有问题。
如下
`<Route path="/"  component={component}/>`
`<Redirect path="/test" to="/login"/>`
请求/test 跳转 login，登录成功跳转到首页/，没有问题。
我猜测在加载Redirect 之前要保证跟路由是存在的，因为这个Redirect 是路由级别的。如果跟路由不存在，即便push到“/”。但是“/”依然要跳转到login，所以才让我以为push“无效”。不知道是不是这样。现在我只好让无状态的用户也展示首页了，但是对某些权限做了动态路由。

**Comment by zhaoyuan7845** [comment]
还有一个解决方式我试过。就是login成功之后的`yield put(routerRedux.push('/'));` 改成`window.location.href = '/';` 就可以实现跳转。但是有点破坏组件了。不知道有没有等效的方案来实现？

**Comment by zhaoyuan7845** [comment]
交代一下背景
一级路由如下：
`<Switch>`
          `<Route exact path="/login" component={LoginPage}/>`
          `<Route path="/" component={BaseLayout}/>`
`</Switch>`
BaseLayout 组件来加载布局，同时动态加载二级路由，加载二级路由之前先异步请求登录态，成功则正常加载，匹配权限等等，失败则设置redirect 强制 登录，这里的强制登录没有加载跟路由，因此出现了push“无效”的问题。
我的疑问是，如果浏览器直接访问login，因为/login在“/”前面，是不是根路由就不加载了？等routerRedux.push('/') 时，又重新匹配根路由，此时匹配上了根路由，继续加载二级路由，因此可以正常工作？但是如果login 是从 redirect 来的，说明二级路由已经加载完，且二级路由设置了所有path的重定向，所以routerRedux.push('/') 不会重新加载二级路由，直接执行了redirect是吗？
抱歉，说得太乱。希望大神们给予指点。谢谢！！！

**Comment by superlbr** [comment]
1. 建议提问针对项目来提，这样代码一致，便于沟通
2. routerRedux还有[go\goBack\replace等用法](https://github.com/reactjs/react-router-redux#pushlocation-replacelocation-gonumber-goback-goforward)可以尝试 
3. 路径匹配原理，参考[react-router](https://react-guide.github.io/react-router-cn/docs/guides/basics/RouteMatching.html)
