### ISSUE TITLE
关于打包部署后样式错误问题

### ISSUE THREAD

**Issue by cesar-blog** [zuiidea/antd-admin#729]
RT
样式错误，附上图

![image](https://user-images.githubusercontent.com/17369383/35429339-9ffdf720-02ae-11e8-928a-a96c09c66e65.png)

![image](https://user-images.githubusercontent.com/17369383/35429375-bf95a682-02ae-11e8-8439-8ce8c9ada3f2.png)

**Comment by cesar-blog** [comment]
在更新一张dist文件夹的图

![image](https://user-images.githubusercontent.com/17369383/35429864-d13d3268-02b0-11e8-84a3-75977aa11490.png)

**Comment by superlbr** [comment]
1. 貌似antd样式没有加载,第一张图重新截取，把文件大小显示出来. 
2. 对比下源码，看看配置差异
3. 另参考 ANTD定制主题文档https://ant.design/docs/react/customize-theme-cn

**Comment by cesar-blog** [comment]
@superlbr 

![image](https://user-images.githubusercontent.com/17369383/35469180-14df0fa4-036b-11e8-8ba4-1878337e374f.png)

**Comment by superlbr** [comment]
一般 mime.type 在nginx.conf里会默认配置的
