### ISSUE TITLE
config文件中的logo、iconFontCSS、iconFontJS是放在那里的？？

### ISSUE THREAD

**Issue by KingHUBIYIN** [zuiidea/antd-admin#730]
name: '安易出行',
  prefix: 'anyicx',
  footerText: '@ 2017 安易运营商智能运营系统  1.0.0',
  logo: '/logo.svg',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  CORS: [],
  openPages: ['/login'],
  apiPrefix: '/api/v1',

**Comment by klren0312** [comment]
# public 文件夹下面。。。
