### ISSUE TITLE
在修改操作时发起两个action，由于传值item中没有文件信息，不得不去请求files，其中一个files使用effect请求后台数据并更新state，一个显示modal，可是是异步处理，每次都是显示了页面没有数据，只能第二次才能有数据，求大神指教

### ISSUE THREAD

**Issue by muyunchun120** [zuiidea/antd-admin#732]
在修改操作时发起两个action，由于传值item中没有文件信息，不得不去请求files，其中一个files使用effect请求后台数据并更新state，一个显示modal，可是是异步处理，每次都是显示了页面没有数据，只能第二次才能有数据，求大神指教
 routes.js

onEditItem (item) {

            dispatch({
                type: 'fault/files',
                payload: {
                    id:item.file_ids,
                },
            });
            dispatch({
                type: 'fault/showModal',
                payload: {
                    modalType: 'update',
                    currentItem: item,
                },
            })
        },
}

models.js

state: {

      currentItem: {},
      modalVisible: false,//modal显示控制
      modalType: 'create',//modal类型
      selectedRowKeys: [],//选中行key
      filesList:[],
      isMotion: window.localStorage.getItem(${prefix}userIsMotion) === 'true',

  },

effects: {

 \* files ({ payload }, { call, put }) {

          const data = yield call(faultService.queryfiles, payload);
          if (data.success) {
              yield put({
                  type: 'updateState',
                  payload: {
                      filesList:data.list
                  }
              })
          } else {
              throw data
          }
      },

}

reducers: {

      showModal (state, { payload }) {
          return { ...state, ...payload, modalVisible: true }
      },

  },

modal.js

const props = {

      action: '/api/v3/project/files/upload',
      onChange({ file, fileList }) {
          if (file.status !== 'uploading') {

          }
      },
      defaultFileList: filesList,

  };

 <FormItem label="文件上传" hasFeedback {...formItemLayout}>
          {getFieldDecorator('upload', {

          })(<Upload {...props}>
            <Button>
                <Icon type="upload" />上传
            </Button>
          </Upload>)}
 </FormItem>

**Comment by superlbr** [comment]
可以把showModal放在data.success里

**Comment by muyunchun120** [comment]
@superlbr 谢谢提醒，已修改


\* files ({ payload }, { call, put }) {

          const data = yield call(faultService.queryfiles, {'id':payload.id});
          if (data.success) {
              yield put({
                  type: 'updateState',
                  payload: {
                      filesList:data.list,
                      modalType: 'update',
                      currentItem: payload.currentItem,
                  }
              });
              yield put({ type: 'showModal' })
          } else {
              throw data
          }
      },

**Comment by superlbr** [comment]
1. 什么情况下，console.log会运行？
2. 把yield put 'updateState'去掉，打印几次？把 yield put ‘showModal'去掉呢

另外：
1. 跟console.log在Modal.js里位置有没有关系？

**Comment by wangcplusplus** [comment]
把yield put showModal去掉，就不会使用modal组件了，把upstateState 去掉，还是会调用两次

routes.js
`onAdd () {
      dispatch({
        type: 'line/getService'
      })
    },`
model.js
```
    * getService({payload = {}}, {call, put}) {
      const dataService = yield call(getService);
      //const dataSource = yield call (getDataSource);
      const dataSource = {}
      if(dataService && dataSource){
        yield put({
          type: 'updateModelState',
          payload: {
            service: dataService.data,
            dataSource: dataSource.data,
          }
        });
        yield put({type: 'showModal'})
      } else {
        throw dataService;
      }
    }
```
reducers
  ```
reducers: {
    showModal(state, { payload }) {
      console.log('被调用');
      return { ...state, ...payload, modalVisible: true };
    }
 }
```
modal.js
```
const modal = ({
  item = {},
  onOk,
  form: {
    getFieldDecorator,
    validateFields,
    getFieldsValue,
  },
  ...modalProps
}) => {
  const handleOk = () => {
    validateFields((errors) => {
      if (errors) {
        return;
      }
      const data = {
        ...getFieldsValue(),
        key: item.key,
      };
      data.address = data.address.join(' ');
      onOk(data);
    });
  };
  console.log(modalProps);
  const modalOpts = {
    ...modalProps,
    onOk: handleOk,
  };
```
routes.js 使用modal组件
```
return (
    <div>
      <Filter {...filterProps} />
      <List {...listProps} />
      {modalVisible && <Modal {...modalProps} />}
    </div>
  )
```

**Comment by superlbr** [comment]
把dva升级到2.2.2

**Comment by wangcplusplus** [comment]
把dva升级到2.2.2，我也重启了,还是会打印两次
![image](https://user-images.githubusercontent.com/24887460/38660718-d8e7807c-3e60-11e8-95d1-508073c5aec4.png)

**Comment by wangcplusplus** [comment]
这个是新增一条数据，我刚才测试更新的时候，就只会打印一次，我再看看是哪里逻辑有问题，多谢@superlbr，非常感谢指导我很多问题

**Comment by superlbr** [comment]
测试了下，跟modalProps里的动态参数也有关系，打印三次也有

**Comment by wangcplusplus** [comment]
但是几次打印的数据一模一样啊
