### ISSUE TITLE
怎么统一在所有的路由后面添加'/admin/'

### ISSUE THREAD

**Issue by cybibo** [zuiidea/antd-admin#733]
比如现在开发环境的路由是
http://localhost:8000/login?from=%2F
想统一在所有的路由后面添加一个‘/admin/'
变成 http://localhost:8000/admin/login?from=%2F
谢谢！

**Comment by superlbr** [comment]
用nginx代理

**Comment by cybibo** [comment]
在nginx里的server{
listen       80;
server_name  _;
location /admin {
            alias /antd-admin/dist;
            index index.html;
        }
}
在浏览器里输入http://localhost/admin/,正确跳入登录首页了，但浏览器里显示还是http://localhost:8000/login?from=%2F

**Comment by superlbr** [comment]
请检查下是否能登陆，打开方式不大对吧，参考https://github.com/zuiidea/antd-admin/issues/641

**Comment by superlbr** [comment]
参考https://github.com/dvajs/dva/issues/1497
Duplicate: https://github.com/zuiidea/antd-admin/issues/129
