### ISSUE TITLE
使用AntD Pro组件 报错

### ISSUE THREAD

**Issue by mochazzxx** [zuiidea/antd-admin#736]
执行npm run build:dll 失败 报错：

Module parse failed: Unexpected token (8:4)
You may need an appropriate loader to handle this file type.
|   const clsString = classNames(styles.globalFooter, className);
|   return (
|     <div className={clsString}>
|       {
|         links && (

Module parse failed: Unexpected token (8:58)
You may need an appropriate loader to handle this file type.
| import responsive from './responsive';
|
| const Description = ({ term, column, className, children, ...restProps }) => {
|   const clsString = classNames(styles.description, className);
|   return (

Module parse failed: Unexpected token (8:82)
You may need an appropriate loader to handle this file type.
|
| const ChartCard = ({
|   loading = false, contentHeight, title, avatar, action, total, footer, children, ...rest
| }) => {
|   const content = (

Module parse failed: Unexpected token (9:2)
You may need an appropriate loader to handle this file type.
|  */
| const Exception403 = () => (
|   <Exception type="403" style={{ minHeight: 500, height: '80%' }} />
| );
|

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd-admin@1.0.0 build:dll: `roadhog buildDll`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-admin@1.0.0 build:dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bian/.npm/_logs/2018-01-30T05_37_09_855Z-debug.log

**Comment by superlbr** [comment]
建议直接拿Antd Pro源码src/components里的组件代码用
报错的原因：
  1. antd pro用了es7的decorators 
  2. antd pro 默认roadhogrc 2.2，配置发生了较大变化

**Comment by mochazzxx** [comment]
@superlbr 感谢!

**Comment by superlbr** [comment]
1. webpack 支持方式, 参考[文档](https://stackoverflow.com/questions/33801311/webpack-babel-6-es6-decorators)
2. 试试develop分支，引入umi之后，babel-preset-umi最新0.2.8默认支持decorators
