### ISSUE TITLE
关于object遮挡message提示框问题

### ISSUE THREAD

**Issue by LDD123** [zuiidea/antd-admin#737]
现在引入一个第三方object组件，但是组件遮挡了message消息提示，如图所示，该怎么解决啊，大佬

![qq 20180130142438](https://user-images.githubusercontent.com/11335860/35551310-76c2695e-05c9-11e8-93dc-6d1d2bc041c3.png)

**Comment by LDD123** [comment]
@afc163 @zuiidea

**Comment by superlbr** [comment]
换个方式呢，比如考虑Alert, Message

**Comment by LDD123** [comment]
@superlbr Alert不是静态提示吗，我感觉这个应用情况应该是，如果有错误或者什么信息跳转到某个页面是吧。感觉不适用啊。
我使用Message实现了，可以避免被遮挡了，感觉这个不是很好的解决方案

**Comment by superlbr** [comment]
1. 善用工具
2. 感觉不是很好，为什么？怎样算好？适合/违反ANTD的什么设计原则？

**Comment by LDD123** [comment]
不是违反什么原则问题，我就是想说，这个问题，使用message只是避免了显示不出来的尴尬，并没有从根本上解决遮挡问题

**Comment by superlbr** [comment]
那分析下:
1. 遮挡问题是z-index的值，对于开发者来说，那写CSS覆盖Notification的z-index。
2. 文档上并未说Notification一定在最上面，Notification的z-index是1010，一般来说这个值已经很文明的表示要最上层了，而这个三方object明显不让，也要上层，z-index肯定是非常的大。那这里两者都希望获取用户的注意，使用z-index去争大小那就不合理。换一种方式会比较好
3. Alert是静态提示，但是也可以动态使用

**Comment by LDD123** [comment]
1.首先确实是z-index问题，但是object标签和html标签生成时效是有问题的，因此用z-index无法控制，你可以百度下object遮挡问题。要能解决，就解决了，提供的方案是使用iframe遮挡object,但是antd，react这种写法，展示提示，不是很会
2.确实Notification的z-index我看过是1010，但是z-index设置不生效
3.Alert能实现，但还是遮挡，现在解决方案是避免与object重合，而不是真正的解决
4.很感谢提出的意见，多谢

**Comment by superlbr** [comment]
总结下:
1. 控制object和notification的布局
2. iframe的方案，类似react-frame-component
