### ISSUE TITLE
antd Icon 相对路径的问题

### ISSUE THREAD

**Issue by Viin-zx** [zuiidea/antd-admin#740]
antd icon 路径是匹配不上
![image](https://user-images.githubusercontent.com/19523605/35800873-44587388-0aa5-11e8-8da8-d4344de74ae9.png)

实际路径为tomcat 下的子目录下。
![image](https://user-images.githubusercontent.com/19523605/35800957-846ae866-0aa5-11e8-87ee-6b9cf2624f8d.png)

其它静态资源在roadhogrc.js 下加了publicPath, 所以ok
![image](https://user-images.githubusercontent.com/19523605/35801010-b0b567b6-0aa5-11e8-84ff-85eb69caa017.png)

然后在 default.less 里加上   **@icon-url: "/antd/iconfont";** 
就会匹配不上路径
尝试着改成 **@icon-url: "./antd/iconfont";**      打包时出现如下报错
![image](https://user-images.githubusercontent.com/19523605/35801102-f85d257c-0aa5-11e8-9ea6-200dee47ed46.png)

请问如何解决。。

**Comment by superlbr** [comment]
tomcat可以映射路径，比如改docBase

**Comment by Viin-zx** [comment]
你好，我对tomcat不太熟悉，我添加了这段配置文件， 看起来效果一样，请问如何做映射？

**<Context path="/nansha" docBase="D:\Program Files (x86)\Java\apache-tomcat-8.5.20\webapps\ROOT\nansha" />**

**Comment by Viin-zx** [comment]
你好，我对tomcat不太熟悉，我添加了这段配置文件， 看起来效果一样，请问如何做映射？ @superlbr

**Comment by Viin-zx** [comment]
@superlbr   你好，我对tomcat不太熟悉，我添加了这段配置文件， 看起来效果一样，请问如何做映射？

		<Context path="/nansha" docBase="D:\Program Files (x86)\Java\apache-tomcat-8.5.20\webapps\ROOT\nansha" />

**Comment by superlbr** [comment]
理清楚appBase，context里的path/docBase之间的关系

**Comment by Viin-zx** [comment]
@superlbr 因为antd icon 要加上这个。
![image](https://user-images.githubusercontent.com/19523605/35845223-65fe6842-0b4c-11e8-9d7f-ba5b9892343f.png)
 所以打包后资源请求会从根目录开始， 然后我就把tomcat改成了这样， 项目可以正常运行了。
![image](https://user-images.githubusercontent.com/19523605/35845298-d21e77c4-0b4c-11e8-9c37-0f24ed59057e.png)
但是我们tomcat下有很多子网页，现在请求http://localhost:8088 是没问题，但是我实际是要在http://localhost:8088/nansha 这个目录下做操作的。 就算映射了 /nansha 路径， 打包后的静态资源因为路径都是 /xxx/xxx， 所以匹配到的都是网站根目录。

有没有更好的方法解决呢？

**Comment by superlbr** [comment]
tomcat 只是容器，不要难为人家，子目录这种让apache/nginx去做吧

**Comment by Viin-zx** [comment]
@superlbr  谢谢您的解答， 不过我觉得开始复杂了，
![image](https://user-images.githubusercontent.com/19523605/35848124-dfd1b222-0b57-11e8-8029-9e9f8d8b5221.png)
 就这个静态资源打包的路径问题，我再研究看看在打包的时候能不能解决。

**Comment by superlbr** [comment]
antd-admin里没看到@icon-url配置，一般这个是去覆盖这个变量的时候，才会主动声明
