### ISSUE TITLE
Adding static pages

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#743]
Is there a way to add static pages using different style sheets. I mean before login to the dashboard I need to add few pages those are having different  styles

**Comment by superlbr** [comment]
You could set the variable "openPages" in utils/config. Jump to login page after show your pages whatever

**Comment by malinda1986** [comment]
@superlbr thanks, But it includes other CSS files, I need to include different set of styles

**Comment by superlbr** [comment]
Just include. Is there error or conflict?

**Comment by superlbr** [comment]
also entry.ejs, you could use if to choose your css fike

**Comment by malinda1986** [comment]
Yes, I did .Open pages works.
Below is the required css for my open pages
`<link rel="stylesheet" href="css/materialize.css"/>
              <link rel="stylesheet" href="css/styles.css"/>
              <link rel="stylesheet" href="css/font-awesome.css"/>`

But it insert dashboard styles for that pages , I need to get rid of those 

`<link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/4d97e30a-f217-4eac-9514-673c40eb11ee"><link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/70c5b715-2dce-4f39-b96f-e7dff2e31463"><link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/ffd1e6f9-07e2-4c2b-8987-2027f6f57dd0"><link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/f2701365-e1d8-4c9b-b4e6-79eb59eb64e6"><link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/18e61477-5f12-4210-9255-4d2707b9dcb2"><link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/ca0cbb63-5297-4134-a2fd-530fd0184357"><link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/7ea6a1cc-8b38-4876-89c8-5ba598ca0fd2"><link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/212951f4-e4aa-493d-9ba2-666e51e9bdd8"><link type="text/css" rel="stylesheet" href="blob:http://localhost:8000/2bbdfdae-b61e-44a0-be3e-bf4933c7fdd8">`

**Comment by superlbr** [comment]
Here're two way:
1. as web server, nginx and apache could handle, just use a location to serve static pages
2. dashboars styles conflict, well, you could modify classname, just different namespaces

**Comment by superlbr** [comment]
for develop branch , use [umi](https://github.com/umijs/umi) , easily [change layout](https://umijs.org/docs/en/html-tpl.html)
