### ISSUE TITLE
请问一下， 怎么使用宋体字体

### ISSUE THREAD

**Issue by 64237442** [zuiidea/antd-admin#744]
开发时候 ，在src\themes\index.less 里面设置样式
body {
  height: 100%;
  overflow-y: hidden;
  background-color:#f8f8f8;
  font-family:'宋体';
}
有效果，字体很清晰， 可是发布到nginx 后 ，宋体 字体无效了 ，看不清楚。
请大家帮帮忙，看看啥情况。
或者可以有宋体一样 清晰的字体也号啊

**Comment by superlbr** [comment]
参考阮老师博客-中文字体网页开发指南 http://www.ruanyifeng.com/blog/2014/07/chinese_fonts.html

**Comment by superlbr** [comment]
参考 https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/

**Comment by 64237442** [comment]
谢谢，搞定了。 采用 英文    font-family: 'SimSun'; 
用中文 乱码导致。谢谢你
