### ISSUE TITLE
页面刷新 那一个LOADING是在哪里设置的呢？

### ISSUE THREAD

**Issue by wunayou** [zuiidea/antd-admin#746]
如题

**Comment by superlbr** [comment]
如我理解，不止是页面刷新、页面加载的时候也会有。Loading很多地方都有，搜索下代码。
这里梳理下：
     1. 从入口index.js去看，createLoading (https://github.com/dvajs/dva/tree/master/packages/dva-loading), 用来提供loading的state。index很简洁，下面就是model和router.
     2. 接着去看model下app.js，没有load之类，过。
     3. 接着去看router下app.js，loading来了，看到<Loader fullScreen spinning={loading.effects['app/query']} />，跟Loader有关
就这样
