### ISSUE TITLE
后台登陆如何设置token，有成功的例子吗？自己改挺多的

### ISSUE THREAD

**Issue by muyunchun120** [zuiidea/antd-admin#750]

**Comment by superlbr** [comment]
首先不知是否指的是mock里的token，对于前端来说使用mock直接开发；对于后台而言，接口中设置就是了。
其次观察mock里token:
     /admin/login(设置token)
     `      res.cookie('token', JSON.stringify({
                id: admin[0].id,
                deadline: now.getTime()
            }), {
                maxAge: 900000,
                httpOnly: true
            })`
    /admin (检查token)
    !cookies.token
