### ISSUE TITLE
怎么实现的滚动条自定义的啊，方便留个联系方式吗

### ISSUE THREAD

**Issue by dzfrontend** [zuiidea/antd-admin#752]

**Comment by zuiidea** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by superlbr** [comment]
@zuiidea 近期是否有更新的计划？比如菜单缓存、权限菜单用户管理、umi。。。

**Comment by superlbr** [comment]
@zuiidea 还有几点，希望也能改进下:
1. current: Number(payload.page) || 1 写成 current: Number(payload.page || 1 ) 会不会好一点
2. table里的update/delete，其实model里可以准确知道更新了什么数据，删了哪一行，尽量可以免刷
3. 嵌套子表格，如果加了List.less，子表格都会挤到一列，感觉global的写法不是很妥
4. Filter里的布局，如果内容较多，撑到多行的话，样式要调
5. 依赖，像egg.js引入的autod，比较方便更新版本

**Comment by zuiidea** [comment]
@superlbr 查收一下邮件
