### ISSUE TITLE
刷新空白页

### ISSUE THREAD

**Issue by chengxinjing** [zuiidea/antd-admin#753]
路由设置：
![image](https://user-images.githubusercontent.com/28032435/36717131-d30184d8-1bd7-11e8-801a-dca3f3a291fd.png)
正常点击可以出现
![image](https://user-images.githubusercontent.com/28032435/36717182-05946c9e-1bd8-11e8-8eb6-024887157b43.png)
手动刷新浏览器 这种路由（/customer/show）:不能够检测到pathname
![image](https://user-images.githubusercontent.com/28032435/36717198-191abe4e-1bd8-11e8-9b29-0d1f27d2f6dc.png)
手动刷新浏览器 这种路由（/customer）：能够出现检测到pathname

**Comment by superlbr** [comment]
不明所以，why not show a gif？

**Comment by chengxinjing** [comment]
just  want to show what happened  不知道为什么难道是我的路由有问题吗？  为什么 /customer/show 像这这样的路由在手动刷新的时候是空白页面  还有clone了你的原项目 启动 手动 刷新的时候总是会闪出404然后才出现刷新页面

**Comment by superlbr** [comment]
1. 路由确实有问题，Switch里面放的应该是Route，看源码
2. 闪出404很正常，因为开发环境，实际build出来没问题

**Comment by chengxinjing** [comment]
但是我换成源码路由 出现一样的问题啊  现在一切不都皆是组件吗？Switch应该能放除了Route之外的自定义组件吧 不然应该会报错吧？

**Comment by superlbr** [comment]
看控制台

**Comment by chengxinjing** [comment]
控制台没报错啊 这就尴尬了

**Comment by superlbr** [comment]
Network的记录看下，还有就是Route 加上exact看下

**Comment by chengxinjing** [comment]
刷新请求成功 但是加载不出js??是不是就是因为加载不出js 啊？

**Comment by chengxinjing** [comment]
但是要是 路由是/case 这样的就能加载出js 这问题会出在哪呢？

**Comment by superlbr** [comment]
加载不出js。。。network里请求不到还是没有请求
或者重新run dev下。。。

**Comment by chengxinjing** [comment]
刷新的时候没有请求js

**Comment by superlbr** [comment]
怀疑没有按源码的方式写，理论上App包裹的应该都会有请求

**Comment by chengxinjing** [comment]
确实没有按照源码一样去写 我自己再对比一下我App和你的APP有什么不一样的  谢谢耐心的指教

**Comment by superlbr** [comment]
不客气，正在写一个头疼的接口，路过。。。
