### ISSUE TITLE
动态加载models及路由时，npm run build打包不了，等了很久的时间报出内存溢出的错误！！！ failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by syaivin** [zuiidea/antd-admin#757]
![p](https://user-images.githubusercontent.com/13479047/36974210-cd7d8240-20b0-11e8-863d-82d045c8e311.png)

**Comment by superlbr** [comment]
建议排除法，上一次正常build起做了什么改动，是model还是路由还是动态加载的问题。经验看有可能是循环依赖

**Comment by syaivin** [comment]
先谢谢了，就是项目的模块越来越多了，就出现内存溢出的问题；想着改成动态加载model、路由，可是还是报内存溢出的问题。

**Comment by superlbr** [comment]
请附上动态加载的部分，另外可以参考ant-design-pro的写法https://pro.ant.design/docs/router-and-nav

**Comment by syaivin** [comment]
能加你ＱＱ，帮我看下这问题吗？

**Comment by superlbr** [comment]
1. 模块越来越多=>内存溢出，所以这是模块的问题，跟动态没有关系。。。请仔细排查近期改动的代码
2. 从未听说模块多，nodejs或者chrome内存溢出。。。

**Comment by syaivin** [comment]
@Baorong Li 
![default](https://user-images.githubusercontent.com/13479047/37018521-ab09f01e-214f-11e8-9d18-cd8c41460b55.png)

![default](https://user-images.githubusercontent.com/13479047/37018646-138334d4-2150-11e8-9313-82418527c1ff.png)

**Comment by superlbr** [comment]
1. 首先确保不加动态，正常
2. require.ensure。。。 你是参照什么文章，哪个思路来做动态
3. antd-admin这个示例其实就是动态，注意dynamic
     `routes.map(({ path, ...dynamics }, key) => (
              <Route key={key}
                exact
                path={path}
                component={dynamic({
                  app,
                  ...dynamics,
                })}
              />
            ))`
4. dva 的 dynamic 方法已经封装好了, 按需加载

**Comment by syaivin** [comment]
@superlbr 改动太大了，都整晕了；有调整内存限制的方法吗？找的资料都说加这个　--max-old-space-size ＝10000 加了没有用

**Comment by superlbr** [comment]
@syaivin 参考 https://github.com/webpack/webpack/issues/1914
回答带赞的关注下，有空我汇总下

**Comment by syaivin** [comment]
@superlbr  好的，谢谢您

**Comment by superlbr** [comment]
@syaivin 不客气，积累经验嘛

**Comment by superlbr** [comment]
推荐试试develop分支，umi自动打包

**Comment by Liqiankun** [comment]
我的也是这个问题! @superlbr @syaivin 你们是怎么解决的？

**Comment by superlbr** [comment]
@Liqiankun roadhog\dva版本更到最新，另外说一下做了什么样的改动触发的，不然很难定位

**Comment by QunxingHu** [comment]
关闭dynamic import,会解决这个问题，我使用的antd pro 1.3, 设置 disableDynamicImport =false的时候，就不会出现这个问题，但是这样编译出来的结果没有进行代码切割，会导致单个js文件过大

**Comment by lolieatapple** [comment]
我的方法是，修改node_modules/.bin/umi 文件在首行env node后面加上 --max-old-space-size=8192
