### ISSUE TITLE
本地运行刷新有样式错乱的闪屏

### ISSUE THREAD

**Issue by hahatiantang** [zuiidea/antd-admin#758]
本地运行刷新有样式错乱的闪屏是什么问题？

**Comment by superlbr** [comment]
开发环境中热更新导致的FOUC(flash of unstyled content)
参考: https://stackoverflow.com/questions/36453826/how-to-stop-fouc-when-using-css-loaded-by-webpack

**Comment by superlbr** [comment]
参考develop 分支, umi打包后没了，全屏loading
