### ISSUE TITLE
可以请教下，怎么在一个modal里面创建两个独立提交的表单吗？

### ISSUE THREAD

**Issue by laiyiyi** [zuiidea/antd-admin#759]
比如：
![image](https://user-images.githubusercontent.com/12541388/37144687-c3c41566-22f9-11e8-825f-81817a2c4d5b.png)

**Comment by superlbr** [comment]
1. 用一个表单可以解决，比如`{checkValue && <FormItem`
2. 根据checkValue切换表单（显示、提交值的判断），2个、3个、4个都ok
