### ISSUE TITLE
URL模式要改成hashHistory的在哪里改？

### ISSUE THREAD

**Issue by winnerwly** [zuiidea/antd-admin#761]
项目由于业务需要 要改成hashHistory模式的，项目要改的地方多吗

**Comment by superlbr** [comment]
导航出什么错？

**Comment by superlbr** [comment]
hashHistory 更换参考 https://pro.ant.design/docs/deploy-cn#%E5%9C%A8-Ant-Design-Pro-%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1

**Comment by winnerwly** [comment]
只能显示一个首页了，其他的都不显示了

**Comment by superlbr** [comment]
这边测下来没发现问题，建议去src/components/Layout/Bread.js里看看参数是否取值正常

**Comment by winnerwly** [comment]
头皮屑解决方法,
失效原因: let pathname = location.pathname 无法获取当前地址
解决方法:   let pathname = window.location.hash!=='/'?window.location.hash.slice(1).split('?')[0]:'/'

注: 我获取pathname的方法比较诡异,哪位兄弟有就给我推荐推荐

**Comment by superlbr** [comment]
windows环境？

**Comment by winnerwly** [comment]
@superlbr 谢谢了 我刚刚也找到那个地方了

**Comment by winnerwly** [comment]
嗯嗯

**Comment by winnerwly** [comment]
这个倒Linux上回出问题吗

**Comment by winnerwly** [comment]
我把window去掉了 一样跑

**Comment by superlbr** [comment]
实测可以用

**Comment by winnerwly** [comment]
嘻嘻
