### ISSUE TITLE
编译之后的 css 和 js 引用成相对路径

### ISSUE THREAD

**Issue by javahuang** [zuiidea/antd-admin#763]
您好，目前编译之后的js 和 css 都是绝对路径，如
``` html
<link href="/4.3.9/index.css?eafb51dd6a5a9997dca4" rel="stylesheet" />
<script type="text/javascript" src="/4.3.9/index.js?eafb51dd6a5a9997dca4" />
```
怎么修改成相对路径
``` html
<link href="./4.3.9/index.css?eafb51dd6a5a9997dca4" rel="stylesheet" />
<script type="text/javascript" src="./4.3.9/index.js?eafb51dd6a5a9997dca4" />
```

**Comment by superlbr** [comment]
为啥要改相对路径，要是我的话，直接ctrl+f替换...逃

**Comment by javahuang** [comment]
@superlbr 遇到一个奇葩的需求啊，要适配后端，没有走 nginx，直接将前端编译后代码整合到后端。
后端要通过 http://192.168.1.100:8080/app 的方式访问，如果是绝对路径的话，请求就成了 http://192.168.1.100:8080/4.3.9/index.css，而实际请求地址应该是  http://192.168.1.100:8080/app/4.3.9/index.css

**Comment by superlbr** [comment]
nginx代理过去不是更方便，后端是java？sprint boot都2.0了，可以考虑

**Comment by javahuang** [comment]
找到地方了，修改 .roadhogrc.js 的 publicPath。
