### ISSUE TITLE
layer组件弹层，外部属性值改变了，layer里面的数据层不会跟着变化

### ISSUE THREAD

**Issue by 31ui** [zuiidea/antd-admin#764]
dispatch({
        type: 'ArchivesManage/queryReportList',
      }).then(()=>{
      layer.open({
        title: '报表定义',
        content: <ListDefineTable {...ListDefineTableProps} />,
        width: '80%',
        wrapClassName: 'TableListWrap',
        maskClosable: true,
        cancelText: '取消',
        okText: '保存',
      });
});
外部ListDefineTableProps 状态属性值改变时，layer 内容不会跟着改变

**Comment by superlbr** [comment]
1. 没用过layer，建议用modal
2. dispatch里然后layer.open，这里的layer感觉就是临时添加的节点，ListDefineTableProps是一次性注入的
