### ISSUE TITLE
添加阿里的ali-oss插件后编译失败

### ISSUE THREAD

**Issue by cybibo** [zuiidea/antd-admin#768]
Failed to compile.

index.js from UglifyJs
Unexpected token: name (Mime) [index.js:62173,8]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qianquduo-admin@2.0.1 build: `roadhog build`
npm ERR! Exit status 1
npm ERR!

**Comment by superlbr** [comment]
分两步：
1. 无视错误编译出来，build 后面加个--watch，build success最后会卡住，ctrl +c就好了。原理就是毕竟是UglifyJs的锅
2. 分析这个问题，找到报错的地方，我贴出来吧，该不该找下ali-oss
`class Mime {
    constructor() {
      this._types = Object.create(null);
      this._extensions = Object.create(null);

      for (var i = 0; i < arguments.length; i++) {
        this.define(arguments[i]);
      }
    }`

**Comment by yzzting** [comment]
建议采用CDN的方式引入

**Comment by cybibo** [comment]
目前解决是采用CDN方式引入没问题。
@superlbr，对，就是这个地方报错,个人认为是不是该采用babel-loader

**Comment by superlbr** [comment]
云谦是打包大师，跟他提了一下，此issue不再跟踪，Close
@cybibo 可以贴下CDN怎么引入的，方便后来人
