### ISSUE TITLE
请问在components组件中编写的less文件，引入背景图，报错，这个怎么解决？

### ISSUE THREAD

**Issue by lilyAlucy** [zuiidea/antd-admin#77]
![image](https://cloud.githubusercontent.com/assets/9443129/23094268/8b8d1e00-f630-11e6-97ca-8c14df1d88e6.png)
![image](https://cloud.githubusercontent.com/assets/9443129/23094280/f98d62fc-f630-11e6-9939-9eba70f2e435.png)

**Comment by lilyAlucy** [comment]
引入路径是对的，但是却报模块没找到 @zuiidea

**Comment by liupeng110112** [comment]
试试 background: ~ "url()"  其他的issues可以找到

**Comment by zuiidea** [comment]
@lilyAlucy 亲测有效，https://github.com/zuiidea/antd-admin/commit/1f796a9a23ceee15f6cefff0f196f997ddbea1e6
