### ISSUE TITLE
能否加上多级嵌套路由和复杂交互处理的demo

### ISSUE THREAD

**Issue by fred1218** [zuiidea/antd-admin#771]
关于这个的处理：
- 基于dva动态加载 Model 和路由，按需加载。

---

目前也在用dva2，也使用了动态导入组件、动态注册model，但这样每次路由加载，或者路由改变，都会导致组件从使用了动态加载的地方开始就会重新创建，而不是re-render，这就导致了复杂交互的时候，类似页面刷新，比如滚动条会丢失，原先组件的state会丢失等等问题，很想看下兄弟关于这种问题的处理。

目前看到demo中对路由的处理还很简单，就一级，也不存在路由嵌套

**Comment by superlbr** [comment]
1. 这个分析不大对吧，滚动条会丢？state会丢？场景和条件要理清楚，才好对症下药
2. state不会丢，示例
![untitled](https://user-images.githubusercontent.com/8142164/38008601-2cc0b06e-3282-11e8-890d-27e7a1d1d4d6.gif)
3. 滚动条的位置，这个要这么看，react页面会怎么样？dva会怎么样？能不能把位置存到state里
滚动条不一定丢的，示例
![untitled](https://user-images.githubusercontent.com/8142164/38008635-5300c052-3282-11e8-9ea3-3be2c3caa554.gif)
不想打理路由，可以参考[umi-antd-admin](https://github.com/umijs/umi-antd-admin.git)

**Comment by fred1218** [comment]
有这么一个场景，首先我所有组件都是用dymamic，然后左边，是很长很长的menu，选择一个menuitem后，对应一个url。这个时候，点击右面某个按钮，打开另一组业务组件，对应的是url的改变。这个时候就发现，左边拉下来的滚动条，又回到了顶部。在constructor中调试，发现时每次都执行构造器，创建了，组件被重新创建，state一定丢失的

**Comment by superlbr** [comment]
state怎么会不在store里面呢。。。那state放在哪里？

**Comment by superlbr** [comment]
app实例启动后injectModel https://github.com/dvajs/dva/blob/585907c668c1c8ee5757a1a1050a157297623ad4/packages/dva-core/src/index.js#L73
dynamic 并未清空state https://github.com/dvajs/dva/blob/master/packages/dva/src/dynamic.js
dynamic 并没调用umodel，https://github.com/dvajs/dva/blob/master/packages/dva/src/dynamic.js，state还在

**Comment by superlbr** [comment]
@fred1218 滚动条这个东西，跟state有什么关系吗

**Comment by superlbr** [comment]
如果觉得路由、动态配置麻烦，参考develop分支，umi默认接管

**Comment by superlbr** [comment]
有关dva的，可以去问作者，微信号sorryccpro
