### ISSUE TITLE
如何 将打包得到的文件引用 配置成相对路径？

### ISSUE THREAD

**Issue by mengwuhen** [zuiidea/antd-admin#772]
![image](https://user-images.githubusercontent.com/22239802/38027039-f850f02a-32c0-11e8-9d0a-2809ba3ff105.png)
![image](https://user-images.githubusercontent.com/22239802/38026820-202bbbee-32c0-11e8-9670-4c1cc906fc93.png)
![image](https://user-images.githubusercontent.com/22239802/38027000-d0dca278-32c0-11e8-80c8-38aa287cb7e8.png)

 期望得到的dist文件 所有的文件引用都是相对路径，类似于上图中的。请问webpack该如何配置。现在打包得到的路径都是绝对路径，导致整个项目404，help。目前webpack的配置和本项目的配置文件一样，求助！！

**Comment by superlbr** [comment]
参考https://github.com/zuiidea/antd-admin/issues/641
