### ISSUE TITLE
关闭当前页面，如何清除本地的localStroage存储的数据？

### ISSUE THREAD

**Issue by mengwuhen** [zuiidea/antd-admin#773]
> 1. 功能需求 => 详细说明
 现在有个需求，需要在当前页面关闭关闭之前，清除本地localStroage存储的token。 目前操作如下图所示，
![image](https://user-images.githubusercontent.com/22239802/38082546-934bb1ec-3379-11e8-9523-018532277b29.png)

但是并没有起作用。 请问各位 这样操作问题出在哪里了？？  具体该如何操作？ @zuiidea @sven0726 @sorrycc

**Comment by superlbr** [comment]
1. 首先不是单纯html引入js文件，放在哪里都可以都能运行的。
2. 其次react组件要渲染才能输出html，那么也应该找个类似html的文件塞进去，比如entry.ejs, routes/app.js, 带div的
3. 建议localstorage放脱敏数据，比如文件配置等等。用户开控制台都能看清楚了，就失去了清除的意义。如果无法避免，那么是不是可以用完即销毁呢。
4. 如果是敏感数据，放session吧，或者至少加个密，或者来个token，不清除也无所谓
