### ISSUE TITLE
user页面，没有参数的情况下，只能返回10行，感觉默认参数并没有被传递，求大神指点

### ISSUE THREAD

**Issue by wangcplusplus** [zuiidea/antd-admin#774]
我理解models/user.js 27行
const payload = queryString.parse(location.search) || { page: 1, pageSize: 10 } 是想要赋给默认参数到后台，但实际上并没有工作，因为queryString.parse(location.search) !== false

**Comment by superlbr** [comment]
嗯，是没有传递
1. 写接口的都懂，就是不要相信传过来的参数。。。
2. 另外参考mock/user.js
   `GET ${apiPrefix}/users`  里面有` pageSize = pageSize || 10`

**Comment by scottming** [comment]
请问下 mock 目录下面的文件如何调试啊？ `console.log ` 但是 web console  和 终端都没有显示。
