### ISSUE TITLE
如果固定请求的地址，而只变更组件的部分

### ISSUE THREAD

**Issue by hehaibo** [zuiidea/antd-admin#775]
如果固定请求的地址，而只变更组件的部分：
现有的请求路径一进来就是：
http://antd-admin.zuiidea.com/dashboard
我期望的是
http://antd-admin.zuiidea.com/index.html#/dashboard
http://antd-admin.zuiidea.com/index.html#/user
http://antd-admin.zuiidea.com/index.html#/post

请大佬指点一二

**Comment by superlbr** [comment]
1. src/index.js
```
import hashHistory from 'history/createHashHistory'
import 'babel-polyfill'

// 1. Initialize
const app = dva({
  ...createLoading({
    effects: true,
  }),
  history: hashHistory(),
```
2. [文档] (https://react-guide.github.io/react-router-cn/docs/guides/basics/Histories.html)

**Comment by hehaibo** [comment]
react不懂，反正就是能模仿着做，不知道能不能提供段代码，感激不尽

**Comment by hehaibo** [comment]
谢谢！
