### ISSUE TITLE
一直弹对话框？

### ISSUE THREAD

**Issue by hehaibo** [zuiidea/antd-admin#779]
const List = ({
  onDeleteItem, onEditItem, isMotion, location, ...tableProps
}) => {
  location.query = queryString.parse(location.search)

  const handleMenuClick = (record, e) => {
    if (e.key === '1') {
      onEditItem(record)
    } else if (e.key === '2') {
      confirm({
        title: 'Are you sure delete this record?',
        onOk () {
          onDeleteItem(record.id)
        },
      })
    }
  }

将user/List.js
改动为
render: (text, record) => {
        return <div> <Button type="primary" onClick={handleMenuClick(record,{key:'2'})} style={{ marginLeft: 8 }}>下架</Button></div>
        //return <DropOption onMenuClick={e => handleMenuClick(record, e)} menuOptions={[{ key: '1', name: 'Update' }, { key: '2', name: 'Delete' }]} />
      },

渲染页面一直弹出兑换框？

**Comment by superlbr** [comment]
因为要这样写onClick={()=>handleMenuClick(record,{key:'2'})}

**Comment by hehaibo** [comment]
谢谢大佬
