### ISSUE TITLE
显示总条数 增加显示总页数，怎么写？这个不对

### ISSUE THREAD

**Issue by hehaibo** [zuiidea/antd-admin#782]
state: {
    list: [],
    pagination: {
      showSizeChanger: true,
      showQuickJumper: true,
      showTotal: (total, totalPage )=> (`共 ${total} 条 共{totalPage} 页`),
      current: 1,
      total: 0,
      totalPage: 0,
      pageSize: 10,
    },
  },

**Comment by hehaibo** [comment]
这个没办法自定义了？

**Comment by superlbr** [comment]
看[文档](https://ant.design/components/pagination-cn/#API) 示例:
`showTotal (total, range) { return `${range[0]}-${range[1]} of ${total} 项` }`
已经有了pageSize和total，页数可以算

**Comment by hehaibo** [comment]
多谢 
 showTotal: total => {
        let num=Math.ceil(total/10);

        return `共 ${total} 条，共 ${num} 页`
      },
