### ISSUE TITLE
develop分支无法运行

### ISSUE THREAD

**Issue by tianlinzx** [zuiidea/antd-admin#783]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
develop分支无法运行

> 2. Bug反馈
develop分支无法运行  
> 2.1 简单描述下报错 
` Failed to compile.
./src/layouts/app.js
Module not found: Can't resolve 'components' in '/Volumes/Data/github/antd/antd-admin/src/layouts'> `
>2.2 你期望什么结果  
正常启动服务
> 2.3 如何操作导致的  
`yarn 
umi dev`
> 2.4 可提供运行环境信息  
node 9.9
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
yarn start。。。
