### ISSUE TITLE
axios post提交spring中接收不到参数

### ISSUE THREAD

**Issue by hehaibo** [zuiidea/antd-admin#784]
@RequestMappting("/api/doLogin")
public Object doLogin(@RequestParam String username, @RequestParam String password) throws Exception {
  System.out.println("username: "+username);
  System.out.println("password: "+password);
  JSONObject json = new JSONObject();
  json.put("success", true);
  return json;
}

request.json 代码：
  axios.post('/api/doLogin', {
    usesrname: 'admin',
    password: 'admin'
  })

还有下面这个也是一样：

@RequestMappting("/api/saveData")
public Object doLogin(@RequestParam String data1, @RequestParam String data2) throws Exception {
.....
  return json;
}

  axios.post('/api/saveData', {
    data1: {
       name:"name",
      username:"username"   
    },
    data2: {
       key1:"key1",
      key2:"key2"   
    }
  })

jquery post 是可以的，请大神指导

**Comment by hehaibo** [comment]
网上说可以实现重写，但是在antd里面怎么重写？

**Comment by superlbr** [comment]
1. antd-admin的src/utils/request里可以改
2. java改个方法也不难，既然都node.js了，为啥不用个egg.js
[参考](https://www.jianshu.com/p/042632dec9fb)

**Comment by hehaibo** [comment]
这个egg能提供个例子么？这个完全不知道怎么引入 都是依葫芦画瓢

**Comment by superlbr** [comment]
1. java按@RequestBody去取值，上面链接例子也有
2. egg的例子，写个controller。。。
```
class UserController extends Controller {
  async login() {
    const { ctx } = this
    const { username, password } = ctx.request.body
    ctx.body = { username, password }
  }
}
```

**Comment by hehaibo** [comment]
谢谢大佬指点
