### ISSUE TITLE
这个框架里面判断typeof数据类型都是object?

### ISSUE THREAD

**Issue by hehaibo** [zuiidea/antd-admin#785]
console.log(typeof cloneData)

 return request({
    url: onUpdateSchemeUrl,
    method: 'post',
    data: [1,3,3],
  })

打印确输出 object?

**Comment by superlbr** [comment]
有什么问题,data是object没毛病

**Comment by hehaibo** [comment]
怎么不能判断为数组？

**Comment by superlbr** [comment]
问度娘。typeof能不能判断数组？js里的object指的是什么？

**Comment by hehaibo** [comment]
谢谢大佬
