### ISSUE TITLE
请教下：pagination分页默认是10，20，30，40 ，我看文档，可以通过pageSizeOptions 这个参数调整选项，但是怎么修改后面的单位显示啊，谢谢，默认是条/页，但是antd-admin 显示/page ，求帮助呀

### ISSUE THREAD

**Issue by wangcplusplus** [zuiidea/antd-admin#787]
还有就是默认值是在哪里声明的呀

**Comment by superlbr** [comment]
1. page => 页，即[中文化](https://ant.design/components/locale-provider-cn/)
2. 默认值 指的是条/页？参考：
    a. 自定义[jumper](https://codepen.io/afc163/pen/brddvO?editors=0010) [出处](https://github.com/ant-design/ant-design/issues/6970#issuecomment-318039942)
    b. 修改[文字](https://github.com/ant-design/ant-design/issues/6013)

**Comment by wangcplusplus** [comment]
多谢指导
