### ISSUE TITLE
怎样禁止每次浏览器刷新需要重新登录

### ISSUE THREAD

**Issue by chaijinsong** [zuiidea/antd-admin#789]
> 1. 功能需求 => 点击浏览器的刷新按钮不跳转到登录页面，而是刷新本页面
> 2. Bug反馈  
> 2.1 点击浏览器的刷新按钮都会重新跳转到登录页面
> 2.2 不跳转登录页面，而是刷新本页面
> 2.3 点击浏览器刷新按钮
> 2.4 google

**Comment by superlbr** [comment]
1. 是本项目？是否DIY？
2. 是否开启无痕浏览，隐私浏览？更换浏览器呢？
3. 这边测下来并没有出现这个问题

**Comment by chaijinsong** [comment]
是项目之前的作者进行了DIY，不是dva的问题。

**Comment by superlbr** [comment]
参考mock.js对token的设置和检查
