### ISSUE TITLE
用户列表样式问题

### ISSUE THREAD

**Issue by icowan** [zuiidea/antd-admin#79]
![](http://source.lattecake.com/images/2017/02/c7/1b/55/c8/20170221-b287836626c7505c5e43b1221bb115f1c80c76a1.jpeg?imageView2/2/w/1280)

**Comment by zuiidea** [comment]
这个应该是由于为了添加动画修改了Table的样式使用了部分css3，你的浏览器可能版本过低，可以升级一下浏览器，或者在修改user/list组件不用动画， 后面处理一下哈

**Comment by icowan** [comment]
浏览器是chrome 最新版 56.0.2924.87 (64-bit)

**Comment by zuiidea** [comment]
@icowan 找到原因了，最新的antd的Table组件设置了scroll.x属性后就会这样，你可以暂时把scroll.x属性注释
https://github.com/ant-design/ant-design/issues/4976

**Comment by afc163** [comment]
<img width="1149" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23245503/eaa78098-f9c7-11e6-8c2a-b352c88a23d7.png">
