### ISSUE TITLE
能不能将这个项目兼容下ssr功能？目前网上存在的ssr看着很吃力

### ISSUE THREAD

**Issue by manuo123** [zuiidea/antd-admin#790]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 目前我们的网站是根据antd-admin引用过来的，但是，现在公司网站需要seo，所以需要做服务器端渲染，但网上资料太少，所以不知道该怎么做，希望能将antd-admin这个项目兼容下服务器端渲染的功能。

**Comment by superlbr** [comment]
1. antd是中后台组件，这是一。中后台seo是很奇怪的
2. ssr更多看底层支持类似next.js，可以尝试
3. antd-admin采用umi作为打包支持，跟umi保持一致，短期不支持
参考 https://github.com/umijs/umi/issues/79

**Comment by superlbr** [comment]
glad to see ssr in roadmap https://github.com/umijs/umi/issues/628
