### ISSUE TITLE
请教下有没有结合react，dva的流程图组件，还有gantt图的组件呀,或者demo啥的

### ISSUE THREAD

**Issue by wangcplusplus** [zuiidea/antd-admin#792]
我看antd 没有做像jsplump，gantt这些组件

**Comment by superlbr** [comment]
1. 这种找react版本就好了，参考src/components写法自行引入 [react-jsplump](https://github.com/gyk001/react-jsplumb) [react-gantt](https://github.com/hustcc/gantt-for-react)
2. 百度[echarts](http://echarts.baidu.com/examples/#chart-type-graph) ，阿里[G6](https://github.com/antvis/g6)都有图表的支持，给你个[示例](https://codesandbox.io/s/p3jry6w230)，抛砖引玉
