### ISSUE TITLE
启动项目是   npm start

### ISSUE THREAD

**Issue by martinwithyou** [zuiidea/antd-admin#796]
启动项目是npm start

不是作者提到的这个 npm run dev

> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
ReadMe的描述蛮清楚的呀。。。
npm start虽然可以一步到位，但是 roadhog buildDll 并不需要每次都运行
