### ISSUE TITLE
请教下，这里这样传值是有啥问题吗，传不过去呢~

### ISSUE THREAD

**Issue by laiyiyi** [zuiidea/antd-admin#797]
在/routes/app.js   传了一个 abc
![image](https://user-images.githubusercontent.com/12541388/38595864-b661e3e8-3d80-11e8-984d-d261ec6e7b0f.png)

在内容页面
![image](https://user-images.githubusercontent.com/12541388/38595881-cf5ad99a-3d80-11e8-8a5e-dc6feab9adde.png)
![image](https://user-images.githubusercontent.com/12541388/38595884-d86b519a-3d80-11e8-96f5-519d497ac623.png)
打印还是  undefined

**Comment by superlbr** [comment]
去看看sysUser里有没有

**Comment by laiyiyi** [comment]
@superlbr   就是不想在sysUser再存state呀，这个参数希望通过这一个地方设置，所有页面都能取到

**Comment by superlbr** [comment]
1. 所有页面都能取到，这个值放state是否合理
2. 左侧切换主题，切换其他页面，主题色并没有改变，这state是咋回事
3. 为啥登录之后，切换其他页面，就不需要登录了

**Comment by laiyiyi** [comment]
@superlbr 这个值是app里的state，每次页面变化都会去改变它，至于要不要登录，这请求api的时候，在后台就处理了，无效的登录肯定会相应返回。就是这个值每个页面都需要，所以不想每个页面的state又存一遍；

**Comment by superlbr** [comment]
再稍稍考虑下吧
