### ISSUE TITLE
代码有歧义，不方便他人阅读和理解：Dashboard.propTypes = {   dashboard: PropTypes.object,   loading: PropTypes.object, }

### ISSUE THREAD

**Issue by martinwithyou** [zuiidea/antd-admin#798]
Dashboard.propTypes = {
  dashboard: PropTypes.object,
  loading: PropTypes.object,
}

export default connect(({ dashboard, loading }) => ({ dashboard, loading }))(Dashboard)

这一段代码的意思是？
感觉表达的不是太好理解。。。。

> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by martinwithyou** [comment]
这一段代码 ，在  src  ====  routes  ==== dashboard  ==== index.js.

**Comment by martinwithyou** [comment]
在这个路径的文件下。

**Comment by superlbr** [comment]
1. antd-admin基于dva，connect及更多参考 [文档](https://github.com/dvajs/dva/blob/master/README_zh-CN.md)
2. propTypes类型检查，参考 [文档](https://github.com/facebook/prop-types)
