### ISSUE TITLE
还有就是代码结构的问题了，我觉得在model文件夹下dashboard.js里面你，直接调用app.js 。。。。。这样真的好吗？他人阅读时会觉得结构不清晰，我个人觉得一个视图，对应一个model,   这个model里面包含对于视图所有的方法和属性，而不是这个model再去调取其他model文件的方法，况且这些属性本来就不是公用，是dashboard私有的。

### ISSUE THREAD

**Issue by martinwithyou** [zuiidea/antd-admin#799]
* queryWeather ({
      payload = {},
    }, { call, put }) {
      payload.location = 'shenzhen'
      const result = yield call(weatherService.query, payload);
      console.log(">>>>>>>>>>>>>");
      console.log(result);
      console.log(">>>>>>>>>>>>>");
      const { success } = result
      if (success) {
        const data = result.results[0]
        const weather = {
          city: data.location.name,
          temperature: data.now.temperature,
          name: data.now.text,
          icon: `//s5.sencdn.com/web/icons/3d_50/${data.now.code}.png`,
        }
 console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        yield put({
          type: 'updateState',
          payload: {
            weather,
          },
        })
console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
      }
    },
  },

还有就是代码结构的问题了，我觉得在model文件夹下dashboard.js里面你，直接调用app.js 。。。。。这样真的好吗？他人阅读时会觉得结构不清晰，我个人觉得一个视图，对应一个model,   这个model里面包含对于视图所有的方法和属性，而不是这个model再去调取其他model文件的方法，况且这些属性本来就不是公用，是dashboard私有的。

> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by martinwithyou** [comment]
console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
yield put({
type: 'updateState',
payload: {
weather,
},
})
console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
不是很能理解，为什么去把改变state的reducer的方法，放在公共的app.js里面？
？
?

**Comment by superlbr** [comment]
1. app.js承载了layout，dashboard作为页面，model、route视图、service都有分开
2. 如果有更好的组织方法，欢迎PR
3. reducer的拆分、组合有很多妙用的，不要局限

**Comment by martinwithyou** [comment]
我明白你的意思，你觉得我的用法太有局限性，但是如果大型项目，这样随便调用其他model里面的reducer方法，难免会显得有一些 “拎不清....................”，第一次看你的项目，我就看得dashboard，我找“updateState”这个方法，就是在model文件夹下       dashboard.js  里面没找到。由于项目文件太多，我用了全局搜索才看到“updateState”这个方法， 然后我还要顺腾摸瓜，一步一步找，去怎么调用这个方法的..........我是从一个开发者的角度来说的。谢谢。

**Comment by superlbr** [comment]
提问要切中肯綮，updateState是因为dashboard.js作为model使用dva-model-extend继承了common.js
