### ISSUE TITLE
mac、safari环境下，缩略菜单显示时会闪现两次

### ISSUE THREAD

**Issue by huangxingpark** [zuiidea/antd-admin#80]
菜单显示如下图所示，请问其他人有没有遇到相同的情况？
GIF显示的比较快，实际上菜单会展开两次。

![menudoubleflash](https://cloud.githubusercontent.com/assets/8498206/23200250/3bda494c-f90e-11e6-977e-3884984e4347.gif)

**Comment by zuiidea** [comment]
因为没有mac，所以没办法复现，你可以试试把子菜单附近的css动画的`transition-duration`值改大一点，调试一下

**Comment by TangMonk** [comment]
同样遇到了这个问题

**Comment by zuiidea** [comment]
@TangMonk，没有mac，能否PR，🙃

**Comment by TangMonk** [comment]
@zuiidea 我是搞后台的。。不太会写css啊
