### ISSUE TITLE
还是dashboard,为啥在视图里面直接调用接口？

### ISSUE THREAD

**Issue by martinwithyou** [zuiidea/antd-admin#800]
<Col lg={24} md={12}>
              <Card bordered={false}
                className={styles.weather}
                bodyStyle={{
                  padding: 0,
                  height: 204,
                  background: color.blue,
                }}
              >
                <Weather {...weather} loading={loading.effects['dashboard/queryWeather']} />
              </Card>
            </Col>
还有，
 I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.
这句话是玛丽莲梦露说的，我读书少，不要骗我。

> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
哪里调用接口？那是传参。。。
loading.effects算function

**Comment by superlbr** [comment]
多看文档，基础扎实很重要

**Comment by martinwithyou** [comment]
这不是在逐步了解嘛。。。。。

**Comment by martinwithyou** [comment]
我看的比较细
