### ISSUE TITLE
我觉得你这个开源项目很不错，可以和蚂蚁金服官方出的“ant design pro”相媲美，我昨天下午都看完你的dashboard, 文件夹下面的所有业务的UI组件，其他都挺好的，但是有一点我不能理解，为什么首页都用recharts?

### ISSUE THREAD

**Issue by martinwithyou** [zuiidea/antd-admin#802]
recharts堪称是声明是图表库，

它是react生态体系里面的吗？

对于国内很火的echarts,
对于国外很火的high-charts,
它的优缺点在于哪呢？

> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
1. 题目与问题无关，这种提问效率很低
2. 优缺点不重要，合适才是最好的，演示而已不用纠结

**Comment by martinwithyou** [comment]
。。。。。。我闭嘴，好了吧。。。。

**Comment by superlbr** [comment]
这个项目不是我的，只是维护而已，目前来说，并不满意
缺实践场景，比如复杂的组件嵌套、调用ant design pro之类
写法有待优化，样式也有些问题

**Comment by superlbr** [comment]
少年，欢迎PR

**Comment by martinwithyou** [comment]
ok,我最近刚好比较有空，在看看你们这个项目， antd-admin,  希望大家可以github这个自由的社区里面，可以讨论自己想要讨论的点。
