### ISSUE TITLE
关于组件的耦合的问题

### ISSUE THREAD

**Issue by martinwithyou** [zuiidea/antd-admin#803]
import React from 'react'
import PropTypes from 'prop-types'
import { routerRedux } from 'dva/router'
import { connect } from 'dva'
import { Row, Col, Button, Popconfirm } from 'antd'
import { Page } from 'components'
import queryString from 'query-string'

import List from './List'
import Filter from './Filter'
import Modal from './Modal'

const User = ({
  location, dispatch, user, loading,
}) => {
	
//	console.log("====================================");
//	console.log("location",location);
//	console.log("dispatch",dispatch);
//	console.log("user",user);
//	console.log("loading",loading);
//	console.log("queryString",queryString);
//	console.log("====================================");

  location.query = queryString.parse(location.search)
  const { query, pathname } = location
  const {
    list, pagination, currentItem, modalVisible, modalType, isMotion, selectedRowKeys,
  } = user

  const handleRefresh = (newQuery) => {
    dispatch(routerRedux.push({
      pathname,
      search: queryString.stringify({
        ...query,
        ...newQuery,
      }),
    }))
  }
  
  

  
  
  const modalProps = {
    item: modalType === 'create' ? {} : currentItem,
    visible: modalVisible,
    maskClosable: false,
    confirmLoading: loading.effects[`user/${modalType}`],
    title: `${modalType === 'create' ? 'Create User' : 'Update User'}`,
    wrapClassName: 'vertical-center-modal',
    onOk (data) {
      dispatch({
        type: `user/${modalType}`,
        payload: data,
      })
        .then(() => {
          handleRefresh()
        })
    },
    onCancel () {
      dispatch({
        type: 'user/hideModal',
      })
    },
  }

  const listProps = {
    dataSource: list,
    loading: loading.effects['user/query'],
    pagination,
    location,
    isMotion,
    onChange (page) {
      handleRefresh({
        page: page.current,
        pageSize: page.pageSize,
      })
    },
    onDeleteItem (id) {
      dispatch({
        type: 'user/delete',
        payload: id,
      })
        .then(() => {
          handleRefresh({
            page: (list.length === 1 && pagination.current > 1) ? pagination.current - 1 : pagination.current,
          })
        })
    },
    onEditItem (item) {
      dispatch({
        type: 'user/showModal',
        payload: {
          modalType: 'update',
          currentItem: item,
        },
      })
    },
    rowSelection: {
      selectedRowKeys,
      onChange: (keys) => {
        dispatch({
          type: 'user/updateState',
          payload: {
            selectedRowKeys: keys,
          },
        })
      },
    },
  }

  const filterProps = {
    isMotion,
    filter: {
      ...query,
    },
    onFilterChange (value) {
      handleRefresh({
        ...value,
        page: 1,
      })
    },
    onAdd () {
      dispatch({
        type: 'user/showModal',
        payload: {
          modalType: 'create',
        },
      })
    },
    switchIsMotion () {
      dispatch({ type: 'user/switchIsMotion' })
    },
  }

//console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
//console.log(filterProps);
  //onAdd,
  //isMotion,
  //switchIsMotion,
  //onFilterChange,
  //filter,
//console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
  
  const handleDeleteItems = () => {
    dispatch({
      type: 'user/multiDelete',
      payload: {
        ids: selectedRowKeys,
      },
    })
      .then(() => {
        handleRefresh({
          page: (list.length === selectedRowKeys.length && pagination.current > 1) ? pagination.current - 1 : pagination.current,
        })
      })
  }

  return (
    <Page inner>
      <Filter {...filterProps} />
      {
        selectedRowKeys.length > 0 &&
        <Row style={{ marginBottom: 24, textAlign: 'right', fontSize: 13 }}>
          <Col>
            {`Selected ${selectedRowKeys.length} items `}
            <Popconfirm title="Are you sure delete these items?" placement="left" onConfirm={handleDeleteItems}>
              <Button type="primary" style={{ marginLeft: 8 }}>Remove</Button>
            </Popconfirm>
          </Col>
        </Row>
      }
      <List {...listProps} />
      {modalVisible && <Modal {...modalProps} />}
    </Page>
  )
}

User.propTypes = {
  user: PropTypes.object,
  location: PropTypes.object,
  dispatch: PropTypes.func,
  loading: PropTypes.object,
}

export default connect(({ user, loading }) => ({ user, loading }))(User)

关于user.js的组件之间的耦合性过重的问题，
import List from './List'
import Filter from './Filter'
import Modal from './Modal'

这3个组件，
所有的属性和方法，
都是父组件提供的，
我觉得这个做不合理，
没有解耦，
子组件，离开父组件就没有办法正常工作了，
我觉得组件之间应该是有自己的独立性的，
就是有自己的css,  uiComponnet,   state.    function,
自己有状态管理的model， service,

而并不是以上的所有都要依赖父组件。
离开父组件没有办法工作，
耦合性太强。。。。

> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
既然你觉得不合理，能不能优化下咧？

**Comment by superlbr** [comment]
耦合这个概念很容易扯皮，https://www.zhihu.com/question/21386172?sort=created

**Comment by martinwithyou** [comment]
现在虽然都是组件化开发前端项目，
但是我个人觉得组件化的意义就是解耦，
很多私有属性和方法，就是放在组件内部，
公共的属性和方法放在dva框架的model里面。

**Comment by martinwithyou** [comment]
个人喜好吧，
这个世界上并没有统一的标准，
就是看什么情况下，
哪种解决方案更加的合理。
ok。

**Comment by superlbr** [comment]
List拿出来估计就是想抽象下，看ant-design-pro直接all in one。。。

**Comment by martinwithyou** [comment]
恩。。。。
