### ISSUE TITLE
User页面， motion这个按钮是什么作用呢？

### ISSUE THREAD

**Issue by martinwithyou** [zuiidea/antd-admin#804]
window.localStorage.setItem(`${prefix}userIsMotion`, !state.isMotion)

我找到了它在localstorage里面设置的代码.

但是它在整个项目里面的作用是？

antdAdminuserIsMotion。

> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
涉及列宽的调整，个人觉得有些鸡肋

**Comment by martinwithyou** [comment]
好吧。
怪不得每次调一下，
列表就抖抖抖。。。。。。一下。
别的也没发现有啥不一样。
