### ISSUE TITLE
关于‘’antdAdmindarkTheme“， 设置为黑色主题后，只有侧边栏被成黑色主题，其他还是白色主题。

### ISSUE THREAD

**Issue by martinwithyou** [zuiidea/antd-admin#805]
我觉得这是个bug
谢谢。

> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
这是ant.desgin的效果，直接调的，当然你也可以改，[文档](https://ant.design/components/menu-cn/#components-menu-demo-theme)

**Comment by martinwithyou** [comment]
好吧， 一般都是整个网站都变颜色， 这是我们前端从用户体验的角度给出的个人建议，
当然，现在这样也是OK 的。
