### ISSUE TITLE
有人跟我一样吗，打开http://localhost:8000是一片空白

### ISSUE THREAD

**Issue by davychan1985** [zuiidea/antd-admin#807]
如题

**Comment by superlbr** [comment]
请问localhost是哪里来的，哪里有提示访问localhost?

**Comment by davychan1985** [comment]
你好，是readme.md说明文档那里这样写的-----------
开发：
npm run build:dll #第一次npm run dev时需运行此命令，使开发时编译更快
npm run dev
打开 http://localhost:8000

**Comment by superlbr** [comment]
1. 建议使用yarn安装依赖
2. 看下终端或者控制台怎么提示的, 是否有报错? 入口不一定是localhost，0.0.0.0, 127.0.0.1都有可能

**Comment by davychan1985** [comment]
cnpm、yarn我都试了。
然后在命令行依次输入：npm run build:dll和npm run dev。
终端提示：
The app is running at:
http://0.0.0.0:8000/

最后访问http://0.0.0.0:8000/时，浏览器提示页面载入出错。

**Comment by davychan1985** [comment]
而且node_modules我都是整个删了，重装依赖的

**Comment by superlbr** [comment]
浏览器载入出错是什么意思? 浏览器控制台有报错吗

**Comment by davychan1985** [comment]
Firefox 无法建立到 0.0.0.0:8000 服务器的连接。

**Comment by davychan1985** [comment]
我的npm全局有webpack3.x、webpack-dev-server有影响吗

**Comment by superlbr** [comment]
windows? chrome呢?
网站确实跑起来了呀

**Comment by superlbr** [comment]
是不是开了什么代理

**Comment by davychan1985** [comment]
没开代理。我先重新clone一份，重头弄一遍，看看有什么问题先。

**Comment by superlbr** [comment]
可以试一下develop分支喔
