### ISSUE TITLE
请教一个modal的问题

### ISSUE THREAD

**Issue by wangcplusplus** [zuiidea/antd-admin#808]
我在modal组件上，想动态添加数据(弹出新的modal添加数据)，如果填加的数据以table的形式呈现在modal中，提交外部modal的时候，怎么能够获取到table的数据呀
![image](https://user-images.githubusercontent.com/24887460/38853207-1251fa44-424f-11e8-8020-f5ee204e058a.png)

**Comment by superlbr** [comment]
把table的数据放state里呗
