### ISSUE TITLE
dva/ router 如何监听路由离开

### ISSUE THREAD

**Issue by 31ui** [zuiidea/antd-admin#809]
当切换路由时对要弹出对话框确定是否跳转的判断
以下写法无法实现效果
const routerWillLeave=(nextLocation) => {
        console.log('react router 路由跳转=======>', nextLocation);
        return false;
      }
 <Route  routerWillLeave={routerWillLeave}  path={path}  component={component}/>

**Comment by superlbr** [comment]
印象中antd-admin里的页面基本是无状态组件，要改写成react.components吧

**Comment by 31ui** [comment]
dva/router 没有看到有监听 离开的钩子

**Comment by superlbr** [comment]
dva使用的应该是react-router v4, so check下 [文档](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md#on-properties)
dva/router本质上还是react-router的封装
