### ISSUE TITLE
如何渲染从后台查询出的html文本到前端，按照html解析，而不是显示标签

### ISSUE THREAD

**Issue by hehaibo** [zuiidea/antd-admin#811]
请教大佬如何渲染从后台查询出的html文本到前端，按照html解析，而不是显示标签

**Comment by superlbr** [comment]
参考 React [文档](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)

**Comment by superlbr** [comment]
另附上：[Set innerHTML vs dangerouslySetInnerHTML
](https://stackoverflow.com/questions/37337289/react-js-set-innerhtml-vs-dangerouslysetinnerhtml)
