### ISSUE TITLE
有qq群吗

### ISSUE THREAD

**Issue by 107295472** [zuiidea/antd-admin#813]
群里好沟通

**Comment by superlbr** [comment]
我建了一个gitter， https://gitter.im/antd-admin/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by 107295472** [comment]
https://github.com/bowencool/dva-antd-admin  这人是不是用你的代码改的

**Comment by 107295472** [comment]
Failed to start the server, since you have enabled dllPlugin, but have not run `roadhog buildDll` before `roadhog server`.

**Comment by 107295472** [comment]
https://github.com/pmg1989/dva-admin  还有这个

**Comment by superlbr** [comment]
互相借鉴，各取所需

**Comment by superlbr** [comment]
https://github.com/umijs/umi
