### ISSUE TITLE
请问为什么本地跑项目会有闪屏的现象？

### ISSUE THREAD

**Issue by JarVan007** [zuiidea/antd-admin#814]
您线上例子进入登陆的时候都没问题，先Loading 再出现登陆框，但是本地跑起来项目之后，进入登陆界面的时候右上角会闪屏没有CSS的HTML是怎么回事呢？能否解答一二，谢谢~

**Comment by superlbr** [comment]
提问前，最好看看有没有类似的提问。
抱歉，不再回答这个问题，谢谢。
https://github.com/zuiidea/antd-admin/issues/758

**Comment by JarVan007** [comment]
嗯，谢谢
