### ISSUE TITLE
add jest and enzyme

### ISSUE THREAD

**Issue by fadiquader** [zuiidea/antd-admin#815]
Hi man,
i have setup jest and enzyme, but the problem here. when i run command roadhog test it gives me error
```
react' is not recognized as an internal or external command,
operable program or batch file.
```
is there anyway to configure this dashboard with jest and enzyme.

thank you

**Comment by superlbr** [comment]
1. just tips, I'm not familiar with that. just take the way of [ant design pro](https://github.com/ant-design/ant-design-pro), little difference, for ant-design-pro uses [roadhog](https://github.com/sorrycc/roadhog) v2, but this project use v1.
2. the master branch is little outdated, you could try develop branch, it uses [umi](https://umijs.org/en/). here's the [test case](https://github.com/umijs/umi/tree/master/packages/umi-test)

**Comment by fadiquader** [comment]
@superlbr 
thank you,
as you said, it os outdated, i will try  roadhog v2
