### ISSUE TITLE
effect中按给出的条件结束轮询

### ISSUE THREAD

**Issue by qingjiaowochengzd** [zuiidea/antd-admin#816]
*foo_effect ({ payload }, { put, select }) {
const { synchromng } = yield(select(_ => _))
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
console.log('444', synchromng.dealallover, synchromng.enableFetch)
let num = 1
while (num === 1) {
if (synchromng.enableFetch) {
yield put({ type: 'getsynchrolist', payload: { filter: { page: 1, per_page: 10 } } })
}
yield delay(10000)
}
},
大致讲下我的需求：
我想根据接口返回信息的某字段判断是否轮询，但enableFetch改为了false，接口还是在调，而且是刚一触发getsynchrolist，就狂调接口，一秒钟20次的样子。试了sega的cancel也取消不掉。求解？
如果没办法，有别的思路可以做吗？

**Comment by qingjiaowochengzd** [comment]
@superlbr 我是要根据接口返回信息来决定是否要settimeout，放在组件中数据会渲染多次，settimeout也会多次被调用

**Comment by superlbr** [comment]
调接口不一定要放在model里，接口返回信息可以调用不同的function呀, 修改了model里的数据，当然会触发渲染
参考:
https://github.com/zuiidea/antd-admin/blob/9fd0abe6ea4af6ddfea1c0ae6f22d24dbb00fde7/src/routes/request/index.js#L117-L134

**Comment by superlbr** [comment]
没反馈，close啦
