### ISSUE TITLE
超过十个项目的二级菜单或者三级菜单？

### ISSUE THREAD

**Issue by zcm211** [zuiidea/antd-admin#818]
显示不出来，求解

**Comment by superlbr** [comment]
请提供更多信息，比如最小可现截图、代码等，不然无法定位，本地这边测试正常

**Comment by zcm211** [comment]
主要是不知道三级菜单的格式

demo里面的 id 或者mpid 是010 那是二级菜单的第十个，还是三级菜单的第0个item呢？
