### ISSUE TITLE
npm start 后，谷歌浏览器可以正常使用，火狐浏览器报错不显示！

### ISSUE THREAD

**Issue by syaivin** [zuiidea/antd-admin#819]
![qq 20180512172608](https://user-images.githubusercontent.com/13479047/39955936-1203fde8-560a-11e8-8dd1-b4ddfebee7bf.jpg)

@zuiidea

**Comment by superlbr** [comment]
zuiidea不活跃了呢。。。
猜测八成是语法错误，这边git clone master下来run没有报错

**Comment by syaivin** [comment]
@superlbr 谷歌浏览器运行是正常的，是不是 roadhog 升级到 "roadhog": "^1.3.1" 原因，"0.0.Ｘ"版火狐是可以显示正常的，是没关闭严格模式吗？要怎么取消呢？
![qq 20180512174405](https://user-images.githubusercontent.com/13479047/39956095-7ddb6518-560c-11e8-8e08-7b4192cd2a7f.jpg)

**Comment by superlbr** [comment]
0.0. X 版？跟火狐版本有关系，这锅就不背了。
[报错参考] (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_initializer_in_const)
