### ISSUE TITLE
Develop 分支无法运行

### ISSUE THREAD

**Issue by scottming** [zuiidea/antd-admin#821]
### 运行环境

* node: v10.0.0
* npm: 6.0.1

### 具体问题

切换到  develop 分支，运行 `cnpm install`，然后 `npm start`:

有一个 warning: 

```
./src/components/DataTable/DataTable.js
  Line 9:  componentWillReceiveProps is deprecated since React 16.3.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops  react/no-deprecated
```
但这个应该不是主要原因，打开 localhost:8000 后，无任何内容显示，有以下报错：

![image](https://user-images.githubusercontent.com/12830256/40046726-41df0014-5860-11e8-977e-629465ff57c6.png)

**Comment by MMMystery** [comment]
根节点没渲染出来，只能两种原因了：
1.代码格式有问题，导致根节点的代码都不能渲染。
2.楼上哥们说的那种，可能是node版本太高，造成渲染有问题。

**Comment by scottming** [comment]
![image](https://user-images.githubusercontent.com/12830256/40048031-c53bb1f2-5863-11e8-9445-92c69aa597c8.png)

```
$ node -v
v8.11.1
$ npm -v
5.6.0
```
回退到了 8.11.1 稳定版，还是有这个问题。

**Comment by superlbr** [comment]
node版本回退之后，建议删掉node_modules, 重新install.
umi is not defined，有点在意，试试yarn install呢

**Comment by scottming** [comment]
删过了，也用过 yarn 了，还是报这个错。

**Comment by scottming** [comment]
```
"umi-plugin-dll": "^0.2.0"
```
这个插件更新之后就可以了，云谦刚刚给的方案。

**Comment by superlbr** [comment]
umi 1.3.0刚出来惹的祸，不背锅

**Comment by scottming** [comment]
但我的 umi 还是 1.2.6 呢。

**Comment by superlbr** [comment]
develop没锁版本，如果node_modules都是如下版本，应该是ok的，毕竟生产环境不会说谎
https://github.com/zuiidea/antd-admin/blob/c66f086f426a9618c2b0711254cc629848827189/package.json#L50-L53
