### ISSUE TITLE
mock部分代码不能实时更新

### ISSUE THREAD

**Issue by devuser** [zuiidea/antd-admin#822]
注意到修改mock文件夹下的代码，控制台不能实时更新，这是什么问题呢？
怎么破？

**Comment by superlbr** [comment]
1. 当修改mock文件夹下某一文件，会有变动提示，例如 `CHANGED ./src/mock/menu.js`
2. 确实更新了，由于不是页面变动，不会刷新页面，只是第二次请求的时候，会产生变动
