### ISSUE TITLE
生成api文档 

### ISSUE THREAD

**Issue by mengchen007** [zuiidea/antd-admin#823]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明 怎么生成api文档 还需要添加什么配置

> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
生成api文档，添加配置。。。，还是做好另开一个项目的准备吧

a. 托管[省力的选项]
  1. github wiki
  2. gitbook
  3. 云雀

b. 自建[参考开源项目]
  1. 模仿ant.design生成文档 [bisheng-antd-doc](https://github.com/wuguanghai45/bisheng-antd-doc-template)
  2. [slate](https://github.com/lord/slate)
  3. [api-json](https://github.com/TommyLemon/APIJSON)
  4. [showdoc](https://github.com/star7th/showdoc.git)
