### ISSUE TITLE
centos7 npm run 不起来没有错误信息

### ISSUE THREAD

**Issue by MikeDGitHub** [zuiidea/antd-admin#824]
![image](https://user-images.githubusercontent.com/21699169/40174425-9d093d94-5a07-11e8-9a43-ada6203279ca.png)

**Comment by superlbr** [comment]
1. 第一张图提示已经说了，还需要执行下yarn build:dll
2. 另外当前不推荐node v10

**Comment by MikeDGitHub** [comment]
我切换到8.9.3也不行。。。。。。

**Comment by superlbr** [comment]
切换之后，删掉node_modules，重新install

**Comment by MikeDGitHub** [comment]
关键是我在mac和win10上都没问题到centos上就不行了。。。。

**Comment by superlbr** [comment]
关掉selinux试试，暂时手上没有centos，debian是ok的

**Comment by MikeDGitHub** [comment]
好的，我试试去

**Comment by superlbr** [comment]
应该是依赖的关系，用yarn
![1526714691421](https://user-images.githubusercontent.com/8142164/40266165-d301ada6-5b78-11e8-8c5c-4058e037e7f7.jpg)
