### ISSUE TITLE
路由重定向问题

### ISSUE THREAD

**Issue by srrrr** [zuiidea/antd-admin#825]
我想在访问项目根目录的时候，跳转 /goods/list 这个路由下的component。

我现在是这么写的
![image](https://user-images.githubusercontent.com/5070841/40228139-056c4c8a-5ac3-11e8-9eb1-cfebae8283a1.png)
![image](https://user-images.githubusercontent.com/5070841/40228127-fd59e0de-5ac2-11e8-879d-f4e458ce7375.png)

但路由并没有进行重定向到 /goods/list
![image](https://user-images.githubusercontent.com/5070841/40228305-7db693c6-5ac3-11e8-8ce0-cbe088a3c59f.png)

我点击左侧导航“商品管理”切换到 /goods/list ，component是能正常显示
![image](https://user-images.githubusercontent.com/5070841/40228330-90786868-5ac3-11e8-89ba-56c3afb3263d.png)

请问这会是什么问题？？？

**Comment by superlbr** [comment]
master分支，git clone后直接修改 Redirect to 是ok的
https://github.com/zuiidea/antd-admin/blob/ba96ebb874562a1d481d174948b875900f5ee7a3/src/router.js#L75
对照你的代码，是不是少了exact的
https://github.com/zuiidea/antd-admin/blob/ba96ebb874562a1d481d174948b875900f5ee7a3/src/router.js#L79

**Comment by srrrr** [comment]
不是exact的问题。现在突然又可以了...

**Comment by wangxiansheng001** [comment]
我这边点击菜单， 一个组件沾满全屏，header   menu 全没了，你是怎么切换菜单的？

**Comment by superlbr** [comment]
@wangxiansheng001 layout没加载呗
