### ISSUE TITLE
登陆及手动刷新页面：404 Not Found

### ISSUE THREAD

**Issue by qunlee** [zuiidea/antd-admin#827]
> 4.3.9版本
> 1. 功能点：登陆或者手动刷新（F5）页面
> 2. Bug反馈：在完全渲染出页面的过程中页面左上角会出现Dashboard/Not Found，404 Not Found等黑色字体
> 2.1 console没有报错输出
> 2.2 刷新过程中不希望出现404
> 2.3 登陆或刷新页面
> 2.4 windows 10，Firefox、Chrome，Mecrosoft Edge未出现
> 3. 代码求助 => 目前5.0版本未出现这种状况，但是不知道4.3.9版本在更新过程中哪个节点修改过这个问题，请问是修改了哪部分代码吗？
谢谢。

**Comment by superlbr** [comment]
duplicate #758
