### ISSUE TITLE
安装依赖时报错，求教

### ISSUE THREAD

**Issue by xh476645818** [zuiidea/antd-admin#828]
如何操作导致的  
WARN node unsupported "node@v6.7.0" is incompatible with umi@1.3.4 › umi-build-d                    ev@0.18.4 › af-webpack@0.22.4 › babel-loader@^8.0.0-beta.0, expected node@>= 6.9

WARN node unsupported "node@v6.7.0" is incompatible with umi@1.3.4 › umi-build-d                    ev@0.18.4 › af-webpack@0.22.4 › fork-ts-checker-webpack-plugin@^0.4.1, expected                     node@>=6.11.5
platform unsupported umi@1.3.4 › umi-test@0.5.5 › ts-jest-babel-7@22.0.7 › cpx@1                    .5.0 › chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatibl                    e with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compati                    ble with your platform(win32)
Love Preact? You can now donate to our open collective:
 > https://opencollective.com/preact/donate
peerDependencies link ajv@5.5.2 in D:\学习demo\antd-admin\node_modules\_ajv-keyw                    ords@2.1.1@ajv-keywords unmet with D:\学习demo\antd-admin\node_modules\ajv(6.5.0                    )
peerDependencies WARNING umi@1.3.4 › umi-test@0.5.5 › ts-jest-babel-7@^22.0.6 re                    quires a peer of jest@^22.0.1 || ^22.1.0-alpha.1 || ^23.0.0-alpha.1 but none was                     installed
peerDependencies WARNING umi@1.3.4 › umi-build-dev@0.18.4 › antd-mobile@2.1.10 ›                     react-native-drawer-layout@~1.3.0 requires a peer of react-native@* but none wa                    s installed
peerDependencies WARNING umi@1.3.4 › umi-build-dev@0.18.4 › antd-mobile@2.1.10 ›                     react-native-collapsible@^0.9.0 requires a peer of react-native@* but none was                     installed
peerDependencies WARNING eslint-config-umi@^0.1.4 requires a peer of eslint-plug                    in-jsx-a11y@^5.1.1 but eslint-plugin-jsx-a11y@6.0.3 was installed
peerDependencies WARNING eslint-config-umi@0.1.4 › eslint-config-react-app@^2.0.                    0 requires a peer of babel-eslint@^7.2.3 but babel-eslint@8.2.3 was installed
peerDependencies WARNING umi@1.3.4 › babel-preset-umi@0.3.0 › @babel/plugin-prop                    osal-export-default@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 b                    ut @babel/core@7.0.0-beta.46 was installed
peerDependencies WARNING umi@1.3.4 › babel-preset-umi@0.3.0 › @babel/plugin-prop                    osal-export-namespace@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32                     but @babel/core@7.0.0-beta.46 was installed
peerDependencies WARNING umi@1.3.4 › umi-build-dev@0.18.4 › af-webpack@0.22.4 ›                     babel-plugin-dynamic-import-node-sync@2.0.1 › @babel/plugin-syntax-dynamic-impor                    t@^7.0.0-beta.39 requires a peer of @babel/core@7.0.0-beta.49 but @babel/core@7.                    0.0-beta.46 was installed
peerDependencies WARNING umi@1.3.4 › babel-preset-umi@0.3.0 › @babel/plugin-prop                    osal-export-default@7.0.0-beta.32 › @babel/plugin-syntax-export-extensions@7.0.0                    -beta.32 requires a peer of @babel/core@7.0.0-beta.32 but @babel/core@7.0.0-beta                    .46 was installed
peerDependencies WARNING eslint-config-umi@0.1.4 › eslint-config-react-app@^2.0.                    0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but eslint-plugin-jsx-a11y@6.                    0.3 was installed
deprecate highcharts-exporting@^0.1.7 this package has been deprecated, just imp                    ort modules from the highcharts folder
deprecate highcharts-more@^0.1.7 this package has been deprecated, just import m                    odules from the highcharts folder
deprecate umi@1.3.4 › umi-test@0.5.5 › enzyme@3.3.0 › rst-selector-parser@2.2.3                     › nearley@2.13.0 › nomnom@~1.6.2 Package no longer supported. Contact support@np                    mjs.com for more info.
Recently updated (since 2018-05-24): 37 packages (detail see file D:\学习demo\an                    td-admin\node_modules\.recently_updates.txt)
  Today:
    → umi@1.3.4 › umi-test@0.5.5 › jest-cli@22.4.4 › istanbul-api@1.3.1 › istanb                    ul-lib-source-maps@^1.2.4(1.2.5) (08:37:46)
    → umi@1.3.4 › umi-test@0.5.5 › typescript@^2.8.1(2.8.4) (04:03:54)

**Comment by superlbr** [comment]
>optional install error: Package require os(darwin) not compati ble with your platform(win32)
windows平台，建议升级nodejs，然后使用yarn安装依赖
