### ISSUE TITLE
Bug反馈  ,修改themes/default.less后不能build

### ISSUE THREAD

**Issue by annie-** [zuiidea/antd-admin#830]
> 2. Bug反馈  
修改src/themes/demes.less后build错误，可以正常启动
![image](https://user-images.githubusercontent.com/4263625/40828894-7872e0b2-65b4-11e8-9a98-e6327f693c83.png)

bulid错误如下
> antd-admin@5.0.0-beta build /Users/annie/Downloads/antd-admin-master
> cross-env BABELRC=1 umi build

⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since it\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, please be careful of the compatibility after upgrading.

**Comment by superlbr** [comment]
> It's not recommended to use webpack.config.js

只是提示而已，不用理会

**Comment by annie-** [comment]
哦好的谢谢
