### ISSUE TITLE
修改登陆后跳转页面

### ISSUE THREAD

**Issue by pickdebug** [zuiidea/antd-admin#831]
其他都正常，去掉 menu的dashboard选项，其他相应的与dashboard相关的也去掉了，只是当我登录成功后或者链接http://0.0.0.0:8000/ 打开项目时，内容部分是not found,面包屑是user/NOT  FOUND,只有当点击左侧列表项时才会显示所点击列表项的内容，现在就是想让项目在用户登录成功或者输入http://0.0.0.0:8000/ 时，直接默认跳至user页，跟以前dashboard一样，不知道在哪改，改什么，怎么改。。。希望能得到解答，谢谢🙏

**Comment by superlbr** [comment]
1. 请确认所有dashboard的部分都检查过了
2. 登陆后跳转哪个页面，看这个function
https://github.com/zuiidea/antd-admin/blob/8c10be6ee606fe78213597bbec2eb86111477d13/src/pages/login/model.js#L10-L25

**Comment by pickdebug** [comment]
首先谢谢你，因为你的回答我现在能做到登录之后自动跳到/user，但是还有就是直接http://0.0.0.0:8000/ 访问它不会跳转到/user而是就像我之前那样的页面，点击左侧列表项之后才会显示内容，这个该怎么改呢？

**Comment by superlbr** [comment]
访问http://0.0.0.0:8000/ 跳转哪个页面，代码在这里，config啥的仔细看看哈
https://github.com/zuiidea/antd-admin/blob/8c10be6ee606fe78213597bbec2eb86111477d13/src/models/app.js#L67-L109

**Comment by pickdebug** [comment]
好了，谢谢

**Comment by atonesapple** [comment]
你好，地址栏输入http://localhost:8000 跳转到指定页面怎么设置，登陆跳转的已经设置好了

**Comment by superlbr** [comment]
@atonesapple 一样啊，上方代码最后'/sys/login'

**Comment by atonesapple** [comment]
> @atonesapple 一样啊，上方代码最后'/sys/login' ，不好意思，问错问题了，是想问输入根路径跳转的制定页面功能，输入其他的路由都可以跳转，就根路径不能实现
![Uploading image.png…]()

**Comment by superlbr** [comment]
@atonesapple 图挂了，还是不明白

**Comment by atonesapple** [comment]
@superlbr 图片上传不了，我附了一段代码上去，path: 'dashboard', path: 'rechargeList',path: 'orderList',path: 'rechargeList',这些在地址栏输入都可以进行正确的跳转，path:'/' 不能正确跳到我指定的页面去

**Comment by superlbr** [comment]
@atonesapple 你这dva 1.x好老了。新的antd-admin用umi的[路由](https://umijs.org/zh-CN/docs/convention-routing)
建议参考https://github.com/zuiidea/antd-admin/blob/4.1/src/router.js改下

**Comment by atonesapple** [comment]
@superlbr 嗯，是以前的老项目，然后添加更新功能，一升级就有很多报错也，只能在原来的基础上修改

**Comment by atonesapple** [comment]
@superlbr 谢谢大神，我参考你发的那个连接修改下，看有能不能实现想要的效果，老系统的东西不能随便升级，升级就一堆的报错

**Comment by superlbr** [comment]
@atonesapple 生命不息，折腾不止
