### ISSUE TITLE
如何在生产和开发下调用不同接口

### ISSUE THREAD

**Issue by pickdebug** [zuiidea/antd-admin#833]
这个项目应该怎么区分开发环境和生产环境，而应用不同后台接口请求地址呢？是在roadhog.js里改吗？不知道怎么改。

**Comment by superlbr** [comment]
既然定位了roadhog，为啥不翻翻[文档](https://github.com/sorrycc/roadhog/blob/1.x/README_en-us.md#env)

**Comment by pickdebug** [comment]
还是不太明白，在roadhog.js里面export default有字段env: {development: {...},production: {...}},但是我现在不知道把上面的接口代理的'target': host，里的host怎么写进这两个对象里面而让他们的host不同，从而正式环境和开发环境使用不同的域名的接口，不用手动去改，那样很麻烦

**Comment by superlbr** [comment]
target在哪里呀？proxy里
把extraBabelPlugins换成proxy可不可以呀

**Comment by pickdebug** [comment]
其实部署的话应该不用那个proxy代理，直接nginx配置里面写一个转发就可以了

**Comment by superlbr** [comment]
hah，看来没带偏
这里要detail一下部署:
1. 首先roadhog build 出来的dist
2. dist走cdn，或者serve
3. 利用web server，比如nginx 或者apache控制域名下路径的访问
