### ISSUE TITLE
项目部署-刷新时报404

### ISSUE THREAD

**Issue by darkfour** [zuiidea/antd-admin#835]
项目部署后，每次点浏览器的刷新时都跳转到nginx404页面，其他操作正常，我的nginx配置如下：
server {
    listen 0.0.0.0:80;
    server_name www.strategym.com;
    root /app;
    index index.htm index.html;
    location /api {
			proxy_pass http://strategymanager:8001;
    }
}
请教一下这是什么原因呢

**Comment by superlbr** [comment]
经测试，打开www.strategym.com，刷新并未404.
值得注意的是：进入www.strategym.com  跳转了二次 ，一次http://www.goofiit.com ，一次http://alpha.goofiit.com

**Comment by superlbr** [comment]
no more feedback

**Comment by superlbr** [comment]
https://github.com/umijs/umi/blob/master/docs/guide/faq.md#build-%E5%90%8E%E8%AE%BF%E9%97%AE%E8%B7%AF%E7%94%B1%E5%88%B7%E6%96%B0%E5%90%8E-404
