### ISSUE TITLE
umi 版本过低，webpack proxy 代理参数传递有问题

### ISSUE THREAD

**Issue by opendingtalk** [zuiidea/antd-admin#836]
同umi作者咨询了下，umi版本过低，webpack proxy 代理参数传递有问题

请 npm install --save-dev@latest 升级

自测一下版本 webpack proxy成功

     "umi": "^1.3.5",
    "umi-plugin-dll": "^0.2.1",
    "umi-plugin-dva": "^0.9.0",
    "umi-plugin-routes": "^0.1.5"

**Comment by superlbr** [comment]
duplicat https://github.com/umijs/umi/issues/510 https://github.com/umijs/umi/issues/479
