### ISSUE TITLE
关于装饰器

### ISSUE THREAD

**Issue by wordStart** [zuiidea/antd-admin#837]
为何在这个项目中无法使用装饰器进行编写

**Comment by superlbr** [comment]
ah，show your code, show your error

**Comment by wordStart** [comment]
![786607c0-b452-4532-be12-bac0f857e4e0](https://user-images.githubusercontent.com/28641282/41277857-f436df1a-6e5a-11e8-8cc1-7a613819b543.png)
![Uploading 7CEB69C2-3883-4420-BF20-EFAE178DD794.png…]()
在.babelrc里面我有配置plugins:["transform-decorators-legacy"]
但是没有用，是我的写法有问题吗？

**Comment by wordStart** [comment]
但是我使用create-react-app采用相同的配置，是可以使用装饰器的，我Google之后，没有特别好的解决方案

**Comment by superlbr** [comment]
1. 建议升级nodejs
2. 建议参考antd-admin更新5.0-beta，目前使用umi 1.3.5，经测试没有报错

**Comment by wordStart** [comment]
我试试，感谢

**Comment by superlbr** [comment]
done in https://github.com/zuiidea/antd-admin/commit/47fd51594491445577f54de705d73bcd85d6eca0
