### ISSUE TITLE
端口可以成8011吗

### ISSUE THREAD

**Issue by mengchen007** [zuiidea/antd-admin#841]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  怎么把8000端口修改成8011
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
package.json中cross-env后加上 PORT=8000指定
