### ISSUE TITLE
不支持ie11浏览器

### ISSUE THREAD

**Issue by mushroomlb** [zuiidea/antd-admin#843]
ant design本身是支持ie9以上的，但是我用ie11打不开antd-admin

**Comment by superlbr** [comment]
打不开是指登陆不了，还是空白页，控制台是否报错

**Comment by mushroomlb** [comment]
![image](https://user-images.githubusercontent.com/1701771/41826373-b75fee14-785b-11e8-93a7-5ac182314f35.png)

输入用户名和密码，一闪又回到登录界面，控制台没有信息

**Comment by superlbr** [comment]
就在这个看上去卡住的界面，刷新下就好

**Comment by mushroomlb** [comment]
试过了，不行，你那里可以试一下，我这里的ie版本：
![image](https://user-images.githubusercontent.com/1701771/41827009-c63c5162-785f-11e8-8cd6-c85a0690dd68.png)

**Comment by superlbr** [comment]
![1](https://user-images.githubusercontent.com/8142164/41827214-d387a906-7860-11e8-8071-6e9efdc0394e.gif)

**Comment by mushroomlb** [comment]
果然可以在刷新过程中在刷新，但是没有好的解决方案吗

**Comment by superlbr** [comment]
可以自行尝试
