### ISSUE TITLE
Browser refresh show 404 error with npm serve

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#847]
npm run dev works for any url with browser refresh, when I used "npm module serve"  it's shows the 404 error for browser refresh. 
Appreciate any advice/help

**Comment by superlbr** [comment]
yeah, npm run dev is develop mode. while npm module serve should run dist(from npm run build)

**Comment by malinda1986** [comment]
@superlbr thanks reply. Let's say url is http://localost/user/details in dev mode even you refresh the browser it load the correct page. but in npm serve if I refresh the browser it shows page not found error

**Comment by malinda1986** [comment]
we have to give the `serve -s or serve --single` to serve single page applications.

**Comment by superlbr** [comment]
I found serve at [create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#static-server)
I just use -s but not know the meaning

**Comment by niyasrad** [comment]
> Found the solution. we have to give the `serve -s or serve --single` to serve single page applications. :)

Can you please explain why this works, but not `npm run serve`?

**Comment by superlbr** [comment]
there is no `serve` defined in scripts of package.json, while serve is a npm package

**Comment by niyasrad** [comment]
> 

If that's the case, then you could add to the `scripts` in `package.json` 

`"serve": "serve -s build"`

**Comment by superlbr** [comment]
@niyasrad  There are a lot of solutions to deploy, not just serve. Questions will come, what's serve, how to get serve. Well, it's far away from this project.

**Comment by Metehan-Altuntekin** [comment]
https://github.com/zuiidea/antd-admin/issues/847#issuecomment-403181852 
`serve -s dist` helped me with Vite React app
