### ISSUE TITLE
下载后解压报错

### ISSUE THREAD

**Issue by syaivin** [zuiidea/antd-admin#848]
> 1. 下载到本地电脑的压缩包解压不成功，报错

**Comment by superlbr** [comment]
zip 文件夹还是tar.gz，哪个版本，windows or mac？试试换个解压软件？

**Comment by syaivin** [comment]
@superlbr 是win7系统，换了几种解压软件都不行，下载下来就是 antd-admin-master.zip，具体如下图：
![qq 20180706110320](https://user-images.githubusercontent.com/13479047/42358194-ff563d26-810d-11e8-8a7f-b37cf260c88b.png)
![2](https://user-images.githubusercontent.com/13479047/42358193-fef36174-810d-11e8-9515-2a42fa90f12e.png)

**Comment by superlbr** [comment]
zip包是不是损坏了, release那里的版本也可用，还可以git clone。
![image](https://user-images.githubusercontent.com/8142164/42358572-cbfd80d6-810f-11e8-9f73-b2aac41956c4.png)

**Comment by syaivin** [comment]
@superlbr 这就尴尬了，我叫几个同事下了也一样解压报错。

**Comment by superlbr** [comment]
同事？公司网？不好的预感，手机开个热点看下
md5校验值看下：1869700fa10163fb83df9e1fa5c0431b

**Comment by syaivin** [comment]
@superlbr 好的，谢谢；估计也是公司网络问题~
