### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by wangxiansheng001** [zuiidea/antd-admin#849]
代码编译到91%  卡住了，无法继续

**Comment by superlbr** [comment]
看到你的提问 https://github.com/umijs/umi/issues/685
实际build到91%，至少还要2-4min的样子
两个建议：node升级到v9.11.1，删掉依赖用yarn试下

**Comment by superlbr** [comment]
如果没有更多反馈，先close

**Comment by superlbr** [comment]
参考 https://github.com/zuiidea/antd-admin/issues/852
