### ISSUE TITLE
The latest version of 3.0 has an error

### ISSUE THREAD

**Issue by shichenda** [zuiidea/antd-admin#85]
utils.js:215 uncaught at sagaWithCatch TypeError: Cannot read property 'weather' of undefined
utils.js:215 uncaught at sagaWithCatch TypeError: Cannot read property 'getHostNode' of null

Resolvent

Add two code in the index.js file below this line
app.model(require('./models/app'))
ADD：
app.model(require('./models/dashboard'))
app.model(require('./models/users'))

Edit file router.js

Delete the following code：

// const cached = {};
// function registerModel(app, model) {
// if (!cached[model.namespace]) {
// app.model(model)
// cached[model.namespace] = 1
// }
// }

// registerModel(app, require('./models/dashboard'))

// registerModel(app, require('./models/users'))

**Comment by zuiidea** [comment]
pull 一下最新的代码

**Comment by shichenda** [comment]
好的，我昨天用的时候时候还好好的，今天上午在家拉了一下，就不能运行了。我看你改动的代码了，所以把几个地方给注销了。
