### ISSUE TITLE
下载到本地webstrom打开显示问题

### ISSUE THREAD

**Issue by syaivin** [zuiidea/antd-admin#851]
> 1、先谢了，源码比如登录页，编辑器显示的好乱写代码都不方便，不支持react格式吗？webstrom设置是对的：
![qq 20180709171742](https://user-images.githubusercontent.com/13479047/42451273-4df6dc76-83b9-11e8-9162-8f355d882085.png)

**Comment by superlbr** [comment]
推荐vs code
好乱。。。没看出来，标签都识别了，如果觉得排版布局不舒服，可以自己改
