### ISSUE TITLE
npm run build失败求助

### ISSUE THREAD

**Issue by testjohnhello** [zuiidea/antd-admin#852]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
您好，npm start正常，但是build的时候报以下错误，请问是什么问题呢？谢谢

C:\Program\antd-admin-master>npm run build

> antd-admin@5.0.0-beta build C:\Program\antd-admin-master
> cross-env BABELRC=1 umi build

⚠️ ⚠️ ⚠️  It\'s not recommended to use webpack.config.js, since it\'s major or minor version upgrades may result in incompatibility. If you insist on doing so, please be careful of the compatibility after upgrading.

  build [==================  ] 91%Total precache size is about 10.3 MB for 40 resources.
Build completed in 112.214s

Failed to compile.

./src/components/Loader/Loader.less
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
    at Array.forEach (<anonymous>)
    at <anonymous>

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd-admin@5.0.0-beta build: `cross-env BABELRC=1 umi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-admin@5.0.0-beta build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program\_logs\2018-07-10T07_50_29_397Z-debug.log

**Comment by testjohnhello** [comment]
Error: antd-admin@5.0.0-beta build: `cross-env BABELRC=1 umi build`

**Comment by superlbr** [comment]
@sorrycc 请教下，这个报错有见过吗

**Comment by testjohnhello** [comment]
@superlbr 请问下编译成功后，我用nginx部署在linux，但是打开主页，不会跳转登录页面，报了一个请求错误。
Request URL:http://times-uat.timesgroup.cn:8099/api/v1/user

与npm start不一样，不知什么原因呢。

**Comment by superlbr** [comment]
本地开发用的是MOCK接口，部署的话接口得提供呀，不然当然报错

**Comment by superlbr** [comment]
参考 #832
