### ISSUE TITLE
首次登录时，后台服务异常，怎样跳转到登录页

### ISSUE THREAD

**Issue by xailocker** [zuiidea/antd-admin#854]
> 前提：修改 antd-admin 请求指向后端服务，而此时后端服务异常无法访问
> 1. 目标：后台服务异常时，前端能跳转到登录页
> 2. Bug：前端页面刷新时，会首先访问 app/query ，此时若后端服务异常，则触发 Promise.reject()。尝试在 app/query 中加入 try catch，并在 catch 时加入 window.location.href = '/login'。这样做导致前端被转到登录页，然后继续访问 app/query，重复try catch。现象是登录页重复刷新。
> 3. 求助：如何让前端在接到 app/query 异常时跳转到登录页，并停止登录页自动调用该接口。

**Comment by superlbr** [comment]
好奇怪的思路
1. 后台服务异常，前端可以跳404，或者提示网络服务不可用，跳登陆页一样不能用。
2. app/query只在登陆时调用，本来就在登陆页，为啥还跳登陆页。
3. 其他页面后台停服务，会提示Gateway Timeout，另外src/plugin/onError.js里可以监听到
