### ISSUE TITLE
Question: antd-admin Vs react-admin (formerly admin-on-rest)

### ISSUE THREAD

**Issue by rrjanbiah** [zuiidea/antd-admin#855]
How does it compare with https://github.com/marmelab/react-admin (which is from https://github.com/marmelab/ng-admin) ?

With react-admin, if we setup few configurations, the whole admin is up and ready. Is antd-admin works like that? (or, mere components that still needs assembling?)  If not, is there any similar projects available that is comparable to https://github.com/marmelab/react-admin in this Ant ecosystem? TIA

**Comment by superlbr** [comment]
Since you got 5min to ask question, why not just git clone and run the demo?
For functional components just an npm, right?
So why not ask yourself is it good to use、to modify、to feed my needs?
In Ant ecosystem, office version: https://github.com/ant-design/ant-design-pro

**Comment by rrjanbiah** [comment]
@superlbr Thanks for your reply. Done that already. Doesn't look like react-admin as it is more of a configuration thing; here need to create pages. Thought of asking as such features may hidden inside Chinese language.

> In Ant ecosystem, office version: https://github.com/ant-design/ant-design-pro

Thank you. But, I was asking for react-admin alternative or like in Ant ecosystem. 

Thanks again for your quick reply.

**Comment by rrjanbiah** [comment]
Thank you!

**Comment by yifeikong** [comment]
The question is very much a valid one for beginners in the react ecosystem like me. However, it's such a pitty to see such unfriendly answer like "Why not try it yourself".

**Comment by superlbr** [comment]
@yifeikong for react-admin, I didn't use before. If you still ask, antd-admin LGTM
