### ISSUE TITLE
部署问题：SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by scottming** [zuiidea/antd-admin#856]
### 部署过程：

首先克隆仓库后，运行了 build

```
$ npm run build 
```

这时会卡在 91%，然后我把 [这一行](https://github.com/zuiidea/antd-admin/blob/master/package.json#L62) 改成了：
```
 "build": "TS_CONFIG_PATHS_PLUGIN=none cross-env BABELRC=1 umi build
```
这时 build 成功了。

这里想问下，上次 sorrycc 说 TS_CONFIG_PATHS_PLUGIN 在 umijs 后面的版本会自动忽略，现在是否是忽略了 `umi dev` 相关的，但`umi dev `相关的并没有忽略？另外 `TS_CONFIG_PATHS_PLUGIN` 写在 `cross-env` 前面会影响后面的 `BABELRC=1` 么？

然后参考了以下 issues：

* [npm run build失败求助 · Issue #852 · zuiidea/antd-admin](https://github.com/zuiidea/antd-admin/issues/852)
* [阿里云虚拟主机怎么配置nigx呀！！ · Issue #641 · zuiidea/antd-admin](https://github.com/zuiidea/antd-admin/issues/641)
* [项目部署 · Issue #269 · zuiidea/antd-admin](https://github.com/zuiidea/antd-admin/issues/269)
 
以及其他的 `serve` 相关的 issues，在 dist 目录下运行：

```
$ serve -s -p 8000
```

### 具体问题

然后网页打开 localhost:8000 后，logo 显示不出来，输入 admin 的账号密码后，点击登录后控制台报错：

```
SyntaxError: expected expression, got '<'
```

![screen shot 2018-07-16 at 4 08 52 pm](https://user-images.githubusercontent.com/12830256/42748419-bd83e72e-8912-11e8-87ae-1e50557da693.png)

**Comment by superlbr** [comment]
提示不影响使用。
另外接口使用，参考https://github.com/zuiidea/antd-admin/issues/832
