### ISSUE TITLE
下载安装后无法启动

### ISSUE THREAD

**Issue by zhoumh1988** [zuiidea/antd-admin#857]
```
Failed to compile.

./src/pages/dashboard/components/comments.less
Module build failed:

@import "~themes/vars";
^
Can't resolve 'themes/vars.less' in '/Users/zhouminghua/Documents/mp/lightbot-stat/src/pages/dashboard/components'
      in /Users/zhouminghua/Documents/mp/lightbot-stat/src/pages/dashboard/components/comments.less (line 1, column 0)
```

操作流程：
- 1 下载项目zip包并解压
- 2 到项目目录下执行```npm install```
- 3 启动服务 ```npm start```

然后就提示上述日志信息
我尝试修改了webpack的配置，又提示了其他同样的问题。
```js
webpackConfig.resolve = {
    alias: {
        themes: path.join(__dirname, 'src/themes')
    }
};
```
```
Failed to compile.

./src/layouts/app.js
Module not found: Can't resolve 'components' in '/Users/zhouminghua/Documents/mp/lightbot-stat/src/layouts'
```

请问如何解决？

**Comment by superlbr** [comment]
推荐yarn, node 版本v8或以上

**Comment by zhoumh1988** [comment]
@superlbr 我node是10.4版本

**Comment by superlbr** [comment]
看环境像是mac，怀疑不是本项目，建议对比.webpackrc.js\.babelrc文件

**Comment by zhoumh1988** [comment]
首先你这个回答貌似在推卸责任呢？！不是你们项目我干嘛来给你提bug，我的时间很便宜是嘛？

再来，本身这个是用node服务去搭建的，跟mac环境有什么关系？

最后，你倒是给我个对比啊～我直接从你的git上clone的，难道在install的时候会变化？

**Comment by superlbr** [comment]
首先说明下个人处理issue的流程：
   1. 复现，至少会在mac\debian\win7三种环境下作测试，测试下来并没有这个问题。
   2. 定位，有人会拿别的项目，比如umi-antd-admin来提问，或者有修改, 并非维护范围

贴下三种环境下的gif，好吧
mac 
![mac](https://user-images.githubusercontent.com/8142164/42926806-11640492-8b65-11e8-935e-df8a6fe4df1c.gif)

debian8
![debian8](https://user-images.githubusercontent.com/8142164/42927052-d2b46a4c-8b65-11e8-9be5-65d36293aee0.gif)

win 7
![win7](https://user-images.githubusercontent.com/8142164/42926807-12a266a0-8b65-11e8-993d-89fae20d3ad0.gif)

**Comment by superlbr** [comment]
😓，这锅不背

**Comment by superlbr** [comment]
借楼存几张图
web:
![4 2 1-demo-1](https://user-images.githubusercontent.com/8142164/43032162-37db46e2-8ce3-11e8-9c7e-73a773bc0545.gif)

mobile:
![4 2 1-demo-2](https://user-images.githubusercontent.com/8142164/43032163-3a1f2838-8ce3-11e8-89c5-8e1ae077d34a.gif)

效果图:
![dashboard](https://user-images.githubusercontent.com/8142164/43032165-5d151bae-8ce3-11e8-9bfd-8a121620ea78.jpg)

**Comment by Angeliz** [comment]
我也遇到了同样的问题……

**start**
```
git clone https://github.com/zuiidea/antd-admin.git
cd antd-admin
yarn install
npm run start
```
就是 @zhoumh1988 第一个图的错误，我修改了路径，但还是报了第二个图的错误

**环境**
- ubuntu 16.04
- node 8.11.3
- yarn 1.9.4
- npm 6.3.0

另外我也重装试了一下，但是不好……
