### ISSUE TITLE
antd 表格中 树型数据展示

### ISSUE THREAD

**Issue by cornwang** [zuiidea/antd-admin#858]
1. 现有需求，需要编辑表格中的树形数据。
如果只是展示数据，是可以展示出来。
问题：
`const columns = [
      {
        title: '名称',
        dataIndex: 'name',
        key: 'name',
        width: '20%',
      }, {
        title: '值',
        dataIndex: 'value',
        key: 'value',
        width: '20%',
        render: (text, record ) => (
          <EditableCell rule ={['includeChinese']} value={text} edits={!disabled} onChange= 
         {this.onCellChange(record, 'value')} />
        )
      }, 
    ];
`
现在给需要编辑的列加上render函数，会报错。
` Objects are not valid as a React child (found: object with keys {name, key, value}). If you meant to render a collection of children, use an array instead.
`
我的children是数据对象
`  children: [
          {
            "name": "F20",
            "key": "F20",
            "value": "MT103_F20"
          }, {
            "name": "Loop1",
            "key": "Loop1",
            "children": [{
              "name": "F13C",
              "key": "MT103.Loop1.F13C",
              "children": [{
                "name": "Code",
                "key": "MT103.Loop1.F13C.Code",
                "value": "MT103_Loop1_LT1_F13C_Code",
              }, {
                "name": "TimeIndication",
                "key": "MT103.Loop1.F13C.TimeIndication",
                "value": "MT103_Loop1_LT1_F13C_TimeIndication",
              }],
              "value": "COM_MT103_Loop1_LT1_F13C",
            }],
            "value": "LOOP_MT103_Loop1",
          }, {
            "name": "F23B",
            "key": "F23B",
            "value": "MT103_F23B",
          }, {
            "name": "F77B",
            "key": "F77B",
            "value": "MT103_F77B",
          },
        ],`

**Comment by superlbr** [comment]
建议在codesandbox或者codepen弄个demo
比如https://codesandbox.io/s/0ql72n5zn
