### ISSUE TITLE
How do add new route 

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#860]
I saw .umi is added to .gitignore, if I add a new route how ti been deploy to the production

**Comment by superlbr** [comment]
.umi is just temp dir for dev.
npm run build will take nesscessary files into dist

**Comment by malinda1986** [comment]
@superlbr  thanks

**Comment by superlbr** [comment]
[deploy in umi](https://umijs.org/guide/deploy.html)
