### ISSUE TITLE
关于路由嵌套问题

### ISSUE THREAD

**Issue by EvansLH** [zuiidea/antd-admin#861]
路由嵌套子页面该如何配置？

![image](https://user-images.githubusercontent.com/18571536/42994965-2cf99716-8c42-11e8-91db-053d442dc9a0.png)

需要带ID 传子页面，这个子页面在菜单栏是不需要显示的；目前我是多写了一层路由，
做了无用功；
![image](https://user-images.githubusercontent.com/18571536/42994936-17876660-8c42-11e8-9534-ab129e0f1e2b.png)

其实理想状态应该和图二 一样的，但无奈 图二的方式无法实现，请问作者有没有更好的方式？
最终结果期待的是：/product/productId/info
流程大概就是列表进入详情页面；
如果作者有幸看到，可加我微信 ：EvansHongZai1214

**Comment by superlbr** [comment]
umi约定路由，了解下 https://umijs.org/guide/router.html#基础路由

**Comment by EvansLH** [comment]
这个是按需加载路由 你发的这个网站我看过，没看到关键信息，大神 能说重点嘛？

**Comment by superlbr** [comment]
Duplicate https://github.com/umijs/umi/issues/708 
other like https://github.com/umijs/umi/issues/289  https://github.com/umijs/umi/issues/285

**Comment by superlbr** [comment]
目录按要求设置呗。
个人不推荐这种写法，参考https://github.com/ReactTraining/react-router/issues/5127
