### ISSUE TITLE
antd-admin怎么给axios加拦截器呢？我在请求回来想整体做一个错误处理

### ISSUE THREAD

**Issue by heimiao** [zuiidea/antd-admin#862]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
其实已经写了
https://github.com/zuiidea/antd-admin/blob/ed88c087bfefa9f8c1ec700090b623b0b762542c/src/utils/request.js#L98-L115
