### ISSUE TITLE
antd 怎样“按需加载”

### ISSUE THREAD

**Issue by xailocker** [zuiidea/antd-admin#863]

**Comment by xailocker** [comment]
试过在 .babelrc 中添加以下配置，不起作用
`
[
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "lib",
        "style": "css"
      },
      "ant"
    ]
`

**Comment by superlbr** [comment]
umi里已经设置过了
参考 https://github.com/umijs/umi/blob/master/packages/umi-plugin-react/src/plugins/antd.js#L22

**Comment by superlbr** [comment]
umi 2.0.0-beta开始build-in antd
https://github.com/umijs/umi/issues/10
