### ISSUE TITLE
[代码求助]不同页面不同的Layout如何实现？

### ISSUE THREAD

**Issue by JevonYang** [zuiidea/antd-admin#865]
> 3. 代码求助
请教一下，代码中，不同页面不同的Layout是如何配置，好像和官方文档配置方法不一样[不同的全局 layout](https://umijs.org/guide/router.html#%E4%B8%8D%E5%90%8C%E7%9A%84%E5%85%A8%E5%B1%80-layout)

望指教。感谢

**Comment by superlbr** [comment]
> 不同页面不同的Layout是如何配置
1. Layout 的定义在 src/layouts/app.js里
2. 不同页面根据传入参数location来识别，写个逻辑，替换Layout即可

> 好像和官方文档配置方法不一样
官方提供了一个思路而已
