### ISSUE TITLE
最新版本代理设置没有效果

### ISSUE THREAD

**Issue by CasperMXP** [zuiidea/antd-admin#866]
> 3. 代码求助 => 可以提，未必及时答复
你好，咨询哈我在.webpackrc.js中配置一个登录接口代理。
`  proxy: {
    "/api/v1/weather": {
      "target": "https://api.seniverse.com/",
      "changeOrigin": true,
      "pathRewrite": { "^/api/v1/weather": "/v3/weather" }
    },
    //用户登录窗口
    "/api/v1/user/login": {
      "target": "http://192.168.0.106:8080",
      "changeOrigin": true,
      "pathRewrite": { "^/api/v2" : "/api/v2" }
    }
  },`
没有效果了，还是请求的mock数据，没有请求代理地址，是需要改动什么地方配置嘛？

**Comment by superlbr** [comment]
1.3 之后 mock 优先于 proxy

参考 https://github.com/umijs/umi/pull/620 https://github.com/umijs/umi/issues/502

**Comment by chj-damon** [comment]
@superlbr 也就意味着我如果mock文件夹下有mock的文件，那我即便在config.js里面设置了proxy，也是不会生效的吗？但是我清除了mock下的文件之后proxy还是不会生效

**Comment by superlbr** [comment]
可以设置参数MOCK=none，https://umijs.org/zh/guide/env-variables.html#mock
>proxy不生效

建议参考umi的配置，测一下，https://umijs.org/zh/config/#proxy
umi只是封装，就是webpack-dev-server的proxy
