### ISSUE TITLE
5.0.0API文档生成

### ISSUE THREAD

**Issue by CasperMXP** [zuiidea/antd-admin#867]
> 1. 功能需求 => 最新版本的api文档怎么生成？以前版本用的.roadhogrc.mock.js.现在升级后只有.umirc.mock.js这个配置文件。无法使用roadhog-api-doc。

**Comment by superlbr** [comment]
linux/unix: 
```ln -s .umirc.mock.js .roadhogrc.mock.js ```
windows:
```mklink /J .umirc.mock.js .roadhogrc.mock.js```

**Comment by CasperMXP** [comment]
![image](https://user-images.githubusercontent.com/8735518/43887869-9a2aded4-9bf2-11e8-9b8c-6c1f3bde1991.png)

windows下按照操作了 没有效果了.....

**Comment by superlbr** [comment]
因为缺少组件
```
   npm install roadhog
  npm install babel-plugin-dva-hmr
  
```
另外建议拆开mock分档和实际代码，对于roadhog-api-doc来说，只需要mock相关文件就够了

**Comment by CasperMXP** [comment]
![image](https://user-images.githubusercontent.com/8735518/43890543-a6d428fa-9bf9-11e8-80a5-9ffcaa80efb8.png)

按照操作了 但是怎么显示的是目录........

**Comment by superlbr** [comment]
因为要仔细看文档，需要访问 /api.html，应该还需要先run一下yarn build

**Comment by CasperMXP** [comment]
![image](https://user-images.githubusercontent.com/8735518/43892342-40fb42f2-9bfe-11e8-810e-ccbb3dd178af.png)
现在又报这个错误........

**Comment by superlbr** [comment]
> const mock = {...}
这是正常的js代码吗

**Comment by CasperMXP** [comment]
........意思是要写2套了mock数据了

**Comment by superlbr** [comment]
这2套mock数据有什么区别？？？这代码改改能用吗？
```
require('fs').readdirSync(require('path').join(__dirname + '/mock')).forEach(function(file) {
	Object.assign(mock, require('./mock/' + file))
})
```

**Comment by CasperMXP** [comment]
大神，能贴哈源码嘛，上周才开始学习前端..........确实基础有点弱.........多谢。

**Comment by superlbr** [comment]
给一点建议，实际工作能用5s解决的问题，尽量不要5min、5h、5天，闲时研究随意。
把mock放在一个文件里，也没什么不好
