### ISSUE TITLE
如何实现proxy配置?

### ISSUE THREAD

**Issue by wuyongdec** [zuiidea/antd-admin#87]
能不能实现
 [12 步 30 分钟，完成用户管理的 CURD 应用](https://github.com/sorrycc/blog/issues/18)
 这样的RESTFul代理配置？
`"proxy": {
  "/api": {
    "target": "http://jsonplaceholder.typicode.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  }
},`
我克隆下来的这个项目并没有.roadhogrc文件呢

**Comment by xiaosansiji** [comment]
@wuyongdec admin项目并没有用roadhog做server，而是用的dora，这个是antdesin脚手架工具里的。proxy代理这个并不是server必须的功能，实际上我们在项目实际部署的时候还是用nginx等软件来做，我现在做本地调试也是用nginx，一样很方便

**Comment by zuiidea** [comment]
@xiaosansiji 厉害咯，哈哈
