### ISSUE TITLE
是否有Typescript对应的版本？

### ISSUE THREAD

**Issue by ZhaoTim** [zuiidea/antd-admin#870]
Typescript已经如此的流行，是否可以开发一个Typescript版本？

**Comment by superlbr** [comment]
好主意，少年，欢迎PR

**Comment by wangxingkang** [comment]
@ZhaoTim 正在写TS版本 欢迎一起  https://github.com/jiumao-fe/react-admin-template

**Comment by superlbr** [comment]
其实typescript完全可以直接写进来，混写，加上tsconfig.json，umi可以编译
