### ISSUE TITLE
页面跳转如何捕获离开页面的路由并且下次进入是进入离开时的路由地址

### ISSUE THREAD

**Issue by wupeng123456** [zuiidea/antd-admin#872]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
每跳转一个页面，就记下来，下次取出来就是了
