### ISSUE TITLE
测试无法运行的问题

### ISSUE THREAD

**Issue by tonyfree** [zuiidea/antd-admin#874]
在src/pages下创建404.test.js，运行npm test，提示错误如下
```
SecurityError: localStorage is not available for opaque origins
```
根据方案（https://github.com/facebook/jest/issues/6766）
在根目录下创建jest.config.js，
```
module.exports = {
  testURL: 'http://localhost'
}
```
再次运行npm test，提示错误如下：
```
SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
```
项目中babelrc已经配置了
```
"presets": [
    "umi/babel"
  ],
```
babel-preset-umi内部也加载了'@babel/preset-env'，接下来该如何处理

**Comment by superlbr** [comment]
参考https://github.com/umijs/umi/tree/master/packages/umi-test/examples/ts
1. 根目录新建tsconfig.json，内容抄上面
2. 404.test.js rename => 404.test.ts
over

@sorrycc bug?

另外关于test
参考 https://github.com/umijs/umi/issues/446

**Comment by tonyfree** [comment]
1.为什么要用ts呢？
2.按照上面的方案添加了tsconfig.json、404.test.js => 404.test.ts
错误提示如下：
```
Test suite failed to run

    SyntaxError: /Users/mac/Desktop/code/github/antd-admin/src/pages/404.test.ts: Unterminated regular expression (3:29)

      1 | import { shallow } from 'enzyme';
      2 | it('renders with Error', () => {
    > 3 |     const wrapper = shallow(/>);                        , expect(wrapper.find('h1').text()).toBe('404 Not Found'));
        |                              ^
      4 | });
      5 |

      at _class.raise (node_modules/@babel/core/node_modules/babylon/lib/index.js:779:15)
```

在jest.config.js中配置了moduleNameMapper，错误提示：
```
● Test suite failed to run

    TypeError: utils.isStandardBrowserEnv is not a function

       6 | import pathToRegexp from 'path-to-regexp'
       7 | import { message } from 'antd'
    >  8 | import { YQL, CORS } from './config'
       9 |
      10 | console.log(YQL)
      11 |

      at Object.<anonymous> (node_modules/axios/lib/helpers/isURLSameOrigin.js:6:9)
```

**Comment by superlbr** [comment]
thx @sorrycc https://github.com/zuiidea/antd-admin/pull/877, fixed now

**Comment by wjjhhh** [comment]
按照楼主的方法

 FAIL  ./a.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'createTransformer' of undefined

      at ScriptTransformer._getTransformer (node_modules/jest-runtime/build/script_transformer.js:232:28)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        9.585s
Ran all test suites.
(node:10456) UnhandledPromiseRejectionWarning: Error: Jest failed
    at _jest.default.runCLI.then.result (F:\ecommerce\node_modules\umi-test\lib\index.js:65:16)
    at <anonymous>
(node:10456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wjjhhh** [comment]
`` FAIL  ./a.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'createTransformer' of undefined

      at ScriptTransformer._getTransformer (node_modules/jest-runtime/build/script_transformer.js:232:28)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        9.585s
Ran all test suites.
(node:10456) UnhandledPromiseRejectionWarning: Error: Jest failed
    at _jest.default.runCLI.then.result (F:\ecommerce\node_modules\umi-test\lib\index.js:65:16)
    at <anonymous>
(node:10456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wjjhhh** [comment]
按照楼主的方法
![image](https://user-images.githubusercontent.com/19969184/49711114-860bde80-fc78-11e8-92b4-f46da71a5c32.png)

**Comment by superlbr** [comment]
@wjjhhh 5.0.0-beta is outdated, check the latest

**Comment by wjjhhh** [comment]
@superlbr 老哥，我拉了最新的5.0.0，但项目已经开发了有段时间，就只改了package.json和.umirc.js，删了.babelrc，发现model里的state都是Proxy对象，请问还有什么要改的
![image](https://user-images.githubusercontent.com/19969184/49776823-abf8b800-fd38-11e8-8e57-d3acb4f321d6.png)

**Comment by superlbr** [comment]
@wjjhhh
> model里的state都是Proxy对象
这是因为开了dva-immer，参考[immer](https://github.com/mweststrate/immer)
其他只要不报错，不要怕

**Comment by wjjhhh** [comment]
@superlbr 谢了，我把immer设false好了
