### ISSUE TITLE
如何在访问不存在页面时重定向到指定页面

### ISSUE THREAD

**Issue by zhaodongxx** [zuiidea/antd-admin#876]
我使用的是新版 antd-admin (dva+umi)

如何在访问不存在页面时重定向到指定页面

**Comment by superlbr** [comment]
在antd-admin里面, 逻辑在这里
https://github.com/zuiidea/antd-admin/blob/cd55df3a152882c67230b14bff6e2e6e2c5a812a/src/layouts/app.js#L117

umi 404 
https://umijs.org/guide/add-404-page.html

**Comment by zhaodongxx** [comment]
@superlbr 这应该不是我要的。

我在你的在线演示工程中，访问地址：`/abc`，最后会重定向到 `/dashboard`。我想知道这个是怎么实现的，在源码里是在是没有收获。并且我把你的工程在本地跑起来也不能进行重定向了。

**Comment by superlbr** [comment]
> 在本地跑起来也不能进行重定向了

因为本地是dev，实际是production。

>访问地址：/abc，最后会重定向到 /dashboard

其实是定向到/

**Comment by superlbr** [comment]
就是上面提到的layout的逻辑里，自行添加
参考 https://github.com/umijs/umi/commit/247cc32c43af2f5d5a7939062fe463e94711428f
route match不到然后如何如何
