### ISSUE TITLE
Typescript文件引入less的css module模式报错

### ISSUE THREAD

**Issue by Slebee** [zuiidea/antd-admin#878]
5.0.0 bate的，基于umi2.0
import styles from './404.less'
console.log(styles) // undefined
想用ts版本，这里要怎么设置吗

**Comment by superlbr** [comment]
根目录引入 https://github.com/umijs/umi-examples/blob/master/ts/tsconfig.json
然后添加ts文件ok

**Comment by hzfvictory** [comment]
declare module "*.less";
