### ISSUE TITLE
如何在login类似页面里写react生命周期的方法？

### ISSUE THREAD

**Issue by lovemegowin** [zuiidea/antd-admin#880]
[login页面](https://github.com/zuiidea/antd-admin/blob/master/src/pages/login/index.js)
connect传入后
不知道怎么加生命周期的方法

**Comment by superlbr** [comment]
这是无状态组件的写法，换成有状态就好了，参考 [components/datatable](https://github.com/zuiidea/antd-admin/blob/master/src/components/DataTable/DataTable.js)
