### ISSUE TITLE
antd的dataPicker支持不友好，不能指定vlaue值，指定value值了就不能切换了

### ISSUE THREAD

**Issue by heimiao** [zuiidea/antd-admin#882]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
看示例文档的[例子](https://ant.design/components/date-picker-cn/#components-date-picker-demo-format)
