### ISSUE TITLE
request文件添加antd组件报warning，请问是怎么回事？

### ISSUE THREAD

**Issue by JarVan007** [zuiidea/antd-admin#884]
1.4.1roadhog版本
Nodejs 8.11.1 and Npm version 6.4.0
win 10 64位

![1](https://user-images.githubusercontent.com/24792319/44645885-dd5caa80-aa0b-11e8-92aa-6544a891111f.png)

大佬我这个项目是参照您，之前版本做的一个后台，这边有个问题，找了一天半了没会解决，就我在封装request请求的文件中想引入一个antd的message做一下报错拦截，但是只要我在这个文件中引用antd的东西roadhog就跑不起来了一直报这个错(如上图)，我自己查了一下都说这个是warning不重要可是项目跑不起来了~求大神告诉一下怎么解决呢？

**Comment by superlbr** [comment]
> 封装request请求的文件中想引入一个antd的message做一下报错拦截

其实有了。
拦截在这里 https://github.com/zuiidea/antd-admin/blob/2de1e8166102af5fda79468836e879f540fa28ba/src/utils/request.js#L98-L118
报错在这里
https://github.com/zuiidea/antd-admin/blob/2de1e8166102af5fda79468836e879f540fa28ba/src/models/user.js#L67-L75

Duplicate https://github.com/zuiidea/antd-admin/issues/862

**Comment by JarVan007** [comment]
我们后端是有自己的两个错误码errCode,1001 1002默认是0是成功，即使200成功返回，如果我这边收到errCode是1001，1002的话，证明后端那边有错误或者验证没过，我这边要提示出来~
我就是要在调用requeset的时候就统一判断一下然后用antd的message提示出来，但是这个文件里面一引用antd的组件就报上面图片那个错误，其他components,models,那些文件夹下面引用antd都没问题就这个utils里面的文件报错，我这个没用umi还是用的之前的react+dva+antd，我下载的也是您这个代码没用umi之前的那个版本4.3.9,但是我看您这个引用antd的组件 npm start的时候就不报错，这个是那个地方的配置有问题么，搞了一天了没搞明白~哎，，，

这是我的request 就是简化了一下您之前写的 麻烦您看一下是哪个地方写的有问题么,主要我就算下面不用，管引用就报错也太难受了~

import axios from 'axios';
// import { message } from 'antd'
import qs from 'qs';
import _ from 'lodash';


const fetch = (options) => {
  let { method = 'get', data, url, } = options;
  const cloneData = _.cloneDeep(data);

  switch (method.toLowerCase()) {
    case 'get':
      return axios.get(url, {
        params: cloneData,
      });
    case 'delete':
      return axios.delete(url, {
        data: cloneData,
      });
    case 'post':
      return axios.post(url, cloneData);
    case 'put':
      return axios.put(url, cloneData);
    case 'patch':
      return axios.patch(url, cloneData);
    default:
      return axios(options);
  }
}

export default function request(options) {

  return fetch(options).then((response) => {
    let { data } = response;
    if (data.errorCode == "1001" || data.errorCode == "1002") {
      message.error(data.message)
    } else {
    // if (data instanceof Array) {
    //   data = {
    //     list: data,
    //   }
    // }
    return Promise.resolve({
      ...data,
    })
    }
  }).catch((error) => {
    const { response } = error;
    let msg;
    let statusCode;
    if (response && response instanceof Object) {
      const { data, statusText } = response;
      statusCode = response.status;
      msg = data.message || statusText;
    } else {
      statusCode = 600
      msg = error.message || 'Network Error';
    }
    /* eslint-disable */
    return Promise.reject({ success: false, statusCode, message: msg })
  })
}

**Comment by JarVan007** [comment]
我把这个request文件冲utils中移出来，放到外层，居然就可以引antd文件了？？ 什么鬼~
