### ISSUE TITLE
鼠标移动到侧边栏会导致晃动

### ISSUE THREAD

**Issue by Louis-7** [zuiidea/antd-admin#887]
现在的侧边栏鼠标放上去就会晃动。我做了一个修改->#886

首页的那个chart也是一样的问题，如果你把鼠标从右边移动进去，那个chart会出scrollbar。 这个问题我本地改了，但是不知道你们是否需要这个修改。 需要的话我可以提PR。

这两个问题在master上都可以重现。

**Comment by superlbr** [comment]
好呀，样式确实不擅长

**Comment by Louis-7** [comment]
有样式需求可以找我 :) 乐意帮忙

**Comment by superlbr** [comment]
antd升级到3.9.0之后，Switch样式不对劲

**Comment by Louis-7** [comment]
是Users这个页面的switch对吧？ 我看侧边栏里的switch没有问题。 这个我会看一下 :)

**Comment by Louis-7** [comment]
PR提了。 我只看到Users页面的switch有问题。 如果还有再告诉我。
