### ISSUE TITLE
table 表header 与每行的列没对齐

### ISSUE THREAD

**Issue by icowan** [zuiidea/antd-admin#89]
如图:

![](http://source.lattecake.com/images/2017/02/14/e0/7f/59/20170227-fc3575322455f5ee7069a989e08d2e7059514452.jpeg?imageView2/2/w/1280)

**Comment by zuiidea** [comment]
这个是由于要做动画造成的，

- `components/users/list.less`文件里设置每栏宽度

或者
- `components/users/list.js` 去掉 `getBodyWrapper`相关代码

- 去掉`components/users/list.less`相关样式代码

**Comment by icowan** [comment]
好的
