### ISSUE TITLE
BUG反馈，最新的代码拉下来之后，在开发环境启不来

### ISSUE THREAD

**Issue by TLOVET** [zuiidea/antd-admin#893]
![image](https://user-images.githubusercontent.com/3888718/45020257-0a8b0780-b061-11e8-842a-55bb59c5100b.png)

**Comment by superlbr** [comment]
请使用yarn安装依赖

**Comment by TLOVET** [comment]
解决了，很久之前配的环境，npm版本太低了，我升级了一下，现在可以了，谢谢
