### ISSUE TITLE
功能需求，建议增加语言国际化，最起码支持中文版和英文版

### ISSUE THREAD

**Issue by TLOVET** [zuiidea/antd-admin#894]
类似于Ant Design右上角，可以选择本网站的语言，最起码支持中文，英文两种，可以不在整个网站上适用，但是可以在几个别页面上做个DEMO

**Comment by superlbr** [comment]
will see in develop(5.0).done in https://github.com/zuiidea/antd-admin/commit/755e19ed12bdb238a9fcf651bb16ef3eb03b7c04
