### ISSUE TITLE
build时，如何打包为二级目录呢？

### ISSUE THREAD

**Issue by GitHub-Leon** [zuiidea/antd-admin#896]
通过umi build执行命令后，出来的文件都是默认根目录，如何配置为二级目录呢？

**Comment by superlbr** [comment]
二级目录，这个？[部署 html 到非根目录](https://umijs.org/zh/guide/deploy.html#%E4%B8%8D%E8%BE%93%E5%87%BA-html-%E6%96%87%E4%BB%B6)
