### ISSUE TITLE
请问如何去掉登录限制？

### ISSUE THREAD

**Issue by Leskur** [zuiidea/antd-admin#897]
我想使用这个框架写一个blog，希望用户能不登录也可以访问一些或者全部页面。

**Comment by superlbr** [comment]
duplicate https://github.com/zuiidea/antd-admin/issues/780
主要调整下下面几个地方：
1. 进入默认打开页面 openpages 
https://github.com/zuiidea/antd-admin/blob/f02d39ace05bcbf18e4a107060498a8754f6ce2a/src/utils/config.js#L12

2. layout加载后权限判断
https://github.com/zuiidea/antd-admin/blob/f02d39ace05bcbf18e4a107060498a8754f6ce2a/src/models/app.js#L74-L107

3. 普通用户权限
https://github.com/zuiidea/antd-admin/blob/f02d39ace05bcbf18e4a107060498a8754f6ce2a/mock/user.js#L35-L46
