### ISSUE TITLE
npm install 后报错

### ISSUE THREAD

**Issue by sexyios** [zuiidea/antd-admin#9]
![4ieyy9iv6e31a0ogp 8bsor](https://cloud.githubusercontent.com/assets/8684040/20959926/99996f34-bc98-11e6-8752-a46fe052cd8e.png)

**Comment by zuiidea** [comment]
你看一下你的8000端口是不是被其他占用了

**Comment by sexyios** [comment]
好尴尬.... 竟然是这个给折腾的  大意了！东西很好，就是注释几乎没有~~  估计过个长时间没敲自个都要花费一段时间才捡的回来了

**Comment by zuiidea** [comment]
哈哈，我觉得注释放在代码中看起来太丑了...
