### ISSUE TITLE
使用IE11访问时登录页面login一直停留在加载状态，点击登录后还是停留在login页面

### ISSUE THREAD

**Issue by xiaohong-jiang** [zuiidea/antd-admin#901]
求助请问大家是否遇到同样问题：
使用IE11访问时登录页面login一直停留在加载状态，点击登录后还是停留在login页面，
但是如果使用Chrome或者Edge就没有任何问题。

我用的IE11是 11.285.17134，代码克隆下来后未做任何修改。
![Uploading login_error.jpg…]()

**Comment by superlbr** [comment]
duplicate #843 
这是由于IE11不支持Promises和Object.assign
而现有的polyfills方案并不令人满意

**Comment by superlbr** [comment]
mark, https://github.com/ant-design/ant-design-pro/issues/2344

**Comment by xiaohong-jiang** [comment]
> duplicate #843
> 这是由于IE11不支持Promises和Object.assign
> 而现有的polyfills方案并不令人满意

明白了，多谢！

**Comment by xiaohong-jiang** [comment]
> duplicate #843
> 这是由于IE11不支持Promises和Object.assign
> 而现有的polyfills方案并不令人满意

@superlbr 能公布一下这个 http://antd-admin.zuiidea.com 演示中的IE11的支持解决方案么，我自己尝试了很多次都没能解决这个IE11支持问题，谢谢啊

**Comment by superlbr** [comment]
目前来看，ie11登录已经正常了
