### ISSUE TITLE
菜单栏选择 Users 在出现的表格中选中表格内的 小愤青丶 左边菜单栏无高亮状态 请问这个有什么办法解决吗

### ISSUE THREAD

**Issue by zhengzejian** [zuiidea/antd-admin#902]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
左边菜单栏无高亮状态?不明白，请截图圈出问题点

**Comment by zhengzejian** [comment]
![image](https://user-images.githubusercontent.com/26517848/46242368-d2c27600-c3fa-11e8-8450-fd12b4f842d5.png)

请看 左边丢失了高亮状态

**Comment by superlbr** [comment]
丢失。。。个人见解不同吧
1. 左边并没有User Detail对应的项
2. Users对应的就是用户列表，而这个是用户详情，如果两个都是Users高亮，是否对应就不一致呢
3. 如果要高亮的话，要修改写代码
   从这里开始，menus过滤掉了-1的部分，然后components/layout/menu.js selectedKeys会显示选中
   https://github.com/zuiidea/antd-admin/blob/dd3c191139e42d27d91213149ad0f909de70d313/src/layouts/PrimaryLayout.js#L35
