### ISSUE TITLE
NumberCard 多出滑动条

### ISSUE THREAD

**Issue by jiyeyuran** [zuiidea/antd-admin#903]
线上演示版是正常的，但本地运行就多出滑动条。修改src/pages/dashboard/index.less
`
    .ant-card-body{
      overflow-x: hidden;
    }
`
改为
`
    .ant-card-body{
      overflow: hidden;
    }
`
可修复。

**Comment by superlbr** [comment]
线上演示版落后很多了。。。

**Comment by JLoveI** [comment]
13434556

**Comment by superlbr** [comment]
dev版本， https://antd-admin-beta.zuiidea.com
