### ISSUE TITLE
登录页面（/login）是如何禁用全局模板的（layout） 关键代码在什么地方？ 怎么没找到呢

### ISSUE THREAD

**Issue by lzc281125911** [zuiidea/antd-admin#904]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
https://github.com/zuiidea/antd-admin/blob/9a5ff4aa982989e5979993bb38f84bceba30230a/src/utils/config.js#L10-L17
😁

**Comment by lzc281125911** [comment]
我下载的是 master 版本   为什么里面两个文件都没有 你上面说的代码呢？   看其他版本倒是有，可我下载的是master版本    这个版本在哪里设置的

**Comment by lzc281125911** [comment]
> [antd-admin/src/utils/config.js](https://github.com/zuiidea/antd-admin/blob/9a5ff4aa982989e5979993bb38f84bceba30230a/src/utils/config.js#L10-L17)
> Lines 10 to 17 in [9a5ff4a](/zuiidea/antd-admin/commit/9a5ff4aa982989e5979993bb38f84bceba30230a)
>  /* Layout configuration, specify which layout to use for route. */ 
>  layouts: [ 
>    { 
>      name: 'primary', 
>      include: [/.*/], 
>      exlude: [/(\/(en|zh))*\/login/], 
>    }, 
>  ], 
> [antd-admin/src/utils/index.js](https://github.com/zuiidea/antd-admin/blob/9a5ff4aa982989e5979993bb38f84bceba30230a/src/utils/index.js#L202)
> Line 202 in [9a5ff4a](/zuiidea/antd-admin/commit/9a5ff4aa982989e5979993bb38f84bceba30230a)
>  export function queryLayout(layouts, pathname) { 
> 😁
我下载的是 master 版本 为什么里面两个文件都没有 你上面说的代码呢？ 看其他版本倒是有，可我下载的是master版本 这个版本在哪里设置的

**Comment by superlbr** [comment]
master 不是禁用，而是没有交集。
master分支什么情况下会有模版呢？hasPermission，而login不在这list里
https://github.com/zuiidea/antd-admin/blob/f02d39ace05bcbf18e4a107060498a8754f6ce2a/src/layouts/app.js#L117

**Comment by lzc281125911** [comment]
好的 我再研究一下    没仔细看  谢谢！

**Comment by lzc281125911** [comment]
> master 不是禁用，而是没有交集。
> master分支什么情况下会有模版呢？hasPermission，而login不在这list里
> [antd-admin/src/layouts/app.js](https://github.com/zuiidea/antd-admin/blob/f02d39ace05bcbf18e4a107060498a8754f6ce2a/src/layouts/app.js#L117)
> 
> Line 117 in [f02d39a](/zuiidea/antd-admin/commit/f02d39ace05bcbf18e4a107060498a8754f6ce2a)
> 
>  {hasPermission ? children : <Error />}

我按照你说的  还是不对     hasPermission 无非就是true 和false     true执行 children   false 执行Error      但是 我单独执行 http://localhost:8000/login   根本不会执行全局模板（layout）代码     我就是想问   login 和   dashboard 同样都是在pages 文件夹下    为什么 dashboard 可以套上全局模板  而login 却没有全局模板套上，login 是如何脱离全局模板的 ，开关在什么地方

**Comment by superlbr** [comment]
> hasPermission怎么来的

const hasPermission = current.length ? permissions.visit.includes(current[0].id) : false

> permissions.visit 又在哪里

https://github.com/zuiidea/antd-admin/blob/f02d39ace05bcbf18e4a107060498a8754f6ce2a/src/models/app.js#L76-L87

> list 哪里来的

const { list } = yield call(menusService.query)

> menusService.query 数据在哪里

mock/menu.js 中有login吗？

**Comment by lzc281125911** [comment]
我找到了    不过确实跟你说的 不是一回事   代码在  layout/app.js      中  if (openPages && openPages.includes(pathname)) {
    return (<div>
      <Loader fullScreen spinning={loading.effects['app/query']} />
      {children}
    </div>)
  }   

我把这行竟然给忽略掉了       直接看下一行的return了        例子很不错  让我获益匪浅    谢谢！

**Comment by TopGuo** [comment]
作者能留个联系方式吗？，远程有偿讲解一下这套架子

**Comment by superlbr** [comment]
@TopGuo 有问题可以提

**Comment by TopGuo** [comment]
有点绕，想用这套架子到公司，我是后台开发，可以有偿请教，本人微信：jkxx123321

**Comment by TopGuo** [comment]
比如说，程序启动，首先跳，http://localhost:9000/zh/login?from=%2F 这个路径
![image](https://user-images.githubusercontent.com/30146744/53300631-ed532b00-3884-11e9-996d-b9f2efbe7d89.png)

退出登录，之后访问内部路径，又跳回到登录页，http://localhost:9000/zh/login?xxxxx

这套的实现你在那里设置？

**Comment by TopGuo** [comment]
![image](https://user-images.githubusercontent.com/30146744/53300668-75d1cb80-3885-11e9-939d-731850c8bff5.png)
这个issue上没有看到答案，刚把dvajs和umijs简单的看了一遍

**Comment by TopGuo** [comment]
![image](https://user-images.githubusercontent.com/30146744/53300712-d8c36280-3885-11e9-9da4-fb71fb7554d4.png)
![image](https://user-images.githubusercontent.com/30146744/53300723-f1337d00-3885-11e9-9271-96d28c58e707.png)
这里你已经重构了吧，找不到了

**Comment by TopGuo** [comment]
![image](https://user-images.githubusercontent.com/30146744/53300803-8df61a80-3886-11e9-9d4e-35e099af6c70.png)
这个好像有点意思

**Comment by superlbr** [comment]
@TopGuo https://github.com/zuiidea/antd-admin/blob/5b32607911b7175803014bd6aa64802f505b91c6/src/models/app.js#L76-L122

**Comment by TopGuo** [comment]
昨天找到这里有，谢谢
