### ISSUE TITLE
Fresh install and then run the npm start gives 'These dependencies were not found:' error

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#905]
* components in ./src/layouts/app.js, ./src/pages/404.js and 14 others
* components/DataTable/AnimTableBody in ./src/pages/user/components/List.js
* utils in ./src/layouts/app.js, ./src/pages/dashboard/index.js and 16 others
* utils/city in ./src/pages/user/components/Modal.js, ./src/pages/user/components/Filter.js
* utils/model in ./src/pages/dashboard/model.js, ./src/pages/post/model.js and 1 other

To install them, you can run: npm install --save components components/DataTable/AnimTableBody utils utils/city utils/model

**Comment by superlbr** [comment]
use yarn instead of npm

**Comment by malinda1986** [comment]
hmm that does not fix the issue :(
