### ISSUE TITLE
antd-admin怎么打包部署到tomcat里面？

### ISSUE THREAD

**Issue by dugu666** [zuiidea/antd-admin#906]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
build之后直接放Tomcat webapps下。
处理静态html，显然apache、nginnx好

**Comment by dugu666** [comment]
你这个等于没说，换个说法吧，在tomcat下运行需要配置 rewrite.config文件，这个文件内容究竟该怎么写。
比如下面这个是iis的配置
Options +FollowSymlinks -Multiviews
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.html [QSA,PT,L].htaccess

这个要怎么转化为tomcat能识别的格式

**Comment by dugu666** [comment]
没有真正在tomcat运行过antd-admin的不要回答了

**Comment by superlbr** [comment]
@dugu666 如果没能解决问题，请贴出报错

**Comment by superlbr** [comment]
参考tomcat的文档，tomcat+apache是标配
http://tomcat.apache.org/tomcat-9.0-doc/rewrite.html
