### ISSUE TITLE
华为自带浏览器显示空白页，还没有报错

### ISSUE THREAD

**Issue by yingyl** [zuiidea/antd-admin#907]
我直接下的最新的代码，本地运行没问题，打包发布之后，电脑可以显示登录页面，但是安卓自带的浏览器无法显示，只显示空白页面，不知如何解决

**Comment by superlbr** [comment]
这边华为nova 2 plus，EMUI8.0.0，测试ok
可以尝试比如嵌入[vConsole](https://github.com/Tencent/vConsole) 在手机上调试
