### ISSUE TITLE
怎么增加新的页面呢？ 

### ISSUE THREAD

**Issue by devuser** [zuiidea/antd-admin#908]
我使用umi创建新的页面，或者复制pages下面的文件夹来产生新的页面，然后启动运行`npm run start`失败。是什么原因呢？

创建新页面需要走过哪几步呢 ？

**Comment by superlbr** [comment]
> umi创建新的页面

需要观察下目录的结构，对比下文件的内容

> 复制pages下面的文件夹来产生新的页面，然后启动运行npm run start失败

看下报错内容吧，model的namespace要唯一的

duplicate: https://github.com/zuiidea/antd-admin/issues/553，其中router.js可以无视
