### ISSUE TITLE
iphone上safari的显示错误

### ISSUE THREAD

**Issue by yingyl** [zuiidea/antd-admin#909]
iphone上safari的里user管理中，table页面无法往下滑动，翻页组件也无法显示
![wechatimg1](https://user-images.githubusercontent.com/25652918/47722147-aa919580-dc8c-11e8-885b-a1199a0320e9.jpeg)

**Comment by superlbr** [comment]
再试试

**Comment by superlbr** [comment]
fixed in dbe86ec
