### ISSUE TITLE
设置子路由一直报错

### ISSUE THREAD

**Issue by kaiserzeng** [zuiidea/antd-admin#910]
You should not use <Route component> and <Route children> in the same route; <Route children> will be ignored
这个错要怎么解决，子路由设置，有文档吗？

**Comment by superlbr** [comment]
1. same route, 不是有提示了。怀疑 https://github.com/ReactTraining/react-router/issues/4491
2. 本项目并没有router设置，采取umi默认的路由
3. [umi文档](https://umijs.org/zh/guide/router.html)
