### ISSUE TITLE
项目build之后的dist直接部署到ngnix上面 为什么左边侧边栏都没有了 前端小白

### ISSUE THREAD

**Issue by lsabella** [zuiidea/antd-admin#911]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息

**Comment by lsabella** [comment]
![Uploading 03F91D3BB7E17216AB14358FD88F8CE3.png…]()

**Comment by lsabella** [comment]
![03f91d3bb7e17216ab14358fd88f8ce3](https://user-images.githubusercontent.com/15812850/48013283-eaf68500-e15e-11e8-8c59-db62943315c5.png)

**Comment by superlbr** [comment]
当然是少了后端的接口，打开chrome控制台看下就清楚了。
因为npm run start本地调试，使用的是mock数据

**Comment by lsabella** [comment]
好的 那有的想使用mock的数据在线上可以怎么配置么

**Comment by lsabella** [comment]
> 当然是少了后端的接口，打开chrome控制台看下就清楚了。
> 因为npm run start本地调试，使用的是mock数据

好的 那有的想使用mock的数据在线上可以怎么配置么

**Comment by superlbr** [comment]
参考https://github.com/zuiidea/antd-admin/issues/832
