### ISSUE TITLE
ie9 兼容问题

### ISSUE THREAD

**Issue by xiaocjin** [zuiidea/antd-admin#912]
请问项目还支持ie9吗？代码配置hashRouter，打包部署后，使用ie9打开页面仍然报错，“无法获取未定或null引用的属性add”

**Comment by xiaocjin** [comment]
https://antd-admin.zuiidea.com/ 使用ie9也是报这个错误

**Comment by superlbr** [comment]
手上没有IE9可以测。方便贴一个完整的报错截图吗?
本项目的polyfills支持来自于umi，参考 https://umijs.org/zh/plugin/umi-plugin-react.html#polyfills

**Comment by superlbr** [comment]
刚虚拟机win7看了下，IE9完全打不开。。。
有意思的是，微软官网都提示了，请升级到IE11
![image](https://user-images.githubusercontent.com/8142164/48118132-4c753b80-e2a6-11e8-831e-a7b07cada399.png)

**Comment by superlbr** [comment]
@joeyFuck 什么问题，这边测下来正常的呀

**Comment by zhans1993** [comment]
clone 下来的工程ie 11 下 报错
HTML1300: 进行了导航。
localhost:7000
SCRIPT1010: 缺少标识符
umi.dll.js (56697,9)
SCRIPT5009: “umi”未定义
umi.js (24236,1)

**Comment by superlbr** [comment]
@zhans1993 调试开发建议使用chrome, build之后再试IE11

**Comment by superlbr** [comment]
IE9下，ant.design\preview.pro.ant.design也是打不开的

**Comment by zhans1993** [comment]
但是也不至于dev环境下，ie11都不行吧。我们之前的项目都是只有ie8需要打包看，ie9+都支持dev的


| |
詹帅
|
|
邮箱：zhans1993@163.com
|

签名由 网易邮箱大师 定制

在2019年01月28日 18:54，Baorong Li 写道：

IE9下，ant.design\preview.pro.ant.design也是打不开的

**Comment by superlbr** [comment]
@zhans1993 dev环境下，没有polyfill

**Comment by superlbr** [comment]
ie11下(antd-admin.zuiidea.com)打不开，可以尝试注释掉pwa的部分
https://github.com/zuiidea/antd-admin/blob/7fdb2f4ea8c3a23dba3e9e8c59168bf93be92b17/.umirc.js#L62-L66
