### ISSUE TITLE
modal put 请求一个借口的数据，返回的数据和接口的数据不一致，数据丢失了。

### ISSUE THREAD

**Issue by luopf** [zuiidea/antd-admin#917]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by luopf** [comment]
![image](https://user-images.githubusercontent.com/22361318/48695440-1d51b900-ec1a-11e8-8dc6-1a300dc2cc1d.png)
![image](https://user-images.githubusercontent.com/22361318/48695446-22166d00-ec1a-11e8-9d85-df25a4582df6.png)
![image](https://user-images.githubusercontent.com/22361318/48695450-25115d80-ec1a-11e8-90db-c00fdefe6902.png)

**Comment by superlbr** [comment]
因为请求的不是一个接口吧，model里的put请求的是mock的数据？

**Comment by luopf** [comment]
是同一个接口

**Comment by superlbr** [comment]
请提供比如Chrome的XHR的具体信息，比如
![image](https://user-images.githubusercontent.com/8142164/48746483-939dfc00-ecaa-11e8-9226-0f96b3139917.png)

如果这个没有问题，那么请提供最小可重现的DEMO
