### ISSUE TITLE
《cotent》中children的内容比较多的话    footer 并不移动到最下方   怎么处理好一些？

### ISSUE THREAD

**Issue by lzc281125911** [zuiidea/antd-admin#918]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复
![qq 20181120172047](https://user-images.githubusercontent.com/44019764/48763746-dda5d280-ece8-11e8-82da-ad4abafe4d01.jpg)
![qq 20181120172116](https://user-images.githubusercontent.com/44019764/48763747-dda5d280-ece8-11e8-8592-997be2bc93e4.jpg)

**Comment by lzc281125911** [comment]
![qq 20181120172938](https://user-images.githubusercontent.com/44019764/48764174-e945c900-ece9-11e8-9731-83fadf16387f.jpg)


我看的就是 5.0的原版也是这么情况      上面的截图就是  5.0版运行后的截图

**Comment by superlbr** [comment]
master分支 最新的演示：antd-admin.zuiidea.com
