### ISSUE TITLE
【代码求助】-子目录中出现package.json，起什么作用

### ISSUE THREAD

**Issue by lwang7212** [zuiidea/antd-admin#919]
不知道在子目录中出现package.json，比如：src/components/Page/package.json src/components/Loader/package.json ，内容类似如下：
{
  "name": "Page",
  "version": "0.0.0",
  "private": true,
  "main": "./Page.js"
}
请问，这个文件起什么作用的，

**Comment by lwang7212** [comment]
不知我的理解是不是正确，"main": "./Page.js"，是覆盖了默认入口文件index.js ,import *  from components/Page ,就找这个入口文件

**Comment by superlbr** [comment]
是，https://codeburst.io/ab-using-package-json-over-index-js-8a7af1cd6550
