### ISSUE TITLE
侧边栏收缩二级菜单弹出显示且错位

### ISSUE THREAD

**Issue by Albuseven** [zuiidea/antd-admin#922]
如图
![1](https://user-images.githubusercontent.com/6004615/49426874-d0a2dc00-f7dc-11e8-8cbf-6bde3fec0028.png)
![2](https://user-images.githubusercontent.com/6004615/49426881-d39dcc80-f7dc-11e8-834b-79482430a65c.png)

**Comment by miaopeng** [comment]
@superlbr 先展开charts菜单，然后点击顶部收缩侧边栏的按钮，charts的子菜单就会显示在异常的位置。（mac chrome）

**Comment by superlbr** [comment]
样式我不擅长，antd-pro貌似没有这个问题，@zuiidea

**Comment by superlbr** [comment]
closed in 6aead03
