### ISSUE TITLE
BUG https://antd-admin.zuiidea.com/zh/login 登陆页面 点击语言 返回404 Not Found

### ISSUE THREAD

**Issue by TLOVET** [zuiidea/antd-admin#924]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
是不是还缺什么步骤，无法重现
![test](https://user-images.githubusercontent.com/8142164/49586300-c2e78500-f99b-11e8-9be2-0bde21fccc06.gif)

**Comment by miaopeng** [comment]
登录之后，从任何一个页面点 sign out 登出，这时 url 后面会跟 from 参数，然后再点中文或 English 就会报错了。

**Comment by TLOVET** [comment]
是我没表达明白，你点击https://antd-admin.zuiidea.com/en/login?from=%2Fzh%2Fdashboard这个链接就会出现，和楼上说的一样，就是登出之后，url后面跟from，再在登录页面点击切换中英文就会报错

**Comment by TLOVET** [comment]
楼上回答正解，我遗漏了from参数，加上之后，你应该就可以复现了
