### ISSUE TITLE
Env based configs

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#925]
I need to deploy this application in qa and prod environments, how do I add env based configs. mainly I want to change parameters in the utils/config.js (api path etc..)

**Comment by malinda1986** [comment]
yes it works thanks, I did something like this 

[https://github.com/malinda1986/antd-admin/pull/1/commits/3f1250de2ed84bbad86149a97164bcfa199d610e]

**Comment by malinda1986** [comment]
@superlbr  that doesn't work if we host on the s3 bucket, node env is not available 
the best way is to override the .umirc.js for each env 
https://umijs.org/guide/env-variables.html#how-to-configure

**Comment by superlbr** [comment]
@malinda1986 you‘re right
