### ISSUE TITLE
Branch 3.0 上面包屑导航错误

### ISSUE THREAD

**Issue by jeffhtli** [zuiidea/antd-admin#93]
是不是与这个commit有关：https://github.com/zuiidea/antd-admin/commit/e03316423f627ae4c758b71f15f8cb5f1be50153

**Comment by zuiidea** [comment]
什么错误

**Comment by jeffhtli** [comment]
比如点击左侧菜单中的“二级导航1”，这时面包屑是 **主页 》导航测试 》二级导航1** ,
正确应该是：
主页：http://domain/#/
导航测试：http://domain/#/navigation

实际是：
主页：http://domain/navigation/navigation1#/
导航测试：http://domain/navigation/navigation1#/navigation

显然这两个地址无法导航
