### ISSUE TITLE
DatePicker 的 locale bug

### ISSUE THREAD

**Issue by whutpsychic** [zuiidea/antd-admin#931]
> 请酌情提供细节，并保持issue精简便于查阅
> 2. Bug反馈  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  

> 2.将 DatePicker 用为受控组件时，默认设置的 value = null；全局、局部均按照官网教程使用 locale 设置为 zh-cn，却出现：星期和月份是英文字符，而日和年却正常（其他也正常），点击onchange之后一切恢复正常；并且每当值设置为 null 时都会导致此情况发生，尝试默认修改locale文件不能解决，不知道是什么原因。
初步怀疑可能是 antd 内部实现问题
> 2.2 我期望将值设置为null时可以正确套用全局设置的 locale。
> 2.3 每次值设置为 null 时发生。

antd 版本 3.10.8
moment 版本 2.10.6

**Comment by superlbr** [comment]
antd也需设置zh-cn，参考https://ant.design/docs/react/i18n-cn

**Comment by afc163** [comment]
升级到最新的 umi 即可

**Comment by superlbr** [comment]
另有： https://github.com/ant-design/ant-design/issues/14205
删掉依赖，重新build
