### ISSUE TITLE
现在的项目无法匹配根路径的网址，显示 not found

### ISSUE THREAD

**Issue by zichen-cici** [zuiidea/antd-admin#935]
现在的项目无法匹配根路径的网址，显示 not found，无法匹配 ‘/’ 下的组件

![image](https://user-images.githubusercontent.com/13568082/50957944-77744980-14fa-11e9-87fc-652714c4d908.png)

**Comment by noobalex** [comment]
没有修复
![image](https://user-images.githubusercontent.com/20298142/62268641-0c24a180-b463-11e9-89c6-7f70a5ca6a14.png)

**Comment by superlbr** [comment]
@noobalex 404是由于最近的一次优化，fixed in 9cf9737
