### ISSUE TITLE
demo例子加载时 有闪屏问题

### ISSUE THREAD

**Issue by codeinfo** [zuiidea/antd-admin#937]
首次加载，点击菜单按钮会有闪烁现象出现

**Comment by codeinfo** [comment]
首次加载，点击菜单按钮会有闪烁现象出现

**Comment by superlbr** [comment]
参考umi文档： [按需加载]( https://umijs.org/zh/guide/deploy.html#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD)
只有加载到该路由的时候，才加载对应的文件，看上去类似页面跳转
