### ISSUE TITLE
models加载的规则是什么

### ISSUE THREAD

**Issue by zhaozhuoguang** [zuiidea/antd-admin#938]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 复杂的页面我会把model细化，4.x版本的时候可以自己写router.js,现在5.x版本的router.js 由umi生成，那我想一个页面connect两个model的时候（同一目录下，如model.js;xxmodel.js），xxmodel.js不会生成在router.js中，但umi却加载了上级目录的model
> 2. 所以我是想知道这里生成的router.js,它加载model的规则是什么

**Comment by zhaozhuoguang** [comment]
{
    "path": "/engineering/product/bom/:id",
    "exact": true,
    "component": _dvaDynamic({
        app: window.g_app,
        models: () => [
            import( /* webpackChunkName: 'p__engineering__product__bom__$id__model.js' */ 'E:/workspace/svn/yixinerp/trunk/code/erp-web/src/pages/engineering/product/bom/$id/model.js').then(m => {
                return {
                    namespace: 'model',
                    ...m.default
                }
            }),
            import( /* webpackChunkName: 'p__engineering__product__models__form.js' */ 'E:/workspace/svn/yixinerp/trunk/code/erp-web/src/pages/engineering/product/models/form.js').then(m => {
                return {
                    namespace: 'form',
                    ...m.default
                }
            }),
            import( /* webpackChunkName: 'p__engineering__product__models__model.js' */ 'E:/workspace/svn/yixinerp/trunk/code/erp-web/src/pages/engineering/product/models/model.js').then(m => {
                return {
                    namespace: 'model',
                    ...m.default
                }
            })
        ],
        component: () => import( /* webpackChunkName: "p__engineering__product__bom__$id__index" */ '../engineering/product/bom/$id/index.js'),
        LoadingComponent: require('E:/workspace/svn/yixinerp/trunk/code/erp-web/src/components/Loader/Loader').default,
    })
},

**Comment by zhaozhuoguang** [comment]
@connect(({ bom, bomPart, loading }) => ({ bom, bomPart, loading }))

**Comment by superlbr** [comment]
参考 [Improve dva models resolve](https://github.com/umijs/umi/issues/171)
另 5.0的主要[break](https://github.com/zuiidea/antd-admin/pull/770)

**Comment by TopGuo** [comment]
![image](https://user-images.githubusercontent.com/30146744/53244036-9f072600-36e4-11e9-8186-d8bc12560ec4.png)

**Comment by superlbr** [comment]
@TopGuo 接口配置了吗？

**Comment by TopGuo** [comment]
> @TopGuo 接口配置了吗？

还没有写接口，iis上部署了一下，可以跑
