### ISSUE TITLE
对于src/services/index.js文件的疑问

### ISSUE THREAD

**Issue by SanPy** [zuiidea/antd-admin#940]
在该文件中只导出了一个：
`export default APIFunction`
在model文件中是这样引用的：
`const {
  queryUserList,
  createUser,
  removeUser,
  updateUser,
  removeUserList,
} = api`
假如我多个service文件，那么是不是service中方法名称是不能重复的，否则会被覆盖？？？？

**Comment by superlbr** [comment]
覆盖？service文件是独立的，重名引入什么的语法会直接报错
