### ISSUE TITLE
mock _util 发生警告

### ISSUE THREAD

**Issue by TopGuo** [zuiidea/antd-admin#944]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

![image](https://user-images.githubusercontent.com/30146744/53244694-9b749e80-36e6-11e9-8704-182b02f62280.png)
请教一下这个提示如何修正？

**Comment by superlbr** [comment]
不用理会。这是js文件，提示却是ts提示
