### ISSUE TITLE
@xxx 装饰器

### ISSUE THREAD

**Issue by TopGuo** [zuiidea/antd-admin#945]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

![image](https://user-images.githubusercontent.com/30146744/53246588-15f3ed00-36ec-11e9-816b-79cd51b46f8a.png)

请教一下，这些@xxx 装饰器的资料，在哪里有，好久不搞，啥时候多处个这个来？

**Comment by superlbr** [comment]
es7语法，百度一下即可

**Comment by superlbr** [comment]
https://www.jianshu.com/p/1a8849880fa9

**Comment by TopGuo** [comment]
> https://www.jianshu.com/p/1a8849880fa9

多谢多谢
