### ISSUE TITLE
默认发送的请求（api/v1/user）是在哪里发送的？

### ISSUE THREAD

**Issue by DerrickTel** [zuiidea/antd-admin#949]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 默认发送的请求（api/v1/user）是在哪里发送的？无论哪个页面都会发送这个请求
> 2. 默认发送的请求（api/v1/user）是在哪里发送的？无论哪个页面都会发送这个请求  
> 2.1 默认发送的请求（api/v1/user）是在哪里发送的？无论哪个页面都会发送这个请求
> 2.2 找到他，并不让他发送 
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
在这里 queryUserInfo
https://github.com/zuiidea/antd-admin/blob/693625bf2c492f0061df76934f3c89bf419ea536/src/models/app.js#L77
