### ISSUE TITLE
问个业务逻辑问题，打开／，没有登录系统就从后台访问dashboad的数据

### ISSUE THREAD

**Issue by zyx4986** [zuiidea/antd-admin#95]
怎么在访问登录后，再访问dashboad的数据呢？

**Comment by jeffhtli** [comment]
你意思是不要登录页面，直接显示dashboard？

**Comment by zyx4986** [comment]
不是，就是dashboad有时会使用一些用户的信息，然而没有登录的时候，路由在 ／时，dashboard就开始访问后台了，这时用户的信息就没取到，怎么在登录后再访问dashboad呢？

**Comment by jeffhtli** [comment]
确实有这个问题，其他模块也有一样的问题，比如没有登录，直接输入http://domain/users ，虽然显示的是登录页面，但users的相关API还是触发了，原因是subscription中setup执行了。

按道理没有登录，这些API是不应该触发的。你可以参考[这里](https://github.com/fireyy/react-antd-admin/blob/master/src/route/index.js) ，看看有没有启发

**Comment by zyx4986** [comment]
研究了下，用这个方法解决的，models 订阅数据源的时候加了个判断
subscript:{
  setup({dispatch,history})
    {
         histoty.listen(location=>{if(location.pathname ==='/dashboard')})
    }
}

**Comment by wuyongdec** [comment]
@jeffhtli 每次跳转路由都检查是否已登录？

**Comment by jeffhtli** [comment]
@wuyongdec 每次跳转onEnter都会执行，但有没有必要每次都检查还是看业务需求。你可以参看这里的讨论 https://github.com/dvajs/dva/issues/95
