### ISSUE TITLE
访问login时控制台报告缺少en

### ISSUE THREAD

**Issue by devuser** [zuiidea/antd-admin#954]
> 请酌情提供细节，并保持issue精简便于查阅
> 2. Bug反馈  

访问Login页面时，在控制输出
```
Message catalog for locale "en" not loaded.
```

这是什么原因呢？找不到原因所在。

**Comment by superlbr** [comment]
1. 在dev环境下会出现，build之后就没有
2. 不影响使用，建议忽略
3. 深究的话，https://github.com/lingui/js-lingui/issues/118，https://itnext.io/simple-internationalization-of-react-apps-34b3bda95725
