### ISSUE TITLE
Any suggestion to reduce the umi.js file size

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#955]
After building the project umi.js size is 9.5 MB , is there a way to reduce the file size

**Comment by superlbr** [comment]
1. first run ```yarn analyze```, see which part cost that much
2. 9.5 MB not compress by gzip, which could be provided by nginx or apache.And umi build will give you a summary, you should provide the pic after ```yarn build```

**Comment by malinda1986** [comment]
thanks @superlbr :) give me a few mins ill get back with the result

**Comment by malinda1986** [comment]
<img width="457" alt="Screen Shot 2019-03-15 at 2 32 10 PM" src="https://user-images.githubusercontent.com/3467935/54420153-3df4d000-472f-11e9-84f6-a72481b18de7.png">
in production it runs the `    "build": "umi build" ` , but still it load ~4MB

**Comment by superlbr** [comment]
1. umi.js in develop, looks 9.5MB, 2.9MB transfered after gzip. just cost 1s more to load in local
2. umi build, pls check this size
![image](https://user-images.githubusercontent.com/8142164/54422857-52929180-474a-11e9-9a6c-cabb338507c0.png)
3. 4MB, should not be that large, pls attach your ```yarn analyze``` result, like this way
![image](https://user-images.githubusercontent.com/8142164/54423360-74d8df00-474b-11e9-85ab-ee3f3396b4b6.png)
4. modules size matters

**Comment by malinda1986** [comment]
<img width="381" alt="Screen Shot 2019-03-15 at 3 39 10 PM" src="https://user-images.githubusercontent.com/3467935/54424381-c9269380-4738-11e9-95a6-50f846f0719b.png">


<img width="1400" alt="Screen Shot 2019-03-15 at 3 41 11 PM" src="https://user-images.githubusercontent.com/3467935/54424396-ccba1a80-4738-11e9-8e86-5051dd7d9e29.png">

how to get that view in yarn analyze ?

**Comment by superlbr** [comment]
![image](https://user-images.githubusercontent.com/8142164/54430401-6fd15b00-475e-11e9-913a-f7ad48d02cf9.png)
1. react-icons, here's a temp solution, require some icons, https://github.com/HeskeyBaozi/reduce-antd-icons-bundle-demo
2. echarts and highcharts, well, duplicate in my view, have you try dynamic import also?
3. react-icons, with es6 import, only needed is imported, https://github.com/react-icons/react-icons#why-es6-import-and-not-fonts
hope it helpful

**Comment by malinda1986** [comment]
thanks, @superlbr , I'll try those options, you are correct echarts and highcharts I can remove completely.
I haven't tried dynamic import, I'll give try on that.

Thanks

**Comment by superlbr** [comment]
there's no vendor in your file list,  perhaps it's not modified on antd-admin@5.x basis
