### ISSUE TITLE
重复点击左侧同一个导航，查询条件无法清空问题

### ISSUE THREAD

**Issue by antiantian** [zuiidea/antd-admin#958]
1. Bug反馈  
执行步骤
1： 查询列表  当输入一个或多个条件时  列表数据按照条件搜索
2：再点击左侧相同的导航 ，列表会重新加载  查询条件没有清空  
![image](https://user-images.githubusercontent.com/23133017/55149514-46182b00-5185-11e9-989a-2a906b604fe4.png)

![image](https://user-images.githubusercontent.com/23133017/55149594-68aa4400-5185-11e9-85cc-5626686b069e.png)

**Comment by superlbr** [comment]
有两种思路:
1. 点击链接，清空查询条件。rc-form设置下，[参考](https://stackoverflow.com/questions/38881324/redux-form-initialvalues-not-updating-with-state)
2. 点击链接，保持现场。判断下路径没有变化就可以了

**Comment by antiantian** [comment]
这个问题貌似没有修复  还是和之前的情况一样  搜索框里的内容不会清空

**Comment by superlbr** [comment]
@antiantian 是的，看错了，不好意思

**Comment by superlbr** [comment]
说下思路，这个点击会触发componentDidUpdate，识别filter为空后resetFields。componentWillUnmount并不会触发。

**Comment by superlbr** [comment]
对于这个refix，并不满意，有好的fix欢迎PR
