### ISSUE TITLE
请问不支持firefox吗？（firefox中异步操作不执行）

### ISSUE THREAD

**Issue by xiangsanmei** [zuiidea/antd-admin#96]
登录时，输入帐号密码后，点击登录，没反映，未执行下面的异步方法
![image](https://cloud.githubusercontent.com/assets/14797835/23455282/f789d9d2-fea9-11e6-90fc-6415761b5f8f.png)

**Comment by zuiidea** [comment]
应该不会啊，这都会转码的，你看看有没有报错

**Comment by xiangsanmei** [comment]
没有报错   我在login里面console.log，没有打印

**Comment by zyx4986** [comment]
firefox跨域访问有限制，可以查查这方面的原因

**Comment by pmg1989** [comment]
@xiangsanmei 这个感觉应该还是少了`babel-polyfill`引起的，试试加一下`import "babel-polyfill"`，可参见[IE 9+ 方案](https://github.com/pmg1989/dva-admin/issues/1)
