### ISSUE TITLE
使用electron编译成桌面应用应该怎么做呢？

### ISSUE THREAD

**Issue by leaez** [zuiidea/antd-admin#960]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

**Comment by superlbr** [comment]
1. 参考官方[文档](https://electronjs.org/docs/tutorial/application-distribution#%E6%89%93%E5%8C%85%E5%B7%A5%E5%85%B7)
2. 问度娘，比如[教程1](https://blog.csdn.net/qq_33323731/article/details/80492191)
