### ISSUE TITLE
请教下，请教下启动后CPU爆满卡死的问题

### ISSUE THREAD

**Issue by laiyiyi** [zuiidea/antd-admin#961]
您好，想请教下3个问题
1、npm run start 后，浏览器访问，然后CPU马上就爆满卡死了，有这种情况吗？IDE是vscode
2、怎么一键删除国际化功能，让整站默认为中文呢？
3、这个能设置全局变量吗？比如之前的webpack可以根据new webpack.DefinePlugin  根据环境变量设置打包的时候存一些全局变量进去，在其他地方${全局变量名}就能取到了

**Comment by superlbr** [comment]
1. nodejs是单线程，webpack消耗大，cpu跑满不奇怪。
    a. 打游戏、解压缩、python跑脚本等等，都会造成CPU短时间高负荷的情况。
    b. 卡死也不奇怪，打游戏的时候为啥把其他窗口关掉。vscode本身chrome内核，吃内存。
2. 一键删不了，默认语言设置src/utils/config.js，`defaultLanguage: 'zh'`
    a. 对应文本文件在mock/route.js
    b. 改掉类似i18n.t`Unpublished`就好了
3. 参考umijs的[文档](https://umijs.org/zh/plugin/develop.html#%E7%B3%BB%E7%BB%9F%E7%BA%A7%E5%8F%98%E9%87%8F)
