### ISSUE TITLE
dist/index.html直接在浏览器中打开时，显示空白页。

### ISSUE THREAD

**Issue by leaez** [zuiidea/antd-admin#962]
在开发模式下可以正常通过浏览器访问http://localhost:8000/正常， 但是编译到dist目录直接打开index.html显示空白。 这样我想通过nw.js/electron编译成静态app显示也是空白。这是umi编译器的问题吗？

**Comment by superlbr** [comment]
1. 显示空白，第一反应应该是去控制台看报错
2. 然后会发现空白是因为静态文件路径不对
3. umi是create-react-app的仿品，这是设计上的考量。可以度娘诸如[参考1](https://flaviocopes.com/react-electron)
