### ISSUE TITLE
感觉还是之前的版本好

### ISSUE THREAD

**Issue by laiyiyi** [zuiidea/antd-admin#963]
感觉还是之前的roadhog，webpack版本好，这个用umijs感觉好重，动不动就电脑卡死了( i7  16G呢)。而且第一次切换菜单整个页面都会闪烁的刷新 😭

**Comment by superlbr** [comment]
1. 切换菜单，页面闪烁，是开了按需编译，https://github.com/zuiidea/antd-admin/blob/59cfe24178387331c51b930f49d6232d003ade8b/.umirc.js#L16-L19
2. `npm run start` cpu会跑到70-80%, 本地开发一直开着就好了。build会跑到100%，让服务器去跑呗

**Comment by laiyiyi** [comment]
好
