### ISSUE TITLE
为什么umi.dll.js体积有3.8MB，请问应该如何压缩？

### ISSUE THREAD

**Issue by birdycn** [zuiidea/antd-admin#966]
为什么umi.dll.js体积有3.8MB，请问应该如何压缩？

**Comment by superlbr** [comment]
umi.dll.js不需要压缩

**Comment by superlbr** [comment]
`npm run build`才是打包, 参考https://github.com/zuiidea/antd-admin/issues/712

**Comment by abcfly** [comment]
可以在Nginx上处理一部分
    gzip on;
      gzip_buffers 32 4k;
      gzip_comp_level 6;
      gzip_min_length 200;
      gzip_types text/css text/xml application/javascript;
      gzip_vary on;

**Comment by kele527** [comment]
为什么这么大？

**Comment by superlbr** [comment]
开发环境，大不奇怪@kele527
