### ISSUE TITLE
在IE下点击首页上方铃铛图标会整体移动到中间

### ISSUE THREAD

**Issue by Mathround** [zuiidea/antd-admin#968]
IE版本：11
点击首页上方铃铛图标会整体移动到中间，这个整体类名rightContainer___1uTMo会移动到中间，谷歌浏览器是正常的

**Comment by Louis-7** [comment]
这个应该是因为父级元素#layoutHeader用了flex布局，当你点击notification图标的时候添加的元素（使用了position: absolute）在#layoutHeader内部所以IE把这个也当成一个flex item了。但是在Chrome里flex-item如果使用了absolute的话将不会继续存在于父级的flex流中。

尝试了一下，目前没找到好的方法让这个notification浮动框在IE里不受父级flex影响。但是可以把这个浮动框添加到#primaryLayout中从而解决这个问题。简单测试了一下引发现其他的布局问题。

但是最好的办法肯定还是用CSS把这个popup从flex流中踢出去。
