### ISSUE TITLE
dispatch执行modle里面的方法 导致所有的组件都刷新了一遍

### ISSUE THREAD

**Issue by encorehe** [zuiidea/antd-admin#97]
你好 我这边有个场景是这样的 添加的时候 弹出一个Modal  然后执行添加方法 在 
`yield put({ type: 'showLoading' })` 的时候 这个弹出层 会闪一下 里面的内容被清空了

请教一下 这个该怎么处理啊

**Comment by feiZhang** [comment]
你应该贴出你的代码。。
推断，你在点击添加的方法中，有 put／dispatch等方法，这些方法，会改变state，导致页面重绘，内容就清空了。。

**Comment by zuiidea** [comment]
@encorehe https://github.com/dvajs/dva/issues/349
