### ISSUE TITLE
How can i add custom font

### ISSUE THREAD

**Issue by aarabmed** [zuiidea/antd-admin#972]
im not sure if this an issue for real.
but i tried to add costume fonts which seem not working for me.
what i did is 
i put the downloaded font  .ttf in the
  
> "assets/fonts/"  folder 
then inside the less file which lives with the component im working on. 
 i have add to it : 
```

@font-face {
  font-family: 'my-font';
  src: url(/assets/fonts/my-font.ttf);
}
```
then i called 
font-family: my-font ;
but that does work !!!  
**Any ideas please , on how to add costume fonts** 
Thanks in advance

**Comment by superlbr** [comment]
Work is good, have fun.
you may refer to [customize-theme](https://ant.design/docs/react/customize-theme#Ant-Design-Less-variables) in ant-design.
And modify here https://github.com/zuiidea/antd-admin/blob/master/src/themes/default.less.
