### ISSUE TITLE
Preview link is broken may 2019

### ISSUE THREAD

**Issue by jeznag** [zuiidea/antd-admin#973]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

SSL cert is invalid and the URL shows a 404
<img width="552" alt="image" src="https://user-images.githubusercontent.com/1034890/57962652-f07a2680-795c-11e9-9d93-443e8a19ef7a.png">

**Comment by superlbr** [comment]
try http

**Comment by superlbr** [comment]
@zuiidea will add https asap
