### ISSUE TITLE
项目外问题请教：Form表单内的控件怎么相互关联进行显示和隐藏

### ISSUE THREAD

**Issue by logyLiang** [zuiidea/antd-admin#98]
例如我有一个select选项，满足其中一个条件，需要显示一个input进行输入值，不满足就需要隐藏，请教下，如果改变model状态太繁琐，而且有刷新感觉很不友好。看API没找到相关的

**Comment by jeffhtli** [comment]
其实也是[表单联动](https://ant.design/components/form-cn/#components-form-demo-coordinated)，  使用 setFieldsValue 来动态设置其他控件的值。但你是显示/隐藏，使用一个state控制就行了：[例子](http://git.oschina.net/jeffhtli/re5lbaqv0s7pj3xwmgk8y48.code)
