### ISSUE TITLE
前端小白，想请问一下在services中配置的api接口什么时候调用index去封装的，是框架内部吗？

### ISSUE THREAD

**Issue by wlkfec** [zuiidea/antd-admin#981]

**Comment by superlbr** [comment]
1. services中的api，只是个常量列表
2. 主要看model.js里的```import api from 'api'```。
    这个api是通过.umirc配置的别名，
  ```alias: { api: resolve(__dirname, './src/services/') }```。
3. src下的services，引入的时候，会默认读取index.js文件。that's all
