### ISSUE TITLE
项目运行报错

### ISSUE THREAD

**Issue by cangyu1993** [zuiidea/antd-admin#983]
![image](https://user-images.githubusercontent.com/42930030/59816748-e37f9700-934f-11e9-8119-edfdcae9caac.png)

**Comment by superlbr** [comment]
umi@2.8.0刚发布，还不稳定，推荐先锁定umi@2.7.7

**Comment by superlbr** [comment]
放到umi去跟进 https://github.com/umijs/umi/issues/2654
