### ISSUE TITLE
点击user菜单 会发起多次请求 

### ISSUE THREAD

**Issue by lovemegowin** [zuiidea/antd-admin#985]
src/pages/user/model.js
<pre>
subscriptions: {
    setup({ dispatch, history }) {
      history.listen(location => {
        if (pathMatchRegexp('/user', location.pathname)) {
          const payload = location.query || { page: 1, pageSize: 10 }
          dispatch({
            type: 'query',
            payload,
          })
        }
      })
    },
  },
</pre>

路由改变都会触发一次请求

**Comment by lovemegowin** [comment]
不建议用上面这种方式去请求数据 ，然后 request 里面还有会改变路由的操作，这样就会导致多次触发请求

 我打算把所有的数据请求方法放到 componentDidMount 里面去 ，然后改写一下 request 方法  @superlbr  @zuiidea  你们有没有啥建议

**Comment by lovemegowin** [comment]
d0a56169e3679d3d8b1051482f5b35ef132452a9 
这个 revert 会导致 dashboard 也会发起多次请求 
我打算把每个页面的数据请求方式重构一下 
在 app.js 中的  subscription 中添加路由重定向的操作  目前如果localstorage里面没有用户权限信息的话，直接打开会提示404渲染 <OnError> 这个组件 
@superlbr

**Comment by superlbr** [comment]
@lovemegowin 
1. 判断下是否刷新，刷新则不query
2. 可以在localstroage里加时间，过期则刷新
