### ISSUE TITLE
能手动添加html模板或者ejs模板么？或者有什么新的姿势来升级老项目？

### ISSUE THREAD

**Issue by CCCYANG** [zuiidea/antd-admin#987]
类似以前版本
![issue](https://user-images.githubusercontent.com/25678262/60338751-6603f880-99d9-11e9-8cd9-1496995eec14.jpg)
需要添加项目需要的静态资源

**Comment by superlbr** [comment]
有几种方式处理静态资源
1. [引入ejs](https://umijs.org/guide/app-structure.html#src-pages-document-ejs)
2. 依赖转换为包的形式，[oss](https://github.com/aliyun-UED/aliyun-sdk-js)，[umeditor](https://github.com/liuhong1happy/react-umeditor)

**Comment by CCCYANG** [comment]
@superlbr 
静态资源引入报错，是什么原因呢
![1561962967(1)](https://user-images.githubusercontent.com/25678262/60415390-9af89100-9c0d-11e9-8c65-b924918a0344.jpg)
![issue2](https://user-images.githubusercontent.com/25678262/60415452-c7141200-9c0d-11e9-96fe-bb59e3091cd4.jpg)

**Comment by superlbr** [comment]
> ico无效

icon的设置在 src/utils/config.js

> js引入报错，Unexpected token <

a. 请点击这个报错，去查看代码哪里报错
b. 发现路径不对， 访问不了对应js
c.  静态文件请放在public文件夹下, ```src="/UEditor/ueditor.all.js"```可以访问到
d. 在react里使用ueditor是不方便的，推荐封装版本，类似[ifanrx/react-ueditor](https://github.com/ifanrx/react-ueditor)
