### ISSUE TITLE
点击Dashboard菜单 或 Posts菜单 会发起多次请求

### ISSUE THREAD

**Issue by ybning** [zuiidea/antd-admin#988]
#### 重现步骤：
点击user菜单，再点击Dashboard菜单 或 Posts菜单，同一接口会触发2次请求（如gif图）

![GIF](https://user-images.githubusercontent.com/3725612/60353778-54344c80-99fd-11e9-8af7-042a587b1511.gif)

![GIF2](https://user-images.githubusercontent.com/3725612/60354135-256aa600-99fe-11e9-987b-aa17fa60d999.gif)

**Comment by ybning** [comment]
@superlbr

**Comment by superlbr** [comment]
最新的dev试试

**Comment by ybning** [comment]
@superlbr 最新的dev试了，一样的问题

**Comment by superlbr** [comment]
看到一个报错，怀疑跟dva有关系
```
index.js:1 uncaught at _callee3 at _callee3 
 at _callee6 
 at takeEvery 
 at _callee 
 at _callee 
 TypeError: Cannot read property '_dontReject' of undefined
    at sagaWithCatch$ (http://localhost:7000/umi.dll.js:208504:31)
    at tryCatch (http://localhost:7000/umi.js:13644:40)
    at Generator.invoke [as _invoke] (http://localhost:7000/umi.js:13870:22)
    at Generator.prototype.<computed> [as throw] (http://localhost:7000/umi.js:13696:21)
```

**Comment by ybning** [comment]
#### master：
![image](https://user-images.githubusercontent.com/3725612/60384609-8ce22d80-9ab2-11e9-8337-b6cf76d7a84a.png)
#### develop：
![image](https://user-images.githubusercontent.com/3725612/60384612-98355900-9ab2-11e9-874e-a8550698a7ef.png)

**Comment by superlbr** [comment]
1. Users只会看到一次，一次成功，一次失败
2. 在model.js里，location的键值有区别，一个有state，一个没有，同一个路径，但是key不同
   ```
      history.listen(location => {
        console.log(location)
        if (pathMatchRegexp('/post', location.pathname)) {
          dispatch({
            type: 'query',
            payload: {
              status: 2,
              ...location.query,
            },
          })
        }
      })
   ```
3. 请参考以上，可自行解决。个人对dva观望

**Comment by ybning** [comment]
@sorrycc 谦神帮忙看看
