### ISSUE TITLE
示例网址打开报错

### ISSUE THREAD

**Issue by laizimo** [zuiidea/antd-admin#990]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复

![image](https://user-images.githubusercontent.com/22924868/60557507-605f3780-9d78-11e9-93dc-a221a0adb682.png)

**Comment by superlbr** [comment]
1. 不知道什么环境？win or mac
2. 不知道什么浏览器？chrome or firefox or edge？
3. 不知道哪个页面？
4. 不能复现
