### ISSUE TITLE
示例网站打开报错

### ISSUE THREAD

**Issue by laizimo** [zuiidea/antd-admin#991]
> 请酌情提供细节，并保持issue精简便于查阅
> 1. 功能需求 => 详细说明
> 2. Bug反馈  
> 2.1 简单描述下报错  
> 2.2 你期望什么结果  
> 2.3 如何操作导致的  
> 2.4 可提供运行环境信息  
> 3. 代码求助 => 可以提，未必及时答复
示例网站地址：http://antd-admin.zuiidea.com
环境：Mac
浏览器：Chrome Version 75.0.3770.100 (Official Build) (64-bit)
报错内容：
![image](https://user-images.githubusercontent.com/22924868/60582576-aee1f580-9dbb-11e9-8a3e-29cb08f661ff.png)
操作：点击了git的网站地址之后，跳转到该网址，打开控制台发现有报错，页面空白

**Comment by superlbr** [comment]
试试https https://antd-admin.zuiidea.com

**Comment by laizimo** [comment]
一样会报错，感觉是Chrome的原因，因为在Safari和Firefox上面都是正常的

**Comment by laizimo** [comment]
找到原因了，我chrome安装了[Egret Inspector]（一款H5游戏引擎的调试插件），它会往对象原型中注入一些方法，和[react-redux]中Object.assign时产生了冲突

**Comment by superlbr** [comment]
nice
