### ISSUE TITLE
[Bug] Close Sidebar

### ISSUE THREAD

**Issue by dannyec** [zuiidea/antd-admin#992]
When a Sub-menu is opened, and then close the Sidebar, this sub-menu is not hidden.

<img width="474" alt="submenu" src="https://user-images.githubusercontent.com/13312135/60638169-e5695000-9e4f-11e9-8d98-a8c7db45f0bf.png">

**Comment by tuantvk** [comment]
@dannyec  i fix it and [PRs 996](https://github.com/zuiidea/antd-admin/pull/996)

**Comment by superlbr** [comment]
yeah，i deleted by mistake
