### ISSUE TITLE
Invalidate browser cache on production build

### ISSUE THREAD

**Issue by malinda1986** [zuiidea/antd-admin#993]
Is there way to invalidate the browser cache and load latests files after the new production release ?

Thanks,

**Comment by superlbr** [comment]
use pwa，it will create a “New Update Available” Notification。
check this https://umijs.org/plugin/umi-plugin-react.html#pwa

**Comment by superlbr** [comment]
more solution: 
[html-headers](https://github.com/facebook/create-react-app/issues/1910#issuecomment-355245212)
[nginx](https://github.com/ant-design/ant-design-pro/issues/1365)

**Comment by malinda1986** [comment]
@superlbr thanks for the update
