### ISSUE TITLE
promise then callback this not found

### ISSUE THREAD

**Issue by vinout** [zuiidea/antd-admin#997]
运行demo，进入admin账号，删除或更新一个用户信息时会出现如下报错
 
![image](https://user-images.githubusercontent.com/43285321/60769062-12428f00-a0fe-11e9-958f-d4a5584cb1a9.png)

**Comment by tuantvk** [comment]
@vinout it fixed in [PR 989](https://github.com/zuiidea/antd-admin/pull/989/) branch develop
@superlbr merge it to master
tks all

**Comment by superlbr** [comment]
@tuantvk  @vinout 
done
