### ISSUE TITLE
关于services的疑惑

### ISSUE THREAD

**Issue by ybning** [zuiidea/antd-admin#998]
现在是services下有一个index.js，而api.js里放接口链接，

实际开发时api.j会根据业务模块拆分为多个js文件。

是否考虑整成这样？

**Comment by superlbr** [comment]
1. 没有看到题目中的疑惑
2. 作为示例项目，api.js只有12条链接，没有拆分的必要
3. 拆分好还是合并好，并无优劣。欢迎提供拆分的例子，可以放文档，或者注释
