### ISSUE TITLE
如何快速去掉国际化？

### ISSUE THREAD

**Issue by ybning** [zuiidea/antd-admin#999]
如何快速去掉国际化？

**Comment by yangdachu** [comment]
+1

**Comment by superlbr** [comment]
1. 路由，结合的有点深
    langFromPath\addLangPrefix\deLangPrefix 相关方法需要清理
2. 依赖，'@lingui/react'相关清理
3. 关键词，withI18n 清理，i18n.t`xxx`替换掉，languages清理

基本上差不多了

**Comment by limenglin0717** [comment]
我清理了一下午……

**Comment by CCCYANG** [comment]
@superlbr 
![1563850035(1)](https://user-images.githubusercontent.com/25678262/61678979-41304600-ad37-11e9-87e0-9cd28631b764.jpg)
这三个依赖需不需要去掉？

**Comment by superlbr** [comment]
@CCCYANG 要

**Comment by Jesse-Weng** [comment]
国际化是什么时候添加的，可以直接回滚吗？想要以前的版本。

**Comment by cw1427** [comment]
国际化影响route path 感觉不是太好，最好能像antd-pro那样，不用在rout path上加多语言locale 标识

**Comment by superlbr** [comment]
@Jesse-Weng f6454e7 
@cw1427 是的，所以@zuiidea 说要改一下，过了半年...

**Comment by biggod-ck** [comment]
+1

**Comment by superlbr** [comment]
参考最新的提交 https://github.com/zuiidea/antd-admin/commit/b2b3fcd4a3684887667aa045b36a832218715d67

**Comment by superlbr** [comment]
set i18n to false or delete it in src/utils/config
